### ISSUE TITLE
[Feature] display button to open crash log/folder or just display crash log when betterdiscord crashes

### ISSUE THREAD

**Issue by HexCodeFFF** [BetterDiscord/BetterDiscord#1000]
**Is your feature request related to a problem? Please describe.**
Several times recently a discord update has made a library plugin crash discord on boot. betterdiscord "handles" this by disabling all plugins and giving the most unhelpful error message in the history of error messages. "disable all plugins" like wow thanks?! i'm usually able to find a fix by going to the pinned messages of the betterdiscord support channel but this feels overly cumbersome to just find the cause of a crash.

**Describe the feature you'd like**
i'd like the error message to do one or more of three things
- give a button that opens the folder where the crash logs live
- give a button to directly open the crash log (i'd prefer the former option so i could open the crash log in whatever program i like, like notepad++
- directly show the crash log on screen.

this would allow people to directly view the cause of the crash. the suspecting plugin would likely be right there in the traceback and would be fairly easy to debug by updating and/or removing the plugin.

**Additional context**
where are the crash logs anyways?

**Comment by rauenzi** [comment]
> where are the crash logs anyways?

That is the problem indeed, we don't get proper crash logs with the way Discord and Electron have been setup.
