### ISSUE TITLE
[Bug] BetterDiscord crash after sharing screen

### ISSUE THREAD

**Issue by howoshi** [BetterDiscord/BetterDiscord#1003]
I started streaming my shared screen to a discord server in a vc with one other person. As soon as the other person started watching the stream, my better discord caused discord to crash and reload. This appeared to be identical to the recently solved crashing issue (with solution pinned in the support channel on the discord), but repeating the steps to fix that didn't fix my better discord. I am unable to get better discord to work again after this. (This happened 9pm EST 8/21/21)

To Reproduce
I have been unable to reproduce due to not being able to fix my BD, but I'd assume streaming your screen (NOT an application) to another person in a server should reproduce it. 

Screenshots
Unable to provide, but it looks like the usual pop up of "Better discord has crashed your discord client"

Discord Version
Most recent? I can't find it. 

Additional Context
I DID have the previous issue that was most recently solved and the solution is pinned in #support. I fixed that when it happened a few days ago, and tried to do it again when this happened. Normally when Discord crashes because of better discord (for me), its as soon as it opens.

**Comment by rauenzi** [comment]
Does this reproduct when running with no plugins?

**Comment by Luigi1000** [comment]
Can confirm. I had same same issues recently with just using base BD w/ no plugins for both screen sharing in DMs or in server voice chat. It happens randomly but when it does it causes it to crash out, tries to reload, fail to reload with popup message box like mentioned in original post and then better discord stops working until you close discord completely and restart.

**Comment by djstini** [comment]
I still have this issue. Exactly like described. When i Screenshare BD crashes and plain discord autostarts.

**Comment by DeMineArchiver** [comment]
This issue persists from summer and still is not fixed

**Comment by rauenzi** [comment]
I still cannot reproduce this issue, please check this still happens on 1.8.2 and note if this is immediate or if it takes time to crash

**Comment by DeMineArchiver** [comment]
> I still cannot reproduce this issue, please check this still happens on 1.8.2 and note if this is immediate or if it takes time to crash

Well, it was crashing randomly, I would say every 2-10 minutes. A good thing is that I experimented with it, and it turns out that Discord will more likely crash when its window is out of focus. I haven't experienced any crashes since 1.8.2 yet. I will let you know when something changes.

**Comment by flaminHotFledge** [comment]
> I still cannot reproduce this issue, please check this still happens on 1.8.2 and note if this is immediate or if it takes time to crash

I've been having this same issue as well, and would like to chime in about my own experience to hopefully fill some gaps:

There have been semi-consistent crashes from streaming, in my server, playing the new pokemon games. I share the application I use to view my capture card, and everything persists just fine for a while until it suddenly crashes, and boots up regular discord with the option to restart as BD.

Sometimes it can be every hour, sometimes it can be up to three, all I know is that it ends up happening multiple times a night, every night. I am running 1.8.2, with my only additions being a notification sounds overhaul and a theme. I can turn those off and run the program, to follow up with this post, if need be.

**Comment by rauenzi** [comment]
It would be best to reproduce on version 1.8.4 with no plugins or themes even in the folders.
