### ISSUE TITLE
Question about CORS Fix

### ISSUE THREAD

**Issue by SirLennox** [BetterDiscord/BetterDiscord#1006]
Hello,
I have a question and it would be nice if you answer it:
How have you fixed the CORS issue if you fetch a site that isn't in the list of Discords trusted sites, I would like to make a script for vanilla discord and this error occours:
![image](https://user-images.githubusercontent.com/52826781/130634843-7fdf72e0-dbc1-4c88-b400-2f7a98e0fe3f.png)

I just made the same thing with my website and added the header:
Access-Control-Allow-Origin": "*"

but it isn't working too.

I would be happy if you help me with this issue.

**Comment by rauenzi** [comment]
See what observer said. We cannot really affect CORs, but we can remove the CSP.
