### ISSUE TITLE
[Bug] DoubleClicking title bar causes Discord to freeze

### ISSUE THREAD

**Issue by fowlis** [BetterDiscord/BetterDiscord#1008]
**Describe the Bug**
Whenever I double click the title bar to resize the Discord window to fit my screen, Discord completely freezes and nothing visually changes when I click on things, or try `Ctrl` + `R` to reload.
Been testing while writing this, and found that dragging the title bar again will un-freeze the window, but that means it doesn't fit to window after dragging it.

Edit: I've also tried running Discord without BD enabled (via the --vanilla tag thing), and the bug didn't occur.

**To Reproduce**
Double click the title bar to try resize Discord to window

**Screenshots**
Video of working example: https://streamable.com/8royth

**Discord Version**
![image](https://user-images.githubusercontent.com/84232621/130658690-2c22af5b-b874-4ee7-9b51-544406483e11.png)

**Additional Context**
Noticed this bug less than 20 mins ago, not sure which update would have broken it.

**Comment by dav1312** [comment]
Do you have transparency enabled in the BD settings?

**Comment by fowlis** [comment]
> Do you have transparency enabled in the BD settings?
I completely forgot about that, my bad. Disabling it fixes it.

Will close this issue now.
