### ISSUE TITLE
Crash on Discord start

### ISSUE THREAD

**Issue by IamKraZ** [BetterDiscord/BetterDiscord#1012]
Ever since the latest update from Discord I can't get BetterDiscord to not crash. 

As soon as I start Discord, BetterDiscord crashes Discord. Yes it reboots Discord, but all my plugins don't work.

How can I get BetterDiscord to work after a Discord update?

**Comment by doggybootsy** [comment]
1) there's already issues on this
2) this isn't a bd issue it's a plugin issue

**Comment by Crni39** [comment]
You need to manually navigate to plugins folder and delete BDFD Plugin.

**Comment by IamKraZ** [comment]
Awesome thanks. That fixed it.
