### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by alx-alexpark** [BetterDiscord/BetterDiscord#1013]
**Describe the Bug**

Can't install

**To Reproduce**

Install betterdiscord using the installer and choose the default discord installation.

**Expected Behavior**

It installs properly

**Screenshots**

![image](https://user-images.githubusercontent.com/63802868/131264927-f70cce4f-befc-4481-8468-3cafa3be7386.png)

**Discord Version**

Stable 95369 (bcfaed2) Host 0.0.15 Linux 64-Bit (5.10.60)

**Additional Context**

NixOS 21.05 (Okapi)
I used the installer package from the nix repos

**Comment by doggybootsy** [comment]
1) wrong repo
2) theres multiple on this
3) redownload the installer

**Comment by rauenzi** [comment]
See above
