### ISSUE TITLE
[Bug] Enable Transparency hangs up Discord when closing with "Minimize to tray" enabled after moving to other screen

### ISSUE THREAD

**Issue by Londek** [BetterDiscord/BetterDiscord#1014]
**Describe the Bug**
Enable Transparency hangs up Discord when closing after moving to other screen with "Minimize to tray" enabled. Faulty lines are in /injector/src/modules/browserwindow.js:13. I have no idea why it hangs up, looks like its Electron/Discord not directly BetterDiscord issue.

**To Reproduce**
1. Make sure "Minimize to tray" setting is checked (App settings > Windows settings)
2. Enable Transparency setting
3. Restart Discord
4. Move Discord to different monitor
5. Try to close Discord window
6. Discord hangs up now

**Expected Behavior**
It should not hang up, just minimize to tray as usual

**Screenshots**
Made a video on it https://youtu.be/djgs7Ii-hl4

**Discord Version**
Stable 95369 (bcfaed2) Host 1.0.9002 Windows 10 64-bit (10.0.19043)

**Comment by danperks** [comment]
Tested and could not reproduce 
Discord Version Stable 95426, BD 1.2.1

**Comment by rauenzi** [comment]
I am unable to reproduce this either.

**Comment by Londek** [comment]
I have linked a video on this bug, hopefully it will help somehow.

**Comment by rauenzi** [comment]
After playing around with it, I was able to recreate it after also hitting maximize a couple of times before attempting to minimize with the X button. As you noted in your original issue, this is an issue with the underlying electron/Discord setup and we are unable to have hooks deep enough to affect anything like that.
