### ISSUE TITLE
[Bug] Discord not showing new message indicators in text channels

### ISSUE THREAD

**Issue by nefariouslegion** [BetterDiscord/BetterDiscord#1025]
**Describe the Bug**
Sometimes when a new message gets sent to a text channel Discord doesn't show the usual dot and bold text indicating a new message in the channel until I actually click into the Discord window. This happens with no plugins or themes installed

**To Reproduce**
Not sure. But it happens more often than not.

**Expected Behavior**
Discord should show the usual indicators that there is a new message in the channels.

**Screenshots**
Attached ia  video showing the issue. You'll see that there is nothing indicating a new message. But the moment I click into Discord it shows up. This also happens regardless of whether or not the category is collapsed.
https://user-images.githubusercontent.com/89366675/132400624-4a965a6e-802f-4b7c-80f6-1e6e68e04be6.mp4

**Discord Version**
Stable

**Comment by QbDesu** [comment]
I honestly have no idea what you mean, the video only shows the channel list behaving the way it normally does.

**Comment by nefariouslegion** [comment]
The message in that video was there the whole time. Just the channel with the dot and bold text didn't show up until I clicked into discord. I shouldn't have to click into discord to see it though.

**Comment by QbDesu** [comment]
And this is not the case when you are using Discord u modded without BD installed?

If so does it happen without any plugins installed to make sure it's not the fault of a specific plugin?

**Comment by nefariouslegion** [comment]
When I launch Discord unmodded using powershell and --vanilla the issue does not occur.
I've also tried testing without any plugins and themes in the respective folders and the issue still occurs.
