### ISSUE TITLE
[Bug] plugin disables itself if there's no `@name`

### ISSUE THREAD

**Issue by DetachHead** [BetterDiscord/BetterDiscord#1029]
**Describe the Bug**
[The documentation](https://github.com/BetterDiscord/BetterDiscord/wiki/Creating-Plugins#overview) seems to imply that `@name` isn't required as long as you have a `getName` method in your plugin class. however this is not the case as described [here](https://github.com/BetterDiscord/BetterDiscord/wiki/Plugin-and-Theme-METAs#plugins)

when you don't include `@name`, the plugin disables itself when you enable it with no error message explaining why

**To Reproduce**
1. create a plugin with no `@name` field
2. open discord settings > plugins and enable it
3. close discord settings
4. open discord settings > plugins

**Expected Behavior**
plugin still enabled, OR an error message occurs when you first enable it saying that it was disabled because it didn't have a `@name`

**Discord Version**
Canary 97046 (273fda6)

**Comment by Strencher** [comment]
See the documentation about the meta fields here: https://github.com/BetterDiscord/BetterDiscord/wiki/Plugin-and-Theme-METAs#plugins. That doesn't include the second issue.

**Comment by rauenzi** [comment]
From the docs:
> These **functions** are not needed if you add them to the META described in point 3

This does not imply the reverse is true

For context point 3 is:

> Plugin files require a special header (see this page for details)

which links to what Strencher linked that states `@name` is required.
