### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by UnbalancedBlade** [BetterDiscord/BetterDiscord#1035]
**Describe the Bug**
 So just randomly this message started popping up "Animated Status: Error. Report at github.com/toluschr/BetterDiscord-AnimatedStatus". I did not change anything or trigger anything

**To Reproduce**
 
![Screen Shot 2021-09-15 at 8 54 22 PM](https://user-images.githubusercontent.com/90793582/133485984-6f7e5f46-171d-4b2b-8671-6a178e21b89a.png)

**Expected Behavior**
 I mean.. I expected my status to be changing without the red text popping up

**Screenshots**

![Screen Shot 2021-09-15 at 8 54 22 PM](https://user-images.githubusercontent.com/90793582/133486086-46438570-0369-4232-b0b6-e7c1bce6c62b.png)

**Discord Version**

Stable 97097 (0ca818c)
BetterDiscord 1.2.1
Host 0.0.263 OS X 10.10.5 (14.5.0)
**Additional Context**

**Comment by Inve1951** [comment]
not one of ours. that's a selfbot
