### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by ImKill6r** [BetterDiscord/BetterDiscord#1046]
**Describe the Bug**

The betterdiscord works very well for me, the only problem is that after between 2 hours - 5 hours the discord begins to lag, then I go to the task manager and it is consuming 2 GB and I say wtf after a few minutes it crashes I do not know that it can making my ram is fine, I don't know if I have to install any add-on or plugin

**Discord Version**

**Comment by rauenzi** [comment]
> I don't know if I have to install any add-on or plugin

Do you have any plugins already installed?

**Comment by ImKill6r** [comment]
![image](https://user-images.githubusercontent.com/76989969/134034589-8e206613-005d-40cd-be6f-51dd6d254d31.png)

**Comment by rauenzi** [comment]
You have unofficial plugins, I would recommend removing all plugins and seeing if the issue persists.

**Comment by ImKill6r** [comment]
I'll try

**Comment by ImKill6r** [comment]
I tried but the problem is that when I enter several servers, that is, when I click on several and watch several channels, the ram starts to go up and after a few hours it crashes
