### ISSUE TITLE
[Bug] Right Clicking Text Box Sticks Context Menu

### ISSUE THREAD

**Issue by dottiekh** [BetterDiscord/BetterDiscord#1047]
**Describe the Bug**
With no plugins installed/enabled, right clicking in the text entry box will pin the context menu until the program is restarted, instead of repositioning it to the mouse each right click.

**To Reproduce**
1. Right click on the text box after starting BetterDiscord.
2. Right click again in a different part of the text box.

**Discord Version**
Stable

**Comment by fowlis** [comment]
I'd like to assume this isn't a BetterDiscord issue, rather an issue Discord has created (in a recent update perhaps) - I just ran Discord with BD disabled, and I'm experiencing the same thing.

**Comment by dottiekh** [comment]
Is that so? I asked someone not using BetterDiscord to try it and it seemed like it was working fine on their end.

**Comment by fowlis** [comment]
I used a Virtual Machine and completely uninstalled Discord (along with deleting any left-over folders).
Then reinstalled and did some testing.

I found that the "bug" happens with spellcheck disabled.
Try enabling spellcheck and right-clicking in different areas in your text box, and then try with spellcheck disabled.

**Comment by dottiekh** [comment]
Oh wow, that does happen exactly as you described. I have a BD SpellCheck plugin which does seem to disable Discord's default one, so this would happen as if it was disabled. Very bizarre, but yes that does confirm it isn't a BetterDiscord bug.

**Comment by dav1312** [comment]
> that does confirm it isn't a BetterDiscord bug

You can close this issue if that's the case

**Comment by dottiekh** [comment]
Will do.

> I found that the "bug" happens with spellcheck disabled. Try enabling spellcheck and right-clicking in different areas in your text box, and then try with spellcheck disabled.
