### ISSUE TITLE
[Bug] Excessive CPU Usage

### ISSUE THREAD

**Issue by KGX-Rusky** [BetterDiscord/BetterDiscord#1048]
**Describe the Bug**: When Discord (with BD enabled) is started, it takes up to 30% of my CPU to start and instantly crashes shortly after. No plugins or themes were enabled.

**To Reproduce**: Enable BD, open Discord and wait for it to complete booting up.

**Expected Behavior**: Discord boots up as normal.

**Discord Version**: Stable (Fresh BD Installation)

**Relevant System Specs**
CPU: Intel i5-5200U @ 2.20GHz
RAM: 8GB
![image](https://user-images.githubusercontent.com/61017474/134342922-9f12e585-f959-4b9f-9a59-8d46a0fe6af3.png)

**Comment by KGX-Rusky** [comment]
*It crashes shortly after the loading screen if that helps.

**Comment by yourfriendoss** [comment]
Couldn't reproduce on

Stable 99357 (77a2dcf)
Betterdiscord 1.2.1
Windows 10 64bit.
