### ISSUE TITLE
[Bug] Transparency broken on Linux after todays discord update

### ISSUE THREAD

**Issue by Rdeisenroth** [BetterDiscord/BetterDiscord#1050]
**Describe the Bug**

The option for transparent windows seems to be broken after the latest discord update:
when enabled, the background is just Black and i see some weird smeiring when scrolling
(i hope im in the right place to report the bug and that it's not just a theme bug)

**To Reproduce**
Use a fully Transparent Theme (i used frosted glass from theme repo and replaced the background image with rgba(0, 0, 0, 0)) and enable the option

**Expected Behavior**

Transparent Discord Background

**Screenshots**

Current behavior:
![Screenshot_20210922_234501](https://user-images.githubusercontent.com/53945743/134426293-42ede78c-393c-4e62-a218-f63ac268993e.png)
Previous behaviour:
![Screenshot_20210923_124629](https://user-images.githubusercontent.com/53945743/134494844-85aa8cb2-c8f2-4649-b299-fb4f2e473ee9.png)

**Discord Version**

Stable

**Additional Context**

- OS: arch linux
- WM: bspwm
- Compositor: picom (jonaburg fork)

**Comment by Vernoxvernax** [comment]
I have the same problem. Even tried discord-ptb
Arch Linux, Plasma KDE

**Comment by puyoxyz** [comment]
Same here. Arch Linux on KDE Plasma X11, happens after updating to host version `0.0.16`

Temporary workaround: `sudo downgrade discord` and pick 0.0.15, then edit `/opt/discord/resources/build_info.json` so that the version is 0.0.16 to trick it into launching anyways

**Comment by Rdeisenroth** [comment]
I think it might have something to do with the Electron version bump...

With this update they bumped the version of electron from `9.3.5` to `13.4.0` (you can check by typing `process.versions.electron` in the console which can be opened with CTRL+SHIFT+I)

**Comment by Suavevillain** [comment]
I'm having this issue on Manjaro Linux. I can use BD fine but transparency doesn't work.

**Comment by Mrkol** [comment]
Same on stock ubuntu 21.10 :(

**Comment by marcoshsbosco** [comment]
> Same here. Arch Linux on KDE Plasma X11, happens after updating to host version `0.0.16`
> 
> Temporary workaround: `sudo downgrade discord` and pick 0.0.15, then edit `/opt/discord/resources/build_info.json` so that the version is 0.0.16 to trick it into launching anyways

Same problem here, but I couldn't get puyoxyz's fix to work on my end. Running `Arch Linux x86_64 | Plasma 5.23.3 | KWin | X11`

**Comment by ilexite** [comment]
Same here.

OS: Manjaro
WM: DWM

**Comment by GlowingUmbreon** [comment]
This is also a issue with my system
AwesomeWM + picom.

**Comment by Rdeisenroth** [comment]
> Same here. Arch Linux on KDE Plasma X11, happens after updating to host version `0.0.16`
> 
> Temporary workaround: `sudo downgrade discord` and pick 0.0.15, then edit `/opt/discord/resources/build_info.json` so that the version is 0.0.16 to trick it into launching anyways

This worked great until 0.0.17 arrived.
Now discord will no longer launch if you try to set it to 0.0.15...

Interestingly, if i switch to wayland (which is still quite buggy for me) the transparency seems to work flawlessly

**Comment by HVisMyLife** [comment]
Any updates on this? I have same problem on Arch + sway..

**Comment by AbhayAysola** [comment]
Yeah, same problem here. Using arch with sway and picom

**Comment by Foresteam** [comment]
The same problem. Manjaro, KDE

**Comment by fun840** [comment]
Arch / KDE, can confirm. It was working for a few hours, and then something changed (I updated the system, or rebooted or something else) and it broke. Reinstalling BD / Discord doesn't work at all, and I can't downgrade to an older version.

**Comment by sus-impost0r** [comment]
It may be more feasible to use a compositor  like picom.

**Comment by mmmsoup** [comment]
I'm having the same problem as well (awesomewm and picom)

**Comment by MeowIce** [comment]
Same here
Fedora 36 with GNOME 42

**Comment by Fancy2209** [comment]
Same here, HW Acceleration disabling doesn't work

**Comment by CorruptedPlazma** [comment]
I see this as well with my recent installation of BD for experimentation purposes. I'm using Ubuntu 22.04 LTS on Gnome 42 on Wayland. Transparency is enabled in settings, and I've tried everything with modifying the theme I'm using (Dark Matter), also trying to insert `{background: transparent!important;}` in the custom CSS page. It all leads me to simply a black background and nothing more.

**Comment by asier-ochoa** [comment]
After updating discord, all I get is a black background with lots of ghosting.

**Comment by FakeMichau** [comment]
Launching Discord with a switch `--use-gl=desktop` allows for use with hardware acceleration and the performance is much better

**Comment by HVisMyLife** [comment]
@FakeMichau Thanks, --use-gl=desktop works perfectly, but that second flag gives blank ( gray ), but clickable ( buttons, etc are simply invisible ) window...

**Comment by rauenzi** [comment]
> I can confirm transparency works in the newest discord version only after disabling hardware acceleration.

Can anyone else confirm this?

**Comment by snoweuph** [comment]
using `--use-gl=desktop` worked under picom and i3

**Comment by Vernoxvernax** [comment]
Also working on:
Kwin; Plasma KDE
Stable 153481 (c00173e)
Host 0.0.20

**Comment by Vernoxvernax** [comment]
> Also working on: Kwin; Plasma KDE Stable 153481 (c00173e) Host 0.0.20

By "working" I am referring to there being at least transparency.
Unfortunately it also adds these flashing artifacts:
https://i.imgur.com/h9FIH2u.png
They do enhance your dnb listening experience a little bit though.

Hopefully this can be fixed as well.

**Comment by rauenzi** [comment]
Unfortunately this is not something BD handles, we simply tell electron to enable transparency mode.
