### ISSUE TITLE
[Bug] Discord Freezes when out of focus

### ISSUE THREAD

**Issue by xenos1337** [BetterDiscord/BetterDiscord#1051]
**Describe the Bug**
Every time I tab out / Discord, not in focus discord freezes, and when I tab back in / Discord is in focus everything shows again as usual. It gets very annoying when you're playing a game and you don't instantly see all your friends messages

**To Reproduce**
Put a window above Discord

**Expected Behavior**
Discord should not freeze and should just show the window and every message normal even tho it's not focused

**Screenshots**
https://youtu.be/r-Jr87AwxEQ

**Discord Version**
Only tried on Stable

**Additional Context**
None

**Comment by yourfriendoss** [comment]
Couldn't reproduce on

Stable 99357 (77a2dcf)
Betterdiscord 1.2.1
Windows 10 64bit.

**Comment by xenos1337** [comment]
fixed after latest update
