### ISSUE TITLE
[Bug] Cannot install/reinstall BD 

### ISSUE THREAD

**Issue by cctong12** [BetterDiscord/BetterDiscord#1052]
**Describe the Bug**

**To Reproduce**
1. Launch BD
2. Repair BD
3. Re-install BD

**Expected Behavior**
Able to reinstall BD and launches with Discord

**Screenshots**
Starting Install...

Creating required directories...
✅ Directory exists: C:\Users\Citrus\AppData\Roaming\BetterDiscord
✅ Directory exists: C:\Users\Citrus\AppData\Roaming\BetterDiscord\data
✅ Directory exists: C:\Users\Citrus\AppData\Roaming\BetterDiscord\themes
✅ Directory exists: C:\Users\Citrus\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
❌ Failed to download package https://api.github.com/repos/rauenzi/BetterDiscordApp/releases
❌ Cannot read property 'assets' of undefined

The install seems to have failed. If this problem is recurring, join our discord community for support. https://discord.gg/0Tmfo5ZbORCRqbAd

**Discord Version**
Stable 98534 (4e1aa2c) Host 1.0.9003 Windows 10 64-Bit (10.0.19042)

**Additional Context**

**Comment by doggybootsy** [comment]
One there's many issues on this
Two wrong repo 

Redownload your installer
