### ISSUE TITLE
[Bug] Fullscreen not working properly

### ISSUE THREAD

**Issue by madmagic007** [BetterDiscord/BetterDiscord#1053]
**Describe the Bug**
winkey + up arrow doesnt maximize discord.
moving the window to the top of the screen and releasing it doesnt maximize it either.
using the fullscreen button isnt actually fullscreen, as wallpaper engine (and all other apps) detect discord as windowed.

uninstalling bd fixes this issue completely, as soon as i reinstall its an issue again. disabling all themes/plugins doesnt resolve this.
reinstalled discord, no issue. installed bd, issue happens again.

**To Reproduce**
have betterdiscord installed

**Expected Behavior**
windows key + arrows working like they should.
dragging the winow to the top or sides should work.

**Screenshots**
https://youtu.be/D7Y2NAAg75c

**Discord Version**
latest stable

**Comment by doggybootsy** [comment]
If you have transparency enabled it will do that

**Comment by madmagic007** [comment]
that does indeed seem to be the case. the one setting i forgot to try out.
