### ISSUE TITLE
BD won't install with changed filename

### ISSUE THREAD

**Issue by rejakor** [BetterDiscord/BetterDiscord#1057]
**Describe the Bug**
W10, typical laptop default setup
windows renames installer exe as i've just autodownloaded it to Downloads
puts a (1)
installer now won't let me install (can't tick 'read' on the eula)
until I rename the exe back to the original name (and delete the other)

**To Reproduce**
give the installer exe any name other than the one it comes with to reproduce

**Expected Behavior**
exe should install regardless of what it is called, or at least with common windows renaming scheme

**Discord Version**
stable/installer issue

**Comment by rauenzi** [comment]
The issue with the checkbox is unrelated to the filename see #1036
