### ISSUE TITLE
New release w/o disclosing source changes

### ISSUE THREAD

**Issue by yT7Af9Fc** [BetterDiscord/BetterDiscord#1059]
**Describe the Bug**
The `betterdiscord.asar` file has been changed in the latest release
https://github.com/BetterDiscord/BetterDiscord/releases/tag/v1.2.1
But **no commits were made** to the repository

MD5 of `betterdiscord.asar`
- From the `main` branch
  - `2f8e007e77771bb33ec97dcfe277b25d`
- From the `bugfix/addon-file-change-treated-as-new-addon`  branch 
  - `0015aa09fe1c9f2d796d5c80aa56ab1b`
- The latest release
  - `dffcd517c140e91b3b39b616a697b0b3`

---

**Expected Behavior**
If the project wants to still claim itself as open source disclose the changes and make a new release (1.2.2 or 1.3.0) instead of replacing the asar file.

---

**Screenshots**

<details>
<summary>
The <code>betterdiscord.asar</code> had more than 300k downloads and now it has 25k which means that the file has been replaced.
</summary>

![image](https://user-images.githubusercontent.com/86932864/134814622-9d3c3b23-b356-4583-83ae-00ab66ca1e5b.png)
</details>

**Comment by rauenzi** [comment]
This was a temporary patch for MacOS which was experiencing crashing issues. The version was not changed because it would cause update notices to all users but the vast majority did not need the patch.

**Comment by yT7Af9Fc** [comment]
> This was a temporary patch for MacOS which was experiencing crashing issues. The version was not changed because it would cause update notices to all users but the vast majority did not need the patch.

That doesn't matter **at all**.
No one would have complained about having to update BetterDiscord when **updates happen once every two months**. 
Now if a Mac user wants to compile BD manually they won't even get the "temporary patch".
Also sadly for the project you removed 300k downloads from the counter...

**Comment by rauenzi** [comment]
> Also sadly for the project you removed 300k downloads from the counter...

I'm really not a stickler for the numbers.
