### ISSUE TITLE
[Bug] The Flatpak version of Discord crashes upon trying to install BD

### ISSUE THREAD

**Issue by TGRush** [BetterDiscord/BetterDiscord#1061]
**Describe the Bug**
The Flatpak version of Discord crashes with a fatal Javascript error after installation, even after trying the repair options

**To Reproduce**
- Install some recent Linux distro with Flatpak and Flathub built in
- install Discord through flatpak: `flatpak install discord -y`
- get the BetterDiscord appimage
- install it under ~/.var/app/com.discordapp.Discord/config/discord
- kill Discord if needed and try running it again

**Expected Behavior**
Discord launches and shows the BetterDiscord changelog

**Screenshots**
https://imgur.com/a/nLgtgth

**Discord Version**
Stable 0.0.16

**Comment by guihkx** [comment]
https://github.com/BetterDiscord/Installer/issues/26

If you want, you can try my modified version of the installer, with Flatpak support: https://github.com/guihkx/Installer/releases
Or you can also try betterdiscordctl: https://github.com/bb010g/betterdiscordctl

**Comment by TGRush** [comment]
Oh damn, Thanks!
I wonder how i missed that issue even though i searched for "Flatpak" and "Linux" before opening, either way i guess for now this is closed
Thanks once again!
