### ISSUE TITLE
[Bug] Multitasking funtion Not Working with BetterDiscord

### ISSUE THREAD

**Issue by qbycode** [BetterDiscord/BetterDiscord#1065]
The multitasking function that helps to enlarge the application only by hitting it against the top of the screen has completely lost its operation, with themes, and whithout them. 

![image](https://user-images.githubusercontent.com/91386213/135701111-a9d46157-7e63-4b12-9b0e-ec00980dfb1d.png)
![image](https://user-images.githubusercontent.com/91386213/135701396-5185fd2a-6de1-4b85-a433-1573161567e0.png)

(note: im using Windows 11)

**Comment by doggybootsy** [comment]
Transparency does that

**Comment by qbycode** [comment]
> Transparency does that

so, if i disable transparency, should be fix it, no?

**Comment by qbycode** [comment]
> > Transparency does that
> 
> so, if i disable transparency, should be fix it, no?

oh, thanks, and isnt any solution to the multitask, WITH trasparency?

**Comment by doggybootsy** [comment]
I don't think there is, I can be wrong I don't know much about windows

**Comment by rauenzi** [comment]
No it is an issue with Electron itself and how it handles window management. This is not something we can fix on our end.
