### ISSUE TITLE
[Feature] ARM64 builds

### ISSUE THREAD

**Issue by adiantek** [BetterDiscord/BetterDiscord#1070]
Discord doesn't have ARM64 builds for M1 and SPX. is this possible that BetterDiscord will add support to ARM64 before official Discord? I know it's crazy question, but I'm curious xD

https://support.discord.com/hc/en-us/community/posts/360054793351-Discord-for-Windows-10-ARM64

Electron has ARM64 support: https://github.com/electron/electron/releases/tag/v7.0.0

**Comment by rauenzi** [comment]
As this project is meant to modify _existing_ Discord installations, this is not something we can/will add. Sorry!

**Comment by adiantek** [comment]
Ok, thanks for very quickly answer!

**Comment by julien-blanchon** [comment]
Discord Canary has actually a well functionning arm build

**Comment by KristenTidmuss** [comment]
Hey, this feature is now in the Discord PTB build. Is it something you would look to implement? Or do you need to wait for it to reach stable
