### ISSUE TITLE
[Bug] Minimal mode no longer correctly displays servers

### ISSUE THREAD

**Issue by ghost** [BetterDiscord/BetterDiscord#1076]
**Describe the Bug**
Minimal mode no longer correctly displays servers on the left-hand side. Every server icon is shifted to the right (presumably to be in its original position). This happens inside folders as well.

**To Reproduce**
Turn on minimal mode.

**Expected Behavior**
Every icon should be in the middle of the dark-gray bar instead of leaning towards the right-hand side of said bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/74354386/136662898-1bfbb077-008f-4967-b0bc-35f29ca7ab87.png)

**Discord Version**
Stable 100804 (26e978a)
BetterDiscord 1.2.1

**Comment by TheForgottenKing** [comment]
Same issue

Stable 100804 (26e978a)
BetterDiscord 1.2.1
Host 1.0.9003 Windows 10 64-Bit (10.0.22471)

Also occurs in folders

**Comment by maisoncastro** [comment]
Minimal Mode on my end isn't doing anything anymore. It's not making it small anymore.
BetterDiscord 1.4.1

**Comment by Acumane** [comment]
@maisoncastro It's been replaced w/ this standalone [theme](https://betterdiscord.app/theme/MinimalMode)
