### ISSUE TITLE
[Feature] Plugin data api improvements

### ISSUE THREAD

**Issue by QbDesu** [BetterDiscord/BetterDiscord#1079]
Proposed changes:
`BdApi.saveData`, and `BdApi.deleteData` should not synchronously write it's changes to the disk but asynchronously
`BdApi.syncData` should be introduced to sync the data to the disk synchronously. (similar to the sync filesystem operation)
`BdApi.loadData` should return the full data object if no key is provided.

Other potential improvements:
BD could automatically load all `.config.json` files in the plugin folder asynchronously. `BdApi.loadData` or rather `ensureData` would still load it synchronously if the file wasn't ready already. The async load couldn't be stopped but it should detect that it was loaded synchronously prior and not save the loaded data in the datastore in case there was a prior `BdApi.saveData` call already.

**Comment by rauenzi** [comment]
Plugin data will be completely reworked in the new addon system/api, I will not be adding this in the interim
