### ISSUE TITLE
[Bug] Pop Out screenshare doesnt work with BD

### ISSUE THREAD

**Issue by mikedrugs** [BetterDiscord/BetterDiscord#1082]
**Describe the Bug**
When you try to pop out a stream to a new window, the window cant be opened, you cant click on it and it wont show anything

**To Reproduce**
install bd
you cant pop out streams to a new window anymore

**Expected Behavior**
it should work

**Screenshots**
![image](https://user-images.githubusercontent.com/88536465/138210463-2dc78bde-d900-49af-ae05-91c7ccd20ed3.png)

![image](https://user-images.githubusercontent.com/88536465/138210363-3633c0b0-b9f8-4606-8962-0c5930735e9e.png)

**Discord Version**
Stable, Windows 10 pro

**Additional Context**

**Comment by Ign1s-Reiga** [comment]
I had a similar problem with mikedrugs in my environment

Stable 103255 (ae3387d)
BetterDiscord 1.2.3
Host 1.0.9003
Windows 10 64-Bit (10.0.19043)

**Comment by sean22922** [comment]
Having same problem. Environment shown as below.

Stable 103508 (42e6c51)
BetterDiscord 1.2.4
Host 1.0.9003
Windows 11 64-Bit (22000.282)

Plugins and Theme list:
- BDFDB v1.9.7
- BetterFormattingRedux v2.3.12
- CharCounter v1.5.6
- CreationDate v1.4.6
- ImageUtilities v4.5.3
- ZeresPluginLibrary v1.2.33
- ServerDetails v1.1.0
- NotAnotherAnimeTheme

**Comment by rauenzi** [comment]
Is this still occurring for you?

**Comment by sean22922** [comment]
> Is this still occurring for you?

Nope, not anymore.
