### ISSUE TITLE
[Feature] Option to Pin Channels on category collapse

### ISSUE THREAD

**Issue by TheVaccin3** [BetterDiscord/BetterDiscord#1089]
I am in a server with a lot of channels/categories. I only look at some categories, and only some of the channels within those categories. I have the channels that I dont look at muted and I also like to keep the categories minimized so I dont have to keep scrolling as much. But then I can't see all the channels I actually care about when they are minimized. 

So, I wanted to know if it was possible to add a feature where I can pin certain channels in a category so that when I collapse a category, those pinned channels still show and do not get minimized. 

eg:
category 1: (not collapsed)
    (muted) channel 1
    (muted) channel 2
    (muted) channel 3
    channel 4
    channel 5 (unread msg)

currently when I collapse, I only see unmuted channels with unread so I see this:
category 1: (collapsed)
    channel 5 (unread msg)

I want to get a way so that I can see all unmuted categories:
category 1: (collapsed)
    channel 4
    channel 5 (unread msg)

I don't know if this makes sense. if it doesnt, just ask.

**Comment by rauenzi** [comment]
Yeah I would recommend suggesting this to plugin devs, this is outside of BD's scope
