### ISSUE TITLE
Mousing to corner does not highlight close button [Bug]

### ISSUE THREAD

**Issue by Alb11747** [BetterDiscord/BetterDiscord#1095]
**Describe the Bug**
Mousing to corner does not highlight close button rather switches to window resize. The cause may be due to the window not being in actual full screen.

**To Reproduce**
Mouse to corner.

**Expected Behavior**
Mousing to corner should highlight close button.

**Screenshots**
On corner
![image](https://user-images.githubusercontent.com/40252880/139515668-600d914d-6555-45b4-a4f7-dafd76f1cfdb.png)
Off corner
![image](https://user-images.githubusercontent.com/40252880/139515664-cc1ef4dd-5da6-4b35-a656-91413bd6a4f4.png)
Expected (Example: Chrome)
![image](https://user-images.githubusercontent.com/40252880/139515672-45d055d1-f111-4eb7-b10d-a6e1d05a854c.png)

**Discord Version**
Stable v6.1.2

**Additional Context**
Windows 11

**Comment by dav1312** [comment]
How is this an issue caused by BetterDiscord?
This is how all apps work (including chrome)

**Comment by Alb11747** [comment]
It works properly in normal Discord.
![image](https://user-images.githubusercontent.com/40252880/139566159-c2fc28c8-7388-4002-909d-4363a5dcbb55.png)

In chrome and other apps mousing to the very corner highlights the close button and makes it clickable. In BetterDiscord the button is not clickable but instead, clicking starts to resize the window.

This video explains why this is a bad design choice. (5:15-6:29)
https://youtu.be/E3gS9tjACwU?t=315

**Comment by dav1312** [comment]
Discord
![cursordiscord](https://user-images.githubusercontent.com/63931154/139579160-38f7ac40-067e-4c90-924a-5512762c9927.gif)
Chrome
![cursorchrome](https://user-images.githubusercontent.com/63931154/139579207-cd462e3b-e9a8-4517-9a59-2e714ffd364f.gif)

**Comment by Alb11747** [comment]
I was referring to when it was in fullscreen

**Comment by Alb11747** [comment]
The screenshot was in fullscreen it's just the program I used to take it (Steps Recorder) added the green border (The only program I could find that includes the cursor). I didn't know that transparency mode caused this behaviour. If this is the intended behaviour for transparency mode you can close this issue. Though I'm not sure why transparency mode would cause this issue.
