### ISSUE TITLE
[Bug] Crash while switching accounts

### ISSUE THREAD

**Issue by miles352** [BetterDiscord/BetterDiscord#1096]
**Describe the Bug**
Switching accounts using the new account switch feature crashes Betterdiscord

**To Reproduce**
Switch accounts using new account switch feature

**Expected Behavior**
Betterdiscord to act like it's just starting up

**Discord Version**
Stable 103016

**Comment by Inve1951** [comment]
Account switching is still an experimental discord features. BD will never add special support for discord's "experiments". If they don't work, they don't work.
If this still happens after the feature leaves the experimental stadium, it will be addressed.

**Comment by dav1312** [comment]
> Account switching is still an experimental discord feature.

They pushed it to stable as a "beta" feature a couple of weeks ago (when this issue was opened)
![image](https://user-images.githubusercontent.com/63931154/141325201-999d9c0d-7458-4144-92e6-8eea9295dd7d.png)

**Comment by Inve1951** [comment]
that changes things, thanks for pointing out the mistake

**Comment by CubergDev** [comment]
Can recreate this, with this function in beta, AND this function is enabled by default (stable)
Discord version: Stable 104752
BetterDiscord 1.2.4

**Comment by kateisprettydamngreat** [comment]
can confirm it occurs with all themes and plugins off

**Comment by CubergDev** [comment]
UPD: Doesn't crash anymore
