### ISSUE TITLE
[Issue] No means of loading an external script with the expectation that it will be loaded when it comes time to use it.

### ISSUE THREAD

**Issue by Jkmcameron** [BetterDiscord/BetterDiscord#1098]
As it stands, any time I try to load an external script and call a function from it in either my `onSwitch` method or `observer` methods of my plugin, I get a fat error when the client tries to load and start the plugin because inevitably the function is "undefined". I have experimentally verified that with how the current system works BetterDiscord will *always* try to use an external script before it has actually loaded.
```
load()
{
  console.log(0)
}

start()
{
  console.log(1)
  var script    = document.createElement("script");
  script.type   = "application/javascript";
  script.src    = "https://...";
  script.onload = function() { console.log(2) };
  document.head.appendChild(script);
}

observer(e)
{
  console.log(3)
}
```
![image](https://user-images.githubusercontent.com/14365419/139559348-02f0bf44-df29-45f6-bc67-8fd6cc1a002a.png)

As you can see, even when loading the script in my `start` method it will never be loaded in time to use it in `observer`. This is why any time I've tried to do so in the past I have been met with a glaring error when the plugin is loaded. The only way I see to get around this is to set the value of a boolean in the `onload` of my script and then check against that value before attempting to call any function in the script, but that is clunky and less than ideal. Worse still, with the `linkJS` function suplied by `BdApi` even this measure is not possible since the user does not have access to the internal document element to modify its `onload` method. As such, I cannot image `BdApi.linkJS` being functionally useful in any capacity if not only will the linked script not be loaded when you intend to use it, but you also have no means to check when it has been laoded.

**Comment by rauenzi** [comment]
If you absolutely require this functionality, then yes the boolean method is effective, you can also simply make use a promise and await the promise to avoid the boolean. However remote linking is deprecated so no improvements to `linkJS` will be made.
