### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by dreamylands** [BetterDiscord/BetterDiscord#1099]
**Describe the Bug**
BD only showing settings tab

**To Reproduce**
fresh install of better discord 

**Expected Behavior**
I could be able to see other tabs like themes , plugins etc.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/83451031/139715857-8b20e5f6-c2c1-457b-988b-10d9b0e55e6d.PNG)

**Discord Version**
Stable

**Additional Context**
I also tried it on canary and same result . I even tried reinstalling twice but no luck

**Comment by zachjmurphy** [comment]
I'm getting the same exact issue.

**Comment by tracedgod** [comment]
Same problem. Tried reinstalling a few times no result. My plugins and themes are still located in AppData dir, but nothing besides the settings menu is loading.
![bd](https://user-images.githubusercontent.com/6174563/139738506-18c43200-b98e-403f-821d-05505b6a56b6.png)
.

**Comment by Nanolocity** [comment]
Same problem here, I removed all the plugins and themes from their folders and it still doesn't reapper. I uninstalled BetterDiscord, repeaired it and it still doesn't work. 
![image](https://user-images.githubusercontent.com/83247672/139739803-f6712292-a1d2-4f2e-bfc2-15c5ca23398d.png)

**Comment by rauenzi** [comment]
Fixed with latest release

**Comment by dreamylands** [comment]
still having the issue in the new update

**Comment by k4zo** [comment]
can confirm not fixed
