### ISSUE TITLE
[Bug] Opening the CSS editor to a detached window causes everything to dissappear.

### ISSUE THREAD

**Issue by identity7** [BetterDiscord/BetterDiscord#1102]
**Describe the Bug**
Detaching the CSS editor causes everything but the editor to go away, and this is only fixed with a restart.

**To Reproduce**
Detach the css editor

**Expected Behavior**
To detach normally

**Screenshots**
Right after detaching it -> https://i.imgur.com/xcxcIBU.png

After closing the editor -> https://i.imgur.com/MrTMPcA.png

**Discord Version**
Stable

**Additional Context**
I have disabled all my plugins and themes. It does this whether you detach it through the editor or have it detach on opening

**Comment by TheGreenPig** [comment]
You can press escape after detaching the window to display everything again. It's not ideal, but it should work for the time being...(Thanks DemetedElmo for telling me this)
