### ISSUE TITLE
1.2.4 broke my theme

### ISSUE THREAD

**Issue by DJS3M3N** [BetterDiscord/BetterDiscord#1103]
I'm use Alexis Modern Discord Theme (https://betterdiscord.app/theme/Alexis%20Modern%20Discord%20Theme) and after update, horizontal server bar stopped working (I can only click on servers in folders)

**Comment by doggybootsy** [comment]
discord changed the classes on the guild

**Comment by DJS3M3N** [comment]
Maybe i can backup to 1.2.3?

**Comment by SmolAlli** [comment]
This is not a BD issue. Make an issue with the theme developer and they will fix it.

**Comment by DJS3M3N** [comment]
> discord changed the classes on the guild

Can i fix this?

**Comment by DJS3M3N** [comment]
> This is not a BD issue. Make an issue with the theme developer and they will fix it.

Ok, sorry
