### ISSUE TITLE
Sideways server selection [Bug]

### ISSUE THREAD

**Issue by ItsLeon15** [BetterDiscord/BetterDiscord#1105]
**Describe the Bug**
The server bar is rotated sideways, refreshing doesn't fix the issue

**To Reproduce**
Unknown reproduction methods

**Expected Behavior**
Rotated to fix the screen roation. 

**Screenshots**
![image](https://user-images.githubusercontent.com/64979109/139961153-16451ab8-ce52-4258-838b-5e91876981e1.png)

**Discord Version**
Stable

**Comment by dav1312** [comment]
This is not a BetterDiscord issue, its a theme issue

**Comment by SmolAlli** [comment]
^ Please tell the theme developer about this bug so that they can fix it.
