### ISSUE TITLE
When using 0.0.51 I get JavaScript Error Occurred in the main Process

### ISSUE THREAD

**Issue by PluckLion** [BetterDiscord/BetterDiscord#1108]
**Describe the Bug**
<Uncaught Exception:
C:\User\name\AppData\Roaming\BetterDiscord\data\betterdiscord.asar\injector.js:1
(0=>{"use strict",var e={n.s=>{var n=s&s._esModule?()=>s.default:()=>;return
e.d(n,{a:n}),n},d:(s,n)=>{for(var t in
n)e.o(n,t)&&!e.o(s,t)&&Object.def,,,,   The code continues on a JavaScript Error page. 

Syntax Error: Unexpected token '.'
at module._compile (internal/modules/cjs/loader.js:815:22)
  There is more to this error. 

**To Reproduce*
Install ptb 0.0.51 and run your better discord for it. It won't work on this version for some reason it throws this error out upon opening ptb discord. 

**Expected Behavior**
<I was hoping for better discord to work on this version 

**Screenshots**
<!-- If appl
![Error 10_30_2021 5_11_28 AM](https://user-images.githubusercontent.com/93794430/140571441-6d918eea-4b83-4e9a-a0d8-f9a7e218550e.png)
icable, 

**Discord Version**
PTB 0.0.51

**Additional Context**
Can you please let me know why this is happening? Thank you. -Lion

**Comment by PluckLion** [comment]
![Error 10_30_2021 5_11_28 AM](https://user-images.githubusercontent.com/93794430/140571588-2311393a-b993-4ef4-ad70-f11eafaebe15.png)

**Comment by rauenzi** [comment]
Your PTB is out of date and unsupported.
