### ISSUE TITLE
Member list visual bug

### ISSUE THREAD

**Issue by Deltaaaaaaaa** [BetterDiscord/BetterDiscord#1109]
**Describe the Bug**
The side, where the members are, appears default no matter the theme.

**To Reproduce**
Open Discord.

**Screenshots**
![kép_2021-11-06_110656](https://user-images.githubusercontent.com/93820663/140605869-10f5b0ed-f695-48b3-ad32-6a897423bb54.png)

**Discord Version**
Stable

**Comment by doggybootsy** [comment]
This isn't a betterdiscord, leave an issue on your themes GitHub if there isn't one already on it

**Comment by TheCommieAxolotl** [comment]
as @doggybootsy said, not a bd issue. Discord changed classes again.
for the meanwhile put this into your custom css at the top
```css
.container-2wlB3z {
  background: transparent !important;
}
```
