### ISSUE TITLE
Can't install BetterDiscord on macOS Monterey 12.1 Dev Beta 2

### ISSUE THREAD

**Issue by mainhathao** [BetterDiscord/BetterDiscord#1112]
![image](https://user-images.githubusercontent.com/48293860/141010382-e4476a4d-5d77-4279-b85a-2db8e26f1952.png)

**Comment by mainhathao** [comment]
Updated screenshot

![Screen Shot 2021-11-10 at 4 49 56 AM](https://user-images.githubusercontent.com/48293860/141010530-5a54b9b5-d939-46c8-a9b6-78e27cfe563b.png)

**Comment by doggybootsy** [comment]
1) Wrong GitHub repo
2) join the support server and they should have a fix for it

**Comment by rauenzi** [comment]
Make sure you have the latest version of the installer, if the issue repeats open an issue on the Installer repo
