### ISSUE TITLE
[Bug] Failed to download package; Cannot read property 'assets' of undefined

### ISSUE THREAD

**Issue by user-levin** [BetterDiscord/BetterDiscord#1113]
**Describe the Bug**
Installation error

**To Reproduce**
I have uninstalled Discord a few times. Always the same error.

**Expected Behavior**
Start Better Discord.

**Screenshots**
![image](https://user-images.githubusercontent.com/72907873/141100892-ba565b4d-518d-4f74-a122-95e07ada6378.png)

**Discord Version**
October 4, 2021

**Comment by SmolAlli** [comment]
1. This is not the correct repository. You should use the https://github.com/betterdiscord/installer repository to report issues.
2. This is a **common** issue with the BetterDiscord repository, and it means that you have an old installer. Get a new one from https://betterdiscord.app
3. Ask in the BetterDiscord server next time - https://betterdiscord.app/invite
