### ISSUE TITLE
BetterDiscord crashes my discord when I try to put in a GIF, Sticker, or Emoji

### ISSUE THREAD

**Issue by Sparrow-05** [BetterDiscord/BetterDiscord#1116]
**Describe the Bug**
Discord shows a 404 screen after clicking on the GIF, sticker, or Emoji icon

**To Reproduce**
Install BetterDiscord, click on the GIF, sticker, or Emoji icon

**Expected Behavior**
GIF, sticker, or Emojis should open to be placed

**Screenshots**
https://gyazo.com/04bfe2a7d2fa554ac46d3f962ba0c8bc (with BetterDiscord installed)

https://gyazo.com/c8c14b8f7a8c657ff4986199803ca70e (without BetterDiscord installed)

**Discord Version**
Stable

**Additional Context**
The problem is with BetterDiscord, as when I uninstall BetterDiscord, this no longer happens

**Comment by AlienXAXS** [comment]
Stack trace if it's of any help:

`cce880051e247eefbd29.js:130 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at nl (29b0241324f43bcdb80c.js:6045)
    at e (29b0241324f43bcdb80c.js:5984)
    at Bo (29b0241324f43bcdb80c.js:5996)
    at $s (29b0241324f43bcdb80c.js:6041)
    at Gu (29b0241324f43bcdb80c.js:6031)
    at Uu (29b0241324f43bcdb80c.js:6031)
    at wu (29b0241324f43bcdb80c.js:6031)
    at Au (29b0241324f43bcdb80c.js:6028)
    at 29b0241324f43bcdb80c.js:5973
    at t.unstable_runWithPriority (29b0241324f43bcdb80c.js:6272)
    at Ki (29b0241324f43bcdb80c.js:5973)
    at Xi (29b0241324f43bcdb80c.js:5973)
    at qi (29b0241324f43bcdb80c.js:5973)
    at we (29b0241324f43bcdb80c.js:6050)
    at en (29b0241324f43bcdb80c.js:5950)
    at HTMLDivElement.r (cce880051e247eefbd29.js:126)
(anonymous) @ cce880051e247eefbd29.js:130`

**Comment by rauenzi** [comment]
This sounds like a plugin issue. Have you tried removing all plugins and seeing if the issue persists?

**Comment by AlienXAXS** [comment]
Yes, removing all plugins and themes still results in the crash.
I also attempted to reinstall Better Discord.

**Comment by trilliana161** [comment]
I have also run into the issue. I've wiped plugins and theme to no avail but disabling BD's Emote System seems to fix it.

**Comment by SmolAlli** [comment]
Looks like it's an issue with ZeresPluginLibrary. This is what I got before the "minified react" https://pastebin.com/VSntuxQu
Stable 104513/BD 1.2.4/Win 10

**Comment by rauenzi** [comment]
@SmolAlli that callback chain actually indicates RemoveChatButtons.plugin.js not the library

As for the larger issue, it could be due to the emote system

**Comment by SmolAlli** [comment]
It appears that there has been some sort of re-work/change with the GIFs favourite menu.
Also the issue for the emote system seems to be with this specific option.
![image](https://user-images.githubusercontent.com/22519967/141387016-218eede4-eab6-48d1-b273-a4df8debe399.png)

**Comment by DreiKamm** [comment]
since its not mentioned here this is how you solve the problem
![image](https://user-images.githubusercontent.com/45890758/141398921-a8ba3ec0-c0dd-4e6a-909e-fc949f55e82f.png)

**Comment by Veyral** [comment]
Can confirm this as well

**Comment by rauenzi** [comment]
Comments like this do not help. For those experiencing this issue, disable BD's emote menu setting and also disable (or update if available) any plugins related to GIFs, tickers, or emojis.

**Comment by tort-oise** [comment]
![image](https://user-images.githubusercontent.com/81963124/141487533-c14fb0f6-5871-4c42-ad00-f76153b43973.png)
Context for the setting mentioned above. Again, some plugins might have fixes, other might not.

**Comment by tort-oise** [comment]
> It appears that there has been some sort of re-work/change with the GIFs favourite menu. 

I saw somewhere mentioned that favourited/saved GIFs are now uploaded to a server, so that they don't disappear. Also introducing a new limit (around 256 or so) for favourited/saved GIFs. 
This removes the need for plugins like gifsaver, which also removes itself after this change. 
Maybe this new feature could be causing it. (most likely, as FavoriteMedia, another plugin, implemented fixes that stop Discord from crashing whenever the emoji menu is opened just recently)

**Comment by vyralove** [comment]
I have 0 plugins installed. I disabled BD's emote system, and I still get this issue. 
Though, I do have ClearVision theme installed. When I disabled this theme, the issue goes away. So, I guess I won't be using ClearVision for a while. xD; Time to find an alternate that works for now.

**Comment by SmileDaemon** [comment]
> ![image](https://user-images.githubusercontent.com/81963124/141487533-c14fb0f6-5871-4c42-ad00-f76153b43973.png) Context for the setting mentioned above. Again, some plugins might have fixes, other might not.

Had the issue as well, can confirm this works.

**Comment by Drflash55** [comment]
![image](https://user-images.githubusercontent.com/13694448/141603082-9b9f6538-b364-484b-b69f-c24cf3d24946.png)

Disabling BD's Emote System fixes the issue for me.
Seems like something happened that makes it crash all the time. I guess I'll have to leave it off until a fix is implemented.

**Comment by bobsyc** [comment]
guys it wurk no way no cap a trsut 103% legit method

**Comment by chanhh01** [comment]
Thanks, it worked
![](https://im7.ezgif.com/tmp/ezgif-7-6891b200beb7.gif)

**Comment by rauenzi** [comment]
Fix has been released, please update to 1.3.0.
