### ISSUE TITLE
crash when using emoji

### ISSUE THREAD

**Issue by HELLSNAKES** [BetterDiscord/BetterDiscord#1119]
crash when using emoj
![sCapture](https://user-images.githubusercontent.com/63496374/141483701-b6c737f6-9506-4b71-b8d5-8f8497d05c87.PNG)

**Comment by HELLSNAKES** [comment]
An error occurred when I tried to use emoj
![Caddddddpture](https://user-images.githubusercontent.com/63496374/141484059-fb670b0a-1b2c-4f56-b5b0-498acfd891e7.PNG)

**Comment by dav1312** [comment]
Duplicate of #1116

**Comment by rauenzi** [comment]
Please read before opening issues Duplicate of #1116
