### ISSUE TITLE
[Bug] Transparency enabled removes rounded corners

### ISSUE THREAD

**Issue by HawksAreNeat** [BetterDiscord/BetterDiscord#1129]
**Describe the Bug**

    When transparency is enabled it removes rounded corners from windows 11
 
**To Reproduce**

    
    1 Use windows 11
    2 Enable transparency
    3 Rounded corners gone
 
**Expected Behavior**

      The rounded corners should stay and not become squared 
**Screenshots**

        
**Discord Version**

     1.9003
**Additional Context**

**Comment by rauenzi** [comment]
This is part of the base electron and is not something we control
