### ISSUE TITLE
[Bug] Installation is non-functional

### ISSUE THREAD

**Issue by Toby222** [BetterDiscord/BetterDiscord#1130]
**Describe the Bug**
Discord crashes on a fresh install of BetterDiscord on Windows

**To Reproduce**
Install and start up.

**Expected Behavior**
Functional installation

**Screenshots**
![image](https://user-images.githubusercontent.com/14962962/141744306-e7070188-bc4f-41df-99ce-8f9666741132.png)

**Discord Version**
Canary

**Additional Context**
I had previously installed Powercord, fully closed Discord and unplugged Powercord before installing BD.

**Comment by TheCommieAxolotl** [comment]
That is a _common_ error, go to the support server and ask for help (https://betterdiscord.app/invite)

**Comment by Toby222** [comment]
Apparently I had a previous installation on this computer that I forgot about, with outdated plugins...
User-error
