### ISSUE TITLE
[Bug] Crash on clicking badge

### ISSUE THREAD

**Issue by CubergDev** [BetterDiscord/BetterDiscord#1133]
When clicking the Nitro Booster badge on server, discord catches the unexpected error

1) Find a Nitro Booster
2) Click pink badge
3)Profit!

**Expected Behavior**
I don't know, but it shouldn't crash

**Screenshots**
![image](https://user-images.githubusercontent.com/69868390/142248291-0f045c28-55bc-41ee-9aec-27a0defa61c6.png)
![image](https://user-images.githubusercontent.com/69868390/142248306-2ecf76da-71b0-4ef3-991a-c6453cbc2f8a.png)

**Discord Version**
Stable, BetterDiscord 1.3.0
Using RadialStatus theme 1.3.0

**Additional Context**

**Comment by CubergDev** [comment]
UPD: Happens without any themes or plugins enabled

**Comment by migue802** [comment]
@CubergDev It works fine for me... By having any themes or plugins enabled you mean that you don't have any plugins or themes downloaded?

**Comment by migue802** [comment]
Oh! And, also try to update Discord in case it needs an update.
