### ISSUE TITLE
[Bug] Mentions inside Slash Commands don't display properly

### ISSUE THREAD

**Issue by CommandMC** [BetterDiscord/BetterDiscord#1134]
**Describe the Bug**

When the current user account is mentioned/pinged inside a slash command, it does not actually show the yellow background in chat. Restarting (either with Ctrl + R or by manually closing and re-opening the client) makes it show up properly.

**To Reproduce**

Have a bot that offers mentioning someone in one if its slash commands (I've used my own [24HS-Bot](https://github.com/24HourSupport/Bot) here). Use that command to mention yourself, or have someone else use it with your account

**Expected Behavior**

The mention should be displayed properly

**Screenshots**

Before refresh:  
![image](https://user-images.githubusercontent.com/34034631/142498361-914a7a7f-6a7b-4cef-98f5-9ac75a1b4921.png)  
After refresh:  
![image](https://user-images.githubusercontent.com/34034631/142498722-de3b357e-19e5-490b-932c-96b993e6a9c1.png)
(I'm using a theme here, but I have verified that this also happens without it)

**Discord Version**

Stable

**Additional Context**

I don't know if the mention should also display a (1) on the server icon that the ping happened in (I know that it doesn't do that on BD, but I don't know if it *does* do that on regular Discord)

**Comment by doggybootsy** [comment]
Try uninstalling betterdiscord and see if it does it

**Comment by CommandMC** [comment]
Huh, *now* it's doing that with BD uninstalled too. I've tested this ~30 minutes ago where it did work with BD removed

Welp, safe to say this isn't a BD issue then. Sorry!
