### ISSUE TITLE
[Bug] Member list isn't shown completely.

### ISSUE THREAD

**Issue by rarararaku** [BetterDiscord/BetterDiscord#1135]
**Description:**
The server's member list doesn't show nothing but the "shadows" from avatar and names after some time scrolling thru it. 

**How to reproduce:**
Open any channel with something like 150+ members and scroll through the member list.
 
**Expected Behavior:**
The list should be shown correctly until the last member appears. 

Screenshots attached to the end of this post.

**Version:**
Stable 105304 (5f6effe)
BetterDiscord 1.3.0
Host 1.0.9003 Windows 10 64-Bit (10.0.19043)

**Additional Context:**
Issue happens on three different computers. The problem didn't happen until I installed BetterDiscord. It started since 1.2.4.

![list1](https://user-images.githubusercontent.com/94774970/142751190-9d46bc30-4a77-4b2f-a4fe-3845af3ba6b4.jpg)
![list2](https://user-images.githubusercontent.com/94774970/142751187-3a7f12e3-2a04-4478-8837-019f2cb4d37a.jpg)

**Comment by doggybootsy** [comment]
That's just lazy loading

**Comment by rarararaku** [comment]
> That's just lazy loading (unless I'm missing a part)
Sadly, that's not it. Even if I leave it open for a hour or so and keep watching, the list stays the same way. I even thought about a issue with my hardware, but that's not the case.

**Comment by doggybootsy** [comment]
Strange, I would go to the support server and try and remove all your plugins and see if still does it

**Comment by rarararaku** [comment]
Looks like it's a problem with the RemoveBlockedUsers plugin. Disabling it solves the issue. Therefore, I use it actively, so I'm still looking forward for any help to solve this.

**Comment by SmolAlli** [comment]
Ask in the support server, specifically in the plugin support. This is not a BetterDiscord issue
