### ISSUE TITLE
[Bug] Fix BD Turned off when i reopen discord.

### ISSUE THREAD

**Issue by SniperWasTaken** [BetterDiscord/BetterDiscord#1136]
**Describe the Bug**
Better Discord is turning off when i reopen discord

**To Reproduce**
Fix it asap

**Expected Behavior**
Somethin' caused bd to turn off

**Screenshots**
None.
**Discord Version**
Stable.

**Additional Context**
Idk

**Comment by TheGreenPig** [comment]
Although this issue is described pretty poorly I'm assuming this is either due to an outdated ZeresPluginLibrary or possibly an old BetterDiscord version. Join the [​Support server​](https://discord.gg/bnSUxedypU) if you need further help.

**Comment by Inve1951** [comment]
sounds like bad plugin
