### ISSUE TITLE
[Bug] init crash when symlinks are present in plugins/themes/(probably others) on Windows

### ISSUE THREAD

**Issue by Mattwmaster58** [BetterDiscord/BetterDiscord#1138]
**Describe the Bug**

I recently was trying to symlink my plugin repo's plugins to the plugin folder to retain the organization of my repo while still enjoying my plugin updating in real time. I tried creating a symlink to accomplish this, but surprisingly, BD crashed. It looks like `fs.statSync` throws when called with a symlink path. It also looks like most places `statSync` is used, `lstatSync` could be a drop in replacement. 

I am happy to submit a PR to fix this but wanted to check-in with the maintainers here to see what goals they had in mind. At the bare minimum, I think that crashing when symlinks are present in the plugins folder should be fixed, but I'd love to add functionality for symlinks.

**To Reproduce**
1.
```
New-Item -Pa "<src path>" -ItemT Sy -Val "<plugins folder>"
```
2. restart discord

**Expected Behavior**
No crash.

**Discord Version**
Stable

**Comment by yourselvs** [comment]
I used the command `mklink "<plugins folder file>" "<source file>"` in an admin command prompt and did not experience this crashing bug.

**Comment by Mattwmaster58** [comment]
Well, this is embarrassing, tried to reproduce the issue and got nothing. I'm assuming the file I symlinked had errors causing BD to crash but I don't think we'll ever know.
