### ISSUE TITLE
Cant see better discord area in settings

### ISSUE THREAD

**Issue by Spoon5678** [BetterDiscord/BetterDiscord#1139]
**Describe the Bug**
Doesnt show etter discord settings
To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by doggybootsy** [comment]
Go to the bd server and ask for support
You installed into the wrong discord installation

**Comment by SmolAlli** [comment]
[Invite link](https://betterdiscord.app/invite)
