### ISSUE TITLE
[Bug] Windows Corner/Side Snapping

### ISSUE THREAD

**Issue by Gensokian** [BetterDiscord/BetterDiscord#1140]
**Describe the Bug**
When using the "Enable Transparency" Toggle in BD, Discord cannot be resized/split/quartered by dragging the title bar to the side of the screen.

**To Reproduce**
1. Enable Transparency
2. drag Window title bar to the top/side/corner of the screen

**Expected Behavior**
Normal Window tiling behaviour

**Screenshots**
Enabled
![image](https://user-images.githubusercontent.com/9213561/144593141-a3d6ac28-fad8-4430-bd95-4728acccf25c.png)

Disabled
![image](https://user-images.githubusercontent.com/9213561/144593174-4f35e4d4-f7fd-4eea-b6ef-da008e88a537.png)

**Discord Version**
Stable

**Additional Context**
Microsoft Powertoys can handle the interaction.

**Comment by QbDesu** [comment]
Known, it's an issue with electron. Nothing BD can do about it.

**Comment by Gensokian** [comment]
Gotcha, thanks!
