### ISSUE TITLE
Crash on Linux when joining a call [Bug]

### ISSUE THREAD

**Issue by wiggleforlife** [BetterDiscord/BetterDiscord#1141]
**Describe the Bug**
Whenever I join a call or voice chat, Discord crashes. It then relaunches with the BetterDiscord crash message, tries to rejoin the call, and crashes again. Still happens when I remove my plugins and themes.

**To Reproduce**
1. Open Discord
2. Join a call or VC
3. Discord crashes and relaunches
4. Repeat

**Expected Behavior**
I should be able to join a call.

**Discord Version**
Stable

**Additional Context**
I'm running Manjaro Linux with KDE. I installed Discord via pacman and BD via the AppImage. I have renamed my BD folder and repaired it using the installer. I think [this bug](https://github.com/BetterDiscord/Installer/issues/114) from the Installer repo is the same as what I'm experiencing, albeit with a different Discord branch. I believe this has been happening since Wednesday.

**EDIT**
Happens with normal Discord as well. My apologies.

**Comment by JoseskVolpe** [comment]
It's happening again when joining a private call

Stable 113194 (8bfb811)
BetterDiscord 1.5.0
Host 0.0.16 
Linux 64-Bit (5.16.4-1-MANJARO)

**Comment by ronneycz** [comment]
it's happening again with server calls and probably PM calls again, I have to kill Discord and once I launch it again I can join voicechats freely, so basically crashes once after boot
