### ISSUE TITLE
can't download asar file

### ISSUE THREAD

**Issue by fwehdrumny** [BetterDiscord/BetterDiscord#1142]
Starting Install...

Creating required directories...
✅ Directory exists: C:\Users\Administrator\AppData\Roaming\BetterDiscord
✅ Directory exists: C:\Users\Administrator\AppData\Roaming\BetterDiscord\data
✅ Directory exists: C:\Users\Administrator\AppData\Roaming\BetterDiscord\themes
✅ Directory exists: C:\Users\Administrator\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
❌ Failed to download package 
https://api.github.com/repos/BetterDiscord/BetterDiscord/releases
❌ connect ECONNREFUSED 127.0.0.1:443

The install seems to have failed. If this problem is recurring, join our discord community for support. https://discord.gg/0Tmfo5ZbORCRqbAd

**Comment by doggybootsy** [comment]
1) wrong github repo
2) go to the [support server](https://discord.gg/0Tmfo5ZbORCRqbAd), and you can get support there

**Comment by Inve1951** [comment]
>  ECONNREFUSED 127.0.0.1:443
suggests you mapped api.github.com to localhost
