### ISSUE TITLE
[Bug] Client crashes mobile stream

### ISSUE THREAD

**Issue by stickfab** [BetterDiscord/BetterDiscord#1143]
**Describe the Bug**
My friend is streaming from the Discord mobile app, and when i try entering their stream with the betterdiscord client, it instantly crashes, but when I enter their stream in browser or in a normal client, It doesn't.

**To Reproduce**
1. Get a friend or an alt to stream their screen on discord mobile
2. Join the stream on the Betterdiscord client

**Expected Behavior**

The client is not supposed to crash the stream, i'm supposed to enter and be able to watch the stream without any issues.

**Screenshots**

Screen recording of the issue in action https://streamable.com/bo4qp3
Screen recording of the same in a browser https://streamable.com/k7s07g

**Discord Version**

Stable 106905 (1eb8c0f)
BetterDiscord 1.3.0
Host 1.0.9003 Windows 10 64-Bit (10.0.19043)

**Additional Context**

It crashes any kind of mobile stream, like ipad, iphone and android.

**Comment by rauenzi** [comment]
Is this still occurring for you?

**Comment by stickfab** [comment]
i haven't been using betterdiscord since but it has happened with replugged installed on stable, installing it on canary fixed the issue. Not sure if it's the case for bd
