### ISSUE TITLE
Extreme instability on *stable* build

### ISSUE THREAD

**Issue by XeonBionic** [BetterDiscord/BetterDiscord#1145]
**Describe the Bug**

locking up and going into a Not Responding state whenever a animation is done, a video/gif is played, or any other windows are open besides the app.

**To Reproduce**

1: Have discord on linux (Linux Mint 20.2 Uma, KDE Plasma 5.18.5) 2: Open discord 3: The crashing is usually triggered by 3 things: Animations (least likely to cause) Videos/gifs playing (also not likely to cause, but it can happen) and most frequently, having ANY other window open other than the discord app, including for example, windows opened to select an image file to upload to chat. 
**Expected Behavior**

Nothing happens, and discord runs as usual. 

**Actual Behavior** 
It does either of 2 things: It locks up into a DNR (Not Responding) state with the normal discord GUI present, and actively updating (chat updating, videos keep playing) and can only be forced to stop by clicking the close button until a window pops up prompting you to close it. Or it shows what was above/behind it, basically like a screenshot of the area the discord window took up, with all the other parts staying the same.

**Screenshots**

will attach a video for proof
https://user-images.githubusercontent.com/94181637/144869009-61391b54-508b-4baa-b4f4-bb7f25fe8382.mp4

**Discord Version**

Stable

**Additional Context**

System Info: https://pastebin.com/qtUxZMYn

**Comment by rauenzi** [comment]
Is this still occurring for you?

**Comment by Haptror** [comment]
occurs for me
