### ISSUE TITLE
[Bug] Crashing on windows 11 on startup

### ISSUE THREAD

**Issue by Blobanium** [BetterDiscord/BetterDiscord#1147]
**Describe the Bug**
BetterDiscord Crashes windows 11 on startup

**To Reproduce**
Try to start Discord with windows 11

**Expected Behavior**
I Expected it to start up normally

**Screenshots**
![image](https://user-images.githubusercontent.com/45613796/146625784-3d1d9dcf-0b9b-4371-8e31-0c60cea38275.png)

**Discord Version**
Canary 108687

**Additional Context**
it shows up for a sec and it straight up crashes.

**Comment by Blobanium** [comment]
hold up i hit enter and it posted without me finishing hold up

**Comment by doggybootsy** [comment]
join the support server [here](https://discord.gg/0Tmfo5ZbORCRqbAd) for support
