### ISSUE TITLE
[Bug] BetterDiscord seems to interfere with Reduced Motion.

### ISSUE THREAD

**Issue by fhuewhd** [BetterDiscord/BetterDiscord#1148]
BetterDiscord seems to mess with the Reduced Motion setting (under Accessibility) in Discord.  When I have BetterDiscord installed, even if I don't have any custom CSS in the box, animated profile pictures play when I hit them with the pointer even with Reduced Motion switched on, and some other animations within Discord's own interface play even without that, such as the one on the pop-up about animated server banners and the one on the "Buy Nitro" pop-up that appears when you click the "gift" icon in the text input box.

**Comment by rauenzi** [comment]
BD absolutely does not touch that or cause those animations to play. If you have any plugins/themes enabled this could happen
