### ISSUE TITLE
[Bug] Hide Gift button does not work

### ISSUE THREAD

**Issue by duqaqon** [BetterDiscord/BetterDiscord#1149]
**Describe the Bug**
Hide Gift button does not work

**To Reproduce**
Go to Settings -> BetterDC Settings -> Hide Gift Button: ON

**Expected Behavior**
To remove the Gift Button from my textbar in chats

**Screenshots**

**Discord Version**
Canary

**Additional Context**
OS: Pop_OS! 21.10 (Running KDE plasma). Also tried on Kubuntu 21.10 and Windows 11

**Comment by doggybootsy** [comment]
duplicate of https://github.com/BetterDiscord/BetterDiscord/issues/841 
Use css or the plugin (RemoveChatButtons) for now

**Comment by duqaqon** [comment]
> duplicate of #841 Use css or the plugin (RemoveChatButtons) for now

Sorry My bad. Closing Issue.
