### ISSUE TITLE
[Bug] Time stamp shows in 24 hour format even when turned off

### ISSUE THREAD

**Issue by 9Craft** [BetterDiscord/BetterDiscord#1151]
**Describe the Bug**
The time stamp on messages shows in 24 hours format from the time of installing BD the toggle button doesn't seem to work at all.

**To Reproduce**
Just install BD on the latest build of Discord.

**Expected Behavior**
The toggle should turn off the 24-hour format when disabled, and turn it back on when it is enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/85939913/147219555-8e999d33-06bc-4ce4-95e2-ab1ccaa3aa0a.png)
![image](https://user-images.githubusercontent.com/85939913/147219628-c23f04c8-fc3f-4033-9f95-ab926f5d9a63.png)

**Discord Version**
Stable 108924 (eb8c571)

**Additional Context**
Not required.

**Comment by SmolAlli** [comment]
This is actually an issue with your language setting. Go to settings -> language and change it to English (US) for an English language, or otherwise you may have to experiment and see which languages will fix this for you.

**Comment by 9Craft** [comment]
> This is actually an issue with your language setting. Go to settings -> language and change it to English (US) for an English language, or otherwise you may have to experiment and see which languages will fix this for you.

Thanks, sorry I didn't know
