### ISSUE TITLE
i want appeal

### ISSUE THREAD

**Issue by PROTEA1529** [BetterDiscord/BetterDiscord#1155]
I was banned from the BETTERDISCORD server for SPAM.
But in reality, it was just my body accidentally pressing down on the keyboard long enough for the CHAT to be dropped in succession.
This was an accident.

**Comment by Strencher** [comment]
Other than you doing the same thing again but with our repos, you don't even tell us who you are so if we would want to consider looking into why you got banned, we couldn't.

**Comment by SmolAlli** [comment]
Please ask in the second BetterDiscord server - https://discord.gg/sbA3xCJ

**Comment by PROTEA1529** [comment]
im protea#1606

**Comment by CarsterX** [comment]
> im protea#1606

We don't care! Please delete your Github account

**Comment by PROTEA1529** [comment]
> Other than you doing the same thing again but with our repos, you don't even tell us who you are so if we would want to consider looking into why you got banned, we couldn't.

my discord is protea#1606

**Comment by PROTEA1529** [comment]
> > im protea#1606
> 
> We don't care! Please delete your Github account

I know there are crazy people like you out there, but for now, stay out of my way.

**Comment by Inve1951** [comment]
appeal is denied
