### ISSUE TITLE
[Bug] Discord crashed, and said I had to remove plugins from betterdiscord, but turned out to be completely wiped from my PC.

### ISSUE THREAD

**Issue by hyxtoria** [BetterDiscord/BetterDiscord#1157]
There was an error, and it said i had to remove plugins, so when i searched my files for it it was completely gone. My discord then said that the file "Update.exe" had been changed, and if I wanted to delete it, so I did (not understanding what it was) and it deleted my discord. 

(This is first time using GitHub, sorry for mismatched info)

**Comment by SmolAlli** [comment]
Update.exe isn't necessarily _required_ to use Discord, but reinstalling may be your best bet for getting that back.
As for your crash, please join the [Discord Server](https://betterdiscord.app/invite) to be assisted with that.
