### ISSUE TITLE
Better discord bug

### ISSUE THREAD

**Issue by JMZll** [BetterDiscord/BetterDiscord#1160]
I was having a bug on better discord every time I use it it double what I sent in the chat Eg. I wrote "Hello" It will resend the word "Hello" one more time
![image](https://user-images.githubusercontent.com/89514736/148324894-63f6ff74-fa01-4802-a88c-0ea3a181f482.png)

**Comment by JMZll** [comment]
Anyone help

**Comment by SmolAlli** [comment]
Can you please test that this isn't a plugin or low internet issue. 
Please join the [Discord Server](https://betterdiscord.app/invite) and ask for assistance in Support before assuming this is a BetterDiscord issue.
