### ISSUE TITLE
[Bug] Discord Client Crashes With BD

### ISSUE THREAD

**Issue by Adrigamer2950** [BetterDiscord/BetterDiscord#1162]
**Describe the Bug**
My discord client crashes everytime I open discord with BD (without plugins and themes), poping up the message shown in Screenshots

**To Reproduce**
Install BD.
Open Discord

**Screenshots**
![image](https://user-images.githubusercontent.com/58531641/148662982-5f51b1da-af6f-4434-9d53-0126fdbfd513.png)

**Discord Version**
Stable

**Additional Context**
It happens with every version of BD, from 1.0.0 to latest

**Comment by SmolAlli** [comment]
You most likely have some outdated plugins. Please join the [Discord Server](https://betterdiscord.app/invite) to get further assistance.

**Comment by Adrigamer2950** [comment]
> You most likely have some outdated plugins. Please join the [Discord Server](https://betterdiscord.app/invite) to get further assistance.

![image](https://user-images.githubusercontent.com/58531641/148707361-5f0625f0-6db1-47ba-8309-e9526e81d35a.png)

**Comment by yoimlive777** [comment]
> > You most likely have some outdated plugins. Please join the [Discord Server](https://betterdiscord.app/invite) to get further assistance.
> 
> ![image](https://user-images.githubusercontent.com/58531641/148707361-5f0625f0-6db1-47ba-8309-e9526e81d35a.png)

Glad they are reading the issue before responding ^^

**Comment by rauenzi** [comment]
Thank you, passive aggressive comments are very helpful.
