### ISSUE TITLE
[Bug] On Discord Canary themes stopped working after update

### ISSUE THREAD

**Issue by BrianMSK** [BetterDiscord/BetterDiscord#1163]
**Describe the Bug**
After latest canary updates, the themes are broken

**To Reproduce**
Install the latest Discord Canary and latest BetterDiscord, activating any theme will only make slight changes and is broken.

**Expected Behavior**
Theme should be working normally.

**Screenshots**
https://i.imgur.com/YSgRW3u.png
https://i.imgur.com/nUfEAiT.png

**Discord Version**
Canary

**Additional Context**
It happend in the last few days when updating my discord canary, the themes stopped working and are only doing small changes to my discord.

**Comment by SmolAlli** [comment]
This is something that the theme developers will have to fix. Not a bd issue.

**Comment by BrianMSK** [comment]
@SmolAlli this is happening on all the themes, is this caused by some Discord update that broke most of the themes? I also got BetterDiscord and settings headings in black color instead of usual one. https://i.imgur.com/hA1Wd1h.png

**Comment by SmolAlli** [comment]
Yes, Discord changed class names. Still not a bd issue.

**Comment by BrianMSK** [comment]
Closing then, thanks for letting me know :)
