### ISSUE TITLE
[Bug] Friend list tab don't have the applied colors from themes

### ISSUE THREAD

**Issue by KayTwenty** [BetterDiscord/BetterDiscord#1164]
**Describe the Bug**
BetterDiscord's friend list tabs don't have the applied color from the themes. I've tested several themes and they all don't apply on the friend list tab. Before, it showed the colors on it. 

**To Reproduce**
Start BetterDiscord, then navigate to the friend list tab

**Expected Behavior**
The theme color should be applied on the friend list tab

**Screenshots**
![image](https://user-images.githubusercontent.com/69999193/148966063-4788e04a-b26f-42c0-bbad-260c487231f0.png)

**Discord Version**
Stable 110451 (c233a73)

**Comment by Rayrsn** [comment]
[Discord has changed its class names](https://discord.com/channels/86004744966914048/178208945410801665/930250941792399380)

**Comment by doggybootsy** [comment]
This is not a betterdiscord issue, discord had a recent update that changed a decent amount of classes

**Comment by Safhirblau** [comment]
> This is not a betterdiscord issue, discord had a recent update that changed a decent amount of classes

Can you do something about it ?

**Comment by Rayrsn** [comment]
you either have to wait for the dev to fix it or you can manually fix the classes using this [file](https://gist.github.com/ExperiBass/2375ac4f7088bb9410d81cd59495f462)

**Comment by dav1312** [comment]
> you either have to wait for the dev to fix it or you can manually fix the classes using this [file](https://gist.github.com/ExperiBass/2375ac4f7088bb9410d81cd59495f462)

You can also use https://laynetheepic.github.io/projects/pc-theme-converter/
It updates all of the classes automatically

**Comment by KayTwenty** [comment]
The converter method seemed to work. Thanks!
