### ISSUE TITLE
[Bug] discord themes not working

### ISSUE THREAD

**Issue by TheBetaTester000000** [BetterDiscord/BetterDiscord#1165]
i discord crashed which happens now and then so i thought nothing of it but since thats happened my themes havent been working, ive tried repairing betterdiscord, reinstalling better discord, deleting betterdiscord to reinstall and uninstally both discord and better discord and nothing seems to be fixing it. i tried fixes online too and it did nothing

**Comment by Zzeyy** [comment]
This is a bug caused by the newest Discord update.
There's little things to do in order to fix OUR issues, but waiting is the best and easiest out of all things.
I expect everything to be working as before in up to a week.

**Comment by doggybootsy** [comment]
Not a betterdiscord issue, discord updated a bunch of classes and that broke a lot of themes

**Comment by TheBetaTester000000** [comment]
> This is a bug caused by the newest Discord update. There's little things to do in order to fix OUR issues, but waiting is the best and easiest out of all things. I expect everything to be working as before in up to a week.

thank you for telling me this

**Comment by rauenzi** [comment]
This is something the individual developers have to fix, not part of BD.
