### ISSUE TITLE
[Bug] colors not being applied

### ISSUE THREAD

**Issue by Serxule** [BetterDiscord/BetterDiscord#1166]
**Describe the Bug**
profile bar and text bar are suddenly not being colored correctly, they were working fine yesterday and a discord update hasnt happened as far as i know, so nothing should change it

**To Reproduce**
?

**Expected Behavior**
should have the same theme

**Screenshots**
what it looks like: 
![image](https://user-images.githubusercontent.com/64584757/149012622-5a1933be-0173-4464-a62d-e7029c17baef.png)

what it should look like: 
![image](https://user-images.githubusercontent.com/64584757/149012644-c64fdadd-d465-49d1-96c4-779886ccef0e.png)

**Discord Version**
stable

**Additional Context**

**Comment by rauenzi** [comment]
Discord updated, the developer of your theme needs to update as well. Comic Sans as your main font should be punishable by law.

**Comment by rauenzi** [comment]
If you made it, then you know CSS and should know how to do it again.

**Comment by Serxule** [comment]
you right, this is annoying though
