### ISSUE TITLE
[Bug] Casual BD fuckery

### ISSUE THREAD

**Issue by qu1ncyx** [BetterDiscord/BetterDiscord#1167]
I'm trying to enable my installed themes but they won't fully activate.

![image](https://user-images.githubusercontent.com/97563164/149031715-60d5b1c2-7889-4f40-89c4-d7f9fb2163f6.png)

For the longest time I've only been using the ELYSIA theme, but earlier this specific bug showed up.
I should note that the same thing has happened before, although a simple repair would fix the issue.

Help me :)

Pretty please?

**Comment by SmolAlli** [comment]
Themes are broken. Go to the support server for that theme. Not a bd issue.

**Comment by brandonchangsan** [comment]
Same thing happened to me. Am using ClearVision theme.

**Comment by Rayrsn** [comment]
read https://github.com/BetterDiscord/BetterDiscord/issues/1164

**Comment by KK-Designs** [comment]
I'm only experiencing this in the latest Discord update.

**Comment by queenbiscuit311** [comment]
in my experience betterdiscord was slowly breaking over the last 2 or 3 updates. for me on canary it just crapped out and died entirely with the latest one and now it's not even active. stable wasnt working well either.

**Comment by DevEvil99** [comment]
Discord has pushed out a large change to both Canary and Stable. It is expected that many plugins, themes, and even certain portions of BD itself will be broken. Please be patient while fixes for each of these are pushed out by the developers.
