### ISSUE TITLE
[Bug] BetterDiscord stopped doing anything (Linux).

### ISSUE THREAD

**Issue by fhuewhd** [BetterDiscord/BetterDiscord#1168]
Opened Discord and BetterDiscord didn't seem to be doing anything.  On checking Settings, it was still there, but none of the settings seemed to do anything.  Minimal Mode was still switched on, but Discord wasn't displaying in Minimal Mode.  I tried activating "hide Gift button" and "hide GIF button", but they didn't do anything.  Nothing in the Custom CSS box was having any effect.  

I've tried closing and restarting Discord, and I've tried reinstalling BetterDiscord (using the "reinstall" command in betterdiscordctl), but that didn't fix it.

I'm using the ordinary version of Discord (Stable, possibly), and I'm using Zorin Linux, a variant of Ubuntu.

The only thing that occurs to me that I'd done to Linux since BetterDiscord was last working is update Wine, but that doesn't sound as if it should have anything to do with it.

I don't know if anyone can make anything of this.

**Comment by TheCommieAxolotl** [comment]
Discord had an update that broke things, ask for help on the support server.

**Comment by fhuewhd** [comment]
Gahhhhh I hate the support server.  Also, I can't seem to find it at the moment, the links here are broken, but I have used it recently so maybe it'll turn up if I do a Web search.

**Comment by fhuewhd** [comment]
Didn't manage to find it.  I found a small unofficial server and asked there but nobody seems to be online or else they don't know.

**Comment by HypedDomi** [comment]
You can find the Invite on the [BetterDiscord Website](https://betterdiscord.app) when you click the Community Button

**Comment by queenbiscuit311** [comment]
same issue on windows, last few updates slowly completely busted it until now.

**Comment by Erebea** [comment]
Is there any update on this?

**Comment by queenbiscuit311** [comment]
> Is there any update on this?

for me it just started working again and recently the dev and most plugin makers have pushed updates to fix issues. i can test linux later to see if its working there too.

**Comment by fhuewhd** [comment]
Not fixed on Linux so far.  I did update it using betterdiscordctl, but it's still not working.

**Comment by Erebea** [comment]
It seems to be working again for me on Ubuntu 20.04

**Comment by fhuewhd** [comment]
Still nothing here.  (Ubuntu 18.04, or rather Zorin 12 Lite, which is a variant of it).
