### ISSUE TITLE
Can i please get another chance to be part of the community.

### ISSUE THREAD

**Issue by ohitstom** [BetterDiscord/BetterDiscord#1170]
**Describe the Bug**
i got banned like 4 months ago for "commenting on everything"

Please just let me back into the community i promise it wont happen again, im just so lonely and miss being in communities like this one like i used to be. I legit crave friendships and its real hard not being able to keep them, so just general chatter about topics i enjoy would be really nice. I feel like being banned for commenting on everything is a bit extreme and it would be nice if someone would give me another chance and take an indepth look at what happened and how i am now.

Please im just so lonely it hurts

**Comment by ItMeSarah** [comment]
You were banned for more than just commenting on everything, distributing and telling people how to get banned plugins, being disrespectful to everyone then, and today calling Zere a dumbass ontop of ban evasion, so no, you will not be unbanned.  This is just the icing on the cake of reasons you will not be unbanned, this repo's issues is not for "waaa im banned unbannd me."

**Comment by rauenzi** [comment]
Congrats you've earned a ban from the GitHub as well!

**Comment by KcTec90** [comment]
sheesh
