### ISSUE TITLE
[Bug] The background images and gifs wont load

### ISSUE THREAD

**Issue by SJJoe** [BetterDiscord/BetterDiscord#1175]
**Describe the Bug**

The background images and gifs wont load for any of my themes, but the colors still remain for the scroll bar, links, etc... everything loads except the background.
**To Reproduce**

I don't know please help.
**Expected Behavior**

To be able to full load the background in any theme correctly coded.
**Screenshots**

![image](https://user-images.githubusercontent.com/98069428/150263145-859894e2-fda2-463b-b443-1441a2901f76.png)
**Discord Version**

?
**Additional Context**

Best of luck, thanks :)

**Comment by doggybootsy** [comment]
This isn't a bd issue, there was a recent class update which broke many themes

**Comment by SJJoe** [comment]
lol

**Comment by SJJoe** [comment]
my bad
