### ISSUE TITLE
[Bug] Better Discord crashes discord when camera is on for an extended period of time

### ISSUE THREAD

**Issue by 21dhruvp** [BetterDiscord/BetterDiscord#1178]
**Describe the Bug**
Whenever I leave my camera on for too long(approx. 30-40 mins) better discord crashes.

**To Reproduce**
1) Join a VC
2) Turn on your camera(and maybe have another person in the call, not sure if that matters)
3) Wait around 30-40 mins, maybe longer but not more than an hour for certain

**Expected Behavior**
I should be able to use my camera indefinitely as discord normally would.

**Screenshots**
Screenshot provided from after crash.
![image](https://user-images.githubusercontent.com/39568064/150910548-b640a4a3-2269-4794-9418-43361d4354a6.png)

**Discord Version**
Stable 111699 (e8f9fb9)

**Additional Context**
I started having this issue starting in version 1.2 of better discord.

**Comment by catb0t** [comment]
Also happens with "Voice & Video" in the settings > Test video. Test video once, it works.

Exit settings and Test video again, BD crashes discord.

**Comment by rauenzi** [comment]
This issue should be fixed with the latest update, if not please reopen this issue
