### ISSUE TITLE
[Feature] Add an option to disable plugin update notifications 

### ISSUE THREAD

**Issue by HumanNugget** [BetterDiscord/BetterDiscord#1180]
**Is your feature request related to a problem? Please describe.**
Its annoying reading a chat and seeing a big fuck off blue line appear saying that some non-important plugin just got an update and now i have to click on it
It becomes a really big annoyance when you have 20 plugins each getting an update every hour 

**Describe the feature you'd like**
A checkmark in the menu that would allow me to stop notifications about updates from appearing

**Additional context**

**Comment by zDylant** [comment]
Support this idea! there are some plugins that I can't update or they just stop working and it's annoying to have a blue rectangle that says update them

**Comment by rauenzi** [comment]
BD does not add this so it is not a BD issue.
