### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by JorgeCepeda** [BetterDiscord/BetterDiscord#1181]
**Describe the Bug**
The Hide GIF picker button in BD Settings broke

**To Reproduce**
Activate the Hide GIF picker button

**Expected Behavior**
The Hide GIF picker button hides or shows depending on the button's state

**Screenshots**
![Captura](https://user-images.githubusercontent.com/69733604/151030466-32d69fab-38f8-44db-9e01-8c9e2ac784ab.PNG)

**Discord Version**
Stable

**Additional Context**
The Stickers button is hidden using additional unrelated CSS

**Comment by dav1312** [comment]
Duplicate of #841

**Comment by SmolAlli** [comment]
[Use this plugin instead](https://betterdiscord.app/Download?id=383)
