### ISSUE TITLE
[Bug] Developer Tools wont open

### ISSUE THREAD

**Issue by squee666** [BetterDiscord/BetterDiscord#1184]
Ctrl Shift I does nothing after update/reload discord

tried disabling all plugins/theme and repairing/reinstalling better discord

Persists

**Comment by l0c4lh057** [comment]
[This is a change performed by discord.](https://www.reddit.com/r/discordapp/comments/sc61n3/cant_inspect_element_anymore/hu4fw5x/?context=1000) There is a PR #1179 open to "fix" this issue but for security reasons we're not really sure if it should get merged like that, it might become a toggle in BD settings that you need to opt in for. The linked reddit comment explains how to enable the devtools manually tho.

**Comment by IamNickerson** [comment]
Do you know when is that Dev tools option gonna get added in the BD settings?

**Comment by squee666** [comment]
> [This is a change performed by discord.](https://www.reddit.com/r/discordapp/comments/sc61n3/cant_inspect_element_anymore/hu4fw5x/?context=1000) There is a PR #1179 open to "fix" this issue but for security reasons we're not really sure if it should get merged like that, it might become a toggle in BD settings that you need to opt in for. The linked reddit comment explains how to enable the devtools manually tho.

yeah seems fair to make it a toggle at least

**Comment by IamNickerson** [comment]
I meant when is this toggle gonna get added in the BD Settings?

**Comment by dav1312** [comment]
Zere already merged the pr, no toggle

**Comment by IamNickerson** [comment]
Oh rlly oh yeah he did

**Comment by rauenzi** [comment]
It will be behind a different kind of toggle.

**Comment by IamNickerson** [comment]
which one?

**Comment by dav1312** [comment]
Its in a toggle now https://github.com/BetterDiscord/BetterDiscord/commit/8365730de53f8547503bf92d071361f2bcd8cc14

![image](https://user-images.githubusercontent.com/63931154/151449812-3aaf14cc-d587-4e2c-8512-a0185356089a.png)

**Comment by IamNickerson** [comment]
Yeah I saw the toggle.

**Comment by IamNickerson** [comment]
Ok can someone close the issue since it is fixed.
