### ISSUE TITLE
[Bug] Starting a stream starts dropping packets and lagging the stream when in voicechat.

### ISSUE THREAD

**Issue by IlySmall** [BetterDiscord/BetterDiscord#1185]
**Describe the Bug**
Starting a stream starts dropping packets and lagging the stream when in voicechat.

**To Reproduce**
Get into a call, start streaming and talking at the same time, either the talking or the streaming will no longer function properly, sometimes both.

**Discord Version**
Stable, Canary

**Additional Context**
Speedtested the internet and streamed on bone stock discord (PTB) without issues.

**Comment by rauenzi** [comment]
I am unable to reproduce this
