### ISSUE TITLE
[Bug] Plugins suddenly stopped working!

### ISSUE THREAD

**Issue by jarrard** [BetterDiscord/BetterDiscord#1187]
**Describe the Bug**
Plugins stopped working today

**To Reproduce**
Load discord

**Expected Behavior**
Plugins working

**Discord Version**
Stable Linux

**Additional Context**
Error Messages: All plugins say this....

BetterVolume: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:311255)
    at Object.loadAddon (<anonymous>:4:273400)
    at Object.loadAddon (<anonymous>:4:310367)
    at Object.loadAllAddons (<anonymous>:4:275654)
    at Object.initialize (<anonymous>:4:270142)
    at Object.initialize (<anonymous>:4:309577)
    at Object.startup (<anonymous>:4:373389)

**Comment by fowlis** [comment]
This repo is for issues with BetterDiscord itself, go to the support server or GitHub repo of the plugin's author for plugin support.

**Comment by jarrard** [comment]
but all plugins don't work... not just a select one...

**Comment by SmolAlli** [comment]
Considering that the error you sent is for one specific plugin, that is not the case. 
Please make sure you are on the most recent version of BD and that you are using the most recent version of plugins.

**Comment by jarrard** [comment]
It's ok, got something sorted out using a different plugin manager. I'll put BD issue to rest.
