### ISSUE TITLE
[Bug] All plugins not working

### ISSUE THREAD

**Issue by jackiexyz** [BetterDiscord/BetterDiscord#1189]
**Describe the Bug**
All of the plugins are not working.
The bd setting menu missing custom css, plugins, and themes section.

**To Reproduce**
Just open discord.

**Expected Behavior**
Everything should be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/4688005/151684859-1448b48d-e1b9-4ed6-8df3-46e2b60b100b.png)

**Discord Version**
Stable 112515, Windows 10 19044

**Comment by fowlis** [comment]
Looks like the install didn't complete due to network issues, have you had BetterDiscord before or is this your first time using it?

**Comment by rauenzi** [comment]
> Looks like the install didn't complete due to network issues

What?

**Comment by jackiexyz** [comment]
> Looks like the install didn't complete due to network issues, have you had BetterDiscord before or is this your first time using it?

I have been using BetterDiscord for a while and it works fine until recently. This issue doesn't exist on ptb and canary, only stable version.
I have tried VPN and reboot several times and reinstall bd, doesn't help.
