### ISSUE TITLE
[Feature] making bot list prebuilt in same way as server list is

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [BetterDiscord/BetterDiscord#1190]
**Is your feature request related to a problem? Please describe.**

its not 

**Describe the feature you'd like**

making a settings-togglable button in server settings in ALL created/moderated servers to be able to choose bots from discord.bots.gg (this site partners with discordservers.com which is prebuilt in server-chooser) and immediatly add them to server (without choosing like discord does'd be best)

**Additional context**

i dont think that i have anything more to say... ;p

**Comment by dav1312** [comment]
Discord is already going to add a "bot list" called App Directory, you will be able to add bots from there
![app directory](https://user-images.githubusercontent.com/28404851/150436306-20e923bb-2321-4ad7-83c2-b01c970618e3.png)

**Comment by hacknorris-aka-penguin** [comment]
wtf?
