### ISSUE TITLE
[Feature] !website idea - adding themes from files (not github integration)

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [BetterDiscord/BetterDiscord#1191]
**Is your feature request related to a problem? Please describe.**

yes, i cant add themes cause i dont have em on github. (i just want to keep my space clean and most repos i have private)

**Describe the feature you'd like**

a way to import css themes either from file or paste css file text to convert into a theme (text editor). not for addons tho. only themes

**Additional context**

**Comment by rauenzi** [comment]
If you mean submitting themes to our website through a file and not github, then no we will not be supporting that.

**Comment by hacknorris-aka-penguin** [comment]
can i have reasons why?

**Comment by hacknorris-aka-penguin** [comment]
and why not also other platforms like codeberg, gitlab....

**Comment by Tropix126** [comment]
> can i have reasons why?

At the very least a git-based setup is required for pushing updates to content for verification. The site also integrates GitHub APIs fairly heavily on the developer side of things. GitLab support *could* be a possibility in the future, but at the moment we only support connecting a repo through GitHub.

**Comment by hacknorris-aka-penguin** [comment]
ya know g-hub based on windoz? microsoft? what bout peeps wanting to get rid of it?

**Comment by Tropix126** [comment]
The majority of the current community uses GitHub for hosting their addons, even prior to the site being finishe. GitHub's association with Microsoft is not my concern, it's just that it's integration in the site was prioritized over other competing platforms.

**Comment by hacknorris-aka-penguin** [comment]
![image](https://user-images.githubusercontent.com/97974194/151856283-97e6479e-91e9-47f0-bea7-a3ed0e0b9eec.png)

**Comment by rauenzi** [comment]
> ya know g-hub based on windoz?

What an interesting, yet inaccurate, perspective.
