### ISSUE TITLE
[Bug] Minimal Mode toggle remains in settings

### ISSUE THREAD

**Issue by Acumane** [BetterDiscord/BetterDiscord#1194]
**Describe the Bug**
Toggle for `Minimal Mode` remains in BetterDiscord settings despite its removal and subsequent replacement by this [theme](https://betterdiscord.app/theme/MinimalMode)

**To Reproduce**
Try toggling `Minimal Mode`

**Expected Behavior**
Compacted interface as seen in versions ~1mo. ago

**Discord Version**
Stable 112644 (2dd6bce)
BetterDiscord 1.4.0

**Additional Context**
Windows 10 64-Bit (10.0.19043)
Reproducible with *and* without plugins installed/enabled

**Comment by dav1312** [comment]
Minimal mode was removed and its now a separate theme https://betterdiscord.app/theme/MinimalMode

**Comment by Acumane** [comment]
@dav1312 Apologies, thanks for pointing this out!
Edited issue accordingly. Really ought to be removed, all the same.

**Comment by dav1312** [comment]
The button will be removed in the next release along with all appearance settings (https://github.com/BetterDiscord/BetterDiscord/commit/f078e3b2dc7c7f187db5e39f12f857734b166509).
It is normal that you still have it, I just mentioned it because it won't be fixed.

**Comment by rauenzi** [comment]
This release was pushed
