### ISSUE TITLE
[Bug] Colored text always turned on

### ISSUE THREAD

**Issue by BrianMSK** [BetterDiscord/BetterDiscord#1195]
**Describe the Bug**
Colored text always turned on, even when its turned off in settings.

**Expected Behavior**
Colored text should be working as in BetterDiscord settings.

**Screenshots**
[Screenshot 1](https://i.imgur.com/a6TDHJi.png)
[Screenshot 2](https://i.imgur.com/MWqUjHo.png)

**Discord Version**
Stable

**Additional Context**
This happend from day to day usage and without my knowledge of anything being touched by me.

**Comment by fowlis** [comment]
BetterRoleColours plugin, its enabled by default for whatever reason. Go to plugin settings

**Comment by BrianMSK** [comment]
Thanks for letting me know, I am now closing this issue! @fowlis
