### ISSUE TITLE
ComponentPatcher fails to get guild component???

### ISSUE THREAD

**Issue by powerbox1000** [BetterDiscord/BetterDiscord#1197]
In the developer console, it shows the error:
<img width="401" alt="Screenshot 2022-01-31 160806" src="https://user-images.githubusercontent.com/72870790/151873323-4b474d8c-15f3-4a4f-a238-026ade6d7fec.png">
Along with that, BetterDiscord's Custom CSS, Plugins, and themes menus are missing:
<img width="145" alt="Screenshot 2022-01-31 160956" src="https://user-images.githubusercontent.com/72870790/151873551-af744760-d838-44a1-84c5-01d8ba988332.png">
I have already tried using Discord PTB and Stable, repairing the install, and reinstalling BetterDiscord.

**Comment by rauenzi** [comment]
This has been fixed with the latest release
