### ISSUE TITLE
[Bug] Theme Background not working

### ISSUE THREAD

**Issue by NoobPratik** [BetterDiscord/BetterDiscord#1199]
**Describe the Bug**
Recently my theme background is not working with any theme, the ui loads and the colors but the bg doesn't
Im sure it happened after the new update of discord,

Currently using Version --> 
Stable 112876 (69f8c1e)
BetterDiscord 1.5.0
![image_2022-02-02_070425](https://user-images.githubusercontent.com/88104744/152079620-530bb452-4a55-435f-8ca0-bc7e5ad9fe33.png)

**Comment by DaSussy** [comment]
themes are independent from bd. you should make an issue to the theme's repo, not here

**Comment by NoobPratik** [comment]
> themes are independent from bd. you should make an issue to the theme's repo, not here

Oh i am sorry i didnt knew that, can you post the link of that repo here?

**Comment by ItMeSarah** [comment]
> > themes are independent from bd. you should make an issue to the theme's repo, not here
> 
> Oh i am sorry i didnt knew that, can you post the link of that repo here?

https://github.com/nextr0ll/nextr0ll.github.io/blob/master/Eclipse/Eclipse.theme.css The theme is probably broken, due to it being 9 months out of date.

**Comment by NoobPratik** [comment]
> 

I have tried other latest one too, like boreal and kimono friend but none of them worked either

**Comment by ItMeSarah** [comment]
> > 
> 
> I have tried other latest one too, like boreal and kimono friend but none of them worked either

Boreal is also outdated, as is Kemono Friends Returns, so makes sense that neither of those would work either.
