### ISSUE TITLE
[Bug] Static issues with audio

### ISSUE THREAD

**Issue by jangxbanger** [BetterDiscord/BetterDiscord#1200]
**Describe the Bug**
After a few hours of troubleshooting I have narrowed my issue down to being with better discord exclusively. At random times my audio will start playing static, it doesn't matter if I'm in a game, on youtube or just listening to music on spotify, at some point it will start chopping up my audio and replacing it with static intermittently. The only way to stop the issue is to kill discord and restart it in which it will only happen again. This is all while not being in a call or channel where discord would be utilizing audio. When I use standard vanilla discord the issue does not happen.

**To Reproduce**
There is no clear way to reproduce the issue, the issue can happen 3 minutes in or 30 minutes in. I have essentially narrowed out every other possibility of other hardware or software creating the issue. Pulled sound card and ran onboard sound, updated drivers, attempted another headset and attempted audio through USB.

**Discord Version**
Stable 113007

I have not attempted a reinstall of better discord, I have disabled my minimal amount of plugins and themes but I would be more then willing to re-install it if needed.

**Comment by iNgeon** [comment]
Could it be related to this ?
https://github.com/BetterDiscord/BetterDiscord/issues/966#issue-955107909
As a side note really wish discord or betterdiscord could improve or expand the features on microphone background noise picking up like adding something like a small dead zone to automatically detect input

**Comment by rauenzi** [comment]
Hard to really say what would cause this as BD does not touch anything even close to the audio system. I am unable to reproduce this issue

**Comment by jangxbanger** [comment]
Closing this issue I left open, issue wasn't with BD was a fairly complex issue involving discord exclusively and my power supply. Doesn't make sense as to why but it was the resolution.
