### ISSUE TITLE
[Bug] Transparency is broken.

### ISSUE THREAD

**Issue by WinnerWind** [BetterDiscord/BetterDiscord#1205]
**Describe the Bug**
Transparency is broken in both themes and custom CSS and instead gives a grey overlay over everything

**To Reproduce**
Open BD settings and enable transparency
Open a theme that is See through or custom CSS the transparency

**Expected Behavior**
Discord to show me what is below the discord window

**Screenshots**
![image](https://user-images.githubusercontent.com/71366717/153139864-967958de-ad75-4926-a8e7-15d5fb6e8567.png)
![image](https://user-images.githubusercontent.com/71366717/153139891-f4464fee-1e58-4dbb-ad1b-ad42514d4f0b.png)

**Discord Version**
Stable

**Additional Context**
The problem was spotted because i was using the brand new float theme before it was public. The transparency worked while the theme was in development but now fails to work with custom CSS.

**Comment by SmolAlli** [comment]
Did not replicate.
BetterDiscord does create a transparent window when the Transparency toggle is enabled, and using the theme Translucense by CapnKitten v1.0.6.3.
Using BetterDiscord 1.5.1 on Stable 113977, Windows 10.

Your issue is most likely that your CSS is not actually making the background transparent. I changed the `--app-bg` to `transparent`, but also changing it to be an RGBA value works.

**Comment by WinnerWind** [comment]
![image](https://user-images.githubusercontent.com/71366717/153327873-ebe1d09f-b4ae-4bb7-9fb6-03e70ad4cf11.png)
It still does the weird darkening thing @doggybootsy 
I do not know the issue at this point of time

**Comment by WinnerWind** [comment]
Update : just did a full clean install of BD and Discord, yet the transparency is super broken.

**Comment by WinnerWind** [comment]
I think i can close this case. It seems to be an issue with my programming. I enabled another transparent theme and now my transparency is totally fine
![image](https://user-images.githubusercontent.com/71366717/153330408-14361062-402a-44cb-8d8c-4deebc66148c.png)
Still do not know what triggered the previous theme to break
