### ISSUE TITLE
[Bug] BetterDiscord crashes when opening user profile

### ISSUE THREAD

**Issue by Aholicknight** [BetterDiscord/BetterDiscord#1206]
I am using the latest version of BetterDiscord; whenever I right-click on any user, it would crash discord.

<img width="704" alt="Screen Shot 2022-02-09 at 10 08 19 AM" src="https://user-images.githubusercontent.com/7843719/153241068-421f4cfb-dec3-436e-8dcb-cfdfd7ee838e.png">

Repeating the same thing, this shows when the console is enabled, I do not know what is causing it.

**Comment by fowlis** [comment]
This is an issue with a few of DevilBro's plugins, not a general BD issue.
See this issue: https://github.com/mwittrien/BetterDiscordAddons/issues/1380

**Comment by Mister36MN** [comment]
Has been fixed by DevilBro with BFBDB and BetterFriendList updates

**Comment by Aholicknight** [comment]
It appears that this has been fixed with the latest updates.
