### ISSUE TITLE
[Bug] Cannot adjust user volumes using slider 

### ISSUE THREAD

**Issue by Tarentules** [BetterDiscord/BetterDiscord#1207]
**Describe the Bug**
Cannot change user volumes in voice channels by pulling the volume slider.

**To Reproduce**
Have BD installed and join a voice channel with another user and try to pull the volume slider to another position.  You can click the volume slider to a random point on the slider and it will jump to that point sometimes but does not always work. 

**Expected Behavior**
Change volume by using the slider normally by pressing and then moving my mouse to adjust it a bit more precisely.

**Screenshots**
Do not have a screenshot but have a gif I made of the error here.
https://i.imgur.com/rscwsl4.gif

**Discord Version**
stable

**Additional Context**
At first I thought this issue was due to the plugin (Better volume) I have installed but I removed that disabled and entirely removed the plugin and still encountered the issue. This was also after removing all other themes and plugins and then re-installing BD as well.

**Comment by rauenzi** [comment]
I am unable to reproduce the issue

**Comment by dav1312** [comment]
Probably an issue with the plugin (BetterVolume) rather than BetterDiscord itself

**Comment by Tarentules** [comment]
Looks like it was a different plugin entirely that also would not show in my plugin list. Sorry about that. Was able to reproduce it with that plugin installed but once it was removed it would work like normal again.

**Comment by Cheekster2016** [comment]
@Tarentules what plugin is it? i am having the same issue
