### ISSUE TITLE
BetterDiscord doesn't auto-update some plugins[Bug]

### ISSUE THREAD

**Issue by skelly37** [BetterDiscord/BetterDiscord#1208]
**Describe the Bug**
Even though [one of the plugins](https://github.com/oSumAtrIX/BetterDiscordPlugins/blob/master/NitroEmoteAndScreenShareBypass.plugin.js) I'm using seems to have correct header with meta, BetterDiscord doesn't fetch updates from Github. It's not a problem strictly connected to me, it happened to other user [link](https://github.com/oSumAtrIX/BetterDiscordPlugins/issues/20).

**To Reproduce**
1) Download the plugin and enable it
2) Wait for eternity until you see a prompt for update

**Expected Behavior**
*New update available* prompt.

**Discord Version**
Stable 113977 (12a4d58)
BetterDiscord 1.5.1

**Additional Context**
I'm using Linux if it changes anything.

**Comment by dav1312** [comment]
BetterDiscord doesn't handle plugin updates

**Comment by TheCommieAxolotl** [comment]
Also that plugin is not supported by BetterDiscord and can get your account banned
