### ISSUE TITLE
[Feature] More insightful debugging data on theme/plugin compile errors

### ISSUE THREAD

**Issue by Delta-official** [BetterDiscord/BetterDiscord#1209]
**Is your feature request related to a problem? Please describe.**

When using CSS supersets like SCSS I've faced a few issues where the code would refuse to compile due to some obscure transpiler behavior and I would often get frustrated because when I try to look where the compilation failed I simply couldn't find the information I needed.

**Describe the feature you'd like**

I'd like that BD would have a better error tracing (i.e line number of where the compilation failed) in order to allow easier debugging

**Comment by TheCommieAxolotl** [comment]
BD already does this to some extent,
<img width="100" src="https://user-images.githubusercontent.com/87679354/153697800-c990efed-e433-4563-988d-3a50319894b2.png">

<img width="362" alt="2" src="https://user-images.githubusercontent.com/87679354/153697804-3aae0750-6019-479f-acc6-3989eaf84104.png">

**Comment by Inve1951** [comment]
Compile errors can't be traced beyond what we already got in the console. This is due to the *compilation* being done by v8, we don't parse the js ourselves.
Is there any other additional information you would you like to see?

**Comment by Delta-official** [comment]
honestly i would be perfectly fine with a line number and possibly column

**Comment by rauenzi** [comment]
Can you give an example of what error you encountered versus what error BD showed in console? As @Inve1951 said, the compilation phase is not done by us.

**Comment by Delta-official** [comment]
i cannot give an example off the top of my head but i definitely do remember some moments where a proper traceback would have been useful in order to track down the error faster

**Comment by rauenzi** [comment]
Well without further info, I'm not sure there's much I can do. As was already stated the compilation stage is done by v8 and any error there is spit out into the console indicating line numbers when possible. See example:
![image](https://user-images.githubusercontent.com/6865942/154309629-bfa1d60e-b5fd-4daa-bc11-fe8e1dd57e18.png)
