### ISSUE TITLE
[Bug] Discord Canary 114799 (009b870) Not Working.

### ISSUE THREAD

**Issue by NightTabGit** [BetterDiscord/BetterDiscord#1214]
**Describe the Bug**
I just updated discord, and now BetterDiscord wont re-install. Using the installer for Repairing does not working, or removing, then re installing. 

**To Reproduce**
Update discord canary. BetterDiscord will not be loaded.

**Expected Behavior**
Standard discord client seen.

**Screenshots**
Regular discord.

**Discord Version**
Canary 114799 (009b870)

**Additional Context**
Nope.

**Comment by hiranokite** [comment]
Canary 114864 (e16662d) not working too

**Comment by ZoeyCluff** [comment]
Canary 114895 (a87dc12) not working as well.

**Comment by MahdeenSky** [comment]
same

**Comment by Evotushon** [comment]
Canary 114909 (fd7024f) not working too

**Comment by Zen1thOrSomething** [comment]
yeah also on mac just stopped working after the update

**Comment by Giotje** [comment]
i switched to the PTB client for the time being. not really a fix, but it still injects

**Comment by gibmadikka** [comment]
Instead of posting more messages with your individual canary versions just react to the emoji in the first post. Discord pushed new features in it and it's expected to be broken, be patient.

**Comment by remtheblue** [comment]
doesn't work for me either

**Comment by rauenzi** [comment]
Please reinstall
