### ISSUE TITLE
[Feature] Winget support? (eh and maybe choco aswell?)

### ISSUE THREAD

**Issue by Macleykun** [BetterDiscord/BetterDiscord#1215]
**Is your feature request related to a problem? Please describe.**
Really easily and quickly install better discord (silently is needed for this)

**Describe the feature you'd like**
winget install betterdiscord.betterdiscord

**Additional context**
Currently i'm working on winget support for a different [project](https://github.com/microsoft/winget-pkgs/pull/46503). But though, why not check if i can do this one aswell :-).

While i'm still figuring out the last bits of the automation/creation of a winget package. I do wanted to suggest the idea.

Dev wise, we do need a silent way to install Betterdiscord however...

**Comment by Inve1951** [comment]
consider silent installation via a batch script:
```bat
git clone https://github.com/BetterDiscord/BetterDiscord.git &&
cd BetterDiscord && ^
npm i && ^
npm run build && ^
npm run inject
```
untested, should work though
obviously depends on git, node.js and npm being installed

**Comment by Macleykun** [comment]
> consider silent installation via a batch script:
> 
> ```batchfile
> git clone https://github.com/BetterDiscord/BetterDiscord.git && ^
> cd BetterDiscord && ^
> npm i && ^
> npm run build && ^
> npm run inject
> ```
> 
> untested, should work though obviously depends on git, node.js and npm being installed

sadly enough, winget requires only one exe and it can only get arguments.
They are quite strict in this sadly :c

**Comment by Inve1951** [comment]
i'm suggesting this as an alternative to winget, which btw i haven't heard of ever

**Comment by Macleykun** [comment]
> i'm suggesting this as an alternative to winget, which btw i haven't heard of ever

winget is like apt/yum/brew on linux/mac but then for windows! (like chocolatly did former to winget).

from powershell, you can easily winget search NAME and winget install NAME withoud using a browser!

**Comment by Macleykun** [comment]
> > Dev wise, we do need a silent way to install Betterdiscord however...
> 
> Can I ask why? I don't see a very big need for this at all. And if the need is there, you can just clone the repo once, then pull and build latest anytime you want to reinstall.

Winget is like apt for linux and winget is able to make it really easy for users to install programs and such.
I think winget is great to quickly install/deinstall programs instead of going to a website. It also allows to update all apps both microsoft store and winget to be updated in one go, silently withoud any user interraction.

That last point is the reason why a silent option would be needed if you want to allow the community/support winget install.

I tottaly understand if you think this isn't useful/ideal for this project and therefore can close the issue if you see fit :).

**Comment by speedstyle** [comment]
What huge changes? Aren't Chocolatey packages just a powershell script to silently download and run an installer?

**Comment by Technetium1** [comment]
I don't believe Powershell has a way to automate a custom Electron app unless flags are added for each feature, and there are none. There is also no MSI option, which would also require adding those flags all around.

**Comment by speedstyle** [comment]
The installer is an electron wrapper on the actual installation scripts. Chocolatey doesn't have to download the GUI, just run those scripts

**Comment by Technetium1** [comment]
That is not my interpretation of it. I reread this readme https://github.com/BetterDiscord/Installer#codebase section and it seems to reinforce that it's an Electron app. The scripts are triggered by an Electron app, rather than the other way around. Look especially at files under: 
> main   // Electron "main" process. Creates and configures the BrowserWindow.

See how you cannot call this script externally for example? https://github.com/BetterDiscord/Installer/blob/development/src/renderer/actions/install.js
