### ISSUE TITLE
[Bug] BetterDiscord not working

### ISSUE THREAD

**Issue by Nixos4444** [BetterDiscord/BetterDiscord#1216]
**BetterDiscord not working on discord PTB**
**Screenshots**
![image](https://user-images.githubusercontent.com/48947296/154169853-8d612975-1c85-4f95-a846-363809f0b91c.png)
![image](https://user-images.githubusercontent.com/48947296/154169892-58caa998-cb90-49d8-8a2e-a84520392b2d.png)
![image](https://user-images.githubusercontent.com/48947296/154170235-c2502277-fc25-45ec-8dfd-a9e144bba01e.png)

**Discord Version**
<PTB Stable 115008 (97968e1) Host 1.0.9003 Windows 10 64-Bit (10.0.19044) >

**Comment by SmolAlli** [comment]
Discord released an update that broke Discord for Canary and PTB. This is also mentioned in #1214

**Comment by Uxusk1** [comment]
same betterdiscord is not working anymore :<

**Comment by xapim** [comment]
Yup latest update blocked better discord

**Comment by SenkoKitsune** [comment]
BetterDiscord not working for me either

**Comment by rauenzi** [comment]
These comments are entirely unhelpful
