### ISSUE TITLE
Better discord stop working [Bug]

### ISSUE THREAD

**Issue by SamKittens** [BetterDiscord/BetterDiscord#1218]
**Describe the Bug**
 I was using discord when suddenly it restarted, by doing this better discord stopped working, try to reinstall better discord, repair it, delete it and put it back and nothing, it doesn't work

**Discord Version**

**Comment by Inve1951** [comment]
Duplicate of #1216.

**Comment by FireTonnor** [comment]
⚠️ A Discord update has broken BD on all platforms and across all release channels. Expect an update soon but be patient.  ⚠️
