### ISSUE TITLE
Auto Updates

### ISSUE THREAD

**Issue by aledlb8** [BetterDiscord/BetterDiscord#1224]
PLEASE ADD AUTO UPDATES, PLEASE
im tired of downloading it in the website everytime a new updates comes out

**Comment by dav1312** [comment]
BD already has update checking and it notifies you when a new update is available... you just need to press a button
You obviously can't use that if Discord doesn't even work with BD (because of a crash for example)

**Comment by Inve1951** [comment]
There already are in-app update notices for BD itself, however, based on the nature of the breakage, it can and does happen that BD *uninjects* in which case a fresh installation will always be necessary. There isn't much we can do about that.
