### ISSUE TITLE
[Bug] Public servers button causing crashes

### ISSUE THREAD

**Issue by fowlis** [BetterDiscord/BetterDiscord#1227]
**Describe the Bug**
Crashing when clicking the public servers button.

**Screenshots**
![](https://i.imgur.com/nLGAm1t.png)

**Discord Version**
![](https://i.imgur.com/BvHBL7N.png)

**Additional Context**
For troubleshooting purposes, I removed all my plugins and the error still occurred.

**Comment by usrDottik** [comment]
I had this issue on Stable Discord, strangely it doesn't seem to happen on Discord Canary
