### ISSUE TITLE
Discord crashes on startup [Bug]

### ISSUE THREAD

**Issue by byKeksYT** [BetterDiscord/BetterDiscord#1228]
**Describe the Bug**
Every time I start the Discord client with BetterDiscord, it loads all the plugins and themes and after a short amount of time it crashes with the `YOU DIED` screen.

**To Reproduce**
Start Discord with BetterDiscord, click on some server and then Discord crashes. Also, if you don't switch to another server before BetterDiscord loads all plugins, it crashes again and again everytime you start up Discord.

**Expected Behavior**
I expect Discord not to crash when I click on a server and when I start it.

**Screenshots**
![Screenshot of my Discord console on startup](https://user-images.githubusercontent.com/54219222/154510852-0fe4fba7-d7b7-4300-8e4a-091682a485a8.png)

**Discord Version**
![Stable](https://verstandlxs.live/png/22af57e584d38102162ffe4af0161b06.png)

**Comment by iy9k** [comment]
if you use the betterbottags plugin, try disabling that as it can cause discord to crash

**Comment by Firecul** [comment]
> if you use the betterbottags plugin, try disabling that as it can cause discord to crash

Yip that was the issue with my crash, thanks for the suggestion.

**Comment by SmolAlli** [comment]
Not a BetterDiscord issue.
