### ISSUE TITLE
[Bug] Doesnt work again quickfix bypassed

### ISSUE THREAD

**Issue by Nixos4444** [BetterDiscord/BetterDiscord#1232]
https://github.com/BetterDiscord/BetterDiscord/issues/1216#issue-1139335754
![image](https://user-images.githubusercontent.com/48947296/154613556-4aabffa3-ff5f-4e7a-ba0d-616d90cac802.png)

**Comment by SmolAlli** [comment]
It was not a "quick fix" and it was not "bypassed". Discord made another change, and that means that you will need to install into the `app-1.0.9004` folder in `%localappdata%\Discord
For any further questions, please ask in #support at the [Discord server](https://betterdiscord.app/invite)

**Comment by Nixos4444** [comment]
my bad had to reinstall after update
