### ISSUE TITLE
BD Installer keeps crashing on i3wm

### ISSUE THREAD

**Issue by jonasrdl** [BetterDiscord/BetterDiscord#1235]
**Describe the Bug**
When i open the BD Installer it keeps crashing.

**To Reproduce**
Download the official installer, run it.

**Expected Behavior**
Install BD

**Discord Version**
Stable

**Additional Context**

OS: Garuda Linux
WM: i3
Graphics Card: Nvidia GeForce RTX 3060

It works fine on Gnome. So it's up to i3wm. I'll leave the issue open anyway, because there will definitely be others with the same problem using i3wm.

It's not a serious bug as there are workarounds (use a different window manager) but I think someone should take a look anyway.

Error message (terminal):
```
Better Discord Installer 1.1.1
The installer is up to date.
[527787:0220/164335.293822:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
[1]    527787 trace trap (core dumped)  ./BetterDiscord-Linux.AppImage
```

**Comment by smol-cat** [comment]
Same issue here, I also use i3wm

**Comment by completelyfcked** [comment]
"gpu process isn't usable"
🤡

**Comment by charitarthchugh** [comment]
I am facing the same thing, on Gnome x11

**Comment by mish1git** [comment]
Try using the installer with --no-sandbox

**Comment by jonasrdl** [comment]
> Try using the installer with --no-sandbox

Actually worked, thanks a lot. I'll leave the issue open anyway. Just someone looking at it.

**Comment by KarlOfDuty** [comment]
I am having the same issue, running Manjaro with KDE-Plasma. I happens both with the AUR package and the official AppImage from here. Running it with --no-sandbox fixes it though as others above have mentioned.

**Comment by DaniloNicacio** [comment]
> Try using the installer with --no-sandbox

Thank you so much, it worked :D

**Comment by iTrooz** [comment]
it works indeed !
May I suggest to add a notice in the logs to use `--no-sandbox`, when it crashes ?
