### ISSUE TITLE
[Feature] Mobile Android Version

### ISSUE THREAD

**Issue by hhroot** [BetterDiscord/BetterDiscord#1240]
**Is your feature request related to a problem? Please describe.**
Cannot communicate on Discord when away from your computer or when there is no computer around

**Describe the feature you'd like**
It is recommended to add an installer or plugin for the mobile Android version

**Comment by SmolAlli** [comment]
There will not be an Android version of BetterDiscord

**Comment by altro50** [comment]
The Android version of Discord is completely different from the regular Electron one, it's not as easy as "add an installer or plugin for the mobile Android version".

**Comment by brys0** [comment]
> **Is your feature request related to a problem? Please describe.**
> Cannot communicate on Discord when away from your computer or when there is no computer around
> 
> **Describe the feature you'd like**
> It is recommended to add an installer or plugin for the mobile Android version
> 

Please look at Aliucord for mobile android!
