### ISSUE TITLE
[Bug] typing "MOIN" leads to nonexisting emote

### ISSUE THREAD

**Issue by 3nt3** [BetterDiscord/BetterDiscord#1243]
**Describe the Bug**
When you create a message only contains "MOIN" BetterDiscord tries to look up an emote that does not exist

**To Reproduce**
Type MOIN and send it or have a message sent to you that contains MOIN

**Expected Behavior**
Either a real image or just the text

**Screenshots**
![2022-02-28T14:39:44+01:00](https://user-images.githubusercontent.com/39235738/155994083-e255dc06-f63e-41c3-a1a1-9c7a425a1937.png)

**Discord Version**
Stable

**Steps to fix**
Block `"MOIN"`

**Comment by SmolAlli** [comment]
It appears that this specific emote has been deleted off of FrankerFaceZ, hence the emote just showing the default "broken image" picture instead.
For a temporary fix, disable FFZ emotes in the emotes settings.

**Comment by 3nt3** [comment]
I know that would temporarily feels it, I was more interested in actually fixing it (if that is even possible)

**Comment by Tropix126** [comment]
> I know that would temporarily feels it, I was more interested in actually fixing it (if that is even possible)

Believe that there are future plans to move the emote module into a separate plugin, so i'd recommend waiting until that happens.
