### ISSUE TITLE
[Bug] Betterdiscord PFP bug

### ISSUE THREAD

**Issue by windosws** [BetterDiscord/BetterDiscord#1249]
On channel the pfp of users bug like this:
![image](https://user-images.githubusercontent.com/101200483/157537632-799a14f5-20dc-4602-97b6-8667fb534ce8.png)

If you know how to fix pls (i turn off all themes and when i install again discord without betterdiscord there is not pfp bug)

**Comment by Strencher** [comment]
This is an issue with a plugin you have ([StatusEverywhere](https://github.com/Strencher/BetterDiscordStuff/issues/158)).

**Comment by doggybootsy** [comment]
This isn't a bug with bd
Place this in custom css for now
```css
.avatar-2e8lTP:before{
display:initial;
}
```
