### ISSUE TITLE
Hot links no longer launch 

### ISSUE THREAD

**Issue by WilsonBradley** [BetterDiscord/BetterDiscord#1250]
Thanks guys for all you do.. Trying to love Discord and this helps.. ;-)

For some reason after installing the mod, clicking on url links in messages no longer launch/ They don't do anything.
Have to copy and paste into browser..

Looking for suggestions where to look to resolve..

Cheers..

**Comment by ItMeSarah** [comment]
I once had this issue, turned out it was nothing to do with BD or Discord at all, running your main browser as Admin causes other programs to no longer be able to have clickable links.

**Comment by rauenzi** [comment]
See above
