### ISSUE TITLE
BetterDiscord does not install at all

### ISSUE THREAD

**Issue by Jorapama** [BetterDiscord/BetterDiscord#1251]
BetterDiscord fails when trying to install on other users

Hi, I'm having a issue to install BetterDiscord If I'm in other Windows account the program simply do not install at all. If I change to the primary account BetterDiscord installs just fine, but in my Windows account simply don't install.

The installer screen log:

```
Starting Install...

Creating required directories...
✅ Directory exists: C:\Users\User\AppData\Roaming\BetterDiscord
✅ Directory exists: C:\Users\User\AppData\Roaming\BetterDiscord\data
✅ Directory exists: C:\Users\User\AppData\Roaming\BetterDiscord\themes
✅ Directory exists: C:\Users\User\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
✅ Package downloaded

Injecting shims...
Injecting into: C:\Users\User\AppData\Local\Discord\app-1.0.9004\resources
✅ Injection successful
✅ Shims injected

Restarting Discord...
Attempting to kill Discord
✅ Discord restarted

Install completed!
```

Note: 
Discord isn't restarted and If I close Discord and open again BetterDiscord isn't installed

![Screenshot 2022-03-14 093219](https://user-images.githubusercontent.com/43591096/158172728-2dbd9eb9-2d83-448b-a539-e97998541402.png)

**Comment by SmolAlli** [comment]
Join the BetterDiscord server for help
https://betterdiscord.app/invite

**Comment by Jorapama** [comment]
I restarted the computer BetterDiscord was installed but the themes and plugins just don't show up in Discord.

Any suggestions on what to do or how to fix it?

![image](https://user-images.githubusercontent.com/43591096/158450844-0dd18377-27b2-4811-aba6-790b2f3409e3.png)

![image](https://user-images.githubusercontent.com/43591096/158450875-aa7c33ab-16a9-4c9b-a772-cf0a7c2b7b2c.png)

**Comment by rauenzi** [comment]
Do you have file extensions hidden? It could be a double `.js` issue
