### ISSUE TITLE
 switches in EXE installer[Feature]

### ISSUE THREAD

**Issue by solomoncyj** [BetterDiscord/BetterDiscord#1252]
**Is your feature request related to a problem? Please describe.**

 switches in EXE installer
**Describe the feature you'd like**

switches that allow silent execution of exe
eg.
``` 
1.<path> /S : automaticaly installs better discord to all found versions of discord
2.<path>/uninstall : uninstalls better discord to all found versions of discord
3. <path> [/uninstall] /target <target version> : installs/uninstalls better discord to target version only
note : [] means optional
```
**Additional context**

**Comment by SmolAlli** [comment]
This should probably go into the [Installer's repository](https://github.com/BetterDiscord/Installer/issues) instead.

**Comment by rauenzi** [comment]
I will not be doing command line switches to silently run an electron application
