### ISSUE TITLE
[Bug] Role icons do not display if Discord is set to “Compact” mode

### ISSUE THREAD

**Issue by alterNERDtive** [BetterDiscord/BetterDiscord#1253]
**Describe the Bug**

When Discord is set to “Compact” mode in “App Settings” → “Appearance” → “Message Display”, role icons are swallowed by BetterDiscord.

**To Reproduce**

Set “Message Display” to “Compact”. 
![image](https://user-images.githubusercontent.com/53827887/159114760-95bfd2f1-3220-44b7-b804-0709f8fc280c.png)

**Expected Behavior**

Role icons should still display next to people’s names.

**Screenshots**

![image](https://user-images.githubusercontent.com/53827887/159114855-844a0674-fed2-42c2-bce1-96fc166e4681.png)
(Compact)

vs.

![image](https://user-images.githubusercontent.com/53827887/159114864-3e927800-b5b8-411a-9203-aa0e050b59c5.png)
(Cosy)

**Discord Version**

![image](https://user-images.githubusercontent.com/53827887/159115020-dc08a599-5b57-4c33-bc3e-984d8d71078b.png)

For the record, same thing on my Linux machines.

**Additional Context**

This is by no means a new bug, it has existed since these icons were introduced. I was just wondering why it was _still_ a thing, and decided to test some things. That’s when I realized that it only happens in Compact mode <.<

I also made sure to test w/o any additional plugins installed in BetterDiscord.

**Comment by SmolAlli** [comment]
Go tell the plugin dev about it. This isn't a repo to report issues for plugins.
https://github.com/mwittrien/BetterDiscordAddons/issues if you need the link for ShowBadgesInChat

**Comment by rauenzi** [comment]
Does this happen without BD installed?

**Comment by rauenzi** [comment]
@SmolAlli I believe you have mistaken this for something else. The user is referring to Discord's role icons from boosting.

**Comment by alterNERDtive** [comment]
> Does this happen without BD installed?

No, vanilla Discord displays the icons just fine in both modes.

**Comment by alterNERDtive** [comment]
> Edit: Actually … WTF. I just went and double-checked. Same bug. Even though I know for a fact that it _did_ display the icons during the last period when BD hadn’t been updated for latest Discord.

This one is really throwing me through a loop now, because at that point (BD didn’t work, role icons appeared) I was sure it was a bug in BD.

**Comment by rauenzi** [comment]
Yeah I thought as much, BD by default doesn't affect anything in that area so it would very strange for BD to cause that.

**Comment by alterNERDtive** [comment]
Sorry for wasting your time and thanks for the immediate response :+1:
