### ISSUE TITLE
[Bug] Missing image icon instead of my nickname in chat

### ISSUE THREAD

**Issue by TomasTokaMrazek** [BetterDiscord/BetterDiscord#1256]
**Describe the Bug**
When someone writes my nickname in a chat, missing icon is presented.

**Screenshots**
![image](https://user-images.githubusercontent.com/15164568/160250431-26fa7185-ab9e-4a60-827f-00f7ab1ffd4d.png)
![image](https://user-images.githubusercontent.com/15164568/160250435-610c670b-24da-41f5-ba60-0487d0a629e1.png)

**Discord Version**
Stable 120595 (9c77fc4)
BetterDiscord 1.5.2
Host 1.0.9004 Windows 10 64-Bit (10.0.22000)

**Additional Context**
All plugins are disabled.

**Comment by TomasTokaMrazek** [comment]
Caused by pulling deleted image from FFZ CDN.

`1:1 GET https://cdn.frankerfacez.com/emoticon/15554/1 404`

**Comment by SmolAlli** [comment]
Same thing as #1243
