### ISSUE TITLE
[Bug] Opening plugins folder using button causes GUI lockup on Linux (duplicate)

### ISSUE THREAD

**Issue by PAI5REECHO** [BetterDiscord/BetterDiscord#1257]
See #647 for original context. Seeing as the original reporter of this issue doesn't want to reopen the issue (https://github.com/BetterDiscord/BetterDiscord/issues/647#issuecomment-1045947903) I'm opening this issue instead.

**Comment by SmolAlli** [comment]
Well can you please give some more information with this issue? Looking at the tags shows that it wasn't reproduced and it wasn't described enough for the cause to be determined.

**Comment by PAI5REECHO** [comment]
> Well can you please give some more information with this issue?

As mentioned in the linked issue this only happens on Linux. I've edited this issue's title to make that more clear.

> Looking at the tags shows that it wasn't reproduced

This is because the person who [tagged](https://github.com/BetterDiscord/BetterDiscord/issues/647#event-4548386405) the issue did not try to reproduce the issue on Linux which is where the bug occurs:

> [Hm this does not happen for me, **however I am not on Linux**. Can anyone else on Linux confirm this?](https://github.com/BetterDiscord/BetterDiscord/issues/647#issuecomment-812911339)

This happens on NixOS, Ubuntu & Arch Linux so it's definitely reproducible.

**Comment by QbDesu** [comment]
"Linux" is not really precise.
Which Desktop Environment and/or Window Manager are you using (KDE, Gnome, i3wm, ...)?
Which installation type are you using (native package/flatpak/snap)?
Which variant are you using (stable/ptb/canary)?
Which version Discord host version are you experiencing this on?
Which filesystem are you using (ext4, btrfs, xfs, f2fs, zfs)?
Any other types of sandboxing going on?

I run both KDE on Arch and i3wm on Fedora, both with stable(0.0.17)+canary, both on ext4, both using native packages, and can't reproduce this nor have I encountered this.

All I'd do is look for known electron bugs anyway, all BD does is use electron's `shell.openPath` function, which in turn just shells out to `xdg-open` on Linux.

**Comment by PAI5REECHO** [comment]
Distro: NixOS Unstable (NixOS/Nixpkgs@710fed5a2483f945b14f4a58af2cd3676b42d8c8)
WM: SwayWM `1.7`
BD Installation: `betterdiscordctl` `2.0.1`
Discord:
```
Stable 122979 (0691b82)
BetterDiscord 1.5.2
Host 0.0.17 Linux 64-Bit (5.17.1)
```

**Comment by PAI5REECHO** [comment]
`xdg-open` isn't assured to fork, it can potentially block indefinitely. That's the bug

**Comment by rauenzi** [comment]
BD does not have control over what electron uses.
