### ISSUE TITLE
[Bug] Discord Canary Stuck on Update Failed Loop (M1 Mac)

### ISSUE THREAD

**Issue by MahdeenSky** [BetterDiscord/BetterDiscord#1258]
**Describe the Bug**

Exactly what the title says, it keeps on retrying every 10 seconds, and fails. I tried repairing and reinstalling, didn't do anything.

**To Reproduce**

All of a sudden discord froze, so i closed it, and when i open it, this happens.

**Expected Behavior**

Discord opens normally. after perhaps an update of some sort because it is discord canary.

**Screenshots**

<img width="298" alt="Screen Shot 2022-03-28 at 12 02 29 AM" src="https://user-images.githubusercontent.com/49484385/160324537-6f8bb135-3679-481b-9f7e-19ee30e03754.png">

**Discord Version**

Canary

**Additional Context**

**Comment by SmolAlli** [comment]
Is there any evidence this is a BetterDiscord issue?
