### ISSUE TITLE
[Bug] so when i go to install bandagedBD it says BandagedBD package does not exist in: C:\Users\Clxpp\AppData\Local\Discord\app-1.0.9004\\resources\BetterDiscordApp-injector. Cannot continue, it is doing it on every build, stable canary and PTB

### ISSUE THREAD

**Issue by Vjrostiic** [BetterDiscord/BetterDiscord#1262]
**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by Vjrostiic** [comment]
![image](https://user-images.githubusercontent.com/103006352/161648067-6780792e-262b-4e9c-90a9-c57d253538c5.png)

**Comment by SmolAlli** [comment]
That is because BandagedBD is really outdated. 
Join the [discord server](https://betterdiscord.app/invite) for help, this doesn't belong on the github repo.
