### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by xapim** [BetterDiscord/BetterDiscord#1264]
**Describe the Bug**

Was working fine yesterday today all channels are locked on all servers cant change to any other channels in any server locked up to the default i was previously 

**To Reproduce**

Repaired same issue removed it completely all went back to normal reinstalled it all locked up again 

**Expected Behavior**

**Screenshots**

even in my own servers all channels are locked up so its unusable right now will have to remove it until the issue is fixed or i cant use discord at all

![image](https://user-images.githubusercontent.com/5507494/162549761-6d4c2c09-b321-498a-a6c0-91f27455a4e1.png)

![image](https://user-images.githubusercontent.com/5507494/162549726-e5cec1e6-3378-499b-b4ba-2e32eeee6f0a.png)

**Discord Version**

Stable

**Additional Context**

**Comment by TheCommieAxolotl** [comment]
This is a plugin issue, not a BD issue, ask in the support server for a fix

**Comment by ArtieFuzzz** [comment]
Disable the ShowhiddenChannels plugin, hopefully it gets fixed sooner or later

**Comment by xapim** [comment]
Yeah just went there ill leave the fix here for those who arent on the discord server 

Disease — Yesterday at 23:48
All channels are locked!
Redownload BDFDB plugin to version 2.2.7. Download latest from the link, save to plugins folder, then press Ctrl+r to restart. https://mwittrien.github.io/downloader/?library
Or try this auto downloader plugin to increase chances of it working. It auto-deletes itself after. https://discord.com/channels/86004744966914048/119918741516451840/962145604107120680

InAppNotifications Spam!
Open the link then press Ctrl/cmd + S, then save to plugins folder.
https://raw.githubusercontent.com/QWERTxD/BetterDiscordPlugins/main/InAppNotifications/InAppNotifications.plugin.js

Plugins Folder Location
Windows: Press win+r and paste
%appdata%/betterdiscord/plugins
Mac: Open Finder, press cmd+shift+G and paste 
~/Library/Application Support/betterdiscord/plugins
Linux: Go to your command line and type 
cd ~/.config/BetterDiscord/plugins
