### ISSUE TITLE
Opening and closing server folders feel laggy

### ISSUE THREAD

**Issue by RenRenIsWeird** [BetterDiscord/BetterDiscord#1268]
**Describe the Bug**
Like the title said, opening and closing server folders feel laggy. Especially when there's more than 5 servers in 1 folder. This never happened when I'm using vanilla Discord

**To Reproduce**
Opening and closing server folders

**Expected Behavior**
Smooth and not laggy animation

**Screenshots**
The video and screenshots of my spec are attached below

**Discord Version**
Stable 123455 (6191f50)

![Screenshot 2022-04-13 002357](https://user-images.githubusercontent.com/56497824/163019390-122d940b-e7b0-4e8a-9760-83cf85f618c1.png)
![Screenshot 2022-04-13 002433](https://user-images.githubusercontent.com/56497824/163019393-2dab2602-6c26-4c77-89fd-3ba125ffbe6c.png)

https://user-images.githubusercontent.com/56497824/163019031-5a266317-aff5-4539-b7c7-a36ce42cc726.mp4

**Comment by Moon99s** [comment]
Yeah , i have the same issue and the more folders the longer it takes to open for me

**Comment by rauenzi** [comment]
Does this occur with a fresh reload using no plugins?
