### ISSUE TITLE
snap support

### ISSUE THREAD

**Issue by jezura777** [BetterDiscord/BetterDiscord#1269]
Please add snap support. Or is there any other option for linux users, because I tried it with official discord download but that didn't work and the installer isn't detecting neither if I try it on official install or on snap install. Your work is amazing and I want to use it but as I mentioned I can't.

**Comment by QbDesu** [comment]
Wrong repo, this is an installer issue and there is already an issue there about it in the Installer Repo:
https://github.com/BetterDiscord/Installer/issues/157

This is however a very low priority and as of now [betterdiscordctl](https://github.com/bb010g/betterdiscordctl) can be used.
