### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by EmbukuN** [BetterDiscord/BetterDiscord#1270]
Discord version- PTB 0.0.29, 64 bit Linux
Betterdiscord v-1.5.3 stops working after discord update and disappears completely from the discord menu alongside all the themes and plugins. The betterdiscord repair feature doesn't work and only causes discord to update again, leading to the same result. Immediate assistance is requested.

**Comment by doggybootsy** [comment]
You should go to the support server for support instead of making a issue
[support server invite](https://discord.gg/0Tmfo5ZbORCRqbAd)
