### ISSUE TITLE
[Bug]BetterDiscord installation problem

### ISSUE THREAD

**Issue by wongFanx** [BetterDiscord/BetterDiscord#1271]
I am in China, using the proxy ClashX. There is a problem that cannot be installed.
<img width="550" alt="image" src="https://user-images.githubusercontent.com/14831158/163143289-00d42750-980f-4e5d-bc56-36e19f34b2d9.png">

**Comment by SmolAlli** [comment]
Join the [BetterDiscord Discord server](https://betterdiscord.app/invite) for support.
This is not for the issues tab on the GitHub.
