### ISSUE TITLE
[Bug] Clash

### ISSUE THREAD

**Issue by tom-choi** [BetterDiscord/BetterDiscord#1272]
**Describe the Bug**

It's not clear about my bugs, but it's seen that when BetterDiscord ender my channel where my discord bot sending messages, it's will clash immediately.
**To Reproduce**

Join https://discord.gg/Ua2njAfQCN and get role for【壞學生】, then open the 【精選R-18】channel
**Expected Behavior**

Clash
**Screenshots**

In normal discord screenshots what will be expected to see
![image](https://user-images.githubusercontent.com/58120532/163153167-85dda163-b1bf-4d51-b18e-84d40c601a4d.png)

**Discord Version**

Stable 123680 (dbf5f56)
BetterDiscord 1.5.3
**Additional Context**

**Comment by FlashlightET** [comment]
same!!!!!! its random as to what channels are doing it ive been having this since my pc restarted itself yesterday

**Comment by FlashlightET** [comment]
It's WhoReacted

**Comment by SmolAlli** [comment]
This is not a BetterDiscord issue. Please use the [Discord server](https://betterdiscord.app/invite) for help when it comes to crashes.
