### ISSUE TITLE
[Bug] canary client crashes instantly

### ISSUE THREAD

**Issue by shamshitty** [BetterDiscord/BetterDiscord#1273]
**Describe the Bug**
whenever i go into a server, my client crashes with discord's normal crash screen (not bd's) and after reloading the client crashes _again_

**To Reproduce**
install bd into canary and just go into any server

**Expected Behavior**
canary not to crash?

**Screenshots**
its hard to capture in screenshots but I do have a recording of it happening

**Discord Version**
Canary

**Comment by SmolAlli** [comment]
Not a BD issue, but rather a plugin. Join the BD server for support - https://betterdiscord.app/invite

**Comment by afl300** [comment]
I'm having this issue but with all my discord versions as i use Discord, Discord PTB and Discord Canary

**Comment by StrandAlexander** [comment]
Did you try disabling all of your plugins and enabling one by one?
I had the same issue this morning and the "WhoReacted" plugin seems to be the perpetrator in my case.

**Comment by ArashiDragon** [comment]
> 

I can confirm that disabling the "WhoReacted" plugin stopped my crashing.
