### ISSUE TITLE
[Bug] Crashing When Going To View A Server/DM

### ISSUE THREAD

**Issue by AnnoyedBlue** [BetterDiscord/BetterDiscord#1274]
**Describe the Bug**
When Leaving To View A Server/DM Discord Crashes And Sends Me To A Reload Screen

**To Reproduce**
View A Server/DM

**Expected Behavior**
Not Crash

**Screenshots**
![image](https://user-images.githubusercontent.com/81892798/163247922-3338d991-62ba-4c8b-b6ab-6e05b592d1bb.png)

**Discord Version**
Stable

**Comment by maenDisease** [comment]
Not a BD issue, quit and reopen Discord, then disable WhoReacted in settings.
