### ISSUE TITLE
my profile does not appear and it crashed when i go to a certain server[Bug]

### ISSUE THREAD

**Issue by XfarisGamerX** [BetterDiscord/BetterDiscord#1275]
**Describe the Bug**
 crashing when i go to a server and pfp and name not appearing

**To Reproduce**
just launch discord for some reason(i cant use ctrl shift i for some reason)

**Expected Behavior**
not crash when i go to servers and seeing my profile

**Screenshots**
![image](https://user-images.githubusercontent.com/56394224/163273396-e087ed47-cae2-4525-b831-1be5405200a7.png)

**Discord Version**
Stable-

**Comment by Strencher** [comment]
This is related to a plugin, not bd itself. Check the pinned messages in our support server.

**Comment by XfarisGamerX** [comment]
which channel
