### ISSUE TITLE
[Bug] Failed to download package: https://api.github.com/repos/BetterDiscord/BetterDiscord/releases - unable to verify the first certificate

### ISSUE THREAD

**Issue by littlekan-gitee** [BetterDiscord/BetterDiscord#1282]
**Describe the Bug**
There is log:
```
Starting Install...

Creating required directories...
✅ Directory exists: C:\Users\78160\AppData\Roaming\BetterDiscord
✅ Directory exists: C:\Users\78160\AppData\Roaming\BetterDiscord\data
✅ Directory exists: C:\Users\78160\AppData\Roaming\BetterDiscord\themes
✅ Directory exists: C:\Users\78160\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
❌ Failed to download package https://api.github.com/repos/BetterDiscord/BetterDiscord/releases
❌ unable to verify the first certificate

The install seems to have failed. If this problem is recurring, join our discord community for support. https://discord.gg/0Tmfo5ZbORCRqbAd
```

**To Reproduce**
I first agreed to the agreement and then chose to install. After selecting the path (I changed the install path of discord), I clicked install. Suddenly, I was prompted that the ASAR file could not be downloaded. I also said that the certificate could not be verified! But I have no problem accessing this address. What the hell is going on?

**Expected Behavior**
I'm from the Internet. I'm going to download it to discord. I thought everything was going well, but I didn't expect this problem!

**Screenshots**
![image](https://user-images.githubusercontent.com/75866787/163797361-c443256a-4e2a-4197-9944-459b47875e26.png)

**Discord Version**
Discord Stable 124397 (2bf79b5) Host 1.0.9004 Windows 10 64-Bit (10.0.22000)

**Additional Context**
Nothing.

**Comment by SmolAlli** [comment]
This is not the right repo, and you should get help in the Discord server rather than on GitHub regardless
https://betterdiscord.app/invite
