### ISSUE TITLE
[Bug]Sometimes users' Cam screen only shows a black screen.

### ISSUE THREAD

**Issue by SeoHoon923** [BetterDiscord/BetterDiscord#1283]
Sometimes users' Cam screen only shows a black screen.
There are times when the cam screen suddenly turns black while it is being displayed normally, and there are times when only a black screen is visible from the start.

The same thing happens with the Discord PTB version of BetterDiscord.

please solve it

**Comment by rauenzi** [comment]
Have not been able to reproduce this, please provide the info the issue template
