### ISSUE TITLE
[Bug] Cannot find Discord, but I have discord

### ISSUE THREAD

**Issue by itsrxmmy** [BetterDiscord/BetterDiscord#1284]
**Describe the Bug**

I opened the installer only to find that discord wasnt found. So I click browse to find it myself, but when I searched "discord" (and "DIscord" in case of case sensitivity) from root "/" it didnt find it. 

If this is important, I installed Discord through the Ubuntu Software Store
**To Reproduce**

```
$ betterdiscordctl --install
```

**Expected Behavior**

BetterDiscord Installer finds Discord
**Screenshots**

**Discord Version**

```
Stable 124823 (6ac2437)
Host 0.0.17 
Linux 64-Bit (5.13.0-40-Generic)
```
**Additional Context**

Ubuntu 20.04.4 LTS is my OS Version

**Comment by rauenzi** [comment]
snap installs are not yet supported and `betterdiscordctl` is not an official BetterDiscord script
