### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Tutuq** [BetterDiscord/BetterDiscord#1285]
**Describe the Bug**
 Better discord crashes the client when the audio device changes and are in a vc 

**To Reproduce**
 Change audio device from what is currently being used while in a vc 

**Expected Behavior**
 Should be able to swap audio devices whenever you like without a crash

**Screenshots**

**Discord Version**
 Stable 124979 (80e9bf7)
BetterDiscord 1.5.3
Host 1.0.9004 Windows 10 64-Bit (10.0.22000)

**Additional Context**

**Comment by Tropix126** [comment]
Can you very that this isn't caused by a plugin?

**Comment by Tutuq** [comment]
> Can you very that this isn't caused by a plugin?

Yes, I ran BD bare bones with no plugins or themes active and it still would crash. I'm not at my computer right now but I believe it also crashes when changing to a different network device too. I updated BD and the issue persisted. On another note, not sure if this helps, but I'm on windows 11 and not 10 like it says in the original post

**Comment by SmolAlli** [comment]
If you enable DevTools (settings -> betterdiscord settings -> developer settings) and open them when you have a crash, is there any errors that you see? If so, please send them. 
Could not replicate Windows 10 (10.019044) BD 1.5.3 Stable 125308

**Comment by Tutuq** [comment]
I did some extra texting and it turned out to be discord itself and nothing to do with BD. I did a full fresh reinstall for Discord and it fixed the issue. Reinstalled BD and everything works great!
