### ISSUE TITLE
[Bug]StereoSoundv0.0.6by bep

### ISSUE THREAD

**Issue by SeoHoon923** [BetterDiscord/BetterDiscord#1286]
I'm using "StereoSoundv0.0.6 by bep" on BetterDiscord.

AppData\Local\Discord\app-1.0.9004\modules
If I replace the discord_voice folder in this path to use the Stereo Plugin, viewers cannot hear the sound of the screen sharing application when I turn on screen sharing in Discord.

If you restore the replaced folder, you can hear the sound from screen sharing, but the Stereo Plugin does not work instead.
What should I do?

I am using version Discord 1.0.9004 / Discord PTB 1.0.1013

**Comment by SmolAlli** [comment]
This is not an issue for this repo, and that plugin is not supported by BetterDiscord.
