### ISSUE TITLE
[Bug] Shakey user profiles

### ISSUE THREAD

**Issue by rjs06** [BetterDiscord/BetterDiscord#1288]
**Describe the Bug**
This doesn't happen all the time, but sometimes when I go to click on someone's profile, it starts almost "bouncing" and I can't interact with their profile.

**To Reproduce**
As I mentioned above, this doesn't always happen but when you click on someone's discord profile it starts to bounce.

**Expected Behavior**
Nothing should happen

**Screenshots**
https://gifyu.com/image/SL5mh

**Discord Version**
Just normal discord

**Additional Context**
N/A

**Comment by Strencher** [comment]
That's an issue with Discord itself, although sometimes plugins can make it worse, but that's still not BD client related.
