### ISSUE TITLE
[Bug] Cant see or change custom status while sing BetterDiscord on MacOS

### ISSUE THREAD

**Issue by Lilith06** [BetterDiscord/BetterDiscord#1289]
I open BetterDiscord on my Mac, everything else is working and is shown perfectly fine except for my custom status. 

This is what i mean.
![Screen Shot 2022-04-27 at 5 36 34 PM](https://user-images.githubusercontent.com/101426270/165489315-7382f029-3890-4582-bec4-3d7d279e5847.png)
I am using the SoftX theme, I also tried changing themes but it would still show up the same. Like so: 
![Screen Shot 2022-04-27 at 5 38 53 PM](https://user-images.githubusercontent.com/101426270/165489764-87ccd818-33d4-40ce-941c-c2f7a5c8edec.png)

**Comment by SmolAlli** [comment]
Disable AccountDetailPlus. Please check that a plugin isn't causing your issue before you post to the GitHub repo, and ask in the Discord server for BetterDiscord.
Invitation - https://betterdiscord.app/invite

**Comment by Lilith06** [comment]
> Disable AccountDetailPlus. Please check that a plugin isn't causing your issue before you post to the GitHub repo, and ask in the Discord server for BetterDiscord. Invitation - https://betterdiscord.app/invite

Thank you so much!  Apologies for causing this. I didn't know, I'll keep it in mind :D
