### ISSUE TITLE
[Bug] Editor-Loader js got blocked by CSP of discord 

### ISSUE THREAD

**Issue by m4p1e** [BetterDiscord/BetterDiscord#1290]
**Describe the Bug**

It seems that our injector for removing csp of discord doesn't work. I have reinstalled discord and BD, but it still didn't work.

**Screenshots**
![image](https://user-images.githubusercontent.com/38675350/165543033-8c0b3d08-ef2d-490e-b097-ee93fd408354.png)
![image](https://user-images.githubusercontent.com/38675350/165543138-10822589-b373-461b-8d8d-64d84d95c6e3.png)

**Discord Version**

Stable

**Additional Context**

**Comment by rauenzi** [comment]
I cannot reproduce this. I have only seen this type of issue occur with people using very aggressive anti-viruses or unregistered versions of Windows. Does any of this apply to you?

**Comment by rauenzi** [comment]
This should be fixed with the latest version using a new method of removing the CSP as well as a failover backup for the editor
