### ISSUE TITLE
[Bug] unable to inject on debian 11

### ISSUE THREAD

**Issue by AcesGamingUK** [BetterDiscord/BetterDiscord#1293]
**Describe the Bug**
error on inject `npm run inject`

**To Reproduce**
run `npm run inject`

**Expected Behavior**
to inject

**Screenshots**
![image](https://user-images.githubusercontent.com/16180389/166126642-f07cebfc-ce98-454f-ab13-7c2ff3e9e757.png)

**Discord Version**
Stable

**Additional Context**

**Comment by SmolAlli** [comment]
Have a try of [betterdiscordctl](https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172) instead.
