### ISSUE TITLE
"You Died" screen upon opening user context menu[Bug]

### ISSUE THREAD

**Issue by risograph** [BetterDiscord/BetterDiscord#1297]
**Describe the Bug**
When I click on my user icon from a text channel, it starts opening up my little user profile, but instead crashes. Other user profiles work, my doesn't.

**Expected Behavior**
Access to personal user popout

**Screenshots**
<img width="1680" alt="Screenshot 2022-05-10 at 6 18 30 PM" src="https://user-images.githubusercontent.com/80423931/167749730-c87dae68-66c5-4db1-ad8b-f2988b60d121.png">

**Discord Version**
Stable, Mac OS 12.1

**Additional Context**
I set up my custom status to be the url of my portfolio, but i just renamed the "Discord" activity. It crashes even after disabling this.

**Comment by SmolAlli** [comment]
Plugin issue not BD issue.

**Comment by afkvido** [comment]
<h2>S K I L L</h2> issue
