### ISSUE TITLE
[Feature] Stop constantly notifying the user when a plugin has an update

### ISSUE THREAD

**Issue by kintsugi** [BetterDiscord/BetterDiscord#1298]
Every time BetterDiscord is launched there is at least one plugin that has an update which requires user interaction to update each plugin. Even when using a reasonable amount of plugins there are multiple updates pushed every day. Previous issues such as #764 and #1224 highlight the problem but the solution given was reactionary and were rightfully closed, but the actual problem is not discussed: it is bad practice when using continuous delivery to actually deliver when the user has no need or want for constant updates. It's annoying and fatiguing and we all don't need yet another distraction.

Silently updating in the background is typically done for services, or for specific cases such as testing versions of software like discord canary/firefox nightly, but plugins should be treated like typical desktop/phone applications, preferably notifying the user about updates at an interval, perhaps weekly. 

Barring that, allow the user to disable update notifications. In my opinion as someone who is particularly anal about applications attempting to grab my attention, not allowing the user to disable update notifications at all is a slap in the face. From what I see of previous issues this has been discussed somewhere before, so I'm curious what opinion the maintainers have about this.

Thanks for your work.

**Comment by SmolAlli** [comment]
1. This is actually something that is done with plugin libraries and not BetterDiscord itself
2. This is done because this being automated is something that BetterDiscord does not want to do, and has been addressed already.
Opening up issues that have already been closed just spams the repository. Please consider this before making an issue.

**Comment by kintsugi** [comment]
I did not suggest for it to be automated, I stated that BD not wanting an automated solution was correct. My proposed solution is to set an interval for update notifications, like many applications do.

**Comment by rauenzi** [comment]
As stated before, this is not done by BD. The libraries check on startup and then at set intervals (~2 hours). The length is so short to account for constant breaking changes since this is a mod where crashes can occur.
