### ISSUE TITLE
[Bug] GPU process isn't usable. Goodbye.

### ISSUE THREAD

**Issue by Crylia** [BetterDiscord/BetterDiscord#1299]
**Describe the Bug**
Trying to launch the Appimage results in the following error
`[13824:0512/204157.656581:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.`

**To Reproduce**
Download the Appimage from the website and launch it

**Expected Behavior**
For it to launch

**Additional Context**
I got an RTX 3070
`NVIDIA-SMI 510.68.02    Driver Version: 510.68.02    CUDA Version: 11.6`

**Comment by Strencher** [comment]
Is this issue related to the BetterDiscord client or the installer? If it's related to the installer, checkout https://github.com/BetterDiscord/Installer.

**Comment by Crylia** [comment]
Thanks, didn't notice.
