### ISSUE TITLE
[Bug] Weird display problems

### ISSUE THREAD

**Issue by GerbilPL** [BetterDiscord/BetterDiscord#1301]
**Describe the Bug**
It makes my display looks like it got older, it has like "scan lines" and resolution gets messed up. This applies to whole screen. This is bad because it even leaves marks of BD UI for a while. And it only happens here.

**To Reproduce**
Go to settings>plugins and open settings for any plugin

**Expected Behavior**
When opening plugin settings everything looks normal.

**Screenshots**

![IMG_20220514_214926](https://user-images.githubusercontent.com/50273945/168446420-a57049d8-f937-4ba2-b584-f30eb30bc522.jpg)
![IMG_20220514_214938](https://user-images.githubusercontent.com/50273945/168446456-603d5224-4bd7-4937-9324-43204bea13c0.jpg)
![IMG_20220514_215024](https://user-images.githubusercontent.com/50273945/168446468-32911490-bb11-404c-adbd-99dcba865ab5.jpg)

**Discord Version**
Stable 128323 (5628003)
BetterDiscord 1.5.3
Windows 10 64-Bit (10.0.22000)

**Additional Context:**
Screen: 2560x1440, G-Sync, 165Hz

Edit: I am unable to reproduce this on my 1920x1080 60Hz screen.

**Comment by Inve1951** [comment]
Try mess with the monitor cable. First two look like a bad DVI connection. No clue what's up with number 3.
Either way, definitely not a BD issue.
