### ISSUE TITLE
[Bug] can't start betterdiscord installer appimage

### ISSUE THREAD

**Issue by samualtnorman** [BetterDiscord/BetterDiscord#1305]
I am getting the appimage from https://betterdiscord.app/ and clicking `Download v1.5.3`.

running in a terminal looks like this:
```
[samual@samual-pc Downloads]$ ./BetterDiscord-Linux.AppImage 
Better Discord Installer 1.1.1
[6947:0518/111841.676023:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
```
a grey rectangle appears in the middle of the screen, then quickly disappears

I have tried deleting and redownloading over and over but nothing changes.

I'm running manjaro kde if that matters.

**Comment by SmolAlli** [comment]
This isn't the right repo, and is a duplicate of https://github.com/BetterDiscord/Installer/issues/247

**Comment by samualtnorman** [comment]
thank you
