### ISSUE TITLE
[Bug] BetterDiscord Enable Transparency Window not working on Linux

### ISSUE THREAD

**Issue by MeowIce** [BetterDiscord/BetterDiscord#1306]
**Describe the Bug**

BetterDiscord Enable Transparency Window not working on Linux.
**To Reproduce**

Click **Gears icon** -> **Settings** under `BetterDiscord` > **Window preference** > **Enable Transparency**.

**Expected Behavior**

BD transparent with this setting enabled.
**Screenshots**

![image](https://user-images.githubusercontent.com/70711319/169240325-da4f50f2-1fb9-4d63-9d53-250c9274dfab.png)

**Discord Version**

Stable 0.0.17
**Additional Context**

OS: Fedora 36
DE: GNOME 42
Windowing system: X11/GNOME on Xorg (nvidia)
Stable 128735 (e3d09bc)
BetterDiscord 1.5.3
Host 0.0.17 Linux 64-Bit (5.17.6-300.Fc36.X86_64)

**Comment by SmolAlli** [comment]
You already linked the old issue which covers this (#1050) and commented on it. You do not need to repost.
Duplicate.

**Comment by MeowIce** [comment]
> You already linked the old issue which covers this (#1050) and commented on it. You do not need to repost. Duplicate.

Is there any workaround for this ? I got it to work yesterday and now it doesn't.
