### ISSUE TITLE
[Bug] BetterDiscord doesn't start on boot/startup

### ISSUE THREAD

**Issue by EmiliaTheGoddess** [BetterDiscord/BetterDiscord#1309]
**Describe the Bug**
BetterDiscord does not load on startup, only starts after a repair.

**To Reproduce**
Install BetterDiscord
Do a reboot
BetterDiscord is gone

**Expected Behavior**
BetterDiscord should not get removed on every system restart

**Discord Version**
Canary

**Additional Context**
I use a fresh Arch Linux install with the 5.17.9 kernel.
I use K Desktop Environment as my DE and Discord Canary is set on startup from KDE settings.

**Comment by SmolAlli** [comment]
Have you tried using betterdiscordctl rather than the appimage installer?
link - https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172

**Comment by EmiliaTheGoddess** [comment]
I just tried it and it worked! Thank you so much for helping me and I'm sorry for wasting your time. Have a nice day!

**Comment by Sir-Calvin** [comment]
Hi i have the same issue but on Windows. Does anyone have a solution for that?
