### ISSUE TITLE
Discord crushes when i unplug and replug my mic in a call[Bug]

### ISSUE THREAD

**Issue by Pougiouk** [BetterDiscord/BetterDiscord#1310]
**Describe the Bug**
For some time now my microphone doesn't get ditected by my computer and i have to unplug and replug it to work but i only remember to do this when im in call and for the past few months Better Dicord crashes at least once when i do it.

**To Reproduce**
Simply join a call and unplug your microphone.

**Expected Behavior**
Discord Souldn't crash when I unplug my mic.

**Screenshots**
https://user-images.githubusercontent.com/77492941/170713066-8da24ba0-4708-4478-afcc-783b41427ffa.mp4

**Discord Version**
Stable 129954 (18fc430)

**Comment by Schweinhitti** [comment]
Looks like a discord issue. It also happened while BD was disabled

**Comment by rauenzi** [comment]
@Pougiouk does this only occur with BD?
