### ISSUE TITLE
[Bug] GPU process isn't usable.

### ISSUE THREAD

**Issue by Jigoku** [BetterDiscord/BetterDiscord#1313]
**Describe the Bug**
```
> $ ./BetterDiscord-Linux.AppImage                                                                        
Better Discord Installer 1.1.1
The installer is up to date.
[10434:0601/005156.501429:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
[1]    10434 trace trap  ./BetterDiscord-Linux.AppImage

```

**To Reproduce**
Run the appimage

**Discord Version**
stable

**Additional Context**
using slackware (-current), normal discord runs fine etc

**Comment by Jigoku** [comment]
Have also tried manually installing it; 
```
> $ npm run inject                                                         [±main ●]

> betterdiscord@1.5.3 inject
> node scripts/inject.js


Ensuring build validity
    ✅ Found /home/jigoku/bin/BetterDiscord/dist/injector.js
    ✅ Found /home/jigoku/bin/BetterDiscord/dist/preload.js
    ✅ Found /home/jigoku/bin/BetterDiscord/dist/renderer.js

Ensuring valid package.json
    ✅ Existing package.json is valid

Injecting into Discord
    ✅ Found Discord in /home/jigoku/.config/discord/0.0.17/modules/discord_desktop_core
    ✅ Wrote index.js

Injection successful, please restart Discord.
```

However, discord just seems to run as it usually would without the modifications / options etc.

**Comment by SmolAlli** [comment]
This isn't the right repo, and is a duplicate of https://github.com/BetterDiscord/Installer/issues/247

**Comment by Jigoku** [comment]
> This isn't the right repo, and is a duplicate of [BetterDiscord/Installer#247](https://github.com/BetterDiscord/Installer/issues/247)

Sorry, confused about the separate repo's, although just saw https://github.com/BetterDiscord/Installer/issues/265 , this solves it. Thanks.
