### ISSUE TITLE
[Bug] BD is in Dutch while regular Discord features are in English like supposed to

### ISSUE THREAD

**Issue by AceKiron** [BetterDiscord/BetterDiscord#1315]
**Describe the Bug**
BetterDiscord is in Dutch (my native language) while regular Discord features are in English like supposed to.

**To Reproduce**
1. Live in the Netherlands
2. Set Discord language to English, UK
3. Inject Discord executable with BetterDiscord

**Expected Behavior**
Everything is in English, like I've set in my Discord settings

**Screenshots**
![image](https://user-images.githubusercontent.com/39498818/171917949-f48954e4-b24f-494b-912a-2353ce944b9a.png)

**Discord Version**
Stable

**Comment by rauenzi** [comment]
After changing if you leave the settings menu then re-open it, is it still mis-translated?

**Comment by AceKiron** [comment]
Yes

**Comment by rauenzi** [comment]
Does this happen now with the latest version?

**Comment by AceKiron** [comment]
Doesn't seem to be, thanks.
