### ISSUE TITLE
[`Feature`] Update All, Show/Filter: {Only Active, Only Inactive, All}

### ISSUE THREAD

**Issue by sapioit** [BetterDiscord/BetterDiscord#1316]
**Is your feature request related to a problem? Please describe.**
When there are plugin or theme updates, having an "update all" option would be nice. For example, I have 22 theme updates (which keep resetting, because my Discord keeps crashing on a certain server), and it would be nice to be able to go in the Themes page of the settings, and update them all with a single click, without needing to click 22 times to update them and 20 times to disable them after the update (since only 2 of them I actively use all the time).

Also, sometimes a plugin or theme interferes with another one and makes the experience worse until it's found, especially after an update which breaks things, so it would be nice to be able to see only the enabled or only the disabled themes or plugins. Same for having lots of inactive plugins or themes and looking for an active plugin or theme whose name you don't remember, to change it's settings. And same for accidentally disabling a plugin or theme and only realizing it after you left the Settings menu, so you have to check the whole list one by one. 

**Describe the feature you'd like**
Open settings page, go to Plugins or Themes page, click "Update All" to update all the pending ones without having them auto-enabled. Next to `Sort By` and `Order`, have the option "Show" or "Filter" with the options "All", "Active" or "Enabled", and "Inactive" or "Disabled".

**Additional context**
![screenshot 13807](https://user-images.githubusercontent.com/3173159/172359608-25aff267-6ae1-47f5-be80-d4052c307a0a.png)

**Comment by SmolAlli** [comment]
The screenshot you are showing is from a plugin. Make a request on the [repo for the plugin](https://github.com/mwittrien/BetterDiscordAddons/issues) instead.

**Comment by sapioit** [comment]
Does BetterDiscord not have the "Themes" and "Plugins" pages in the settings? The red bar is from a plugin, but the "Themes" "Themes" and "Plugins" pages are from BetterDiscord, as far as I know. I mean, I suggested for the "Update All" and for the activity filter to be added to BetterDiscord, not to the plugins made for BetterDiscord. Or did you mean that a separate repo is used for those two pages (one repo each, or one for both of them)? 

Thanks for the quick reply! _Sorry I didn't reply sooner, I just saw the email notification._

**Comment by sapioit** [comment]
> The screenshot you are showing is from a plugin. Make a request on the [repo for the plugin](https://github.com/mwittrien/BetterDiscordAddons/issues) instead.

And on that github, I was redirected here. It's officially a catch-22, with everyone ignoring the request.

https://github.com/mwittrien/BetterDiscordAddons/issues/1633

**Comment by sapioit** [comment]
I have edited the original comment, to remove the parts which were from a plugin.
