### ISSUE TITLE
Installer always stuck on killing discord

### ISSUE THREAD

**Issue by Blackpillar** [BetterDiscord/BetterDiscord#1317]
No matter the option I take, uninstall or install or repair, the installer always gets stuck on "Killing Discord... Attempting to kill Discord"
![image](https://user-images.githubusercontent.com/60469830/172687787-c82d93fd-50b5-4b3f-848b-db92e2411e33.png)

**Comment by UltraSyko** [comment]
This also happens to me

**Comment by MKKelvinHK** [comment]
i haven't try for uninstall betterdiscord, but when i try to repair it, it said cannot kill the Discord even with Discord not running atall plus it's fresh new downloaded in official betterdiscord website
![MKKelvinHK_ScreenShot_2022-06-09_17-10-42](https://user-images.githubusercontent.com/42489566/172798261-459d751c-7aed-438d-b698-5b0bb246cefd.png)

**Comment by Evernow** [comment]
> better Discord needs to be updated it doesnt work anymore

Works on my end.

**Comment by SmolAlli** [comment]
First of all, issues with the installer should go to https://github.com/BetterDiscord/Installer/issues
Second of all, you are all coming in here talking about different issues. 
Thirdly - join the Discord server and ask for help before ever making a GH issue - https://betterdiscord.app/invite
