### ISSUE TITLE
[Feature] Windows 11 Window Snap Support

### ISSUE THREAD

**Issue by Dajova** [BetterDiscord/BetterDiscord#1318]
**Is your feature request related to a problem? Please describe.**
This is not related to the Linux Snap issue ive been mostly seeing here, but to the Window Snap feature in Windows 11. BD seems to not even be recognised as a window when using it.

**Describe the feature you'd like**
Just support for Windows 11 Window Snap. Nothing more.

**Additional context**
Base Discord works just fine with it, so it's something BD-related (possibly the Linux Snapping mentioned above)

**Comment by doggybootsy** [comment]
Disable transparency in betterdiscords settings

**Comment by Dajova** [comment]
Huh, that did it. That's interesting. Not sure why that would mess with the snap feature, but at least it works now. Thanks.

**Comment by ChausseBenjamin** [comment]
> Huh, that did it. That's interesting. Not sure why that would mess with the snap feature, but at least it works now. Thanks.

According to BetterDiscord, this is an issue with electron: https://github.com/BetterDiscord/BetterDiscord/issues/362#issuecomment-638200707

This is what they are referring to: 
https://bugs.chromium.org/p/chromium/issues/detail?id=854601
