### ISSUE TITLE
Apple silicone M1 not compatible

### ISSUE THREAD

**Issue by DanielAbsi** [BetterDiscord/BetterDiscord#1321]
I use an apple Apple silicone M1 and BetterDiscord is unable to work on my apple silicone M1

**Comment by maenDisease** [comment]
It works on my M1 MacBook Air

**Comment by Vendetta-Does-Stuff** [comment]
It works perfectly on my m1 MacBook, it's a problem on your end not a bug for all m1 macs.

**Comment by SmolAlli** [comment]
you have also provided no information on what your issue is. please close this and get some support from here - https://betterdiscord.app/invite
