### ISSUE TITLE
Allow SVG custom emojis to be imported[Feature]

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [BetterDiscord/BetterDiscord#1324]
**Is your feature request related to a problem? Please describe.**
SVG is higher quality than PNG

**Describe the feature you'd like**

**Additional context**

**Comment by rauenzi** [comment]
Importing custom emojis is not a feature of BD and will likely never be

**Comment by H-A-M-G-E-R** [comment]
like BD giving you free nitro
