### ISSUE TITLE
Server Channels Jump on First Load [Bug]

### ISSUE THREAD

**Issue by mekasu0124** [BetterDiscord/BetterDiscord#1327]
**Describe the Bug**

When first loading BetterDiscord, it loads all of my addons and themes, including Server Columns. After all the mods are loaded, I'll go to click on a server and I have to wait an extra 5 seconds in order to click the server I want to join as I have to wait for them jump up 3cm and then freeze, and then drop back down 3cm to become clickable

**To Reproduce**

Everytime I load Better Discord. Completely close out the app (right-click icon in system tray and close Discord) <- as I have it set to when the X is clicked, it minimizes instead of closing.

**Expected Behavior**

Load mods, and then click desired server without waiting for everything to jump up and then back down

**Screenshots**

cannot take screen shots as the action is just slightly too fast. I do not have time to prepare the screen shot application, snipping tool.

**Discord Version**

BetterDiscord 1.5.3
Stable 133852(ad1408e)

I also noticed here, that when I clicked Settings, and scrolled to the bottom, the application is registering Window10 instead of Windows11. I'm not on 10. I'm on 11.

**Additional Context**

I'm not sure if it's a margin issue, or what, but I'm unable to fix it myself and I really am enjoying BetterDiscord a lot.

**Comment by Soulivan71** [comment]
I'm having the same

**Comment by rauenzi** [comment]
This is the same root issue as #1203
