### ISSUE TITLE
[Bug] No "Plugins" found

### ISSUE THREAD

**Issue by catarch** [BetterDiscord/BetterDiscord#1328]
**Describe the Bug**
After installing BetterDiscord , there's only "Settings" option under **BETTERDISCORD**

**To Reproduce**
download appimage
run appimage and install BD
no plugins option found in discord settings

**Expected Behavior**
there should be the plugins option

**Screenshots**
![图片](https://user-images.githubusercontent.com/89088411/176641932-be946134-a30e-43ca-adbe-452bd1593fe6.png)

**Discord Version**
Stable 134335 (a128825)
BetterDiscord 1.5.3

**Additional Context**
OS: Arch Linux (Kernel 5.18.7)

**Comment by shaped1** [comment]
Happened to me too

**Comment by lijianyv2-1** [comment]
Oh, this is a serious bug

**Comment by SmolAlli** [comment]
These issues are generally caused by proxies or VPNs which do not allow proper connections to services such as GitHub, leading to BD not loading properly and not showing options other than "settings". Please configure these properly.

**Comment by rauenzi** [comment]
Please see if this still happens with the latest version.

**Comment by andpeterson** [comment]
I want to add that it's even worse for me. I don't have any options listed. I should be on v1.6.2 as I downloaded it yesterday on Discord v141471 Windows10 
![image](https://user-images.githubusercontent.com/13080580/184515336-229df774-d3ce-4659-b323-1bb036c8cad3.png)
