### ISSUE TITLE
Does BD actually modify Discord servers (not the type of servers you can boost)?

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [BetterDiscord/BetterDiscord#1329]

**Comment by Strencher** [comment]
I'm unsure what you mean. Do you mind explaining it a bit better using a comment?

**Comment by H-A-M-G-E-R** [comment]
like a youtube server not discord server

**Comment by Tropix126** [comment]
No, BD runs strictly client-side.

**Comment by Fisheiyy** [comment]
no, how would it even get access to a discord backend server to modify in the first place? you have no idea what your talking about clearly so close this ticket, it literally just makes no sense
