### ISSUE TITLE
Make BD allow me to post stickers larger than 512 kb

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [BetterDiscord/BetterDiscord#1330]
60fps APNGs are gud like nitro-exclusive default stickers

**Comment by TheCommieAxolotl** [comment]
BetterDiscord isn't something to bypass Nitro restrictions, doing so also makes Discord way more likely to terminate your account. I sincerely recommend **not** attempting to bypass size restrictions.

**Comment by Tropix126** [comment]
This also likely isn't possible in the first place.
