### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by buzzgroundie** [BetterDiscord/BetterDiscord#1333]
**Describe the Bug**
Its a bug, where if you type a certain abbreviation it turns into a little emoji of some sort without actually typing colons

**To Reproduce**
Type WTFFFF or NOOOOOO

**Expected Behavior**
I though the text would come out normally

**Screenshots**
![image](https://user-images.githubusercontent.com/90298162/177217165-746e96f7-d959-4c7d-846e-8a229db3f12c.png)
![image](https://user-images.githubusercontent.com/90298162/177217315-b785f0eb-60d8-4439-afd5-e38ccc27c39f.png)

**Discord Version**
Stable: 134842 (3e9741b)

**Additional Context**
It only happens when in uppercase, and I literally have less than a day for nitro to end. But I don't use any emoji plugins.

**Comment by SmolAlli** [comment]
This is the emote system. If you do not want to see this, disable it within BetterDiscord's settings. 
Next time, maybe have a look for yourself or as in the Discord server before just going straight to the repo to report a "bug".

**Comment by buzzgroundie** [comment]
> This is the emote system. If you do not want to see this, disable it within BetterDiscord's settings. Next time, maybe have a look for yourself or ask in the Discord server before just going straight to the repo to report a "bug".

ok so it was the better ttv or frankerfacez emotes. Sorry for bothering you.
