### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by GamerLogic** [BetterDiscord/BetterDiscord#1335]
**Describe the Bug**
<Discord Crashes with "Error Level 9000">

**To Reproduce**
<Seems to be random, sometimes it happens when opening DMs, sometimes happens when trying to access a server>

**Expected Behavior**
<Able to access DMs/Server>

**Screenshots**
<
![Bruh](https://user-images.githubusercontent.com/76422260/178897484-8d25d896-0978-4b83-92fe-b995924410d7.png)
>

**Discord Version**
<Stable>

**Additional Context**
<Bug use to happen with old version of StatusEverywhere (Aug 2020) and ImageUtils (May 2021), but I have neither plugin installed

**Comment by ItMeSarah** [comment]
This is not a BetterDiscord issue. One of your plugins is at fault, currently known issue with AvatarsEverywhere and BetterMessageLinks. If you have either of those, there you go, remove  AvatarsEverywhere, and update BetterMessageLinks to version 1.4.12

**Comment by GamerLogic** [comment]
> This is not a BetterDiscord issue. One of your plugins is at fault, currently known plugins with issues are AvatarsEverywhere and BetterMessageLinks. If you have either of those, there you go, remove AvatarsEverywhere, and update BetterMessageLinks to version 1.4.12

Hi, 1st, thank you for your help, 2nd, sorry I knew this was a plugin issue and not a bd issue, but this [post](https://github.com/BetterDiscord/BetterDiscord/issues/422) was made 2 years ago so I thought itd be ok to post this stuff, so sorry again.
