### ISSUE TITLE
Linux crash with gpu issue .appimage [Bug]

### ISSUE THREAD

**Issue by minecraft333238** [BetterDiscord/BetterDiscord#1336]
**Describe the Bug**
When i start the application (BetterDiscord-Linux.AppImage) the application crash with this error
`[40765:0715/133923.424678:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.`

**To Reproduce**
Use PopOS or ubuntu based distros and run the application with the command
`chmod a+x ./BetterDiscord-Linux.AppImage`
`./BetterDiscord-Linux.AppImage`

**Expected Behavior**
No crash

**Screenshots**
![image](https://user-images.githubusercontent.com/79372025/179217088-5dd79655-9e74-4621-9665-e2160a395d66.png)

**Additional Context**
**But** i can use the arg --disable-gpu-sandbox to fix the crash
Like this `./BetterDiscord-Linux --disable-gpu-sandbox`

Hope this help

**Comment by Inve1951** [comment]
See https://github.com/BetterDiscord/Installer/issues/247
