### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by YuiTakarada** [BetterDiscord/BetterDiscord#1340]
**Describe the Bug**
When I join a call or talk, streams that are open are displayed multiply times. Doesn't matter if i joined the stream or not. After rejoining the talk, reinstalling/repairing betterdiscord and restrting Discord itself doesnt fix the problem.  

**To Reproduce**
 (i dunno what you mean with this question but i'll just answer with what i've thought it means) It happens within at least 5 minutes as i join a talk or call 

**Expected Behavior**
 Every stream to be shown just once. 

**Screenshots**
![image](https://user-images.githubusercontent.com/109485146/179425056-a0ffd9ed-42c8-4149-88e4-6f8c8bce012f.png)
![image](https://user-images.githubusercontent.com/109485146/179425065-ac642b53-856b-4b66-8761-6766138c6deb.png)

**Discord Version**
 standard

**Additional Context**
-

**Comment by maenDisease** [comment]
Does this issue happen with BD uninstalled

**Comment by YuiTakarada** [comment]
> Does this issue happen with BD uninstalled

no

**Comment by maenDisease** [comment]
I have come across several people with this issue and resulted with it being a Discord issue, would you mind troubleshooting it in the BetterDiscord support server?

**Comment by YuiTakarada** [comment]
i will, thanks
