### ISSUE TITLE
[Feature] Use canary flatpak from beta flathub branch

### ISSUE THREAD

**Issue by kaosine** [BetterDiscord/BetterDiscord#1341]
**Is your feature request related to a problem? Please describe.**
When setting up betterdiscord I am unable to specify and use the canary build that's on flatpak. Have to downgrade to normal discord for it to work.

**Describe the feature you'd like**
After adding:

`flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo`

On a system, we should be able to use betterdiscord on that. Yes, I know I can install it from my repos, but I've gotten used to installing things in flatpak or otherwise to keep it contained and prevent stuff from interacting and/or breaking the system.  Plus, it's no different from the normal canary, so it should just work.

The remote add should also be specified in instructions for other users wanting to do the same.

**Comment by maenDisease** [comment]
See #1269

**Comment by kaosine** [comment]
Oh. My bad…IDK why I clicked on this one instead of installer.
