### ISSUE TITLE
[Bug] JavaScript Error

### ISSUE THREAD

**Issue by Gabetoo** [BetterDiscord/BetterDiscord#1344]
**Describe the Bug**
When I try to open BD, shows a JavaScript Error. Says "Cannot find module" (screenshot below).

**To Reproduce**
Just open the main app.

**Expected Behavior**
I don't know why this happens, the last time I opened Discord, was all fine and I neither changed a thing.

**Screenshots**
![image](https://user-images.githubusercontent.com/100107012/180631794-0677f71a-38d6-45bc-ba8c-8d60d5476e88.png)

Maybe if I stop and try to understand what is happening, I could solve the problem, but im too dumb.

**Comment by SmolAlli** [comment]
Are you sure that you haven't touched any of BetterDiscord's files?
You should have a try of uninstalling and reinstalling.
If that doesn't work, uninstall, delete everything in `%appdata%\betterdiscord` (save your addons if you want them still) and then reinstall.

**Comment by Gabetoo** [comment]
Thank you so much.
I only had to delete everything, like you said. I think it was a problem with betterdiscord.asar file, but now is solved.
