### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by RemyBorius** [BetterDiscord/BetterDiscord#1345]
**Describe the Bug**
On linux (I use popOS), when I want to unfold multiple choice selector, nothing appears

**To Reproduce**
- go to Plugins in parametters
- go to the settings of a plugins that contains a multiple choice selector (example : betterformattingredux of betteranimation)
- find a selector
- nothing happens

**Expected Behavior**
- see the choices

**Screenshots**

fold
![image](https://user-images.githubusercontent.com/83087445/180669868-e8bc16d1-7a7e-4ea4-8260-2877be869827.png)

unfold
![image](https://user-images.githubusercontent.com/83087445/180669878-6d43a125-dbea-40e4-9e45-80a99715a076.png)

**Discord Version**
Stable

**Comment by Inve1951** [comment]
This issue tracker is for issues with BetterDiscord only. Plugin settings are provided by the plugin itself.
