### ISSUE TITLE
[Feature] Allow link files for themes and plugins

### ISSUE THREAD

**Issue by CakeWithDivinity** [BetterDiscord/BetterDiscord#1346]
**Is your feature request related to a problem? Please describe.**
I customized my theme a bit by changing the colors in the `.css` file. Now I use [dotbot](https://github.com/anishathalye/dotbot) to organize my dotfiles repo, which creates link files (linux command `ln`) to link the config files to the files in the dotfiles folder. The issue with BetterDiscord is that those link files don't seem to work. Themes are not displayed in the settings anymore and as soon as you restart discord, BetterDiscord crashes until you delete the link file.

**Describe the feature you'd like**
It would be great if BetterDiscord could handle link files, so you can save your BetterDiscord configuration and theme in a dotfiles repo. 

**Additional context**
I can't test this on any other system, but this might also be caused by Discord running as a flatpak program. I am using Fedora with Flathub and installed Discord as a Flatpak, which might cause some issues. Perhaps someone could test with a normal installation if this issue also occurs there.

**Workaround**
For anyone coming across the issue, I am using a workaround to not use link files, but I setup a shell command in my dotbot configuration to move the theme file I customized to the respective folder. This is working fine so far, I can't experience any issues with it.

**Comment by Inve1951** [comment]
It's called [symlinks](https://en.wikipedia.org/wiki/Symbolic_link) and yes, BD does not support them on a per-file basis. This is partly due to the reason that it wouldn't be able to detect file changes.
You can however create a directory symlink instead and cover the whole themes/plugins folder.

**Comment by CakeWithDivinity** [comment]
Oh well okay, I am gonna try that. Thank you for the info.
