### ISSUE TITLE
[Feature] Auto Update Plugins!

### ISSUE THREAD

**Issue by SpencerComputers** [BetterDiscord/BetterDiscord#1347]
**Is your feature request related to a problem? Please describe.**
That little banner that pops up which asks you to update plugins is annoying and repetitive, especially for plugins which get committed to every day.

**Describe the feature you'd like**
Make a toggleable setting which disables that banner and instead automatically updates the plugins without asking.

**Comment by SmolAlli** [comment]
Duplicate of #1224

**Comment by Tropix126** [comment]
BD has no updater at all yet, any notices you get for updating plugins are added by other plugins (probably BDFDB or ZeresPluginLibrary).

**Comment by SpencerComputers** [comment]
> BD has no updater at all *yet*, any notices you get for updating plugins are added by other plugins (probably BDFDB or ZeresPluginLibrary).

Ah okay, makes sense. Thank you!

**Comment by bingbingyahoo27** [comment]
Does BetterDiscord 1.8.0's new plugin/theme update system allow for client-level updating rather than plugin-level? This would be very convenient if so.
