### ISSUE TITLE
[Bug] Latest hotfix isn't working with Discord PTB

### ISSUE THREAD

**Issue by maicol07** [BetterDiscord/BetterDiscord#1348]
**Describe the Bug**
BD is not installed when installing on Discord PTB

**To Reproduce**
Install BD 1.5.3-hotfix on Discord PTB

**Expected Behavior**
Working

**Discord Version**
PTB

**Comment by SmolAlli** [comment]
Was there any particular reason that you downloaded the hotfix?

**Comment by maicol07** [comment]
The standard 1.5.3 didn't work either, so I've tried the hotfix I've seen some minutes ago

**Comment by fowlis** [comment]
I have a solution that worked for me, you could try it too
I first noticed the BD section looked weird, so I assumed it was still installed, just not applying correctly.
![Snipaste_2022-08-01_09-31-00](https://user-images.githubusercontent.com/84232621/182107349-245a1476-f7cd-425d-a43a-fdb9426f42b2.png)
(tried to recreate it, imagine the blurred area isn't there and the seperator is directly below the "BetterDiscord" text)
I redownloaded the installer from https://betterdiscord.app/ and chose "Repair"
And it works fine (for now).
![Snipaste_2022-08-01_09-34-59](https://user-images.githubusercontent.com/84232621/182108055-02054b76-99ef-4cb3-863f-ff9424bf1de7.png)

**Comment by maicol07** [comment]
@fowlis I've already tried to install and repair BD multiple times but none of them worked

**Comment by SmolAlli** [comment]
Did you do what was actually suggested, though? That was the question.

**Comment by maicol07** [comment]
Yes, but I don't see the BetterDiscord section in settings

**Comment by SmolAlli** [comment]
The hotfix was to fix this problem shown below:
![image](https://user-images.githubusercontent.com/22519967/182109752-a6c9924b-612d-4659-b507-6a8e29e79579.png)
Do you even have this present? If not, then you are most likely installing BetterDiscord incorrectly. Regardless, this conversation should be continued in the [BetterDiscord server](https://betterdiscord.app/invite)

**Comment by maicol07** [comment]
No, I don't have it. I've sent a message on BD server!

**Comment by maicol07** [comment]
Fixed with manual version selector in BD installer (preselected version was wrong)
