### ISSUE TITLE
[Bug] Still suggest update after 1.5.3 hotfixe is done

### ISSUE THREAD

**Issue by Airwayx** [BetterDiscord/BetterDiscord#1349]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/70035113/182115720-d6fff09f-0a70-4914-93e6-fd3251f5c0f9.png)
The pop-up still shows for the update to 1.5.3 even if already done.

**To Reproduce**
Restart  Discord

**Expected Behavior**
No more pop-up after the restart installing the hotfix

**Screenshots**
![image](https://user-images.githubusercontent.com/70035113/182115953-96ccf157-e9bf-41a0-8ad2-6a0ac662120e.png)
![image](https://user-images.githubusercontent.com/70035113/182115976-ee1e0fa1-53bf-434d-a3d6-bc16dd4482a1.png)

**Discord Version**
Stable 138734 (047115f)

**Additional Context**
X

**Comment by fowlis** [comment]
This is known. Just skip the prompt and BetterDiscord should work fine.

**Comment by SpotlightForBugs** [comment]
same issue
