### ISSUE TITLE
[Bug] really high ram usage.

### ISSUE THREAD

**Issue by TheRealJake12** [BetterDiscord/BetterDiscord#1352]
**Describe the Bug**

high memory usage (its been at around 600mb before.
**To Reproduce**

Step 1. Open Discord.
Step 2. Join VC for 3 hours. 
Step 3. High memory usage.
**Expected Behavior**

Step 1. Open Discord.
Step 2. Join VC for 3 hours.
Step 3. 300mb memory usage.
**Screenshots**

woops I restarted discord and its normal again. once its high than 300mb Ill post a screenshot.
**Discord Version**

Stable
**Additional Context**

**Comment by SmolAlli** [comment]
This is more likely an issue with a plugin.

**Comment by DogTheBoss** [comment]
I don't know exactly what it's from, plugin or not, but this seems to be a memory leak that eventually causes my discord to crash.

**Comment by StandingPadAnimations** [comment]
What worked for me was removing BDFDB and all the plugins that used it. I think that plugin library has an issue with memory leaks (and I found a lot of replacements) as Discord seems to work perfectly fine now

**Comment by TheRealJake12** [comment]
> What worked for me was removing BDFDB and all the plugins that used it. I think that plugin library has an issue with memory leaks (and I found a lot of replacements) as Discord seems to work perfectly fine now

nah it didnt work. I deleted, reinstalled BD, and used plugins that dont use BDFDB and it was still high

**Comment by ImperiusFate750** [comment]
I can confirm that this always happens with Better Discord. I have no idea if it's related to a plugin or not, but when you leave Discord with BD open for many hours the RAM usage goes up from 300-400 to 800-900 or even more, depends. I always restart my Discord every 3-4 hours so that the RAM usage goes down.

**Comment by TheRealJake12** [comment]
with 1.6.1 its improved but still gets a little high. I'll leave this open for anyone else

**Comment by rauenzi** [comment]
Update 1.6.0 helped to reduce a lot of the memory and leaks from BD itself. It can only do so much for plugins.

**Comment by TheRealJake12** [comment]
ye I have games that have mods and memory is a pain to do. I **Have** to have good memory management because 8gb isnt fun
