### ISSUE TITLE
[Bug] The plugin "EditUsers" keep prompting discord to restart every launch

### ISSUE THREAD

**Issue by burntato** [BetterDiscord/BetterDiscord#1353]
**Describe the Bug**
When better discord launch it tries to activate all plugins that are available and when it tries to activate EditUsers the windows is frozen for a split second and the screen shows a button to restart and nothing more

**To Reproduce**
use the "EditUsers" plugin by devilbro or download the plugin here here
https://betterdiscord.app/plugin/EditUsers

**Expected Behavior**
discord will freeze for a second while its activating the plugin and the window will change into a button that says restart

**Screenshots**

**Discord Version**
Stable

**Additional Context**

**Comment by SmolAlli** [comment]
Then disable it. The upkeep of a plugin is for the developer to deal with, not BetterDiscord.

**Comment by Inve1951** [comment]
not relevant for this codebase
