### ISSUE TITLE
The ability to launch the application without BetterDiscord (for 1 time)

### ISSUE THREAD

**Issue by MrJackcall** [BetterDiscord/BetterDiscord#1354]
Add the ability to disable the launch of Better Discord once (launch the original Discord without modifications). Like "Safe Mode" in Windows
This is useful if you need to take screenshots or videos, for example, but you can't show modifications

**Comment by SmolAlli** [comment]
[This already exists.](https://smolalli.github.io/BetterDiscord/#vanilla)

**Comment by MrJackcall** [comment]
Thanks ♥
