### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Xeris1** [BetterDiscord/BetterDiscord#1355]
**Describe the Bug**
After updating BetterDiscord using the in-app updater, My discord continues to crash when using it for about 30 seconds.

**To Reproduce**
Update to the hotfix version on windows.

**Expected Behavior**
I would expect discord to work :P

**Screenshots**
[](https://imgur.com/NRZzwvz)

**Discord Version**
 Stable

**Additional Context**
 Only happened after updating. Have tried repairing the installation and the issue is still occurring.

**Comment by SmolAlli** [comment]
You should have read the pins in the [BetterDiscord server](https://betterdiscord.app/invite) rather than coming here. Plugins are the culprit for the crash, and the issues page here isn't where you complain about it.

**Comment by Xeris1** [comment]
Didn't mean to complain, was just reporting the crash.
