### ISSUE TITLE
[Bug] BetterDiscord fails to initialise LocaleManager

### ISSUE THREAD

**Issue by rekkisomo** [BetterDiscord/BetterDiscord#1357]
**Describe the Bug**
When BetterDiscord is initialising, it fails on LocaleManager due to an undefined Dispatcher

**To Reproduce**
1. Install BetterDiscord on Canary (139676 (6b089cc))
2. Start Discord

**Expected Behavior**
BetterDiscord loads correctly without fail

**Screenshots**
![image](https://user-images.githubusercontent.com/17891896/182507873-67e5675a-9316-4544-a710-b30a3f42018f.png)
![image](https://user-images.githubusercontent.com/17891896/182507957-cffc847e-3033-435b-aa45-dbc332d9df4b.png)
![image](https://user-images.githubusercontent.com/17891896/182508004-63c403d3-dadf-456e-a4dc-cd8af213654c.png)

**Discord Version**
Canary 139676 (6b089cc)

**Comment by Aida-Enna** [comment]
I'm also getting this bug on stable Discord, it seems the subscribe event code was removed or does not function as intended?

![image](https://user-images.githubusercontent.com/5483362/182686984-13c109a6-4a40-490d-9391-ee0927bb3fe0.png)

![image](https://user-images.githubusercontent.com/5483362/182687143-d7b9f2bf-e849-4955-9bf8-e4e06175d9a2.png)

**Comment by xchatiii** [comment]
Fixed (for me) upon repairing BetterDiscord. Hope this helps.
