### ISSUE TITLE
[Bug] Error Loading, all plugins failing

### ISSUE THREAD

**Issue by cedrixm** [BetterDiscord/BetterDiscord#1359]
**Describe the Bug**
From today, When I load Discord, every plugin fails to load with "couldn't be constructed" displayed for each on the "ADDON ERRORS" Pop-up. And there is no way to get read of the popup, clicking ok, clicking away, Esc, Enter, nothing reacts. So Discord is blocked

**To Reproduce**
Just Load Discord

**Expected Behavior**
Load without error, or at least, allow the "ERROR ADDON" window to be discarded (too big? too many errors? the list spread over the window itself down below)

**Screenshots**

**Discord Version**
Tried Stable, PTB and Canary latests

**Additional Context**
Tried to repair one or all of BD Discord versions, but no change

**Comment by Thijke** [comment]
i also had this, download the new hotfix on the website.

**Comment by cedrixm** [comment]
> i also had this, download the new hotfix on the website.

I'm already on 1.5.3 HF2 :(

**Comment by cedrixm** [comment]
![image](https://user-images.githubusercontent.com/100139179/182615127-d25df0f6-7007-4e02-a394-6e5a542fccc0.png)

**Comment by cedrixm** [comment]
Re-downloaded 1.5.3 HF2, repaired reinstalled, still the same.
Just PTB and Canary seem impacted, for now stable seems to work

**Comment by maenDisease** [comment]
The plug-in errors are due to a Discord update, the hotfix was to fix BetterDiscord not loading.

**Comment by EMREOYUN** [comment]
Weird, I only have issues with UserDetails plugin and nothing else. Using 1.5.3 HF2

**Comment by cedrixm** [comment]
It was working and suddenly not more. There are some issues with plugins indeed, however, not all of them should fail, and must of all (and it's the reason why I reported it here) this windows should disappear and let me use Discord by clicking away or Okay, which doesn't happen, so Discord is blocked

**Comment by DannyPt** [comment]
to me is only ChannelDms

> ChannelDms: Could not be constructed.
>     at Object.initializeAddon (<anonymous>:4:306851)
>     at Object.loadAddon (<anonymous>:4:268341)
>     at Object.loadAddon (<anonymous>:4:305889)
>     at Object.loadAllAddons (<anonymous>:4:270617)
>     at Object.initialize (<anonymous>:4:265066)
>     at Object.initialize (<anonymous>:4:305099)
>     at Object.startup (<anonymous>:4:367116)

**Comment by EMREOYUN** [comment]
Oh, they made it like Russian Roulette.

**Comment by Erfesto** [comment]
My plugin not gives any errors, but changes after plugin editing only accepts after discrod restarting.
Strange.

**Comment by HiddenLeveI** [comment]
> i also had this, download the new hotfix on the website.

I need help, I downloaded it and I tried to install and repair better discord but it can't find discord on my computer, I don't know why. It could be because I'm using a flatpak for discord and or because I'm using ZorinOS as my operating system

**Comment by cedrixm** [comment]
Hi @rauenzi could you please comment on the closure?
Different comments mentioned plugins error but that was not related to BD.
Issue on BD is that when a lot of plugins are in error, the ADDON ERROR window cannot be closed.
Thanks
