### ISSUE TITLE
Error with add ons stuck on screen

### ISSUE THREAD

**Issue by hyxtoria** [BetterDiscord/BetterDiscord#1360]
The error with my add on got stuck on my screen, and i cannot press anything. Not "Okay." or anything else behind it. I've had to completely uninstall BetterDiscord for my discord to work and repairing doesn't fix it.

**Comment by SmolAlli** [comment]
This issue is caused by InvisibleTyping, and potentially other plugins. Remove it from your plugins folder.

**Comment by hyxtoria** [comment]
> 

I removed the addon which had an error. It was secret ring tone. Although after i uninstalled an reinstalled better discord and now it's come up with "Looks like discord has crashed unexpectedly, we've tracked the error and will get right on it" and has given me the option to reload. although it comes up with the same message after i press it.

**Comment by ItMeSarah** [comment]
Then another plugin you have is causing the issue. Check the pins of the support channel in the Discord for information about which plugins are currently causing that issue.
