### ISSUE TITLE
[Bug] None of the plugins are working, and when I try to get into the BetterDiscord settings, it just says changelog

### ISSUE THREAD

**Issue by HiddenLeveI** [BetterDiscord/BetterDiscord#1361]
**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by SmolAlli** [comment]
You need to reinstall BetterDiscord. This has already been fixed with the hotfix releases.

**Comment by StrikerFNOnYT** [comment]
If I reinstall it will it save all my plugins or do I need to re-download them?
