### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by StrikerFNOnYT** [BetterDiscord/BetterDiscord#1363]
**Describe the Bug**

So quick answer, the plugins are not working or showing. Neither is the BetterDiscord Tab In setting.

**To Reproduce**

**Expected Behavior**

I thought all the plugins and the better discord tab in settings would show.

**Screenshots**

<img width="128" alt="image" src="https://user-images.githubusercontent.com/98457448/183395297-b22160d5-f941-4d4d-96f5-fbe7a839d276.png">

**Discord Version**

v1.5.3

**Additional Context**

**Comment by SmolAlli** [comment]
https://github.com/BetterDiscord/BetterDiscord/issues/1361#issuecomment-1205997555
