### ISSUE TITLE
Make Better Discord support Android version of Discord with the new React Native version.

### ISSUE THREAD

**Issue by shawny43** [BetterDiscord/BetterDiscord#1364]
**Is your feature request related to a problem? Please describe.**

We are all waiting for make support BD on all platforms. But now there a new feature that Discord team was there and is about the React Native would replace the old one in Android, that could help the most of people. Just simply doing the same method has Lucky patcher does and you are ready to go. You can see the Youtube Vanced where they made a modded app of YouTube to block any ads in place. It's still possible. Why BetterDiscord still focus on both CSS and JS?

**Describe the feature you'd like**

When React Native version of Discord for Android will come, you can write themes and plugins base under Javascript supported method and build the Discord you want to see at anytime. Themes and Plugins could works if is written on JS in the same way that plugins was made in ElectronJS version of Discord for Desktop. Inject the BD has the mod manager and you are ready to go. In the same way of YT Vanced or Lucky Patcher does.

The only thing BD could do is the same way of YT Vanced and add a Download manager for keep Discord updated on their app and make work across the bridge of Discord API. By creating a Modded React Native version of Discord to allow mods. 

**Additional context**

React Native is a open source project made by Facebook where you can see these links bellow.
https://reactnative.dev/
https://github.com/facebook/react-native

You can see the new Discord Framework update there: https://discord.com/blog/android-react-native-framework-update

**Comment by SmolAlli** [comment]
React Native has been the platform for iOS for a while and yet there hasn't been a single plan for it to be made available for it. Have you ever considered, that maybe that's a lot of work? That other people have already done it with other client mods, and maybe the devs for BetterDiscord simply don't care about the mobile versions of BD?

**Comment by Tropix126** [comment]
Just to answer a few things:
- Although both apps *technically* use react and share many internals with each other, they are still fundamentally different codebases. Just as an example, mobile builds are bundled with Metro while desktop is bundled with Webpack, which would require different module searches.
- React Native is not a browser enviornment like electron. Most plugins heavily rely on browser-specific internals such as the DOM. The JS runtime it uses (Hermes) doesn't even support ES6 classes as of yet, which immediately invalidates BD's current plugin format which is class-based.
- Many plugins rely on desktop-specific internals, such as node and access to the filesystem, which are simply not available on more locked-down mobile operating systems.
- Theme cross-compatibility is more or less a lost cause. Styling works completely different in React Native compared to W3C-complaint CSS.

While i'm not saying it's *impossible* to create a project that has some level of cross-compatibility, it's severely out of the scope of what BD does, and it would require a highly abstracted API as well as an extreme amount of maintenance (the developers of such a mod would need to keep up reverse-engineering two separate production codebases).

That being said, there are already mods for mobile builds of Discord (see: Emnity for android, Aliucord, for iOS). These have their own plugin and theme ecosystem and aren't associated with this project.
