### ISSUE TITLE
[Bug] Extension error popup can't show details

### ISSUE THREAD

**Issue by Rayjacker** [BetterDiscord/BetterDiscord#1365]
**Describe the Bug**

When the extension error popup is shown, clicking on the broken extension to show details shows nothing.

**To Reproduce**

- Launch Betterdiscord with a broken extension installed
- Try to click on the extension's error message
- Nothing pops up.

**Expected Behavior**

The popup should show a detailed explanation of what parts of the extension have gone wrong.

**Screenshots**

![image](https://user-images.githubusercontent.com/77126320/183737030-5603841c-777c-4928-b10a-3397685f3533.png)
TypingUsersPlus is the extension I've clicked on for details.

**Discord Version**

Stable 140575 (12c29a3)
BetterDiscord 1.6.1
Host 1.0.9005 Windows 10 64-Bit (10.0.19044)

**Additional Context**

Did not happen on versions prior to 1.6.1.

**Comment by rauenzi** [comment]
You should report it to the developer. Sometimes there is not much more information to give.
