### ISSUE TITLE
[Inquiry] Can I create a custom install location?

### ISSUE THREAD

**Issue by nilill** [BetterDiscord/BetterDiscord#1366]
I have been trying to move both Discord and BetterDiscord to my secondary drive (D:\). This has come with numerous issues, like having to change Discord's "app-1.0.1016\resources\app\index.js" to require a new location of the betterdiscord.asar file. 

Currently I'm facing two issues: 
1: I'm unable to change the Themes and Plugins folders to the _actual_ BetterDiscord Plugins and Themes paths.
2: There are too many hoops to jump through just to change the directory of my BD install. 

If I may, could I request one or two things to make this easier down the line?
1: Add a custom directory to BD's install path, instead of going straight into "C:\Users\XXXX\AppData\Local\Roaming"
and 2: Some assistance helping me change the directory of BD.

Thank you very much. This isn't an inquiry and more like a half bug report and half feature request, but so be it. Any help would be greatly appreciated.

**Comment by SmolAlli** [comment]
Look into SymLinks.

**Comment by nilill** [comment]
Yeah. Symlinks are the best option. I hope that BD will make it easier to change the directory over time though.
