### ISSUE TITLE
[Bug] Opening Custom CSS crashes Discord PTB

### ISSUE THREAD

**Issue by fowlis** [BetterDiscord/BetterDiscord#1371]
**Describe the Bug**
Title

**To Reproduce**
Try to access Custom CSS on Discord PTB

**Screenshots**
![Snipaste_2022-08-16_12-25-21](https://user-images.githubusercontent.com/84232621/184872316-6301da6d-da17-4625-b56d-91e142b01cd6.png)
Gif example
![](https://cdn.upload.systems/uploads/qJwial9S.gif)

**Discord Version**
Ptb 141822 (e53c017)
BetterDiscord 1.6.2
Host 1.0.1017

**Additional Context**
I did some extra troubleshooting to see if I could fix it myself, I tried:
1. Doing a clean install of PTB with this guide -> https://support.discord.com/hc/en-us/articles/115004307527--Windows-Corrupt-Installation 
2. Unloading all plugins & themes

Not sure if this error occurs on Canary since I don't use it.
Happy to provide more info if needed

**Comment by SmolAlli** [comment]
Can confirm for Canary.

**Comment by Crazypersonalph** [comment]
Can also confirm for Canary

**Comment by Crazypersonalph** [comment]
For me, Discord opens a dialogue saying "Discord crashed, BetterDiscord has automatically disabled itself to prevent further crashing."
It only occurs after ~15 seconds of opening Discord with BetterDiscord

**Comment by fowlis** [comment]
I would edit the issue itself, but I think it would make it look messy, so I'll write this as a seperate comment:
It's also crashing when typing anything into the server search bar.
![](https://cdn.upload.systems/uploads/7nsW6yco.gif)
Through a tiny bit of testing, I can only reproduce this in servers with a lot of messages to search through, I made a blank server to test with and I couldn't reproduce it there.

**Comment by Crazypersonalph** [comment]
> I would edit the issue itself, but I think it would make it look messy, so I'll write this as a seperate comment: It's also crashing when typing anything into the server search bar. ![](https://camo.githubusercontent.com/55af388e707ae8e4ddfb0fa7bab3524d4c99f82de81eeb5e23de8f9fcad18a7b/68747470733a2f2f63646e2e75706c6f61642e73797374656d732f75706c6f6164732f376e73573679636f2e676966) [ ![68747470733a2f2f63646e2e75706c6f61642e73797374656d732f75706c6f6164732f376e73573679636f2e676966](https://camo.githubusercontent.com/55af388e707ae8e4ddfb0fa7bab3524d4c99f82de81eeb5e23de8f9fcad18a7b/68747470733a2f2f63646e2e75706c6f61642e73797374656d732f75706c6f6164732f376e73573679636f2e676966) ](https://camo.githubusercontent.com/55af388e707ae8e4ddfb0fa7bab3524d4c99f82de81eeb5e23de8f9fcad18a7b/68747470733a2f2f63646e2e75706c6f61642e73797374656d732f75706c6f6164732f376e73573679636f2e676966) [ ](https://camo.githubusercontent.com/55af388e707ae8e4ddfb0fa7bab3524d4c99f82de81eeb5e23de8f9fcad18a7b/68747470733a2f2f63646e2e75706c6f61642e73797374656d732f75706c6f6164732f376e73573679636f2e676966) Through a tiny bit of testing, I can only reproduce this in servers with a lot of messages to search through, I made a blank server to test with and I couldn't reproduce it there.

Yeah, I can't reproduce it in my group DM

**Comment by Crazypersonalph** [comment]
I'm not getting a crash message directly through Discord though, it is through another popup, probably because I am on Arch Linux and something is probably different

**Comment by fowlis** [comment]
Fixed in 1.6.3

**Comment by Crazypersonalph** [comment]
I still have this issue, I see it has been fixed, but it is still occurring.
