### ISSUE TITLE
[Bug] BetterDiscord needs to be reinstalled after a Discord update, which is very frequent

### ISSUE THREAD

**Issue by Xryphon** [BetterDiscord/BetterDiscord#1374]
**Describe the Bug**

BetterDiscord is unable to automatically install after a Discord update, meaning that twice every week or so, when Discord updates, I have to reinstall/ repair BetterDiscord.

**To Reproduce**

Update Discord. 

**Expected Behavior**

BetterDiscord should still be installed, albeit it is not.

**Screenshots**

**Discord Version**

Stable.

**Additional Context**

I only remember this occurring now rather than before. Perhaps Discord changed something with updates and it happens to override BetterDiscord?

**Comment by fowlis** [comment]
On Discord Stable, I very rarely receive updates that push out BetterDiscord and force me to install it again. It may be that your client is damaged, and is forcing out the BD injection more frequently.
Also, BetterDiscord cannot automatically reinstall itself when uninjected from the client - it doesn't even load unless it's installed onto your client, so it can't check to see if its been uninjected.

**Comment by Xryphon** [comment]
Seems like it's gotten back to normal for me.

**Comment by LouhaneDelforge** [comment]
up cause I'm experiencing this issue too
this week, discord push 3 updates on startup, had to reinstall better discord each time..

**Comment by fowlis** [comment]
Not an issue exactly, just a byproduct of the way BetterDiscord injects to Discord's files. Those files are commonly replaced every Discord host update which causes BD to "not work" and need reinstalling.

There has been word of the injection method being changed for this to not be a problem anymore.

**Comment by JFMugen** [comment]
> There has been word of the injection method being changed for this to not be a problem anymore.

I guess there is still no change about that right?

**Comment by Zwylair** [comment]
Until the developers made a solution to this, I made a [script](https://github.com/Zwylair/BetterDiscordAutoInstaller) that solves this problem (win only, i'll add linux support soon).

**Comment by Nostrildumbass** [comment]
> Until the developers made a solution to this, I made a [script](https://github.com/Zwylair/BetterDiscordAutoInstaller) that solves this problem (win only, i'll add linux support soon).

Just wanted to drop by and say thank you for creating this, it is appreciated
