### ISSUE TITLE
[Bug] Permanent (And old ) version of a plugin of betterdiscord

### ISSUE THREAD

**Issue by Alvaroelcrak** [BetterDiscord/BetterDiscord#1376]
**Describe the Bug**
Every time i open the discord, i get a message saying that i have to update a plugin and it isnt remove by the new one.
![imagen_2022-08-20_150120411](https://user-images.githubusercontent.com/111641551/185747327-820e9db7-0b5f-4e1c-b971-9352307742ec.png)

**To Reproduce**
The only action that hapens is that i open discord and i get that message.
**Expected Behavior**
I was thinking that repairing the betterdiscord would work. (What a misstake) I try to reinstall the betterdiscord and happens the same.
**Screenshots**
![imagen_2022-08-20_150333791](https://user-images.githubusercontent.com/111641551/185747393-55f37076-f7ff-476c-9a25-4fe9a1c33006.png)

The message of update appears again.
![imagen_2022-08-20_150607783](https://user-images.githubusercontent.com/111641551/185747476-0342eb80-63ce-42be-8184-695f9ede980c.png)

**Discord Version**
Stable 142868 (7835ca6)
BetterDiscord 1.6.3
Host 1.0.9006 Windows 10 64-Bit (10.0.22000)

**Comment by SmolAlli** [comment]
Can you please send a screenshot of your plugins folder?

**Comment by Alvaroelcrak** [comment]
![image](https://user-images.githubusercontent.com/111641551/185747680-d9802e1b-f9ca-40f4-83d0-9208c06188a0.png)

**Comment by Alvaroelcrak** [comment]
I try to uninstall it by this way, but it seems that the file is "inremovable", because if i remove it, appears the next day there like nothing happen.

**Comment by vincentwang0905** [comment]
same
![image](https://user-images.githubusercontent.com/76867533/185748055-10f99d79-f0aa-4ef5-81f4-cbf609cada1f.png)
i update it
reload betterdiscord or reboot betterdiscord
appeared again

**Comment by Alvaroelcrak** [comment]
but i reppair it and nothing seems repaired

**Comment by Alvaroelcrak** [comment]
and i do it 3 times

**Comment by Rayjacker** [comment]
Try to uninstall BetterDiscord, delete the file, and reinstall it. You probably need to manually update the plugin anyway.
