### ISSUE TITLE
[Bug] error 9000 pops up whenever i join a room

### ISSUE THREAD

**Issue by DanielTrye** [BetterDiscord/BetterDiscord#1379]
**Describe the Bug**
 whenever i join a room this error pops up and when i disconnect or someone kicks me and respawn to last checkpoint its okay again

**To Reproduce**
 what?

**Expected Behavior**
 to join a room without the error ._.

**Screenshots**
 ok

**Discord Version**
 idk but i reinstalled everything when i tried to fix it so i got the new ones

**Additional Context**
 nothing.

**Comment by maenDisease** [comment]
Please visit the BetterDiscord support server so we can troubleshoot this further
