### ISSUE TITLE
Discord restarts every 1-3 minutes

### ISSUE THREAD

**Issue by LovelesStraw** [BetterDiscord/BetterDiscord#1382]
It restarts at random times, or  if it doesn't restart it hides the channels and it shows the old messages for some minutes and then restart. I use stable version. The problem might be because Discord got a new update last night and I guess BetterDiscord isn't updated?
![image](https://user-images.githubusercontent.com/111982669/186414753-8bb1d87a-887d-4295-b509-835326a1c5c1.png)
![Screenshot_1](https://user-images.githubusercontent.com/111982669/186414892-e36a673f-f080-4f7a-862d-a4705d9fc151.png)

**Comment by fowlis** [comment]
You're probably using message logger, which is an unofficial plugin and seems to be causing these issues. I'd advise you to delete it.

**Comment by LovelesStraw** [comment]
Okay! Thanks<3, I didn't knew earlier. If it happens again I'll keep you in update

**Comment by top1apelsin** [comment]
Same.
Also fixed with remove message logger.

**Comment by 0Fox** [comment]
There is an update (v1.8.20) for message logger that fixes it.

**Comment by ItMeSarah** [comment]
> There is an update (v1.8.20) for message logger that fixes it.

Not a good idea to use plugins that are unsupported.

**Comment by zxsleebu** [comment]
> There is an update (v1.8.20) for message logger that fixes it.

can you please send the repository link here?

**Comment by 0Fox** [comment]
> > There is an update (v1.8.20) for message logger that fixes it.
> 
> can you please send the repository link here?

https://github.com/1Lighty/BetterDiscordPlugins/tree/master/Plugins/MessageLoggerV2

**Comment by zxsleebu** [comment]
> > > There is an update (v1.8.20) for message logger that fixes it.
> > 
> > 
> > can you please send the repository link here?
> 
> https://github.com/1Lighty/BetterDiscordPlugins/tree/master/Plugins/MessageLoggerV2
thank you 🥰
