### ISSUE TITLE
[Bug] BetterDiscord does only show the settings button after a refresh on the plugins page if getSettingsPanel is set after the plugin loads

### ISSUE THREAD

**Issue by abUwUser** [BetterDiscord/BetterDiscord#1383]
**Describe the Bug**
BetterDiscord does not add the settings button if the getSettingsPanel property is set after the plugin starts. To demonstrate this. lets grab a basic plugin example:
```js
module.exports = class {
   start() {

   }
   stop() {

   }
};
```
This is the structure of a plugin. Since it is a class, you can do class declarations anywhere inside the plugin
```js
module.exports = class {
   start() {
      this.hello = "hi"
   }
};
```
But what if you set a `getSettingsPanel` property? This is where the issues comes in
```js
module.exports = class {
   start() {
      this.getSettingsPanel = () => BdApi.React.createElement("div", {}, "uwu")
   }
};
```
Since BetterDiscord does look to that property when it loads the plugin, and not when it starts, BetterDiscord does actually add a settings page, but it won't display the settings button until you hit it.

**To Reproduce**
1- Set `getSettingsPanel` when starting a plugin
2- Notice that the button isn't loaded
3- Refresh the plugins page (by going to the themes page for example)
4- See the button

**Expected Behavior**
It should update the UI and show the settings button

**Screenshots**

https://user-images.githubusercontent.com/27961224/187093454-746dc0e1-e87c-44f3-a129-7e7a8502891c.mp4

**Discord Version**
Stable, Canary, PTB. Any of them can work

**Comment by rauenzi** [comment]
This is intentional. `getSettingsPanel` should exist as a function alongside `start` and `stop` as per the documentation https://docs.betterdiscord.app/plugins/introduction/structure#optional-functions. It is not called if the plugin is not enabled so I don't see the benefit to supporting this method.
