### ISSUE TITLE
[Bug] Plugins.json and themes.json files do not reflect changes in plugins folder

### ISSUE THREAD

**Issue by ItMeSarah** [BetterDiscord/BetterDiscord#1384]
**Describe the Bug**
plugins.json and  themes.json files do not reflect changes in plugins/themes, if you delete a file it does not get removed from the plugin.json

**To Reproduce**
Delete a plugin or theme, go to the plugins.json/themes.json file, plugin/theme stays in the json with the state it was deleted in (true/false for enabled/disabled.)

**Expected Behavior**
Json files should update when plugin or theme is removed from the plugins/themes folder.

**Discord Version**
All versions

**Comment by Thisisauser6443** [comment]
Can confirm this. Not only are entries in the list not removed, but the state of being enabled/disabled is unaffected, no matter the changes

**Comment by Inve1951** [comment]
It's not really a bug but i get if you want it changed. Currently plugin reloading (e.g. when updating) depends on this behavior.
