### ISSUE TITLE
[Bug] Manually installing BetterDiscord for Discord PTB does not work

### ISSUE THREAD

**Issue by Aholicknight** [BetterDiscord/BetterDiscord#1386]
**Describe the Bug**

I am trying to install BetterDiscord manually and it does not work for some reason. [The guide says](https://smolalli.github.io/BetterDiscord/#manual:~:text=For%20that%20last%20command%2C%20if%20you%20are%20using%20a%20non%2Dstable%20install%20of%20Discord%2C%20add%20canary%20or%20ptb%20at%20the%20end%20of%20the%20command.) to place `canary` or `ptb` at the end of the command but it does not work.
**To Reproduce**

1. Open powershell **without admin**
2. Paste the command `git clone https://github.com/BetterDiscord/BetterDiscord.git; cd ./BetterDiscord/; npm install; npm run build; npm run inject ptb` 
3. The error will show up

**Expected Behavior**

Should have installed successfully. 
**Screenshots**

![WindowsTerminal_7947942926](https://user-images.githubusercontent.com/7843719/187777626-26173a48-910a-4ea9-b840-49cd8fdcf322.png)

**Discord Version**

PTB
**Additional Context**

**Comment by rauenzi** [comment]
Can you manually remove or remove that folder/file that is having an issue? That seems to be specific to your installation

**Comment by Aholicknight** [comment]
@rauenzi For some reason when I closed discordptb a discordptb process was still running. I closed it, ran the command again, and it worked.
