### ISSUE TITLE
crashing[Bug]

### ISSUE THREAD

**Issue by Staticdevvv** [BetterDiscord/BetterDiscord#1387]
my discord keeps crashing how do i fix that 
![image](https://user-images.githubusercontent.com/75772083/188142637-81474104-4e95-46ae-8e6a-cfe9675c3303.png)

**Comment by fowlis** [comment]
This is (usually) a plugin issue, so this isn't the correct place to post issues like these. 
Please join the  [Support Server](https://discord.gg/0Tmfo5ZbORCRqbAd) for help with this.

**Comment by integrated-circuit** [comment]
same error with devil's bro plugins

**Comment by rauenzi** [comment]
Many crashing, memory, and cpu issues have been fixed with the latest update.
