### ISSUE TITLE
Something in BD crashes the client when opening a group chat

### ISSUE THREAD

**Issue by BossAydan** [BetterDiscord/BetterDiscord#1389]
When trying to open a certain group chat, discord crashed, but when entering different ones, it doesn't happen, and on some occasion when trying to restart I got this error message. Why does this happen?
![unknown (1)](https://user-images.githubusercontent.com/112825656/188330162-d0dc9531-2764-47fb-a0c5-f6e3080d1242.png)

**Comment by maenDisease** [comment]
Have you already determined if this is a BetterDiscord issue and not a plugin issue?

**Comment by BossAydan** [comment]
> Have you already determined if this is a BetterDiscord issue and not a plugin issue?
I found that the plugin, "PlatformIndicators" was what made it crash

https://user-images.githubusercontent.com/112825656/188330794-06acdffa-8d02-4d2c-953b-d610947995d4.mp4

**Comment by SmolAlli** [comment]
So... you have plugins enabled. What was asked of you is to see if it happens with no plugins enabled.
