### ISSUE TITLE
Can't Find Discord

### ISSUE THREAD

**Issue by dxomg** [BetterDiscord/BetterDiscord#1390]
**Describe the Bug**
Hi!, I wanted to install better discord on my laptop using Ubuntu 22.04.1 LTS but it couldn't find the discord folder

**To Reproduce**
Install Discord from .deb package and run better discord
and then try to install better discord

**Expected Behavior**
It should find discord as it isn't a snap package

**Video**

https://user-images.githubusercontent.com/101947415/188336725-e56e843b-49e7-4993-8859-b4e66ccccb5e.mp4

**Discord Version**
Latest, 0.0.19

It seems to be sort of a duplicate of  #1284

**Comment by maenDisease** [comment]
See https://github.com/BetterDiscord/BetterDiscord/issues/1269#issuecomment-1097231484

**Comment by dxomg** [comment]
> See [#1269 (comment)](https://github.com/BetterDiscord/BetterDiscord/issues/1269#issuecomment-1097231484)

so should use [betterdiscordctl](https://github.com/bb010g/betterdiscordctl) ?

**Comment by dxomg** [comment]
[betterdiscordctl](https://github.com/bb010g/betterdiscordctl) Helped me, Thanks!

**Comment by B-Nerd** [comment]
looks like this bug is back
& here is the new path on linux 
.config/discord/app-1.0.136/modules/discord_desktop_core-1/discord_desktop_core/
also installed it there & it works
