### ISSUE TITLE
BetterDiscord options not showing.

### ISSUE THREAD

**Issue by dehnzel** [BetterDiscord/BetterDiscord#1393]
Betterdiscord Options is not showing.
![image](https://user-images.githubusercontent.com/31786530/188775851-bad1927c-126b-491c-81db-efb189b6ad5e.png)

I did a clean uninstallation of discord and betterdiscord from the installer. Cleared the folders in %appdata% for both Discord and betterdiscord. Did a fresh installation and replaced .asar file but it's still not showing for me. I also did a manual installation but there's no luck.

Discord version: 1.0.9006
BetterDiscord version: v1.6.3

**Comment by ItMeSarah** [comment]
Have you checked if a VPN helps the issue, changing your region/location to a US based server?

**Comment by dehnzel** [comment]
> Have you checked if a VPN helps the issue, changing your region/location to a US based server?

I tried using a VPN but it still doesn't show the options for me.

**Comment by dehnzel** [comment]
Any fix for this?

**Comment by Andy4169** [comment]
same issue. powercord doesn't work either.

**Comment by Andy4169** [comment]
normal, ptb and canary broken

**Comment by Andy4169** [comment]
with a vpn

**Comment by AisuTistoto223** [comment]
Normal, PTB, Canary, all stopped working simultaneously. No known reason why Was working fine. One crashed, didn't load back. ended the other two, reopened, no longer worked..

**Comment by dehnzel** [comment]
Thank you for the updates.
