### ISSUE TITLE
Switching accounts loading infinitely [Bug]

### ISSUE THREAD

**Issue by Andrea-moth** [BetterDiscord/BetterDiscord#1399]
Betterdiscord will occasionally load infinitely when switching accounts, it seems to be random and the only way to fix it is to close out of discord and then reopen it

I have tried uninstalling betterdiscord and it works perfectly 

**Discord info**
Stable 147616 (3fa3a2f)
BetterDiscord 1.6.3
Host 0.0.20 
Linux 64-Bit (5.19.9-Arch1-1)

**Comment by SmolAlli** [comment]
Have you tested this without any plugins in your plugins folder, and was there any difference in the result when you did so?

**Comment by Andrea-moth** [comment]
Thank you that was the issue, I'm still not sure why a plugin would be able to cause it but I'm glad I know
