### ISSUE TITLE
[Bug] Forum "create tag" emoji picker affected by BD classes

### ISSUE THREAD

**Issue by Saltssaumure** [BetterDiscord/BetterDiscord#1400]
**Describe the Bug**
The emoji in the "create tag" popover is set to 100% width due to the `.bd-change-modal img` selector. Occurs with all themes and plugins disabled too.
![image](https://user-images.githubusercontent.com/29710355/190868187-2d5d52ae-4404-450f-baa9-8b1f7d5db2e4.png)

**Discord Version**
Stable 147616 (3fa3a2f)
BetterDiscord 1.6.3
Host 0.0.20
Linux 64-Bit (5.4.0-100-Generic)

**Comment by rauenzi** [comment]
Is this still happening? I cannot reproduce

**Comment by Saltssaumure** [comment]
Seems to have fixed itself.
