### ISSUE TITLE
[Bug] Language does not change until reload

### ISSUE THREAD

**Issue by phoriah** [BetterDiscord/BetterDiscord#1401]
**Describe the Bug**
Changing languages takes effect immediately, except it affects everything but BD

**To Reproduce**

1. Change language to Deutsch (German)
2. Manually reload Discord (CTRL + R)
3. Now your Discord and BD are both in Deutsch (German)
4. Change to English (USA)
5. Discord flashes for a moment and changes to English but BD is still in Deutsch (especially "Settings" tab in User Settings)
6. Manually reloading once more fixes the bug above

**Expected Behavior**
I would expect BD to change language along with how Discord does it. Without manual reload (CTRL + R)

**Screenshots**
You can see for yourself. Probably affects multiple languages.

**Discord Version**
Stable, PTB. Possibly Canary.

**Additional Context**
None.

**Comment by rauenzi** [comment]
Hi this should be fixed in the latest version
