### ISSUE TITLE
[Feature] Possibility of injecting BetterDiscord instead of modifying Discord's source code?

### ISSUE THREAD

**Issue by GameParrot** [BetterDiscord/BetterDiscord#1402]
**Is your feature request related to a problem? Please describe.**
It would be more similar to a browser extension, which would not require changing Discord's code directly (which is against the ToS.)

**Describe the feature you'd like**
A way to use BetterDiscord without having to modify Discord's code 

**Additional context**
This could be done by using https://github.com/tintinweb/electron-inject to inject a custom javascript into the official Discord client.

**Comment by ItMeSarah** [comment]
BetterDiscord already is an injection and does not touch Discord's source code..

**Comment by rauenzi** [comment]
As said above, we do not modify Discord's source. However injection is also against the ToS because it is still a modification to electron.
