### ISSUE TITLE
[Bug] Ubuntu 22.02 GPU process isn't usable (Installer broken)

### ISSUE THREAD

**Issue by ColinTimBarndt** [BetterDiscord/BetterDiscord#1403]
**Describe the Bug**
The AppImage (`sha256 1198fcbd1c966c47c26a0cbfc774131400ef13a67be9faa70d54506610f44b69`) does not start/crashes.

**To Reproduce**
Launch the installer using the setup described below.

**Discord Version**
Stable / does not matter as the installer cannot start.

**Additional Context**
Console Errors
```
$ ./BetterDiscord-Linux.AppImage 
Better Discord Installer 1.1.1
[9231:0924/174430.117667:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
[1]    9231 trace trap (core dumped)  ./BetterDiscord-Linux.AppImage
``` 

<details><summary>OS Details</summary>

```
OS: Pop!_OS 22.04 LTS x86_64 
Kernel: 5.19.0-76051900-generic 
Uptime: 11 mins 
Packages: 3035 (dpkg), 37 (flatpak), 7 (snap) 
Shell: zsh 5.8.1 
Resolution: 1920x1080, 1920x1200 
DE: GNOME 42.3.1 
WM: Mutter 
WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 7 1700X (16) @ 3.400GHz 
GPU: NVIDIA GeForce GTX 1060 6GB 
Memory: 3853MiB / 64237MiB
```

</details>

Other electron-apps are also broken since the 22.04 Ubuntu update.

**I suspect this error has something to do with Nvidia graphics drivers**

**Comment by fowlis** [comment]
Try running the AppImage with `--disable-gpu-sandbox` appended

**Comment by ColinTimBarndt** [comment]
> Try running the AppImage with `--disable-gpu-sandbox` appended

I know that the `--no-sandbox` flag solves these issues with Electron, but this is only avoiding the issue. Will I need to start BD using this fix as I need to do it with my electron-based password manager?

**Comment by maenDisease** [comment]
https://github.com/BetterDiscord/Installer is the correct repo for installer issues

**Comment by Inve1951** [comment]
See https://github.com/BetterDiscord/Installer/issues/247.
