### ISSUE TITLE
Fail to inject due to the latest update of discord on Sept 26th,2022

### ISSUE THREAD

**Issue by Tian7777** [BetterDiscord/BetterDiscord#1404]
Fail to inject due to the latest update of discord canary on Sept 26th,2022

Checking in as I am not sure if it's just me or yall got the problem too

**Comment by ItsMitchh** [comment]
I believe this only impacts Canary, stable is fine.

**Comment by Aholicknight** [comment]
> I believe this only impacts Canary, stable is fine.

@ItsMitchh This also affects PTB, see issue #1405

**Comment by BadKiko** [comment]
> I believe this only impacts Canary, stable is fine. 

Stable doesn't work for me either

**Comment by BadKiko** [comment]
> I believe this only impacts Canary, stable is fine. 

Stable doesn't work for me either

**Comment by HugoCe17** [comment]
stable not working - reinstalling / fixing didn't help.

**Comment by BadKiko** [comment]
Discord switched from Babel to SWC for minifying its code, which breaks our usual methods of finding webpack modules to inject into. (by Powercord)
Waiting fix

**Comment by Tropix126** [comment]
![image](https://user-images.githubusercontent.com/42101043/192402292-1b3808f5-4a18-4d7e-8954-64d6cdffa472.png)

For anyone looking for specifics: Discord moved from Babel => SWC in their transpilation step (likely to improve performance), which results in many webpack modules lacking important information BD looks for when doing module searches in discord's internals. Options are being explored at the moment, and BD alone will likely be fine, but plugins are a much different story.

**Comment by FenyLabs** [comment]
Is there any way to downgrade Discord to the previous version until BD gets fixed?

**Comment by Giotje** [comment]
i don't think there's a downgrade option. also, i wouldn't be afraid of BD, that'll be fine. just all the plugins that might choose to not update
