### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by KelTCM** [BetterDiscord/BetterDiscord#1405]
# Better discord won't load on Discord PTB (PTB specifically)
Not sure why, but this morning, I went on discord (PTB as I usually use that with BetterDiscord) and it wouldn't load better discord
I tried reloading it, I tried repairing it, and reinstalling discord, but nothing would get it working again
I also tried installing it on the regular discord client, and it worked fine
![2022-09-26 14_15_41-My Account _ User Settings - Discord](https://user-images.githubusercontent.com/52837791/192362718-c57665c2-a7e9-4b9c-9a43-21a6e86e60f3.png)

**Comment by maenDisease** [comment]
Discord updates, wait for it to be fixed or Discord rolls back their updates

**Comment by BadKiko** [comment]
Yeah, waiting for fix :(

**Comment by Aholicknight** [comment]
Getting the same problem

**Comment by patjldeiM0IP** [comment]
It's not just PTB - same problem with `Stable 149262 (20e06bf)`

**Comment by BadKiko** [comment]
> It's not just PTB - same problem with `Stable 149262 (20e06bf)`

The same problem, updated the libraries for the script and now it does not work on the stable version either

**Comment by BadKiko** [comment]
> It's not just PTB - same problem with `Stable 149262 (20e06bf)`

The same problem, updated the libraries for the script and now it does not work on the stable version either

**Comment by jali-peno** [comment]
can confirm its happening on stable too `Stable 149301 (f79bc1f)`

**Comment by Lumince** [comment]
Anyone know of a way to downgrade your windows installation of discord without it auto updating??

**Comment by deadHvman** [comment]
not working on Stable 149345 (f0be125) here

**Comment by TheAlphaReturns** [comment]
yep, same issue

**Comment by NahNahNahNahNah** [comment]
not working on Stable 149301 (f79bc1f)

**Comment by BadKiko** [comment]
Discord switched from Babel to SWC for minifying its code, which breaks our usual methods of finding webpack modules to inject into. (by Powercord)
Waiting fix

**Comment by IXSENPA1XI** [comment]
its not just ptb but the regular discord as well

**Comment by Aholicknight** [comment]
Seems to be working for now

**Comment by StarWolf3000** [comment]
> Seems to be working for now

How does it work for you? It doesn't for me on Stable 149345 (f0be125) (I'm waiting for a fixed Auto Installer)

**Comment by Aholicknight** [comment]
> How does it work for you? It doesn't for me on Stable 149345 (f0be125) (I'm waiting for a fixed Auto Installer)

![DiscordPTB_5572996786](https://user-images.githubusercontent.com/7843719/192439691-d872e82d-a662-45c8-b09c-55da954715a1.png)

@StarWolf3000 worked for me fine

**Comment by ViLiDi230** [comment]
> > How does it work for you? It doesn't for me on Stable 149345 (f0be125) (I'm waiting for a fixed Auto Installer)
> 
> ![DiscordPTB_5572996786](https://user-images.githubusercontent.com/7843719/192439691-d872e82d-a662-45c8-b09c-55da954715a1.png)
> 
> @StarWolf3000 worked for me fine

It's Working if delete all plugins and Reinstall BetterDiscord (For me)

**Comment by StarWolf3000** [comment]
My host app is 0.0.309, not the 1.x (those lag as hell on my system).
