### ISSUE TITLE
[Bug] Non Reply Mention is broken

### ISSUE THREAD

**Issue by GTREDITION** [BetterDiscord/BetterDiscord#1410]
NRM.plugin.js stoped working with the last update of discord it needs to be updated

**Comment by StandingPadAnimations** [comment]
Discord pushed an update that broke all client mods. While BD is a hotfix, all plugins are now broken and now need to be fixed by the individual plugin developers

**Comment by GTREDITION** [comment]
forgive me, i had to go to the creator's github, sorry i don't use github
