### ISSUE TITLE
[Bug]Plugin could not be compiled

### ISSUE THREAD

**Issue by NetherDragonTw** [BetterDiscord/BetterDiscord#1411]
**Describe the Bug**
idk, i just started the discord and i just see this error

**To Reproduce**
idk

**Expected Behavior**
idk

**Screenshots**
<!-- If applicable, add 
![螢幕擷取畫面 (1660)](https://user-images.githubusercontent.com/99878040/192516049-6c4a05c4-87c5-4b45-a4c2-371c15ec0894.png)

**Discord Version**
Stable

**Additional Context**
pls fix this i really want it working again, my plugins all get this error.

**Comment by SunRaysFalls** [comment]
> **Describe the Bug** idk, i just started the discord and i just see this error
> 
> **To Reproduce** idk
> 
> **Expected Behavior** idk

Discord pushed an update that changed almost everything... so most plugins and things are broken. BD devs and themes/plugins devs are working as we speak to fix them

**Comment by NetherDragonTw** [comment]
> > **Describe the Bug** idk, i just started the discord and i just see this error
> > **To Reproduce** idk
> > **Expected Behavior** idk
> 
> Discord pushed an update that changed almost everything... so most plugins and things are broken. BD devs and themes/plugins devs are working as we speak to fix them

oh bruh, nice discord u just broken the nice addon

**Comment by NetherDragonTw** [comment]
> > **Describe the Bug** idk, i just started the discord and i just see this error
> > **To Reproduce** idk
> > **Expected Behavior** idk
> 
> Discord pushed an update that changed almost everything... so most plugins and things are broken. BD devs and themes/plugins devs are working as we speak to fix them

so i need wait devs fix the BD?

**Comment by The-Epic** [comment]
mainly the plugin devs now

**Comment by ProxxDev2** [comment]
damn
