### ISSUE TITLE
waitForModule docs wrong

### ISSUE THREAD

**Issue by bepvte** [BetterDiscord/BetterDiscord#1412]
https://github.com/BetterDiscord/BetterDiscord/blob/9b38e442da7f24024997e0509e3e7dd343507a7c/renderer/src/modules/pluginapi.js#L665

"options" does not actually do anything relating to if more then one module is returned

**Comment by bepvte** [comment]
![image](https://user-images.githubusercontent.com/8226605/192598052-15898f84-676c-4358-b442-80ba3ff8c05d.png)
this happens a few times in the docs

**Comment by rauenzi** [comment]
This is fixed in the latest release!
