### ISSUE TITLE
Plugins cannot load (problem stems from Electron)

### ISSUE THREAD

**Issue by PitchBlackNights** [BetterDiscord/BetterDiscord#1414]
**Describe the Bug**
When BetterDiscord tells a plugin to load, it fails to complete the load of the plugin

I opened Discord today to find that BD was not working, so I downloaded the installer to repair BD. It "repaired" BD, but plugins no longer worked. I uninstalled BD, then installed the newest version thinking that the repair just failed, but the problem was still happening. I opened the developer console to find that BD kept throwing an error: 
```
VM88 C:\Users\pitch\AppData\Roaming\BetterDiscord\data\betterdiscord.asar\preload.js:1 Uncaught Error: Cannot read property 'upperCaseFirstChar' of null
    at IncomingMessage.<anonymous> (VM88 C:\Users\pitch\AppData\Roaming\BetterDiscord\data\betterdiscord.asar\preload.js:1)
    at IncomingMessage.emit (VM14 events.js:327)
    at endReadableNT (VM81 readable.js:1327)
    at processTicksAndRejections (VM24 task_queues.js:80)
```

**To Reproduce**
Use the latest release of BD (v1.7.0)
Copy a plugin to the plugins folder (I used PluginRepo, ThemeRepo, and ServerCounter)
Nothing will change

When using the developer console, the plugins that I tested never loaded because of problems with electron. (VM24 task_queries.js:80)

**Expected Behavior**
Plugins load like normal

**Screenshots**

**Discord Version**
Stable 149345 (f0be125)
Host 1.0.9006
Windows 10 64-Bit (10.0.19044)

**Additional Context**

**Comment by m0ney-dev** [comment]
"Discord has pushed out an absolutely massive change that completely restructures all of their internals and changes the functionality of countless modules. This has broken BetterDiscord itself and plugins completely. It will likely take time to adjust to these changes so please be patient. There will be another post here to let you know when a fix is available for BetterDiscord. However, is no ETA at this time."

**Comment by rauenzi** [comment]
Well this is a new one, haven't seen this before. `upperCaseFirstChar` is not used anywhere in our code afaik, so this error is beyond me.

**Comment by PitchBlackNights** [comment]
> "Discord has pushed out an absolutely massive change that completely restructures all of their internals and changes the functionality of countless modules. This has broken BetterDiscord itself and plugins completely. It will likely take time to adjust to these changes so please be patient. There will be another post here to let you know when a fix is available for BetterDiscord. However, is no ETA at this time."

@m0ney-dev Where did you find this?

**Comment by PitchBlackNights** [comment]
nevermind, found it on the discord server
