### ISSUE TITLE
[Issue] Memory Leak and crashing

### ISSUE THREAD

**Issue by PipCryt** [BetterDiscord/BetterDiscord#1417]
The Discord works stably for some time and consumes about 400 megabytes of RAM, but after 20 to 40 minutes, consumption increases 4 times, as well as when switching between servers, channels and when printing text, strong freezes occur and there is a load on the processor from the Discord and after a short time - discord crashes with the following error (screenshot attached below). I have no plugins installed, the problem was both with and without plugins.

In my case, the problem occurred 20 - 40 minutes after opening the Discord with BetterDiscord installed, I haven't checked the work without BetterDiscord yet, but there is still a problem.
Possibly memory leakage.

Discord version: Stable 1.0.9006
Better Discord version: 1.7.0
Windows 10 64-Bit: 21H2 (19044.1889)

Screenshot: https://user-images.githubusercontent.com/34980941/192817419-61fb2746-25a6-45c0-86a2-a89c33c3e300.png

**Comment by koocgum** [comment]
experiencing this issue as well, discord chills at 200-300mb of usage with rare spikes up to 500/600,

the issue has been persisting regardless if i have any plugins enabled or disabled, even right now, with barely any plugins enabled, better discord crashes more often, especially when i rapidly switch guilds / dms

`Stable 149549 (1e1ae6d)`
`Host 1.0.9006` 
`Windows 10 64-Bit (10.0.19043)`

**Comment by Lordanem** [comment]
This is a bug with base Discord, doesn't look like anything to do with the BD client.

**Comment by koocgum** [comment]
> This is a bug with base Discord, doesn't look like anything to do with the BD client.

this is most definitely not an issue with base discord, it does not occur when better discord isn't loaded into discord, crashes occur only when betterdiscord is running

**Comment by ImperiusFate750** [comment]
Same in here. Really weird issues with BD since the 1.7.0 update. If I leave my Discord open for around 3-4 hours without restarting it then it'll lag out a lot then crash.. mostly because it's RAM usage reaches over 1.3 GB and sometimes a little bit higher.

I've had similar issues in the past with Better Discord, but then an update popped up and it fixed everything. Discord with BD was running flawlessly.

`` Canary 150486 (e587472) ``
``Host 1.0.49 ``
``Windows 11 22H2 64-Bit (22621.521) ``

**Comment by FOSSEnjoyer** [comment]
> > This is a bug with base Discord, doesn't look like anything to do with the BD client.
> 
> this is most definitely not an issue with base discord, it does not occur when better discord isn't loaded into discord, crashes occur only when betterdiscord is running

Yup, same here. When I uninstall BetterDiscord it doesn't happen. This only started happening with the 1.7.0 release.

`Stable 150489 (4590418)`
`Host 0.0.20` 
`Linux 64-Bit (5.15.0-48-Generic)`

**Comment by george2781** [comment]
Absolutely a BD issue.
```
Stable 150489 (4590418)
Host 1.0.9006
Windows 10 64-Bit (10.0.19045)
```

**Comment by Lordanem** [comment]
Funny how I've been downvoted on this numerous times, however the original comment above does seem a bit bare so I guess people just assumed this wasn't tested -  I understand there's people who have stopped encountering this issue after a removal however this is personal experience alone.

Stable 150489 (4590418) Host 1.0.9006 Windows 10 64-Bit (10.0.22000)
Above doesn't reflect right, I am on Windows 11 64-Bit

No BD installed. - when Discord crashes and restarts this is confirmed by not receiving the BetterDiscord crash screen, I have also completely uninstalled the client and reinstalled Discord using the official installer alone from Discords website, this issue remains after a reinstall.

I have two other people including myself affected by a memory leak within the base application - one who has never installed BD before

If any further information is needed for this situation alone, I'm open, if this is indeed a BD issue, then fair enough.

**Comment by FOSSEnjoyer** [comment]
> Funny how I've been downvoted on this numerous times, however the original comment above does seem a bit bare so I guess people just assumed this wasn't tested - I understand there's people who have stopped encountering this issue after a removal however this is personal experience alone.
> 
> Stable 150489 (4590418) Host 1.0.9006 Windows 10 64-Bit (10.0.22000) Above doesn't reflect right, I am on Windows 11 64-Bit
> 
> No BD installed. - when Discord crashes and restarts this is confirmed by not receiving the BetterDiscord crash screen, I have also completely uninstalled the client and reinstalled Discord using the official installer alone from Discords website, this issue remains after a reinstall.
> 
> I have two other people including myself affected by a memory leak within the base application - one who has never installed BD before
> 
> If any further information is needed for this situation alone, I'm open, if this is indeed a BD issue, then fair enough.

Well maybe it's two separate issues dependant on hardware, or maybe something that isn't present on certain hardware that bd activates somehow. I don't know. All I can say is I've also installed from 100% only the official installer and never had this happen. It only happens when BD 1.7 is installed.

**Comment by Xelus22** [comment]
Same as FOSSEnjoyer here. Issue only when BD is installed.
I do also have OpenASAR installed, but it shouldn't be an issue.

Hardware:
AMD R9 5900X
32GB RAM Crucial Ballistix
NVIDIA RTX 3070Ti
Windows 10 21H2 - Build 19044.2006

**Comment by varxxx** [comment]
So you can reliably reproduce this very quickly by switching servers and channels on a fresh start. Each time you change servers the memory usage will spike up as it loads messages and images posted, this happens even without BD Installed, but here comes the main change; When BD is installed that memory spike never clears out and just builds up and up and up. I was able to get it to spike from 200MB to 800MB in less than a minute just swapping channels. Attempting to reproduce without BD installed spikes it to 400MB then it drops back down to 200MB

**Comment by AlienXAXS** [comment]
I also have the same issue, but as others have said it seems more that having BD installed causes, what I would assume to be Garbage Collection to not fire as often or not collect as well as it could?

Not having BD installed: Clicking channels and loading text/images into memory totally as expected makes the memory spike
Having BD Installed: doing the above also causes memory to spike, but it never is released.

**Comment by SoftwareGuy** [comment]
I'm going to throw my two cents in and definitely can see a spike in the RAM usage, but it seems to slowly be coming back down. I assume that's probably background loading functions grabbing message history and other things. This is after a BD crash and clicking "Try again".

I have also noticed switching channel and server lag, where Discord will hang for a longer-than-usual period of time. If I'm under fire with pings, it can get to the stage where Discord freaks out, crashes and BD throws a safety net warning popup asking continue using BD or unload for this session.

There's definitely something up with BD. Loaded plugins are bare bones at the moment because the 1.7.0 update breaking them, i'd really love to rollback to a older build of discord and BD but alas, I guess that's no cigar.

**Comment by nightshade231** [comment]
This issue is also happening to me. while it does unload _slightly_, it still keeps the large heap. Stand-alone Discord only ever peaked constantly to ~550MB when switching servers quickly. When doing the same with BD installed, it can peak as high as 1,400MB of heap, which is a fair amount to keep around. 

While writing this, it only has gone down ~100MB, at a slow rate of typing.

**Comment by HyperSoop** [comment]
The memory leak is insane. I have to close and reopen my client every 30 orso minutes or it becomes unusable.

**Comment by Infinitay** [comment]
> So you can reliably reproduce this very quickly by switching servers and channels on a fresh start.

Yes! I have experienced the same thing endlessly as I mentioned on https://github.com/BetterDiscord/BetterDiscord/issues/1311#issuecomment-1258808351

> This wouldn't happen to explain why BD feels sluggish on first loads would it? Specifically, when I first get on Discord and despite plugins has finished loading; when I click on a channel Discord lags for 1-3 seconds but doesn't switch to the channel. I have to click it a second time for it to go through.
> 
> This also rarely happens throughout the day after some long period of time. A CTRL+R fixes this and stops the _sluggishness_.  

I used to t hink this was because of the ServerFolders and having them display in a new column, but I suppose that isn't the case.

**Comment by TheRealArchie** [comment]
Memory doesn't unload properly. Makes sense with the new update.

**Comment by rauenzi** [comment]
We have identified major leak issues and have fixed them for the next release of BD. Please be patient as we want to make sure the next release is a good one

**Comment by Infinitay** [comment]
Great to hear. Glad to see this issue finally being recognized and resolved. 

Thank you all!

**Comment by SoftwareGuy** [comment]
Thank you very much for paying attention to the memory issues. I was getting to the stage where I was considering going back to vanilla Discord.

**Comment by rauenzi** [comment]
This has now been released!

**Comment by Infinitay** [comment]
![image](https://user-images.githubusercontent.com/6964154/195664529-ae5b2983-bf57-4bf7-bd5e-5e5106a3c16b.png)
Has anyone noticed an up-tick in CPU usage today?

**Comment by ITCMD** [comment]
Still having this issue. Discord has two executables running, or maybe 7... not sure if Im reading this right

![image](https://github.com/BetterDiscord/BetterDiscord/assets/32961763/e9158a99-003b-4a93-b89c-1ca6595699e9)

Both the discord process by itself and the grouped one of 6 threads or proceses or whatever gain 0.1-0.2 mb of ram usage every second. Performance is rough.
