### ISSUE TITLE
[Bug] Changelog is not being shown after clicking a button in settings.

### ISSUE THREAD

**Issue by PolakPL2002** [BetterDiscord/BetterDiscord#1419]
**Describe the Bug**
Changelog is not being shown after clicking a button in settings.

**To Reproduce**
Click a button and observe changelog not appearing.

**Expected Behavior**
A modal with a changelog should be shown.

**Discord Version**
Stable

**Additional Context**
[BetterDiscord] [Modals] showChangelogModal missing modules

**Comment by rauenzi** [comment]
This is fixed in the latest release!
