### ISSUE TITLE
[Bug] PlatformIndicators

### ISSUE THREAD

**Issue by Enrico9431** [BetterDiscord/BetterDiscord#1421]
Indicator Tooltip stays after clicking on it

Click on a few indicators of people (in a server)

**Expected Behavior**

![image](https://user-images.githubusercontent.com/85672311/193163890-7eaae957-7dc2-48ca-bdf7-bdbfb320dcfa.png)

Latest Stable version

To fix it discord has to be reloaded

**Comment by Soulivan71** [comment]
PTB too
