### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by TadymanCZ** [BetterDiscord/BetterDiscord#1423]
i have problem with BDFBD from DevilBro it say's that there is soem error in console and when i open console there are many errors and still going up with the numbers and idk how to fix it can someone help me?

**Comment by TadymanCZ** [comment]
![obrazek](https://user-images.githubusercontent.com/114802082/193400285-3774e496-f087-41a0-958d-e7277edb90e9.png)

**Comment by SmolAlli** [comment]
1. This is an issue with a plugin, not BD itself. It does not belong on this repository.
2. Basically all plugins are broken right now. Be patient and wait for the developers to fix them.

**Comment by TadymanCZ** [comment]
> 1. This is an issue with a plugin, not BD itself. It does not belong on this repository.
> 
>     2. Basically all plugins are broken right now. Be patient and wait for the developers to fix them.

oh okay thx

**Comment by TadymanCZ** [comment]
thx

**Comment by xHyroM** [comment]
Close this
