### ISSUE TITLE
[Bug] no plugins and themes

### ISSUE THREAD

**Issue by Nquster** [BetterDiscord/BetterDiscord#1424]
![resim_2022-10-01_135331103](https://user-images.githubusercontent.com/114808870/193406173-4f9f360e-4331-4cc7-a97e-41acdb76f4c2.png)
**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by SmolAlli** [comment]
This is due to broken plugins in your plugins folder.

**Comment by Nquster** [comment]
how do I know how to fix

**Comment by Nquster** [comment]
> This is due to broken plugins in your plugins folder.

how do I know how to fix

**Comment by fowlis** [comment]
If you're in the support server, use this message link -> https://discord.com/channels/86004744966914048/1024019229839724544/1024790468577468447

**Comment by rauenzi** [comment]
Broken plugins should no longer cause this in 1.8.0
