### ISSUE TITLE
[Feature] Frameless option

### ISSUE THREAD

**Issue by DaBluLite** [BetterDiscord/BetterDiscord#1426]
**Is your feature request related to a problem? Please describe.**
My feature request is related to the lack of a frameless mode for the linux discord app

**Describe the feature you'd like**
Enable/uncomment the 2 lines that enable the frame settings in BD's `settings.json` file

**Additional context**
It would just be nice to just disable he frame of the discord app and use our own in one way or another

**Comment by DaBluLite** [comment]
[This commit](https://github.com/DaBluLite/BetterDiscordFrameless/commit/e9bc4eb44aa7187c38e3cbaf5cb3703d29998425) is the frameless option being uncommented (in [DaBluLite/BetterDiscordFrameless](https://github.com/DaBluLite/BetterDiscordFrameless))

**Comment by rauenzi** [comment]
Duplicate of #1062
