### ISSUE TITLE
[Bug] BdApi.Plugins .toogle, .disable, .enable does not change switcher position if plugins list is displayed.

### ISSUE THREAD

**Issue by Mopsgamer** [BetterDiscord/BetterDiscord#1427]
**Describe the Bug**
`BdApi.Plugins.toggle('*anyPluginName*')` has no effect on switches while the addon list is displayed in settings.

**To Reproduce**
- Go to the plugins section in the settings.
- Run the code in the developer console: `BdApi.Plugins.toggle('*anyPluginName*')`
- The switcher is not toggled. A notification appears that the plugin has been enabled/disabled.

**Expected Behavior**
The switcher should have changed position.

**Screenshots**
![image](https://user-images.githubusercontent.com/79159094/193466668-3ac29eb5-dda8-4d8f-acb2-498322e91fea.png)

**Discord Version**
Canary, never mind

**Additional Context**
This also applies to `BdApi.Plugins.enable` and `BdApi.Plugins.disable`.

To display the switchers correctly, you need to close and open the plugins section.

**Comment by Bettlee** [comment]
I tried the same thing and the switch does toggle, but not as you expected. Going to another page and coming back it shows it has been toggled off. I looked into it and found that the React state isn't properly updating for some reason
