### ISSUE TITLE
[Translation] Cannot contribute to the translations

### ISSUE THREAD

**Issue by LukeSavefrogs** [BetterDiscord/BetterDiscord#1429]
Currently there are quite a bit of wrong/bad translations in italian (it's my native language) and i'd like to improve them...

[This part](https://github.com/BetterDiscord/BetterDiscord/blob/main/CONTRIBUTING.md#translations) in the CONTRIBUTING.md file says that translations "should be submitted via [POEditor](https://poeditor.com/join/project?hash=nRljcnV0ET)", but when i go to the linked website it says that "there are no languages available to translate in this project".

![image](https://user-images.githubusercontent.com/33452387/194168946-e617f0dc-40e6-4c3f-a208-a9e1f68b7dee.png)

How can i contribute? I love BD and i want it to be even better. 🚀

**Comment by LukeSavefrogs** [comment]
I found the translation json [here](https://github.com/BetterDiscord/BetterDiscord/blob/main/assets/locales/it.json) and this is an example of "bad translations" i mentioned before:
https://github.com/BetterDiscord/BetterDiscord/blob/e63695e17f7de22f2cdd9da403fb4484b97f735c/assets/locales/it.json#L271-L313

Should i just make a PR with the "correct" translations?

**Comment by SmolAlli** [comment]
I'll let someone from the team know about this issue. Making a PR would not be the best. 
In the meantime, could you please join the BD discord server, if you haven't already? https://betterdiscord.app/invite

**Comment by LukeSavefrogs** [comment]
Thank you for the quick response!
I just joined the Discord server. Do you need my ID?

**Comment by rauenzi** [comment]
The POEditor project should be active again!

**Comment by LukeSavefrogs** [comment]
> The POEditor project should be active again!

I can confirm @rauenzi. Thank you very much! 

I'll be glad to be of any help in the translations.
