### ISSUE TITLE
Incompatible with Canary 151788 (936c89b) - Host 0.0.286

### ISSUE THREAD

**Issue by UBFI** [BetterDiscord/BetterDiscord#1430]
This is the current version of canary I guess I was the first person to be unlucky enough to reload. This does not create a better discord crash due to it being a discord crash. I will be posting Electron log output shortly.

**Comment by SmolAlli** [comment]
![image](https://user-images.githubusercontent.com/22519967/194697098-cabace01-5b11-460e-8090-b6ced8da0c6a.png)
Cannot replicate. On Linux Pop!OS 22 and Discord Canary 0.0.139. (Same update hex)

**Comment by UBFI** [comment]
Hmm this could suggest its possibly an arm related issues. The two instances I have tried are Linux Arm and OS X ARM .

**Comment by UBFI** [comment]
Well this is very strange even when using a VPN or another IP my client isn't able to pull down the required java script files from canary.discord.com .

**Comment by UBFI** [comment]
Issues unrelated to BetterDiscord standard discord client works fine so possibly some sort of fingerprinting is banning only a handful of addresses. I'll perform more testing and report back to this ticket if needed but for now im going to close it.

**Comment by UBFI** [comment]
It appears that I can load with BetterDiscord running but without plugins loaded at all or only a theme. Is there a way to remediate this currently?

**Comment by patjldeiM0IP** [comment]
Same problem here, but with PTB. Stable is perfectly fine but PTB+BD causes discord itself to crash, remove BD and PTB launches as expected.

```
Ptb 151788 (936c89b)
Host 0.0.33
Linux 64-Bit (5.4.0-126-Generic)
```

**Comment by eclipsek20** [comment]
Same issue on windows, whenever I load any plugins it crashes instantly, if i only load the themes it works.

**Comment by UBFI** [comment]
I knew i wasnt going crazy.

**Comment by eclipsek20** [comment]
> I knew i wasnt going crazy.

What's happening is that all plugins got broken for some reason.
