### ISSUE TITLE
better discord stopped working on newest update

### ISSUE THREAD

**Issue by Nautiical** [BetterDiscord/BetterDiscord#1431]
better discord has stopped working on latest 1.0.9006 stable discord build

**Comment by maenDisease** [comment]
Stopped working in what way

**Comment by ChutMei** [comment]
It keeps crashing I have also tried repairing it but that has no fix to it

**Comment by eclipsek20** [comment]
Most likely your problem relates to the plugin "disaster" that happened. TLDR: all plugins are broken.

**Comment by iiMundu** [comment]
I'm having the same issue with it not working,-It's not showing my themes,Nor the plugins button to see the plugs, I tried to repair it,redownload it,but nither worked,was hoping i could find some help here

**Comment by super-cinnamon** [comment]
I'm having the same issues as above comment, I experienced the plugin disaster as my themes and most of my plugins died a few weeks back, I decided to get betterdiscord again and while some plugins were working, in this latest version I lost the plugins and themes tab in settings, only betterdiscord settings and custom css tabs were left. no amount of changing in the betterdiscord or discord settings brought them back (which means I couldn't deactivate the plugins that I had previously installed and were still working)

**Comment by SmolAlli** [comment]
These discussions don't need to be in the BD repo, join the BD discord server for support. https://betterdiscord.app/invite
Also if you have missing plugin/theme options in settings check your plugin/theme folders for any files that aren't named properly, e.g. have a `(1)` at the end of them.
