### ISSUE TITLE
[Bug] BetterDiscord installed but does not work

### ISSUE THREAD

**Issue by dankYoff** [BetterDiscord/BetterDiscord#1434]
**Describe the Bug**
BetterDiscord installs but does not work

**To Reproduce**
1) Install Discord
2) Installation BetterDiscord
3) Rebooting Discord

**Expected Behavior**
BetterDiscord installs but does not work and does not appear in the discord menu

**Screenshots**
![image](https://user-images.githubusercontent.com/91318807/195211584-7ca02055-837b-4a3e-a261-d569f14dbc86.png)
![image](https://user-images.githubusercontent.com/91318807/195211619-6698a071-ffb6-4713-b57c-54efdabf697d.png)

**Discord Version**
Stable 151857 (383a8ed) Host 1.0.9006 Windows 10 64-Bit (10.0.19044)

**Comment by fowlis** [comment]
I suggest joining the support server, a fix for this is listed in the #known-issues channel

**Comment by dankYoff** [comment]
I searched the Discord channel, but there is no such error

**Comment by rauenzi** [comment]
Try the first one under general issues https://docs.betterdiscord.app/users/getting-started/troubleshooting#general-issues

**Comment by dankYoff** [comment]
fixed, reintall in other path
