### ISSUE TITLE
BetterDiscord ENTIRELY broken again....[Bug]

### ISSUE THREAD

**Issue by JimDude7404** [BetterDiscord/BetterDiscord#1435]
**Describe the Bug**
Discord now crashes if BetterDiscord is installed.

**To Reproduce**
Install BetterDiscord and try to launch Discord.

**Expected Behavior**
Discord Launches

**Screenshots**
<img width="1440" alt="Screen Shot 2022-10-11 at 9 22 14 PM" src="https://user-images.githubusercontent.com/67085206/195227294-e1dc91e5-e329-41b0-8c06-3039bca2450d.png">

**Discord Version**
Stable

**Additional Context**

**Comment by maenDisease** [comment]
Have you tried reinstalling BetterDiscord, like now
