### ISSUE TITLE
Better discord setup doesn't work [Bug]

### ISSUE THREAD

**Issue by tyfexx** [BetterDiscord/BetterDiscord#1437]
**Describe the Bug**
I opened the setup and saw a black window pop up.

**To Reproduce**
Dowload the setup that was up on 12.10.2022 (DD/MM/YYYY) at 19:57. When u open it you will see black window open up.

**Expected Behavior**
I would expect the setup to let me install, repair or uninstall and the steps followed by choosing one of these options.

**Screenshot**
![image](https://user-images.githubusercontent.com/88140166/195419119-010bac58-8780-4ae6-be03-52f9842f4b2c.png)

**Discord Version**
Stable

**Comment by fowlis** [comment]
Please join the support server and you will find solutions for this listed in the #known-issues channel

**Comment by tyfexx** [comment]
> Please join the support server and you will find solutions for this listed in the #known-issues channel

I did, thank you very much
