### ISSUE TITLE
Github blocked by something[Error]

### ISSUE THREAD

**Issue by tyfexx** [BetterDiscord/BetterDiscord#1438]
I wanted to use some plugins, but when trying to use all of them none works.
To understand better, please look at the screenshot inserted below. I installed them today and i tried to use them today.

**Screenshot**
![image](https://user-images.githubusercontent.com/88140166/195422759-8da17534-a5d7-4d19-87f7-bf59a9f3a8a0.png)

**Comment by maenDisease** [comment]
This is an issue with a plugin, not BetterDiscord.
