### ISSUE TITLE
[Bug] settings menu and copy

### ISSUE THREAD

**Issue by Suprenok** [BetterDiscord/BetterDiscord#1440]
**Describe the Bug**
 fix better discord menu disappears when you move the slider

**To Reproduce**

**Expected Behavior**

**Screenshots**
 
![image](https://user-images.githubusercontent.com/13561619/195574458-ca839b0d-4590-4765-b097-d3b05b569c4d.png)

**Discord Version**
 stable 152131 (6ed73b9)

**Additional Context**

**Comment by rauenzi** [comment]
BetterDiscord doesn't add anything to context menus, this is an issue with one of your plugins.
