### ISSUE TITLE
Profile Pictures Missplaced When Theme is Applied 

### ISSUE THREAD

**Issue by Ronan7x** [BetterDiscord/BetterDiscord#1441]
Issue:
When applying any theme, all user profile pictures are slightly lowered cutting into usernames.  This only happens while a theme is applied. 

To Reproduce:
Apply a theme

Expected Behavior:
The profile pictures should normally be placed within the grey circle and above usernames

Screenshot:
![bug](https://user-images.githubusercontent.com/33204767/195733060-cf472a3b-ea52-4c96-9e6d-f6a425d37828.PNG)

Discord Version:  Stable 152131 (6ed73b9)
Windows 10 64-bit

**Comment by Saltssaumure** [comment]
Discord has been changing user profile layouts frequently over the past few weeks, with the updates coming to some users but not others. It's pretty much impossible for a theme to look correct across all the different variations, so for now please wait for Discord to settle down and the themes to be updated.

**Comment by rauenzi** [comment]
This is something that themes themselves must account for.
