### ISSUE TITLE
[Bug] "child_process" module missing

### ISSUE THREAD

**Issue by Mortreng** [BetterDiscord/BetterDiscord#1443]
After the broken Discord update, I can no longer use the "exec" command of the "child_process" module. The "require" command no longer sees this module. Does BetterDiscord have a way to get this module or is there an alternative?

**Screenshot of the error**
![error](https://user-images.githubusercontent.com/68241298/195989447-77a0ec15-52e4-42d9-b6dc-3727d719d66b.png)

**Additional context**
I don't know if this is a problem on the BetterDiscord side or not, so I apologize if this ticket here is inappropriate and not related to BetterDiscord. I also haven't come across any other tickets on this topic, so I don't know if bringing it back is in your plans

**Comment by rauenzi** [comment]
Unfortunately there is no long direct node access so that module is completely inaccessible to plugins.
