### ISSUE TITLE
[Bug] Auto Update Featrue Broken

### ISSUE THREAD

**Issue by NextdoorPsycho** [BetterDiscord/BetterDiscord#1452]
**Describe the Bug**
After clicking the download button on Better discord internally it breaks and wont let me open.

**To Reproduce**
Use the internal update button on canary from 1.8.1 to 1.8.2

**Expected Behavior**
Allow me to open discord after updating

**Screenshots**
[
![image](https://user-images.githubusercontent.com/29320316/196320465-84ee0156-1685-4c9f-90a8-acfacc2857fc.png)
**Discord Version**
Canary

**Comment by maenDisease** [comment]
Fixed with 1.8.2, reinstall BD through the BD installer to update to it.

**Comment by Rashed3901** [comment]
same bug
![image](https://user-images.githubusercontent.com/82941630/196328072-d04e8926-2075-40b2-8646-e9f85f96f1c7.png)

**Comment by thehorrorevent** [comment]
Discord Stable crashes every time after update

**Comment by nemesio65** [comment]
Repair/Install from the BetterDiscord installer. Auto-Update on the app from 1.8.1 is broken. 1.8.2 fixes it, but will require a reinstall of BetterDiscord.

**Comment by EDM115** [comment]
> **Discord Version** Canary

Also happens with PTB :  

![image](https://user-images.githubusercontent.com/82015596/196417716-6151f411-d21f-4125-a101-d11d9dfa1cad.png)

**Comment by alterNERDtive** [comment]
> Repair/Install from the BetterDiscord installer. Auto-Update on the app from 1.8.1 is broken. 1.8.2 fixes it, but will require a reinstall of BetterDiscord.

Well … 
![image](https://user-images.githubusercontent.com/53827887/196420819-6208dadd-a392-4b54-b77f-2f1626653438.png)
