### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by yasszou** [BetterDiscord/BetterDiscord#1455]
![image](https://user-images.githubusercontent.com/70234998/196562534-6ceaf87f-d3d4-4d32-bc2d-0c8b681110e9.png)
I think is self explanatory

**Comment by maenDisease** [comment]
Reinstall BD

**Comment by yasszou** [comment]
i already tried.

> Reinstall BD

**Comment by showierdata9978** [comment]
im having the same problem
![image](https://user-images.githubusercontent.com/68120127/196576421-bc509382-42e7-4675-bc3b-23136e441947.png)

**Comment by hazlema** [comment]
This happened to me when I updated via the User Settings Updater.  I used the utility 'BetterDiscord-Linux.AppImage' did a repair and it fixed the issue.  Same exact error message

**Comment by fowlis** [comment]
Duplicate of https://github.com/BetterDiscord/BetterDiscord/issues/1452
