### ISSUE TITLE
[Bug] Entirely Transparent Crash Screen

### ISSUE THREAD

**Issue by PixelGuy123** [BetterDiscord/BetterDiscord#1458]
**Describe the Bug**
When better discord crashes, this screen appears, but if you have transparent mode enabled (on the settings), the entire window gets trasparent

**To Reproduce**
Crash it somehow

**Expected Behavior**
Not... be transparent?

**Screenshots**
![image](https://user-images.githubusercontent.com/89644121/196803670-30f4cad6-a0af-41aa-b8da-16f86e591b6a.png)

**Discord Version**
Stable

**Additional Context**
_Yep_

**Comment by PixelGuy123** [comment]
Also, I would like to ask: when it crashes, it asks me to use ctrl + shift + i to see the console (so I can finally find out why does it randomly crashes in first place), but it doesn't work on stable

**Comment by rauenzi** [comment]
That only happens with your specific theme. BD does not make the window transparent without external CSS

**Comment by PixelGuy123** [comment]
Well, I use the clear vision theme, and when it crashes, it shows with the default discord theme, but when transperency one, this screen appears

**Comment by PixelGuy123** [comment]
Just as I said:
![image](https://user-images.githubusercontent.com/89644121/196815380-8382e161-6749-4455-b90f-1179265627c6.png)
(I disabled trasperency this time)

**Comment by PixelGuy123** [comment]
Oh wait you right, holy crap, I feel dumb rn, i just disabled the themes and check it out again
