### ISSUE TITLE
[Bug] Windows 7 installer stuck

### ISSUE THREAD

**Issue by jacobwatkinsgit** [BetterDiscord/BetterDiscord#1464]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Starting Install...

Creating required directories...
✅ Directory exists: C:\Users\me\AppData\Roaming\BetterDiscord
✅ Directory exists: C:\Users\me\AppData\Roaming\BetterDiscord\data
✅ Directory exists: C:\Users\me\AppData\Roaming\BetterDiscord\themes
✅ Directory exists: C:\Users\me\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
✅ Package downloaded

Injecting shims...
Injecting into: C:\Users\me\AppData\Local\Discord\app-1.0.9007\resources
✅ Injection successful
✅ Shims injected

Restarting Discord...
Attempting to kill Discord

Aaaaand stuck. The installer is not frozen, it just never continues.

### Expected Behavior

Restarting Discord should do something?
Kill process either shouldn't run... or whatever when Discord isn't found.

### Steps To Reproduce

Windows 7, B.D. 1.8.0 installed, got the "notification" to upgrade. ("Update" label in the settings does nothing but that's not why I'm here)

Closed Discord. Downloaded the 1.1.2 (?) version, Windows exe.

Install on top of: c:\Users\me\AppData\Local\Discord\app-1.0.9007\resources

Result ^

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.8.2 ?

Edit: username change

**Comment by maenDisease** [comment]
Installer issues go to https://github.com/BetterDiscord/Installer/issues

**Comment by jacobwatkinsgit** [comment]
Closing, since the bug is reported over there.
