### ISSUE TITLE
[Bug]BD not installing on Latest Canary

### ISSUE THREAD

**Issue by NextdoorPsycho** [BetterDiscord/BetterDiscord#1466]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

BD Will not install on Canary

### Expected Behavior

It Should install and i should be able to use it

### Steps To Reproduce

Download Canary latest
install 1.8.2
profit

### Operating System

Windows

### Discord Version

Canary

### BetterDiscord Version

Canary 154680 (94a897a) Host 1.0.51 Windows 10 64-Bit (10.0.22621)

### Anything else?

Thanks for maintaining this project

**Comment by NextdoorPsycho** [comment]
And for people having this issue too. Please don't say "ME TOO" just react with a Thumbs up
👍 to the main Message.

**Comment by NextdoorPsycho** [comment]
This is still an issue on latest Canary:
Canary 156668 (1fcc9a8) Host 1.0.52 Windows 10 64-Bit (10.0.22621)

**Comment by UBFI** [comment]
Can confirm still an issue on MacOS, Linux(Debian), and Windows

**Comment by prforty** [comment]
Confirmed on macOS Silicon, Discord stable

**Comment by Loganbogan9** [comment]
Compiling from source fixed this for me.

**Comment by fowlis** [comment]
@prforty 
> Confirmed on macOS Silicon, Discord stable
> 
> `Injecting shims... Injecting into: /Applications/Discord.app/Contents/Resources ❌ Could not inject shims to /Applications/Discord.app/Contents/Resources ❌ EPERM: operation not permitted, mkdir '/Applications/Discord.app/Contents/Resources/app'
> 
> The install seems to have failed. If this problem is recurring, join our discord community for support. [https://discord.gg/0Tmfo5ZbORCRqbAd`](https://discord.gg/0Tmfo5ZbORCRqbAd%60)

This error is unrelated to the issue this post was created for. If you haven't joined the support server and received help to fix this I'd suggest doing that.

**Comment by AngelCMHxD** [comment]
This is happening since the electron update occurred on Canary:
Can reproduce this on Canary 158173 (c13e624) Host 1.0.53 (26936)
Windows 10 64-Bit (10.0.22000)
Electron version: 17.4.9 (Wasn't on first post)

**Comment by NextdoorPsycho** [comment]
Again you should stop posting replies, just hit the 👍, everyone (83+ people) get spammed with emails, so a 👍 is better for count

**Comment by BlueStarBRS** [comment]
if someone dont know how to fix here a tutorial how to install it Manuall (Windows)
https://youtu.be/yU9LqgXSPlk
also here a guide in text form:

Guide
how to install BD on Cannery Manually

- Download and install: 
https://git-scm.com/download/win
https://nodejs.org/dist/v18.12.1/node-v18.12.1-x64.msi

- close all Discord clients ⚠️   
- open Windows PowerShell (Terminal) 

- take these commands in one after the other:

npm install -g pnpm
Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
- Press A  and then Enter

git clone https://github.com/BetterDiscord/BetterDiscord.git
cd betterdiscord
pnpm recursive install
pnpm run build
pnpm run inject canary


- start Discord and Done

**Comment by Crypt0Beaver** [comment]
It seems the issue arrived on PTB too now.

**Comment by ZeldrexK0DE** [comment]
PTB doesnt load yep

**Comment by Nimon77** [comment]
Like we say earlier please just add a 👍 to the last comment, thanks !

> Again you should stop posting replies, just hit the 👍, everyone (83+ people) get spammed with emails, so a 👍 is better for count

**Comment by rauenzi** [comment]
This has now been fixed
