### ISSUE TITLE
[Feature] debug log history folder

### ISSUE THREAD

**Issue by ColonelGerdauf** [BetterDiscord/BetterDiscord#1468]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

Currently, the debug logs, when you enable it, is singular and keeps track of everything for all of time.

For long term use, this can quickly become burdensome when it comes to looking for the right logs.

So what I can suggest is having the logs be per-session. What that means is that whenever Discord starts up again, it moves the existing log, if it exists, to a directory where the different logs are stored with the timestamps. You can either have the file individually timestamped on initial creation, or you can have Y/M/D subdirectories like how ShareX has done it.

This way, people do not need to worry about having to turn it off or on at the right times, or to wipe the logs before checking for bugs.

**Comment by rauenzi** [comment]
This should not be on in the long term and should only be used when asked to by support staff.
