### ISSUE TITLE
[Bug] i cant install the better discord

### ISSUE THREAD

**Issue by xXHakaseXx** [BetterDiscord/BetterDiscord#1469]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

https://www.youtube.com/watch?v=bKIhpmF-jwc

### Expected Behavior

https://www.youtube.com/watch?v=bKIhpmF-jwc

### Steps To Reproduce

https://www.youtube.com/watch?v=bKIhpmF-jwc

### Operating System

Windows

### Discord Version

Canary

### BetterDiscord Version

v1.8.2

### Anything else?

https://www.youtube.com/watch?v=bKIhpmF-jwc

**Comment by SmolAlli** [comment]
We are aware of this and it is being fixed. It is confirmed.
Details: Due to Discord updating the version of Electron to 17.
