### ISSUE TITLE
[Bug] Nie mogę wyłączyć pewnej opcji

### ISSUE THREAD

**Issue by xXHakaseXx** [BetterDiscord/BetterDiscord#1470]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

![obraz](https://user-images.githubusercontent.com/67443169/198833975-92fb010b-719c-43b1-b21c-7095b8cfb7b9.png)

### Expected Behavior

![obraz](https://user-images.githubusercontent.com/67443169/198833984-46dc5e9a-a99d-470e-9b05-672e117f6587.png)

### Steps To Reproduce

![obraz](https://user-images.githubusercontent.com/67443169/198833988-cd8d3a20-224a-4eb1-8701-0136bc7336de.png)

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.2

### Anything else?

![obraz](https://user-images.githubusercontent.com/67443169/198834005-ead4c832-a2f9-482d-bffa-187444832ec4.png)

**Comment by SmolAlli** [comment]
Hello, this GitHub repository is for English only.
> I cannot turn off a certain option
The emote system is currently not working, and has been greyed out as such. The option showing as "on" is not completely intended.
This option will be removed if/when #1467 is merged.
