### ISSUE TITLE
[Bug] Fake screen burn-in effect when unfocused

### ISSUE THREAD

**Issue by sorae42** [BetterDiscord/BetterDiscord#1472]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When Discord is unfocused, a weird screen burn-in effect can be seen when having transparency on.

<img width="365" alt="Screenshot 2022-11-06 at 03 38 46" src="https://user-images.githubusercontent.com/34794115/200140511-bf6c909a-a528-43b5-b2bd-36c1d0538016.png">

### Expected Behavior

There shouldn't be any effect like that when unfocused.

### Steps To Reproduce

Using any transparent theme with transparent mode turned on will have this issue.

### Operating System

MacOS

### Discord Version

Stable

### BetterDiscord Version

v1.8.2

**Comment by rauenzi** [comment]
This is not something BetterDiscord can do. We simply pass the flag to electron and they handle all the graphics related to transparency,
