### ISSUE TITLE
[Bug] BD BUG let some plugins don't work properly

### ISSUE THREAD

**Issue by BlueStarBRS** [BetterDiscord/BetterDiscord#1476]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

some plugins dont work anymore i ched the console and found some BD errors in the console maybe discord whas maked some internal changes

![image](https://user-images.githubusercontent.com/25110093/201206389-6034c1af-5e73-4e1f-8c06-cafae75c5ac0.png)
![image](https://user-images.githubusercontent.com/25110093/201206393-d289f596-5e8a-4db2-aadf-7fca088e7925.png)
https://streamable.com/40bi2x here a video of my **Full** Log (pause to read)

### Expected Behavior

that there is no error and the plugins work

### Steps To Reproduce

check your console also use as example BDFDB with friend notifications,read all, removeblockedusers to see a effeckt from the error of BD

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.8.2

### Anything else?

before i go to bed everything works then im awake and it dosnt work anymore i guess ds maked some internal changes

**Comment by Kaonashie** [comment]
Same thing here 
<img width="275" alt="image" src="https://user-images.githubusercontent.com/45643611/201210548-485b41d7-4bec-4f1c-a4af-b11ffac67e21.png">

full logs : 
[discord.com-1668116097966.log](https://github.com/BetterDiscord/BetterDiscord/files/9984749/discord.com-1668116097966.log)

**Comment by rauenzi** [comment]
What you've screenshotted are just warnings. The errors from both of you are specific to the plugins and not something for BD to fix.

**Comment by Kaonashie** [comment]
> Thank you and sorry. Should've been more thorough with my reading of the logs.

**Comment by BlueStarBRS** [comment]
in any case, there are problems that can only be traced back to the bd api/app Eg the context menu for channels no longer shows the plugins tabs @rauenzi 

![image](https://user-images.githubusercontent.com/25110093/201295280-308c7114-4077-4e13-a4ce-339a95d139ed.png)
so idk

**Comment by rauenzi** [comment]
In the future, don't mention me for non-urgent, thanks.
