### ISSUE TITLE
[Bug] Profile Theme Color Button Deleted

### ISSUE THREAD

**Issue by 0xc60f** [BetterDiscord/BetterDiscord#1477]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When BetterDiscord is enabled, without enabling any plugins or themes, the profile theme button changers for the main profile, the server profile dropdown, and the change banner button for server profiles is deleted.

Screenshots:

![image](https://user-images.githubusercontent.com/45770865/201237558-aea0f2b6-5a5d-4fbe-99d9-a4760f79887e.png)

![image](https://user-images.githubusercontent.com/45770865/201237596-c930cd85-a76c-4868-9df0-07d7bb06e271.png)

![image](https://user-images.githubusercontent.com/45770865/201237746-cff32424-51c0-4082-8219-0ecc00662451.png)

### Expected Behavior

The buttons mentioned above should show properly.

### Steps To Reproduce

1. Install BetterDiscord
2. Go to Settings --> Profiles

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.2

### Anything else?

Uninstalling BD fixes the issue but reinstalling it will cause the bug to show again.

**Comment by SmolAlli** [comment]
Cannot replicate. With or without BD, no buttons were missing on the "User profile" page.

**Comment by 0xc60f** [comment]
Closing, it appears that a recent BD update which came 30 minutes after I posted this fixed the issue.
