### ISSUE TITLE
[Feature] Add a message when macOS blocks install

### ISSUE THREAD

**Issue by halfcyan** [BetterDiscord/BetterDiscord#1479]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

When installing BetterDiscord on macOS (presumably starting with Ventura, as this did not happen before I updated), a notification pops up saying that macOS has stopped BetterDiscord.app from modifying other applications on your Mac. There should likely be a notification in the console explaining that you need to click allow on that notification and enable BetterDiscord to have App Management permissions.

I can likely add a PR for this at some point.

**Comment by SmolAlli** [comment]
this isnt the repo for the installer
