### ISSUE TITLE
[Feature] suggestion to add disable all plugins button  Suggestion

### ISSUE THREAD

**Issue by PsychoManiac189** [BetterDiscord/BetterDiscord#1480]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

id like  an option to enable/disable this then i can just turn them on one by one  to determin what is causing an issue i have

**Comment by SmolAlli** [comment]
[This plugin](https://betterdiscord.app/plugin/Toggle%20Your%20Stuff) is able to perform that action with a keybind

**Comment by rauenzi** [comment]
#723
