### ISSUE TITLE
[Feature] Allow disabling non working plugins

### ISSUE THREAD

**Issue by rp1231** [BetterDiscord/BetterDiscord#1482]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

Right now, a lot of plugins broke with the recent discord update.
The broken plugins show an error each time discord is started up.
It is currently not possible to disable the broken plugin.
The only way to avoid the broken plugin notification at startup is to uninstall the plugin.

### Anything else?

<img width="351" alt="np3Y6OIc3R" src="https://user-images.githubusercontent.com/47380919/204125315-6f7b3c51-2199-4ddc-b40c-798741520b0d.png">

Maybe the toggle button can be green with the "x" on it to indicate that it is a broken plugin , and should turn grey with the "x" and move to the disabled position only when you disable it.

**Comment by rauenzi** [comment]
They should be automatically disabled under the covers.
