### ISSUE TITLE
[Bug] Installed BetterDiscord doesn't show profile themes

### ISSUE THREAD

**Issue by thejulfor** [BetterDiscord/BetterDiscord#1483]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When BetterDiscord is installed on clean Discord installation, profile themes don't show at all. Before installing BetterDiscord, all themes could be seen.

### Expected Behavior

Profile themes shown

### Steps To Reproduce

1. Reinstall Discord
2. Install BetterDiscord (without any plugins/themes)

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.2

**Comment by rauenzi** [comment]
I cannot recreate this issue at all. Is this still ocurring?

**Comment by SupraM4** [comment]
je ne peut pas faire la nouvelle maj avez d'autre idée ?
