### ISSUE TITLE
No matter what theme I use, I get a grid overlay over everythin, which causes problems with image readability. [Bug]

### ISSUE THREAD

**Issue by GenGremlin** [BetterDiscord/BetterDiscord#1484]
### Before Reporting

- [X] I found no existing issues matching my bug
- [x] My issue is not caused by a plugin or theme

### Describe the Bug

![image](https://user-images.githubusercontent.com/119559010/204971221-11a364a8-e928-4f89-b7eb-3a4058c19ee1.png)
![image](https://user-images.githubusercontent.com/119559010/204971296-784498d6-d3ad-4852-8f9b-e6fa55cf37b5.png)
![image](https://user-images.githubusercontent.com/119559010/204971349-ee5c0471-fa9f-41ae-bc32-950ef6d3101c.png)
![image](https://user-images.githubusercontent.com/119559010/204972290-a8d3f43e-6112-4214-adf7-1f85e4257b85.png)
(image above with fallout 4 terminal theme loaded, image below without any themes)
![image](https://user-images.githubusercontent.com/119559010/204972327-b988820b-90a5-433a-b332-5f6609d19d9d.png)

I don't use any plugins, so it's not their fault, default background lacks the grid seen on above screenshots. It does not outright break anything but it makes images harder or unable to read clearly, which is rather annoying, having to go to settings, disable a theme, read what I need, then go back and re-enable it. The examples are NieR Automata both light and dark themes and fallout 4 terminal. I also use radial status theme alongside, but disabling it does not change anything. the grid appears right after loading a theme, but there is a small window of time during which it is absent, around half to 1 second, then the grid appears

### Expected Behavior

A short time after loading a theme / launching discord a grid overlay appears over the whole program making most images unreadable

### Steps To Reproduce

1.launch discord
2.turn on any theme
3.have grid
4.be annoyed

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.2

**Comment by ItMeSarah** [comment]
This is due to a theme you're using. Fallout4terminal has that, you can disable it.  https://github.com/CommandCrafterHD/Fallout4TerminalTheme/blob/main/css/disableCRT.css

**Comment by CommandCrafterHD** [comment]
> This is due to a theme you're using. Fallout4terminal has that, you can disable it.   @import url('https://commandcrafterhd.github.io/Fallout4TerminalTheme/css/disableCRT.css');

As the dev of the Fallout4Terminal theme I second this! :D

**Comment by GenGremlin** [comment]
> > This is due to a theme you're using. Fallout4terminal has that, you can disable it.   @import url('https://commandcrafterhd.github.io/Fallout4TerminalTheme/css/disableCRT.css');
> 
> As the dev of the Fallout4Terminal theme I second this! :D

I highly doubt it, as the problem was present for months before I even installed the fallout 4 theme. Originally I had only the NieR theme, but I just assumed it was how the theme was, now I'm not sure...
