### ISSUE TITLE
[Feature] remapping to vim keybindings or just add vim keybindings as a plugin

### ISSUE THREAD

**Issue by fislysandi** [BetterDiscord/BetterDiscord#1485]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

so basically im in a quest of using only keyboard for controlling my pc ie. tiling wms,neovim,vimium c,ranger,etc.

and i would really love to have vim keybindings in betterdiscord so that will reduce my mouse usage even more.

### Anything else?

example of vim keybindings 
# ranger https://gist.github.com/rpietro/f606e1a9cc5eb9e9ef8666b441c31648

**Comment by rauenzi** [comment]
If a plugin wants to add that, that's fine. It will not be added as part of BD.
