### ISSUE TITLE
[Bug] Devtools shortcut is ctrl+shift+i on MacOS

### ISSUE THREAD

**Issue by Yourself1011** [BetterDiscord/BetterDiscord#1486]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

On MacOS, the keyboard shortcut for opening the devtools is ctrl+shift+i (⌃⇧i)

### Expected Behavior

Like most browsers on MacOS, the keyboard shortcut should be cmd+shift+i (⌘⇧i)

### Steps To Reproduce

1. be on macos
2. turn on DevTools setting
3. try ⌘⇧i (doesn't do anything)
4. try ⌃⇧i (opens devtools)

### Operating System

MacOS

### Discord Version

Stable

### BetterDiscord Version

v1.8.2

**Comment by rauenzi** [comment]
I would not say this is a bug, as this was the intention. This could be a feature request though.
