### ISSUE TITLE
Installing BetterDiscord on ChromeOS Freezes [Bug]

### ISSUE THREAD

**Issue by An-Untitled-Developer** [BetterDiscord/BetterDiscord#1487]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

On ChromeOS when you run the .AppImage everything is fine and dandy until the installation part and it freezes up. I tested BetterDiscord in a Linux VM and it does the same thing.  

### Expected Behavior

It would just install and everything would be good to go.

### Steps To Reproduce

1. Have ChromeOS or Linux
2. Have Discord
3. Attempt to install betterdiscord
4. That's all

### Operating System

Linux

### Discord Version

Stable

### BetterDiscord Version

Unknown

**Comment by SmolAlli** [comment]
Could you please be more specific about the installation "freezing up"? Like, does the app go unresponsive, or does the installation bar just stop moving. A video of this would be helpful.
Also, for installer-specific issues, you should use https://github.com/BetterDiscord/installer

**Comment by rauenzi** [comment]
We do not officially support ChromeOS
