### ISSUE TITLE
[Bug] Better Discord won't install on DiscordPTB

### ISSUE THREAD

**Issue by KelTRM** [BetterDiscord/BetterDiscord#1488]
### Before Reporting

- [x] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

I recently updated BetterDiscord (on PTB), but afterwards, all my themes, and plugins just stopped working, and the BetterDiscord logo on loading screen just isn't there

### Expected Behavior

BetterDiscord to be present (after install on PTB)

### Steps To Reproduce

Environment: DiscordPTB
Steps:

1: Install BetterDiscord on PTB

(If it was reproduced, it should restart and not be present)

### Operating System

Windows

### Discord Version

PTB

### BetterDiscord Version

1.8.2 (I think?)

### Anything else?

![2022-12-09 10_30_25-My Account _ User Settings - Discord](https://user-images.githubusercontent.com/52837791/206749385-8c1a89ac-d7d7-40ed-b360-0e320b4c853d.png)
![2022-12-09 10_32_08-My Account _ User Settings - Discord](https://user-images.githubusercontent.com/52837791/206749655-5cf05f3c-9476-497a-bce9-41c5c118e48f.png)

**Comment by fowlis** [comment]
Known. Same issue that was already on Canary.
You can [install BD manually](https://docs.betterdiscord.app/users/getting-started/installation/#manual-installation) which should work, because the fix for this issue is already on the BD repo - just not available via the installer.

**Comment by Owned67** [comment]
it work/load for me with .exe installer.

Windows 10 x64 
PTB: 1.0.1023

**Comment by rauenzi** [comment]
This has now been fixed!
