### ISSUE TITLE
[Bug] The Pnpm inject script tries to rename app.asar into discord.asar

### ISSUE THREAD

**Issue by CraftingDragon007** [BetterDiscord/BetterDiscord#1489]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When trying to inject Better Discord into the newest update (using pnpm run inject), it would try to rename a non existing app.asar file. So it showed an error message
![image](https://user-images.githubusercontent.com/68032198/206839807-8568e5b7-9d2b-41d8-b947-03338da968e2.png)
I could manage to inject Better Discord, but only when manually renaming the core.asar file to app.asar and then after the injection process renaming it to core.asar again.

### Expected Behavior

It shouldn't try to rename the app.asar file. And no error message should show up

### Steps To Reproduce

1. Install the 0.0.22 version of discord 
2. Then inject BetterDiscord via `pnpm run inject`
3. The error should show up

### Operating System

Linux

### Discord Version

Stable

### BetterDiscord Version

v1.8.2

**Comment by ItMeSarah** [comment]
Close discord completely and then try injecting

**Comment by CraftingDragon007** [comment]
I had it closed

**Comment by CraftingDragon007** [comment]
As I said, it worked after renaming the file manually

**Comment by rauenzi** [comment]
> It shouldn't try to rename the app.asar file.

It should.

**Comment by CraftingDragon007** [comment]
But why does this file not exist?

**Comment by Strencher** [comment]
> But why does this file not exist?

This is actually an issue with our inject script, I forgot that Linux injection is different from Windows/MacOS. I'll put it on my todo list for later.

**Comment by rauenzi** [comment]
This has now been fixed!
