### ISSUE TITLE
[Bug] BetterDiscord no longer runs on PTB

### ISSUE THREAD

**Issue by LoganDark** [BetterDiscord/BetterDiscord#1493]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

BetterDiscord seems to have stopped working as of (at least) PTB 163627 (1e908d9)...

I can clone the repository, run `pnpm install && pnpm build && pnpm inject ptb`, and it injects just fine and the files look OK (identical to our install of Stable with still-working BD), but BetterDiscord just doesn't load! Discord starts fine and perfectly, but without any trace of BetterDiscord.

### Expected Behavior

BetterDiscord should prooobably be loading~

### Steps To Reproduce

1. Install the latest PTB
2. Try to install BetterDiscord, either using the installer or via manual install
3. Observe that BetterDiscord doesn't run

### Operating System

Windows

### Discord Version

PTB

### BetterDiscord Version

N/A

### Anything else?

There are a variety of other "it doesn't work" issues open that haven't been closed, but they are from months ago and I think this one is different, since PTB was working as of a couple days ago (as in, it's been fully updated at that point). Pleeease let us know if this is inappropriate or something, I know you probably get enough issues that say "it doesn't work". I made sure that nobody else has opened this one yet

**Comment by LoganDark** [comment]
Oh, it appears that *something* is going on, but the loader on the splash screen doesn't show up, and our custom CSS doesn't apply.

![image](https://user-images.githubusercontent.com/4723091/207162863-2c3cae27-8259-4c25-a2cb-f80512b4fbfa.png)

**Comment by PixelGuy123** [comment]
This is also happening in my discord, it is the stable version, and has the same issue (even the screenshot above is relatable)

**Comment by LoganDark** [comment]
Commit d2594463c061bc25f90636bb02ae587a47afd4c1 fixes this for me!
