### ISSUE TITLE
[Bug] BetterDiscord does not load after installing

### ISSUE THREAD

**Issue by wozniak** [BetterDiscord/BetterDiscord#1495]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

no submenus under BetterDiscord in settings and no plugins loaded
![image](https://user-images.githubusercontent.com/106494504/207193771-e1d46140-f9cf-4e30-b949-8471c1b3ab85.png)

### Expected Behavior

BetterDiscord works as normal

### Steps To Reproduce

1. update discord
2. reinstall betterdiscord
3. observe as it doesn't work

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.7

**Comment by Uxusk1** [comment]
omg also experiencing this problem!

**Comment by TheGoldenProof** [comment]
Also having this issue, and I think you meant v1.8.2, not v1.8.7

**Comment by MrComexs** [comment]
I'm also having the same problem.
### Operating System
Linux 64-Bit (6.0.12-Artix1-1)
### Discord Version
Stable 163658 (28d41b4)
### BetterDiscord Version
```
❯ betterdiscordctl --version
betterdiscordctl 2.0.1
```
### Anything else?
```
❯ betterdiscordctl -v reinstall
V: Found modules in /home/comexs/.config/discord/0.0.22/modules
Killing Discord  processes...
Discord killed (pid 14324)
Discord killed (pid 14327)
Discord killed (pid 14328)
Discord killed (pid 14330)
Discord killed (pid 14358)
Discord killed (pid 14367)
Discord killed (pid 14392)
Discord killed (pid 14420)
Discord killed (pid 14460)
V: Downloading BetterDiscord asar...
V: Injecting into index.js...
Reinstalled.
```

**Comment by NayooZ** [comment]
Perform a manual install until the installer has been updated.

https://docs.betterdiscord.app/users/getting-started/installation/#manual-installation

**Comment by MrComexs** [comment]
Betterdiscord is now working as intended.

**Comment by rauenzi** [comment]
This has now been fixed!
