### ISSUE TITLE
[Bug] Does not display plugins/themes list after updating to most recent version of discord.

### ISSUE THREAD

**Issue by agedplato** [BetterDiscord/BetterDiscord#1496]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

List does not appear after updating to most recent version of discord, NOT BETTER DISCORD.
![Screenshot 2022-12-12 194406](https://user-images.githubusercontent.com/100545380/207198544-77a7110c-d940-47c7-b309-e9ce6cad57fa.png)

### Expected Behavior

List should appear allowing for selection of themes/plugins/ect.

### Steps To Reproduce

1. install 1.8.2
2. check if list appears

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.8.2

### Anything else?

I have attempted to force quit discord and restart it as well as restart my PC.
Windows 10 as operating system.

**Comment by malthegod** [comment]
The same thing is happening to me

**Comment by NayooZ** [comment]
Perform a manual install until the installer is updated.

https://docs.betterdiscord.app/users/getting-started/installation/#manual-installation

**Comment by rauenzi** [comment]
This has now been fixed!
