### ISSUE TITLE
[Bug] Better discord is not starting at all for me.

### ISSUE THREAD

**Issue by Pejsek34** [BetterDiscord/BetterDiscord#1497]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

I've tried repairing, reinstalling, it did not work. Better Discord does not launch at all when starting Discord, no error, no nothing, just does not start.

### Expected Behavior

I would expect Better Discord to launch when I start Discord

### Steps To Reproduce

Install Better Discord
Start Discord
Realize Better Discord did not launch

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

newest (Can't bet it from setting as it does not launch at all)

**Comment by fowlis** [comment]
Join the [support server](https://discord.gg/0Tmfo5ZbORCRqbAd) and read [this #known-issues post](https://discord.com/channels/86004744966914048/1019687030826999830).

**Comment by rauenzi** [comment]
This has now been fixed!
