### ISSUE TITLE
[Bug] Not installing 

### ISSUE THREAD

**Issue by MKDonaghue** [BetterDiscord/BetterDiscord#1498]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Installer is failing to grap assets required to install like "betterdiscord.asar"

### Expected Behavior

Should be able to grab the files it needs to complete install/repair

### Steps To Reproduce

just try to install or repair better discord for it to happen

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.8.3

### Anything else?

![image](https://user-images.githubusercontent.com/120471839/207325144-2b0aaf16-2240-4629-8610-a8d2360db9e6.png)

**Comment by fowlis** [comment]
This repo is not for support with installer-related issues.
Either join the [support server](https://discord.com/invite/0Tmfo5ZbORCRqbAd) or post this issue on the [sister repo for the installer](https://github.com/BetterDiscord/Installer).
