### ISSUE TITLE
[Bug] Installer not working

### ISSUE THREAD

**Issue by HeyItSloth** [BetterDiscord/BetterDiscord#1499]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

I downloaded the latest installer, and when I run it, all I get is a blank screen on the installer

![image](https://user-images.githubusercontent.com/54008276/207631070-b60939f5-bdcd-4824-b566-a4ffde2ea99c.png)

### Expected Behavior

Allow me to install BetterDiscord.

### Steps To Reproduce

Just downloaded the latest installer and ran it (tried multiple downloads, not just one .exe)

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.3

**Comment by maenDisease** [comment]
This repo is for BD development, installer issues go to https://github.com/BetterDiscord/Installer/

**Comment by tnbhaeufi** [comment]
Issue still exists for me, sorry.
