### ISSUE TITLE
[Feature] Custom JS

### ISSUE THREAD

**Issue by ArnavGupta30** [BetterDiscord/BetterDiscord#1500]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

Add an option to add Custom JS for small things.
Like 
> Adding a button to clear text bot
> Adding a button for DM user
> Adding channel desc under the channel

**Comment by rauenzi** [comment]
This would encourage bad actors to attack uninformed users. Just use plugins.
