### ISSUE TITLE
impossible de télécharger la nouvelle maj et faire marcher betterdiscord

### ISSUE THREAD

**Issue by SupraM4** [BetterDiscord/BetterDiscord#1501]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

La nouvelle MAJ ne veut pas se télécharger pour la raison et que mon site internet ne fait pas confiance a betterdiscord. avez vous des solution ?

### Expected Behavior

j'aimerais juste que sa marche

### Steps To Reproduce

1. télécharger la nouvelle maj
2. le bug

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

V1.2.1

**Comment by SupraM4** [comment]
Et sur discord bien évidemment je n'est pas la casse de better discord

**Comment by rauenzi** [comment]
Sorry, we can only support English language issues at this time. Based on the version you gave, you are referring to the installer which is in a different repo.
