### ISSUE TITLE
Installer still not showing anything

### ISSUE THREAD

**Issue by tnbhaeufi** [BetterDiscord/BetterDiscord#1503]
Issue still exists for me, sorry.
![image](https://user-images.githubusercontent.com/25664410/207947354-629b8d3b-b89f-44c9-acc7-b3f0dd73cfbb.png)

_Originally posted by @tnbhaeufi in https://github.com/BetterDiscord/BetterDiscord/issues/1499#issuecomment-1353579194_

**Comment by rauenzi** [comment]
Does not follow issue template and is on the wrong repo.
