### ISSUE TITLE
[Bug] Can't Install BD

### ISSUE THREAD

**Issue by MaximIce1** [BetterDiscord/BetterDiscord#1505]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

After install and restarting Discord BetterDiscord don't installer
Manual install doesnt help
https://i.imgur.com/eXRUXwO.png

### Expected Behavior

'Plugins' and 'Themes' folders in settings

### Steps To Reproduce

Manual install BD

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.4 i think

**Comment by ShadowDevilsAvenged** [comment]
did you try the new installer?  https://betterdiscord.app/
