### ISSUE TITLE
[Feature] Changelog on updates page

### ISSUE THREAD

**Issue by master3395** [BetterDiscord/BetterDiscord#1506]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

When you get updates on addons, there should be an update log, perhaps on the red box on the image below.
Or an button saying "Changelog" somewhere.
![image](https://user-images.githubusercontent.com/4199669/208312292-13d7fbaf-4655-4ed9-a3b0-2fdf776d3d8b.png)

**Comment by rauenzi** [comment]
Going to combine this with #871
