### ISSUE TITLE
[Bug] `BdApi.ContextMenu.ControlItem` is `undefined`

### ISSUE THREAD

**Issue by ssense1337** [BetterDiscord/BetterDiscord#1507]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

The regex doesn't match `ControlItem` because its identifier and type are on separate lines.

### Expected Behavior

`BdApi.ContextMenu.ControlItem` found

### Steps To Reproduce

Build a context menu item or simply put `BdApi.ContextMenu.ControlItem` in Discord's console

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.4

### Anything else?

This issue can be fixed with `/if\(\w+\.type===\w+\.(\w+)\).+?type:"(.+?)"/gs` or
`/if\(\w+\.type===\w+\.(\w+)\)[\s\S]+?type:"(.+?)"/g`

**Comment by rauenzi** [comment]
This should now be fixed
