### ISSUE TITLE
Snap packages support ubuntu

### ISSUE THREAD

**Issue by BGOPC** [BetterDiscord/BetterDiscord#1510]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

I wanted to install better discord on my ubuntu machine
It couldn't detect my discord which is installed with snap
I mainly located my snap installed discord at my root file system
but when I pressed ok
It said: 
"Sorry, Better Discord currently doesn't support snap packages"
I Appreciate if u guys add support for snap packages

### Anything else?

![image](https://user-images.githubusercontent.com/94793764/209082795-1959b044-88ad-423b-9dfd-6f339341a3ec.png)
Ubuntu 22.04.1

**Comment by SmolAlli** [comment]
[betterdiscordctl](https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172) supports snap and flatpak versions of discord, you should be using that instead of this installer for linux in general.
Also, this isn't the [right repository](https://github.com/BetterDiscord/Installer/)

**Comment by rauenzi** [comment]
This is being tracked in the installer repo
