### ISSUE TITLE
[Bug] Voice quality decreases over time

### ISSUE THREAD

**Issue by Wormix48** [BetterDiscord/BetterDiscord#1511]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

After some time in the voice channel, my interlocutors say that the sound of the microphone is ruined (but I can hear myself in the headphones fine without distortion), only restarting the channel helps

### Expected Behavior

The sound of the voice should not change over time

### Steps To Reproduce

I don't know how to reproduce it, I'm just sitting in the ds

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.4

**Comment by fowlis** [comment]
BD can't touch your mic input, so its likely Discord or another software interfering with it.

**Comment by rauenzi** [comment]
Yeah same as above, BD does not touch any audio streams.
