### ISSUE TITLE
[Feature] Add a way in the settings to disable plugins update "notifications"

### ISSUE THREAD

**Issue by Palloxin** [BetterDiscord/BetterDiscord#1512]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

These notifications (see image at the bottom)
I am suggesting the addition of a way to disable them completely in the settings.
Why?  Personlly ( i guess other users can relate too), because i need them occasionally so watching them appear everytime i open discord is very annnoying. When i will need them and they don't work i will just update them manually in the settings
so there is no need to make the app pop up the notification every single time i open discord.

### Anything else?

![image](https://user-images.githubusercontent.com/75091899/209436239-d02639e1-b6ab-4f05-993c-c121fb54d35a.png)

**Comment by maenDisease** [comment]
The first banner is not from BD, but by your BDFDB plugin.
The second banner is not from BD, but by plugins that use the ZeresPluginLibrary updater.
The third banner is from BD.

**Comment by Palloxin** [comment]
I am asking if BD can block the appearance of them

**Comment by Senliast** [comment]
@Palloxin here.
[UpdateNoticesRemover.zip](https://github.com/BetterDiscord/BetterDiscord/files/10528352/UpdateNoticesRemover.zip)

**Comment by Strencher** [comment]
Please do not share random ZIP files on github, make a github gist with whatever is in there.

**Comment by rauenzi** [comment]
The other ones are not something BD controls, but they should stop soon. BD will probably not add that option for it's own banner.
