### ISSUE TITLE
[Feature] Add a way in the settings to disable the "load" notifications of plugins

### ISSUE THREAD

**Issue by Palloxin** [BetterDiscord/BetterDiscord#1513]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

This notification (see image at the end)
A way to eliminate/disable the load notification of plugins every time i open discord or when i update a plugin in the settings. 
Why? Aesthetically speaking i don't like it. The more plugins one has, the more "loads" appear as a notification and i don't like it
Make it appear ONLY if the load of the plugin fails for some reason, that would be useful.

### Anything else?

![immagine](https://user-images.githubusercontent.com/75091899/209436556-9f5d7d37-7e6f-4e1b-b570-30c0b28a5e8b.png)

**Comment by rauenzi** [comment]
Try toggling the disable toasts setting.

**Comment by Palloxin** [comment]
i don't want to disable toasts, just plugin notifications of that kind

**Comment by maenDisease** [comment]
That is not a toast by BD, but by your BDFDB plugin.

**Comment by Palloxin** [comment]
Yes but can't BD control the flux of toast that aplear inside itself?

**Comment by maenDisease** [comment]
This can already be disabled inside BDFDB settings.

**Comment by Palloxin** [comment]
What about other plugins not made by devil bro?

**Comment by Palloxin** [comment]
nvm i got it
