### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by moosje2003** [BetterDiscord/BetterDiscord#1515]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

a plugin for predictive text like you have on powershell

**Comment by maenDisease** [comment]
This repo is for BD development, not plugin suggestions.

**Comment by moosje2003** [comment]
oh okay where can i make plugin suggestions?

**Comment by maenDisease** [comment]
There are no official dedicated places to do it, it's up to individual developers to decide.

**Comment by moosje2003** [comment]
okay  i will close this thread
