### ISSUE TITLE
Remove Public Servers Tab/Filter Shown Servers

### ISSUE THREAD

**Issue by KristalAndStarlight** [BetterDiscord/BetterDiscord#1516]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

If you open the public servers tab, a lot of the servers are just NSFW, which isn't right, there are many underage users using this client mod, and it just promotes NSFW servers to them.

**Comment by ShadowDevilsAvenged** [comment]
This isn't really a BD issue

**Comment by SmolAlli** [comment]
The servers are gotten from an [external source](https://discordservers.com/) and are not moderated by BD.

**Comment by ItMeSarah** [comment]
You can also disable the tab all together, by  going to settings, and unchecking public servers.

**Comment by Maniacsan** [comment]
This should be disabled to begin with and a option to enable.

**Comment by KristalAndStarlight** [comment]
> This should be disabled to begin with and a option to enable.

yeah, that's sorta what we meant
