### ISSUE TITLE
[meta] Installation section on wiki does not link to correct page

### ISSUE THREAD

**Issue by nagaisa** [BetterDiscord/BetterDiscord#1517]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

(not realy a feature request or a bug, but it seems like pull requests cant be used for wiki pages) Installation wiki page link does not link to the correct new page the wiki links to https://docs.betterdiscord.app/general/introduction/installation but correct page is https://docs.betterdiscord.app/users/getting-started/installation

**Comment by rauenzi** [comment]
Wiki has been disabled
