### ISSUE TITLE
[Feature] Allow theme installation as UserCSS for better compatibility with browser extensions like Stylus

### ISSUE THREAD

**Issue by ttang4299** [BetterDiscord/BetterDiscord#1518]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

The Stylus devs have mentioned having a framework available to help BetterDiscord with UserCSS support, should BetterDiscord choose to support it. Please look further into this, as I would like autoupdating themes from BetterDiscord in Stylus.

**Comment by rauenzi** [comment]
> The Stylus devs have mentioned having a framework available to help BetterDiscord

Without any further info there's not much I can do, I don't have the time to look through everything in Stylus.

**Comment by TheCommieAxolotl** [comment]
> as I would like autoupdating themes from BetterDiscord in Stylus.

I'm not very familiar with Stylus but this sounds like something to be implemented on their end, not BD's.

**Comment by rauenzi** [comment]
We're moving in a different direction eventually--away from comment based metas
