### ISSUE TITLE
[Bug] BetterDiscord unloads after I restart Discord.

### ISSUE THREAD

**Issue by trollfacenan** [BetterDiscord/BetterDiscord#1519]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When I close Discord, then I open it again my BD just unloads, I have to reinstall it again so it works. If I restart discord using Ctrl + R, BD is still there.

### Expected Behavior

BD should still stay after I restart discord.

### Steps To Reproduce

/shrug

### Operating System

Windows

### Discord Version

Canary

### BetterDiscord Version

v1.8.4

### Anything else?

Just comment if you want a video lol.

**Comment by SmolAlli** [comment]
Sounds like an issue with the version of Discord on your taskbar being different to the one that you installed BetterDiscord onto. Could you please send the version that is on the taskbar?

Steps to do so:
Right click Discord on the taskbar
Right click "Discord" from the popup
Click properties
Send a screenshot of this, make sure to have the app-1.0.900x number visible somewhere.

Screenshot of where "properties" is:
![image](https://user-images.githubusercontent.com/22519967/212462994-58dc37e4-f5e8-42b8-bdba-d746d69dc9c9.png)

**Comment by maenDisease** [comment]
Discord Canary regularly refreshes its files, removing BD through updates, you can use Stable or PTB if you don’t want to deal with having to deal with regularly reinstalling BD.

**Comment by trollfacenan** [comment]
Thanks for the tip above, it worked and now BD works perfectly fine without me having to reinstall it.
