### ISSUE TITLE
[Bug] Emotes setting/option not showing up

### ISSUE THREAD

**Issue by Miniontoby** [BetterDiscord/BetterDiscord#1520]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

I just use the default installer and such. And I don't see the Emotes Section or Button or whatever it should be in my BetterDiscord Section of the Settings page

### Expected Behavior

Any kind of Emotes button/section in the settings

### Steps To Reproduce

1. Just use the default installer or source to install BD
2. Open settings
3. And Voila there you have no Emotes button!

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.8.4

### Anything else?

Here is a screenshot. (yes I know it is in dutch, but there is no such thingy seen here called Emotes or something like it)

![image](https://user-images.githubusercontent.com/47940064/212715574-159bf80d-4404-4931-8bda-aa4b9e7cf105.png)

**Comment by Strencher** [comment]
The emotes feature was removed after a community survey had shown that the majority doesn't need it. It will be available as plugin in the future.

**Comment by Miniontoby** [comment]
Oke thanks for the info
