### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by micuit-cuit** [BetterDiscord/BetterDiscord#1521]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

transparency does not work
with or without theme or plugin

### Expected Behavior

a transparent or semi-transparent font

### Steps To Reproduce

enable transparency and reboot beterd

### Operating System

Linux

### Discord Version

Stable

### BetterDiscord Version

v1.8..4

**Comment by fowlis** [comment]
The transparency option does nothing on its own. You need to have a theme that supports transparency (basically anything that sets a background image on Discord) and to change the background variable's value to `transparent`.

**Comment by micuit-cuit** [comment]
but no theme is activated

**Comment by micuit-cuit** [comment]
![Capture d’écran du 2023-01-25 13-07-06](https://user-images.githubusercontent.com/89157073/214568960-91ef1734-528c-41db-b49e-38f9ade1ef28.png)

**Comment by Strencher** [comment]
# You need to have a theme activated that supports transparency
