### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Tabiz1** [BetterDiscord/BetterDiscord#1522]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

It was fine before but now whenever  open any dm or chat the background is grey and no matter how man times i repair better discord it wont work

### Expected Behavior

this is what the background
![2023-01-26 20_54_14-Window](https://user-images.githubusercontent.com/123708595/214993724-e37a38d8-3395-449e-9228-ffca14c9dd33.png)
 should be

### Steps To Reproduce

![2023-01-26 20_53_22-Window](https://user-images.githubusercontent.com/123708595/214993612-9cc08434-18d7-4dd3-9c73-7ed73a4b53a3.png)
this is how it looks any chat or dm i go

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.4

**Comment by maenDisease** [comment]
This is not for BetterDiscord itself to fix. The developer of your theme should be informed of the issue.

**Comment by Tabiz1** [comment]
> This is not for BetterDiscord itself to fix. The developer of your theme should be informed of the issue.

okay ! is it all themes cuz i checked all my other themes i saved and it does the same thing

**Comment by maenDisease** [comment]
It's due to Discord experimenting with new features, that's why it affects some themes.

**Comment by Tabiz1** [comment]
> It's due to Discord experimenting with new features, that's why it affects some themes.

okay! should i just wait it out or?

**Comment by maenDisease** [comment]
> The developer of your theme should be informed of the issue.

**Comment by Tabiz1** [comment]
> > The developer of your theme should be informed of the issue.

Thats the thing one. i made it and two. it was form the template maker

**Comment by maenDisease** [comment]
you're not the dev if you used a template maker, if you took it from a BD theme editor, look for who is credited

**Comment by Tabiz1** [comment]
> you're not the dev if you used a template maker, if you took it from a BD theme editor, look for who is credited

oh i think i see the issue now.. i dont see Spectra (the person who made it) on the site anymore
