### ISSUE TITLE
[Bug] The theme is not loaded

### ISSUE THREAD

**Issue by korzxcc** [BetterDiscord/BetterDiscord#1524]
### Before Reporting

- [X] I found no existing issues matching my bug
- [ ] My issue is not caused by a plugin or theme

### Describe the Bug

Everything is in the screenshots, help who can, Reinstalled the discord and BD, did not help
screenshots: https://imgur.com/a/DCgkIFu
[https://imgur.com/a/DCgkIFu](url)

### Expected Behavior

It should be correct

### Steps To Reproduce

1. I went into discordant 
2. I go into chat
3. like this

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.4

**Comment by korzxcc** [comment]
[fowlis](https://fasthub.cc/fowlis) no, I use different topics, others too, the same, even worse, sometimes it does not load at all

**Comment by fowlis** [comment]
It's still an issue with the themes. Discord updated some classes recently which is causing this.

**Comment by korzxcc** [comment]
[fowlis](https://fasthub.cc/fowlis) I think so, after the update everything happened, but I don't know how to fix it, either through css
