### ISSUE TITLE
[Bug] AppImage installation fails.

### ISSUE THREAD

**Issue by rokejulianlockhart** [BetterDiscord/BetterDiscord#1528]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Installation fails at ![this stage.](https://user-images.githubusercontent.com/42837531/217392850-7ea0abee-a625-4b18-a4b0-511a586a22f8.png) It appears to hang.

### Expected Behavior

BetterDiscord should install.

### Steps To Reproduce

1. Download the AppImage.
2. Invoke the AppImage.

### Operating System

Linux

### Discord Version

Stable

### BetterDiscord Version

null

**Comment by bryant-the-coder** [comment]
facing this issue as well

**Comment by rauenzi** [comment]
duplicate of https://github.com/BetterDiscord/Installer/issues/323

**Comment by rokejulianlockhart** [comment]
@rauenzi, https://github.com/BetterDiscord/Installer/issues/226, really.

**Comment by rauenzi** [comment]
This was a completely unnecessary mention and comment, thanks.
