### ISSUE TITLE
[Bug] Discord Crashing by open Settings

### ISSUE THREAD

**Issue by LopeKinz** [BetterDiscord/BetterDiscord#1529]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

No Plugins or theme installed

### Expected Behavior

Open settings

### Steps To Reproduce

1.Open Settings in Discord
2.Crash

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.4

### Anything else?

https://youtu.be/e9CvPZoDoTM

Workaround : Rightclick the settings

Error : 
```
dba4fb0b04a3f8198c97.js:152 TypeError: Cannot read property 'Header' of undefined
    at he.render (<anonymous>:4:119159)
    at Cs (71e2907e1982c4e4e19e.js:1623)
    at Rs (71e2907e1982c4e4e19e.js:1622)
    at yu (71e2907e1982c4e4e19e.js:1663)
    at Oc (71e2907e1982c4e4e19e.js:1655)
    at Ic (71e2907e1982c4e4e19e.js:1655)
    at hc (71e2907e1982c4e4e19e.js:1654)
    at ic (71e2907e1982c4e4e19e.js:1651)
    at oc (71e2907e1982c4e4e19e.js:1650)
    at g (71e2907e1982c4e4e19e.js:1772)
    at L (71e2907e1982c4e4e19e.js:1773)
    at t.exports (dba4fb0b04a3f8198c97.js:21)
    at g.<computed> (dba4fb0b04a3f8198c97.js:36)
    at Number.m (dba4fb0b04a3f8198c97.js:36)
    at MessagePort.b (dba4fb0b04a3f8198c97.js:36)

**Comment by Loatchi** [comment]
I get the same behavior on Linux (Gentoo Base System release 2.13).

**Comment by MrJuaumBR** [comment]
Same Problem, but if you press Control + R it resolve(Press until it work)

**Comment by russo-2025** [comment]
I have the same problem (Windows)

**Comment by iqnite** [comment]
Same on Windows

**Comment by xkieras** [comment]
Same problem on Windows

**Comment by KanenaJP** [comment]
Same problem Win10 64x

**Comment by MrEvilOnGitHub** [comment]
Fedora 37, same problem here too. Can also confirm that reloading the window in place (Ctrl+R) provides a temporary solution

**Comment by aVitomin** [comment]
same 
win10

**Comment by Pilogoude** [comment]
I don't know how, but the fact that the ctrl + r solution works disappoints me. Maybe because it didn't help me to understand the source of the problem and because I'm afraid the bug will happen again, I guess :l

**Comment by LopeKinz** [comment]
> I don't know how, but the fact that the ctrl + r solution works disappoints me. Maybe because it didn't help me to understand the source of the problem and because I'm afraid the bug will happen again, I guess :l

The Problem is that some Components of the CSS Layout are not found/Loaded. So it crashes. But ctrl+r maybe loads those missing components

**Comment by yoaki-code** [comment]
same problem on windows 10

**Comment by enigmapr0ject** [comment]
Same problem here on W11 Pro. VCs also seem to be busted in this bug, the green ring around speaking users does not seem to be updating at all and voice transmission doesn't work, despite being able to hear everyone else.

**Comment by Kostasopro1** [comment]
I get this too on stable release of discord. But I dont get with latest release of discord ptb. I have Windows 10 64bit

**Comment by kazuviking2** [comment]
If i'm in a voicecall for longer than 10min and click the settings it crashes, after that if i wanna join any voice channel it gives me RTC connecting till i switch the audio mode. If discord crashes via the settings then its gonna crash infinitely if i press the settings till i press ctrl+r.

**Comment by Tim-Odermatt** [comment]
Same when it asks me to update a Plugin (it drags me in to the plugin/Settings screen)

**Comment by iamfvllout** [comment]
same on win 11, just installed today, stable last discord, last better discord ver.

**Comment by ElTioRata** [comment]
> RTC

I'm having the same issue with the RTC thing. What do you mean by "audio mode"? Where's that option?

**Comment by kazuviking2** [comment]
> I'm having the same issue with the RTC thing. What do you mean by "audio mode"? Where's that option?
Settings > Voice & Video > Scroll down > Audio Subsystem > And just witch between normal and experimental.

**Comment by Furdox** [comment]
Getting the same bug too, I have to use web Discord for now. Win10 64-bit x64 22h2 on high-end hardware.

**Comment by vperpl** [comment]
a9b168fe85091eaa359c.js:152 TypeError: Cannot read property 'Header' of undefined
    at he.render (<anonymous>:4:119159)
    at Cs (3b4371c2a53c83d58eb5.js:1623)
    at Rs (3b4371c2a53c83d58eb5.js:1622)
    at yu (3b4371c2a53c83d58eb5.js:1663)
    at Oc (3b4371c2a53c83d58eb5.js:1655)
    at Ic (3b4371c2a53c83d58eb5.js:1655)
    at hc (3b4371c2a53c83d58eb5.js:1654)
    at ic (3b4371c2a53c83d58eb5.js:1651)
    at oc (3b4371c2a53c83d58eb5.js:1650)
    at g (3b4371c2a53c83d58eb5.js:1772)
    at L (3b4371c2a53c83d58eb5.js:1773)
    at t.exports (a9b168fe85091eaa359c.js:21)
    at g.<computed> (a9b168fe85091eaa359c.js:36)
    at Number.m (a9b168fe85091eaa359c.js:36)
    at MessagePort.b (a9b168fe85091eaa359c.js:36)

**Comment by Strencher** [comment]
I've submitted #1530 to fix this issue! Please be patient.

**Comment by Gamer08YT** [comment]
Same issue, Press Control + R to solve it.

**Comment by Leah96xxx** [comment]
> Same issue, Press Control + R to solve it.

Ctrl+R doesn't resolve it. The error will appear again the next time you try to open settings.

**Comment by vperpl** [comment]
spamming ctrl + r helps sometimes

**Comment by GraTooY** [comment]
Win 11 - Betterdiscord app 1.8.4 - Latest Stable Discord vers.
Issue : Without any plugin or theme, Discord **crashes as soon as I press the settings button**

Exactly the same problem.
