### ISSUE TITLE
[Bug] BetterDiscord Installer stops when trying to kill discord.

### ISSUE THREAD

**Issue by Prospy006** [BetterDiscord/BetterDiscord#1531]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Better Discord Installer stops when trying to kill discord.

### Expected Behavior

Every time I try and install BD for Discord, it stops when trying to kill discord. I have been waiting in this menu for over like, an hour. And I have also tried to close discord or open it before it installs, and it doesn't change anything.
![image](https://user-images.githubusercontent.com/74852993/219872051-f13442bd-af50-4910-9bfa-53b8e817bb77.png)

### Steps To Reproduce

1. Click install
2. Lag for a short bit
3. Get stuck in the attempting to kill discord screen

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.4

### Anything else?

Starting Install...

Creating required directories...
✅ Directory exists: C:\Users\prosp\AppData\Roaming\BetterDiscord
✅ Directory exists: C:\Users\prosp\AppData\Roaming\BetterDiscord\data
✅ Directory exists: C:\Users\prosp\AppData\Roaming\BetterDiscord\themes
✅ Directory exists: C:\Users\prosp\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
✅ Package downloaded

Injecting shims...
Injecting into: C:\Users\prosp\AppData\Local\Discord\app-1.0.9011\modules\discord_desktop_core-1\discord_desktop_core
✅ Injection successful
✅ Shims injected

Restarting Discord...
Attempting to kill Discord

**Comment by maenDisease** [comment]
Make sure there are no Discord processes running in task manager and in the details tab, if issue persists, try keeping the installer open where it says attempting to kill discord, then without closing the installer, restart pc.

**Comment by bryant-the-coder** [comment]
> Make sure there are no Discord processes running in task manager and in the details tab, if issue persists, try keeping the installer open where it says attempting to kill discord, then without closing the installer, restart pc.

mine just stuck at downloading asar file. what should i do?

**Comment by rauenzi** [comment]
If this is windows 7 just kill it yourself, the install itself is fine.

**Comment by Paft** [comment]
What was this closed? I'm on Win 11 and have had this issue for what feels like a year. I have to keep installing 1.1.1.
