### ISSUE TITLE
[Bug] Random Crash of BD while active plugins

### ISSUE THREAD

**Issue by DarkNachtara** [BetterDiscord/BetterDiscord#1532]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

BD crashes if any plug-in is loaded

Discord Version Stable 175517

### Expected Behavior

Running Plugins as it should

### Steps To Reproduce

1. activate Plug-in (any)
2. after 30 Sek - 1 Min crashes 
3. Restarts Discord
4. no Plug-in loaded 

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.8.4

**Comment by maenDisease** [comment]
Join the [support server](https://discord.com/invite/0Tmfo5ZbORCRqbAd) so we can debug this further
