### ISSUE TITLE
[Bug] Loops crash plugins

### ISSUE THREAD

**Issue by AstraxVZ** [BetterDiscord/BetterDiscord#1533]
### Before Reporting

- [X] I found no existing issues matching my bug
- [ ] My issue is not caused by a plugin or theme

### Describe the Bug

When I finished creating my plugin, I tried to start it, but it gave me error "DiscoParty could not be started." (DiscoParty is the plugin name). Are endless loops inside of plugin scripts not supported? When I remove the loop, it just gets fixed. Since that is caused by a endless loop, is there any way to fix this? Here is a screenshot: 

![issuescreenshot](https://user-images.githubusercontent.com/91541572/219964234-145c21f0-494d-4c1a-bde5-6d601cb3bbd1.png)

**I appreciate every answer on this issue!**

### Expected Behavior

I expected the plugin to start and work without any errors.

### Steps To Reproduce

1. Make a plugin script that has a loop inside of it (doesn't matter if it is the same as in the picture above, it just has to be endless)
2. Open Discord with BetterDiscord installed
3. Enable that plugin
4. You will get a error that the plugin could not be started

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.4

**Comment by rauenzi** [comment]
Can you show the whole plugin? Or check console for errors?

**Comment by realfaceitkantesilvestrs** [comment]
Have you considered that `arguments` is not allowed under strict mode?
