### ISSUE TITLE
[Bug] Opening the settings causes the "Well, This is awkward" crash screen to appear.

### ISSUE THREAD

**Issue by brunorurz** [BetterDiscord/BetterDiscord#1535]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Just like the name suggests, as soon as I try to open the settings in Discord, the screen appears and forces Discord do refresh. I've tried unmounting any plugins or themes I had, and even tried to reinstall BetterDiscord outright to no effect. The recent update to that updated the image and video preview in chat may be the cause. I'm attaching a screenshot of said screen.
![bugscreen](https://user-images.githubusercontent.com/71721681/220761871-d1c68ec1-3bea-421b-9ae1-042a078e1d55.png)
Sorry for the different language, but I'm not bothered to uninstall BetterDiscord to switch it and install it again just to reproduce the bug.

### Expected Behavior

The Discord settings are normally expected to open no problem.

### Steps To Reproduce

1. Just try and open the settings with BetterDiscord installed.

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.4

**Comment by maenDisease** [comment]
Duplicate of #1529

**Comment by Skip75** [comment]
A fix has been merged (https://github.com/BetterDiscord/BetterDiscord/pull/1530)
but the new .exe installer is still not released.

**Comment by brunorurz** [comment]
Well, good. I guess that's solved then. Now we just have to wait for the new version. Thanks.

**Comment by fowlis** [comment]
> A fix has been merged (https://github.com/BetterDiscord/BetterDiscord/pull/1530)
> but the new .exe installer is still not released.

A new installer for every BD release is unnecessary, the installer will download the latest release

**Comment by JourneyOver** [comment]
@fowlis other than the fact that even with a brand new install of BD this is still happening, so I think we will need a new installer, or the installer just isn't picking up the latest changes still.

**Comment by Aloncheeto** [comment]
same issue for me here.

**Comment by JourneyOver** [comment]
The only way I found to fix the issue currently is to grab the `betterdiscord.asar` from the betterdiscord discord server under known issues crash tracker channel.. once I started using that instead of the one from the installer the crashes stopped when going into the settings menu.

**Comment by marcussacana** [comment]
> The only way I found to fix the issue currently is to grab the `betterdiscord.asar` from the betterdiscord discord server under known issues crash tracker channel.. once I started using that instead of the one from the installer the crashes stopped when going into the settings menu.

or if you arent in the server, download from GH Actions, like this one https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389
move to C:\Users\YOU\AppData\Roaming\BetterDiscord\data

**Comment by brunorurz** [comment]
Hey, that seems to have fixed it for now. Thanks to everyone who helped.

**Comment by framkie101** [comment]
Wait what?
How do I download that?

**Comment by JourneyOver** [comment]
> or if you arent in the server, download from GH Actions, like this one [BetterDiscord/BetterDiscord/actions/runs/4290243389](https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389) move to C:\Users\YOU\AppData\Roaming\BetterDiscord\data

yep this one should work as well, wasn't available at the time of my writing so I couldn't make mention of the github action one.
