### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by VEERT00X** [BetterDiscord/BetterDiscord#1538]
### Before Reporting

- [x] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

After exiting **DiscordCanary** from **system tray** **DiscordCanary** will try to update next time its open and will delete the **BetterDiscord** Injection.

### Expected Behavior

**BetterDiscord** should remain installed and working even afrer rebooting **DiscordCanary**.

### Steps To Reproduce

1. Open **DiscordCanary** with **BetterDiscord** Installed.
2. Exit **DiscordCanary** from **system tray**.
3. Open **DiscordCanary** again.
4. **DiscordCannary** will update automatically and **BetterDiscord** Injection will be removed.

### Operating System

Windows

### Discord Version

Canary

### BetterDiscord Version

v1.8.4

**Comment by maenDisease** [comment]
Discord Canary updates constantly, refreshing its Discord files, use Discord PTB or Stable if you don't want to constantly reinstall BD

**Comment by willybobbyidkbro** [comment]
i need help when i try to install it, it keeps saying ✅ Discord not running
✅ Discord restarted

**Comment by VEERT00X** [comment]
> Discord Canary updates constantly, refreshing its Discord files, use Discord PTB or Stable if you don't want to constantly reinstall BD

Well that was not always the case at least i think so. Over a year ago there were no problems like this even when i used Canary.

**Comment by maenDisease** [comment]
> > Discord Canary updates constantly, refreshing its Discord files, use Discord PTB or Stable if you don't want to constantly reinstall BD
> 
> Well that was not always the case at least i think so. Over a year ago there were no problems like this even when i used Canary.

There has been major client updates since then.

**Comment by VEERT00X** [comment]
> > > Discord Canary updates constantly, refreshing its Discord files, use Discord PTB or Stable if you don't want to constantly reinstall BD
> > 
> > 
> > Well that was not always the case at least i think so. Over a year ago there were no problems like this even when i used Canary.
> 
> There has been major client updates since then.

Well if thats the case @willybobbyidkbro Still has a problem.

**Comment by VEERT00X** [comment]
I was able to resolve the problem, and I recommend that anyone facing a similar issue should completely delete and reinstall DiscordCanary. This solution worked for me, but if the problem persists, it is recommended to install BetterDiscord on the stable or PTB version, as suggested by @maenDisease comment.

@willybobbyidkbro , your error is unrelated to this issue, so please create a separate one.

**This marks the issue as resolved.**
