### ISSUE TITLE
BetterDiscord Crashing

### ISSUE THREAD

**Issue by mei1012** [BetterDiscord/BetterDiscord#1539]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

BetterDiscord keeps crashing.

Whenever I open Discord it crashes.

I have tried repairing and uninstalling and reinstalling it,

### Expected Behavior

Discord will open normaly

### Steps To Reproduce

1. Open Discord
2. Crash?

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.4

### Anything else?

For a short term fix simply uninstall it

**Comment by xray-tango** [comment]
The exact same thing is happening just here now. I backed up and deleted my plugins and themes folder yet discord is still crashing.
I'm using a fully synced Arch Linux system and the stable version of discord with the most up do date betterdiscord version (freshly installed).

**Comment by hcube7** [comment]
Same issue! Stable version of Discord, fresh install of BetterDiscord, and MacOS Ventura 13.2.1.

**Comment by SparkieFloof** [comment]
same issue here with me too, found removing plugins seem to let it load but pressing settings will then crash Discord

**Comment by ItMeSarah** [comment]
Known issue, a fix is being worked on. Check the BetterDiscord discord  Known Issues/Crash Tracker support post for more information.

**Comment by RagingEnby** [comment]
Same issue

**Comment by JoshHarris4** [comment]
same issue

**Comment by KaoticOblivion** [comment]
Same issue, also tried same steps

**Comment by SploeCyber** [comment]
same

**Comment by ToxicSmurf** [comment]
> Known issue, a fix is being worked on. Check the BetterDiscord discord Known Issues/Crash Tracker post for more information.

sorry I'm not smart, where do I find this?

**Comment by Technetium1** [comment]
@ToxicSmurf [Here's an invite](https://discord.gg/0Tmfo5ZbORCRqbAd), look in the `Support` forum.

**Comment by Freakidann** [comment]
• For Fix Issue Go Into C:AppData\Roaming\BetterDiscord\data\stable
Open plugins
and You must always put on True and disable the plugin one by one and reload better discord with each modification!

LOOK MY VIDEO TUTO
https://ZmeiNoch.is-cute-af.xyz/‍‍ඞ​ඞ​ඞ‍‍​​‍‍‍‍ඞ‍​ඞ​​ඞඞ​‍‍ඞ​‍‍ඞඞඞඞ‍​ඞඞ‍‍

**Comment by Aholicknight** [comment]
> • For Fix Issue Go Into C:AppData\Roaming\BetterDiscord\data\stable Open plugins and You must always put on True and disable the plugin one by one and reload better discord with each modification!
> 

@Freakidann this does not work.

**Comment by Freakidann** [comment]
I managed to find out that the plugin was crashing, since it works better, the best thing is to wait for the Better Discord update, this solves a lot of problems.

**Comment by Freakidann** [comment]
I managed to find out that the plugin was crashing, since it works better, the best thing is to wait for the Better Discord update, this solves a lot of problems.

**Comment by Freakidann** [comment]
**_BETTER DISCORD CRASH ?_**
**_TEST THIS !_**

- [ ] 1. Close BetterDiscord by clicking on the "Exit" button in the system tray icon's context menu. 

- [ ] 2. Open the Task Manager by pressing CTRL+ALT+Del simultaneously and select "Task Manager" in the context menu. 

- [ ] 3. Locate BetterDiscord in the list of processes and click "End Process" to fully close it. 

- [ ] 4. Restart the computer.

- [ ] 5. Once the operating system has restarted, try to open BetterDiscord again.

_⚜️ Freakidann#5818⚜️__

**Comment by rauenzi** [comment]
This has been fixed in the latest release
