### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Gamer08YT** [BetterDiscord/BetterDiscord#1541]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Discord is crashing after the Last Update when you start it,
It's crashing before i can do anything...

![image](https://user-images.githubusercontent.com/31771657/221766523-7588157d-04ea-41db-aec0-f8580c38ca0b.png)

Reloads or Restarts not helping me out!

### Expected Behavior

Just open Discord with the latest Discord Version.

### Steps To Reproduce

1. Start Discord

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

Can't see it

**Comment by vincentwang0905** [comment]
https://github.com/BetterDiscord/BetterDiscord/issues/1540

**Comment by Gamer08YT** [comment]
> #1540

As i said, not when entering Settings...

It appears when you start Discord!!

**Comment by burcuberk** [comment]
Same

**Comment by rauenzi** [comment]
This has been fixed in the latest release
