### ISSUE TITLE
[Bug] Crashes

### ISSUE THREAD

**Issue by RexQueenston** [BetterDiscord/BetterDiscord#1543]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Discord crashes whenever I open settings.
Sometimes it opens even when discord is opening without being able to do anything.

### Expected Behavior

Settings should open normally

### Steps To Reproduce

Open discord.
Click on the settings button or do it with the keyboard shortcut.

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.8.4

**Comment by rauenzi** [comment]
This has been fixed in the latest release
