### ISSUE TITLE
[Bug] Discord crash on startup

### ISSUE THREAD

**Issue by crummei** [BetterDiscord/BetterDiscord#1544]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

I start up discord and it immediately crashes, I've tried removing literally every file and folder from my plugins folder and it still doesn't do anything, I've repaired BD and reinstalled multiple times.

### Expected Behavior

1. Open discord
2. Use discord

### Steps To Reproduce

1. Turn on pc
2. Discord opens automatically
3. Disappointment![image](https://user-images.githubusercontent.com/56043602/221805641-7782c389-997c-4804-aa02-7ec1c1424a48.png)

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

Idk, latest version. I can't go in settings

**Comment by KungFoodPanda** [comment]
Same

**Comment by ItsNekoRx28** [comment]
Same

**Comment by bakanayasai** [comment]
https://github.com/BetterDiscord/BetterDiscord/suites/11245321973/artifacts/575964235
replace this file in>  C:\Users\User\AppData\Roaming\BetterDiscord\data

**Comment by crummei** [comment]
> https://github.com/BetterDiscord/BetterDiscord/suites/11245321973/artifacts/575964235 replace this file in> C:\Users\User\AppData\Roaming\BetterDiscord\data

It worked! Thank you.

**Comment by m0ncHyyy** [comment]
> https://github.com/BetterDiscord/BetterDiscord/suites/11245321973/artifacts/575964235 replace this file in> C:\Users\User\AppData\Roaming\BetterDiscord\data

eror 404, can u send again ?

**Comment by crummo1** [comment]
had this exact same issue, could you show me what file to replace pls?

**Comment by McDonaldsJFK** [comment]
it says that

> https://github.com/BetterDiscord/BetterDiscord/suites/11245321973/artifacts/575964235 replace this file in> C:\Users\User\AppData\Roaming\BetterDiscord\data

the link isnt usable anymore, can u replace the link?
