### ISSUE TITLE
[Bug] BetterDiscord keeps crashing randomly

### ISSUE THREAD

**Issue by DabMK** [BetterDiscord/BetterDiscord#1546]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

BetterDiscord randomly crashes very often after the last update

Error in the console:
`Error: Menu API only allows Items and groups of Items as children. Received [object Object] (object) instead
    at 288aa17d3bf2f0a3351d.js:2748
    at Array.reduce (<anonymous>)
    at qr (288aa17d3bf2f0a3351d.js:2747)
    at 288aa17d3bf2f0a3351d.js:2747
    at Array.reduce (<anonymous>)
    at qr (288aa17d3bf2f0a3351d.js:2747)
    at Jr (288aa17d3bf2f0a3351d.js:2750)
    at Sa (288aa17d3bf2f0a3351d.js:1608)
    at yu (288aa17d3bf2f0a3351d.js:1662)
    at Oc (288aa17d3bf2f0a3351d.js:1655)
    at Ic (288aa17d3bf2f0a3351d.js:1655)
    at hc (288aa17d3bf2f0a3351d.js:1654)
    at ic (288aa17d3bf2f0a3351d.js:1651)
    at oc (288aa17d3bf2f0a3351d.js:1650)
    at g (288aa17d3bf2f0a3351d.js:1772)
    at L (288aa17d3bf2f0a3351d.js:1773)
    at t.exports (ff334c0250254fc1c9ca.js:21)
    at g.<computed> (ff334c0250254fc1c9ca.js:36)
    at Number.m (ff334c0250254fc1c9ca.js:36)
    at MessagePort.b (ff334c0250254fc1c9ca.js:36)`

I have no themes and no plugins
I alredy have the new asar file that should fix it, but it doesn't
(https://cdn.discordapp.com/attachments/826217269323235358/1079920833662816277/betterdiscord.asar)
(https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389)

### Expected Behavior

BetterDiscord shouldn't crash

### Steps To Reproduce

1. Open BetterDiscord
2. Interact with the application in any way or just wait a bit

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

Core v1.8.4

### Anything else?

Settings button just moved behind deafen button (I can still click it tho)

**Comment by DabMK** [comment]
Turned out I had to reinstall BetterDiscord, but the settings button is still stuck behind the other one

**Comment by p0s0** [comment]
I'm having the same issue, however sometimes I do not receive messages from group chats or DMs until I restart Discord. Sometimes, messages and group chats don't load at all.

**Comment by tilsgee** [comment]
same

![image](https://user-images.githubusercontent.com/62179071/221881449-977cb2b4-213b-416f-a5ae-3b1ab4d81e28.png)

**Comment by FoxoBread** [comment]
Trying to open settings or update plugins causes a crash for me too.

**Comment by ForBai** [comment]
same for me

**Comment by Zeroaim-exe** [comment]
same for me aswell

**Comment by Willvern** [comment]
Same for me 
![image](https://user-images.githubusercontent.com/32403341/221891600-b21fc219-38e2-47a7-ba4a-f493b654de76.png)

**Comment by DeathGod2k1** [comment]
Same problem, using discord on Arch Linux with the updated asar

**Comment by TheAnnoyingRat62** [comment]
Im having the same issues.

**Comment by Taupe** [comment]
Same problem

**Comment by Suprcheese** [comment]
I'm experiencing this same issue as well.

**Comment by Aida-Enna** [comment]
> Trying to open settings or update plugins causes a crash for me too.

This issue has been resolved. The installer doesn't seem to download the latest version of BD yet, but you can install the fix manually.

Here's how to install the fix manually:
1) Close Discord and head to https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389
2) Download the [betterdiscord.asar](https://github.com/BetterDiscord/BetterDiscord/suites/11245321973/artifacts/575964235) (which will be a zip)
3) Extract it to ``%appdata%\BetterDiscord\data`` (``C:\Users\YOU\AppData\Roaming\BetterDiscord\data``), overwriting the previous one
4) Re-open Discord

**Comment by Ireheart** [comment]
> 

This works

**Comment by Taupe** [comment]
Works for me too

**Comment by rauenzi** [comment]
This has been fixed in the latest release
