### ISSUE TITLE
[Bug]#1549

### ISSUE THREAD

**Issue by Enkovich** [BetterDiscord/BetterDiscord#1549]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Better Discord crashes when opening settings

### Expected Behavior

I open Better Discord, click on the settings icon and Better Discord crashes

### Steps To Reproduce

1. Run Discord
2. Select settings

### Operating System

Linux

### Discord Version

Stable

### BetterDiscord Version

latest

**Comment by lukas5450** [comment]
same

**Comment by Blekke2801** [comment]
same, i tried the old fix (ctrl + r) but it doesn't work

**Comment by Aida-Enna** [comment]
This issue has been resolved. The installer doesn't seem to download the latest version of BD yet, but you can install the fix manually.

Here's how to install the fix manually:
1) Close Discord and head to https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389
2) Download the [betterdiscord.asar](https://github.com/BetterDiscord/BetterDiscord/suites/11245321973/artifacts/575964235) (which will be a zip)
3) Extract it to ``%appdata%\BetterDiscord\data`` (``C:\Users\YOU\AppData\Roaming\BetterDiscord\data``), overwriting the previous one
4) Re-open Discord

**Comment by CMNDRGreyFox** [comment]
> This issue has been resolved. The installer doesn't seem to download the latest version of BD yet, but you can install the fix manually.
> 
> Here's how to install the fix manually:
> 
> 1. Close Discord and head to https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389
> 2. Download the [betterdiscord.asar](https://github.com/BetterDiscord/BetterDiscord/suites/11245321973/artifacts/575964235) (which will be a zip)
> 3. Extract it to `%appdata%\BetterDiscord\data` (`C:\Users\YOU\AppData\Roaming\BetterDiscord\data`), overwriting the previous one
> 4. Re-open Discord

doing this does nothing for me

**Comment by Powershard** [comment]
Fixed for me, I guess GreyFox has an user error.

**Comment by Enkovich** [comment]
Thanks. Fixed for me

**Comment by canerolu2019** [comment]
> 

Does the plugins work again? Have you tested it?

**Comment by canerolu2019** [comment]
> This issue has been resolved. The installer doesn't seem to download the latest version of BD yet, but you can install the fix manually.
> 
> Here's how to install the fix manually:
> 
> 1. Close Discord and head to https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389
> 2. Download the [betterdiscord.asar](https://github.com/BetterDiscord/BetterDiscord/suites/11245321973/artifacts/575964235) (which will be a zip)
> 3. Extract it to `%appdata%\BetterDiscord\data` (`C:\Users\YOU\AppData\Roaming\BetterDiscord\data`), overwriting the previous one
> 4. Re-open Discord


Does the plugins work again? Have you tested it?

**Comment by MrJuaumBR** [comment]
> This issue has been resolved. The installer doesn't seem to download the latest version of BD yet, but you can install the fix manually.
> 
> Here's how to install the fix manually:
> 
> 1. Close Discord and head to https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389
> 2. Download the [betterdiscord.asar](https://github.com/BetterDiscord/BetterDiscord/suites/11245321973/artifacts/575964235) (which will be a zip)
> 3. Extract it to `%appdata%\BetterDiscord\data` (`C:\Users\YOU\AppData\Roaming\BetterDiscord\data`), overwriting the previous one
> 4. Re-open Discord

**YOU NEED TO HAVE BETTERDISCORD INSTALLED! CLOSE DISCORD, AND RE-OPEN!**

That's worked.
