### ISSUE TITLE
Crash when opening settings menu[Bug]

### ISSUE THREAD

**Issue by BlueColorsin** [BetterDiscord/BetterDiscord#1551]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When I open the settings menu it crashes 
Got this bug on both normal and canary 

### Expected Behavior

I wanted to open the settings menu to edit my plugins 

### Steps To Reproduce

1. install BetterDiscord
2. open settings 
3. crash

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.4

### Anything else?

Windows 11 btw 
![DiscordCanary_QUvY2fkpA1](https://user-images.githubusercontent.com/76269429/222117546-b018a010-7eac-4e50-8a05-704a2f235819.gif)

**Comment by Fris44** [comment]
Duplicate of #1540

**Comment by danbopes** [comment]
So much for "I found no existing issues matching my bug"

**Comment by Raltyro** [comment]
@BlueColorsin Try the actions build and see if that works for you

**Comment by BlueColorsin** [comment]
Whoops I missed that lmao 
Closing it now 

for anyone else having this problem 
-> https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389

**Comment by Den104Ten** [comment]
I have the same problem. And i have spend 30 min to fix it. So guys you need to press win + r. Copy this: %appdata%/betterdiscord/data and go to it. After it delete file with name as betterdiscord.asar and go to this link https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389, where you need to download file betterdiscord.asar. Then copy it and paste in folder, when you have just delete the file with same name betterdiscord.asar
Hope it's help you to fix this bug.
