### ISSUE TITLE
[Bug] Messages not showing

### ISSUE THREAD

**Issue by bob-carter** [BetterDiscord/BetterDiscord#1554]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

For some reason in one of my servers in general chat it says I have a new message unseen, but when I click on it the notification doesn't go away, and it doesn't show me the new messages till I control + R, restarting the client.

### Expected Behavior

When I click on a channel on a server I expect to see my new messages in a channel, and for the notification to go away once I see them.

### Steps To Reproduce

Fresh install
No modifications
Run program from clean boot
Randomly takes effect with some channels on servers.

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.4

### Anything else?

I am using the fix mentioned in the discord server for the settings crash.

**Comment by AztralMenu** [comment]
This same issue is happening for me in DM's only haven't had issues with servers as of yet! so i feel your pain!

**Comment by elijaholmos** [comment]
I've had this issue on my client as well; couldn't consistently reproduce it, though. Viewing the channel or DM that shows unread notifs on a separate platform (my mobile device or web browser) properly displays the messages.

**Comment by Gegahex** [comment]
I'm having the same issue

**Comment by PFNB** [comment]
been having the same issue for about a week

**Comment by AztralMenu** [comment]
after a day of using vanilla discord with no BD i have concluded that the msg issue is strictly only with better discord ( on BD it will notify you of the notification but when clicking on it the conversation loads but never sends any new msgs also never updates for any new msgs until you control R) on vanilla discord this does NOT happen at all the issue is always preset there isnt any ways to reproduce because it simply does it all the time for new msgs you have to constant press CTRL R but no matter what you still cant send msgs,

**Comment by bryant-the-coder** [comment]
facing this issue after the new discord update.

**Comment by Mylloon** [comment]
this also prevents sending message in a channel

**Comment by rauenzi** [comment]
I've never experienced this issue personally and it doesn't really make sense. I have seen vanilla Discord do the ghost notification issue.

**Comment by amazman** [comment]
currently having the same issue to

**Comment by Arkteus** [comment]
I also had the same problem when this issue was created, I uninstalled better discord temporarily and reinstalled it today and I still have the same problem.
Hope you will find the problem.
Thank you to all the team for this great project!

**Comment by rauenzi** [comment]
As of yet I've still been unable to reproduce.

**Comment by rauenzi** [comment]
If anyone is still experiencing this, please comment and let us know if there's a pattern as to when this occurs, and what plugins you or themes you have installed.
