### ISSUE TITLE
[Bug] BD gives an error when opening the settings

### ISSUE THREAD

**Issue by IlyStra** [BetterDiscord/BetterDiscord#1555]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug
After updating Discord and Better Discord the application gives an error when opening the settings, and all plugins do not work.
After breaking Discord's auto-update, I repaired BD through a new version of the installer.

_(DS and BD update date: **`01.03.2023`**)_

### Expected Behavior

I don't know what else to say, there are no logs

### Steps To Reproduce

**1:** _Update discord_
**2:** _Repair Better discord_
**3:** _Open Better discord_
**4:** _Open Settings_
**5:** _Look at this_
![image](https://user-images.githubusercontent.com/105174554/222252486-e1e5b60d-d490-459c-b1d9-d16828e90e46.png)

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.8.4

**Comment by NaghDiefalla** [comment]
Same Issue

**Comment by OkffPls** [comment]
same error

**Comment by RDJ79** [comment]
yea i have that issue too

**Comment by Aida-Enna** [comment]
https://github.com/BetterDiscord/BetterDiscord/issues/1548#issuecomment-1448743598
