### ISSUE TITLE
[PSA] Messages not showing? Discord crashing at settings or when you right click? Check here first!

### ISSUE THREAD

**Issue by Aida-Enna** [BetterDiscord/BetterDiscord#1556]
### Current known issues with BD

1) When you load a channel with certain plugins that modify/read/manage/mess with messages, it can crash. It can also prevent the messages from showing and prevent you from sending/receiving messages in certain channels. Restarting discord will put it in a loop of loading the channel -> crashing over and over. Rename the plugins folder, start discord again, and slowly add in plugins, enabling each one until it crashes again. That's your problematic one.

2) When you click the settings button, BD crashes. The fix for it isn't available in the distributed build yet, but you can fix it yourself via https://github.com/BetterDiscord/BetterDiscord/issues/1546#issuecomment-1448904244 (as shiseni referenced above)

3) Crashing when right clicking - This is typically caused by plugins that add their own menus/items to the right click context menu. You can identify these in the same way as the first one. Rename the plugins folder, start discord again, and slowly add in plugins, enabling each one until right clicking on the item crashes again. That's your problematic one.

I've made this in hopes that we can alleviate the repeated process of people making threads about it, closing it, then someone making a new one 5 minutes later. If that's not something the BD team wants, you can close this issue and I'll just keep posting on new ones instead of making a issue like this. 🙏

**Comment by rauenzi** [comment]
Sorry but things like this do not actually help, users don't read existing issues.

**Comment by RODIOMG7** [comment]
ok im going to try that
