### ISSUE TITLE
[Feature] 'Save' button in plugin list to load selected plugins

### ISSUE THREAD

**Issue by haemtim** [BetterDiscord/BetterDiscord#1558]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

In Settings > Betterdiscord > Plugins, it would be great to to first switch the plugins on, and then load them all at the end, using a 'save' button for example. Some plugins refresh the GUI, witch resets the plugin list as well. If you have a lot of plugins, this is really annoying, as you have to scroll down to where you just were a lot.

**Comment by rauenzi** [comment]
> Some plugins refresh the GUI, witch resets the plugin list as well.

If plugins are refreshing the entire UI, this is a bug with the plugin. Please report them to the plugin developer.

This feature will not be added.
