### ISSUE TITLE
[Bug] User Settings Menu crashes every time

### ISSUE THREAD

**Issue by thatjamesemo** [BetterDiscord/BetterDiscord#1559]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When getting a notification from Better Discord for a plugin update, or you simply try to access any settings, the client will crash, and you will have to reload.

### Expected Behavior

The expected behavior would be that you could easily access and use the menu, without any crashing of the entire client.

### Steps To Reproduce

1. Standard BetterDiscord installation, on a Windows Machine
2. Click on any notification from BetterDiscord or open the settings gear on the user profile section.
3. The client will crash, with no obvious error code for the user to report with.

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.5

### Anything else?

This issue has only started for me today, when it alerted me to this update. Not sure if this correlates to the 27th Feb Crash reports, however still without any plugins or modifications, other than the usual BetterDiscord, the issues still arise.

**Comment by thatjamesemo** [comment]
> Yeah, manually installing new update does the trick

Thank you, were you able to retain any information after the update or did you have to manually remove all plugin and data files from all BetterDiscord AppData folder?

**Comment by sf-knight** [comment]
> > Yeah, manually installing new update does the trick
> 
> Thank you, were you able to retain any information after the update or did you have to manually remove all plugin and data files from all BetterDiscord AppData folder?

I just downloaded the latest betterdiscord installer off the site and installed it again, still kept all my plugins and themes, just newest update

**Comment by thatjamesemo** [comment]
Okay, thank you!
**Fix:**
1. Reinstall BD from the latest installer.
2. If you face any more issues, seek further support.

**Comment by PFNB** [comment]
fix does not work
