### ISSUE TITLE
[Bug] My Discord crashes when I try to view some servers.

### ISSUE THREAD

**Issue by BlackLightX** [BetterDiscord/BetterDiscord#1564]
### Before Reporting

- [X] I found no existing issues matching my bug
- [ ] My issue is not caused by a plugin or theme

### Describe the Bug

Not on every server. It only happens on some servers. When I want to view that server, Discord suddenly crashes. 

### Expected Behavior

I need to be able to view the server without any crashes.

### Steps To Reproduce

1. I'm starting the Discord.
2. I try to view the server where I had the crash.
3. My Discord crashes.

![Screenshot_1](https://user-images.githubusercontent.com/65299525/222894705-1002adab-894b-44f7-b830-da299ac15ea5.png)

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.5

### Anything else?

I mentioned that Discord crashes when I try to view some servers (1-2). When I try to restart Discord, I keep getting crashes because the server I'm experiencing crashes on remains open on the screen. Now I realized that when I restart Discord, I keep trying to view another server until I install the plugins (in short, I click with the mouse on any server I'm not experiencing crashes on). When I view that server, I don't get crashes, but if I try to view the servers where I get crashes again, my Discord crashes directly.

**Comment by maenDisease** [comment]
Does this issue happen with all plugins removed or disabled?

**Comment by rauenzi** [comment]
I've seen the error you've posted occur on vanilla Discord after some recent Discord changes

**Comment by LizardLiang** [comment]
I'm having this problem too, 
Discord crashed and ask me to reload when I was trying to open setting page or right click on any user
I've tried to removed all the plugins and themes I have 
But it does not work until I removed BetterDiscord from my discord

**Comment by rauenzi** [comment]
Is this still happening?

**Comment by LizardLiang** [comment]
The problem is no longer happening again, thanks

**Comment by CharlieEurope72** [comment]
I had this problem too, but I believe it was caused by plugins. I disabled some outdated plugins and the issue stopped happening for me.
