### ISSUE TITLE
Please make better discord for mobile 

### ISSUE THREAD

**Issue by lNethunter** [BetterDiscord/BetterDiscord#1567]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

It'll be so awesome, it'll be so cool

**Comment by fowlis** [comment]
Mobile support is unplanned since the desktop version and mobile version(s) of Discord are too different. 
There are plenty of client mods for mobile if you Google it.

**Comment by rauenzi** [comment]
> I don't think it would be too different

This is unfortunately not the case. We will not be making a mobile version.
