### ISSUE TITLE
[Bug]When discord opens ona  system startup better discord does not launch with it

### ISSUE THREAD

**Issue by KNS247** [BetterDiscord/BetterDiscord#1570]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

when I turn on my computer discord launches automatically, better discord does not launch and I have to reinstall better discord every time. 

### Expected Behavior

better discord shouldn't need to be installed everytime i launch my computer

### Steps To Reproduce

turn on computer
let discord open
done

### Operating System

Windows

### Discord Version

Canary

### BetterDiscord Version

v1.8.5

**Comment by maenDisease** [comment]
Duplicate of #1538
