### ISSUE TITLE
[Bug] An error occurs as soon as the discode is turned on. What should I do to come out normally?

### ISSUE THREAD

**Issue by SinQ0227** [BetterDiscord/BetterDiscord#1571]
### Before Reporting

- [X] I found no existing issues matching my bug
- [ ] My issue is not caused by a plugin or theme

### Describe the Bug

![image](https://user-images.githubusercontent.com/128206267/226085567-a720318b-2c30-4e5b-9f91-6280c91f3da9.png)

### Expected Behavior

There should be no errors such as the image.

### Steps To Reproduce

I tried to reinstall version 1.8.5 because I thought it would fix the problem, but it still gets a bug.

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.5

**Comment by asogamer** [comment]
Same problem here, but with a different image. Reloading doesn't work, because it shows the same error.
<img width="402" alt="betterdiscordcrash" src="https://user-images.githubusercontent.com/128856305/227643296-19dbcc92-8a97-4178-8e3d-a0b5849c7242.png">
The only way to make Discord work again is to uninstall BetterDiscord. Also I tried repairing but that didn't work either

**Comment by MrDuckz** [comment]
To me, the issue seems to be happening due to plugins, I tried moving plugins outside of the folder and it worked, but I want to use those plugins

**Comment by ScrubN** [comment]
Simply having plugins exist in the plugin folder seems to be the issue, even if all of said plugins are disabled. Here is what appears to be the associated error in the console:
![image](https://user-images.githubusercontent.com/72096833/227645027-a133d629-e371-45f1-bcf4-d1b8a2fb5b31.png)

**Comment by silversaturn** [comment]
I had the same issue I just ran the repair option on the appimage (linux) and the discord booted up fine after.

**Comment by Inve1951** [comment]
@SinQ0227 does this still happen after installing BD's v1.9.1?
If so we'll need more details: list of installed plugins, console logs.

**Comment by teddythinh** [comment]
I ran the repair option in the Windows installer, and now it works for me. I also enable plugins and themes, and everything worked fine with the latest versions of BD v1.9.1.

**Comment by Kathund** [comment]
@SinQ0227 are you still getting this issue
