### ISSUE TITLE
Cant write in channels[Bug]

### ISSUE THREAD

**Issue by Gaminguide1000** [BetterDiscord/BetterDiscord#1572]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

After starting Discord, when it openes in a certain channel (which only happens when it crashes), i cant write in it. Sometimes i also cant get messages from someone (cant reproduce it tho).

### Expected Behavior

Being able to Write in channel

### Steps To Reproduce

1. Start Discord
2. Get into a channel
3. Crash Discord (not with task manager, it has to crash with the "Oops Discord crashed, Reload" screen)
4. Click on Reload
5. Try to write in the channel

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.5

### Anything else?

Video of the Bug (with proof of no Plugin being activated)
https://user-images.githubusercontent.com/63616197/226110692-9b7a5f98-5cb4-4b28-bd18-b5759204ab49.mp4

**Comment by Gaminguide1000** [comment]
also works with CTRL+R

**Comment by Kxsumi** [comment]
Now, you wouldn't happen to have a plugin called "XenoLib" would you?

**Comment by moops44** [comment]
The Devs block any plugin from Lighty thats why ..

**Comment by Kxsumi** [comment]
> The Devs block any plugin from Lighty thats why ..

This is not correct

**Comment by Inve1951** [comment]
Doesn't seem to be a BD issue.
Feel free to reopen if this happens with no plugins installed.
