### ISSUE TITLE
[Bug] Orange outline around servers list

### ISSUE THREAD

**Issue by ipkpjersi** [BetterDiscord/BetterDiscord#1573]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

I am experiencing an orange outline around my servers when I close out of Discord then open it from my tray in Ubuntu 22.04 LTS Linux with Xfce 4.14 desktop environment:

![](https://i.imgur.com/cZtJ5to.png)

### Expected Behavior

I am not expecting an orange outline around my servers.

### Steps To Reproduce

1. Close out of Discord but don't exit it.
2. Open Discord from the tray.
3. You can now see the orange outline, or at least I can.

### Operating System

Linux

### Discord Version

Stable

### BetterDiscord Version

v1.8.5

**Comment by maenDisease** [comment]
Have you tested if this issue occurs with BD uninstalled?

**Comment by ipkpjersi** [comment]
Oops, it does occur with BD uninstalled. This issue is invalid so I will close it.
