### ISSUE TITLE
DoNotTrack plugin is not blocking process scanner[Bug]

### ISSUE THREAD

**Issue by yopburner** [BetterDiscord/BetterDiscord#1574]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

DoNotTrack plugin is not blocking the process scanner and is allowing discord to find what games are being played and put them in the registered game tab.  This seems to be broken across all third party discord clients, so it was probably some update.

### Expected Behavior

When games are played they will not show up in the registered games tab and will not be shown in rich presence

### Steps To Reproduce

1. Install DoNotTrack plugin
2. Play game, it will show up in the registered game tab

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.8.5

**Comment by rauenzi** [comment]
> My issue is not caused by a plugin or theme

This is most definitely a problem with the plugin...
