### ISSUE TITLE
[Bug] Some Default Emoji Missing.

### ISSUE THREAD

**Issue by AnviIndo** [BetterDiscord/BetterDiscord#1579]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

after i installed new core of betterdiscord, looks like some default emoji from discord was missing, u will know when that convert into text and u cant click it normally. for example i will use  sparkle emoji for bugged one and droplet emoji for normal one.
![bug tolo](https://user-images.githubusercontent.com/88024047/227039799-59d20f19-0f71-43b0-8847-b1e8ef06e5de.png)

### Expected Behavior

just expected to be normal again, default windows emoji so awfull and thats bug converted some emoji into normal text size make it small as hell.

### Steps To Reproduce

1. i am update the core into v1.9.0, before update happen i already check about emoji things is normal as always
2. when new core installed, some emoji converted into normal text as u can see in above screenshot

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.0

**Comment by maenDisease** [comment]
Have you tested with BD uninstalled

**Comment by AnviIndo** [comment]
> Have you tested with BD uninstalled

wait, i will test it out

**Comment by AnviIndo** [comment]
> Have you tested with BD uninstalled

bruh, after i reinstall it, it still same, after i ask my friend who doesnt installing betterdiscord, lookslike discord has the issue.
