### ISSUE TITLE
[Bug] Discord instantly crash

### ISSUE THREAD

**Issue by EDM115** [BetterDiscord/BetterDiscord#1580]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

![image](https://user-images.githubusercontent.com/82015596/227530370-485aab72-8c5b-412e-b5de-c400a0fa250c.png)

getting that error on every launch  
running the `--vanilla` version works however
- All plugins disabled
- Only `dracula` and `EmojiReplace` themes enabled, but they don't cause the bug

### Expected Behavior

I expect Discord to launch normally

### Steps To Reproduce

1. Install BetterDiscord 1.9.0
2. Run Discord
   
(side note : prior versions worked just fine)

### Operating System

Windows

### Discord Version

PTB

### BetterDiscord Version

v1.9.0

**Comment by maenDisease** [comment]
Use Stable or remove all plugins from plugins folder if preferred until fixed.

**Comment by Zorunel** [comment]
i have the same problem

emptying the plugin folder works

**Comment by Fatalclearout01** [comment]
I Cant event open discord it instantly goes to discord crash screen cant reach plugins folder

**Comment by EDM115** [comment]
> I Cant event open discord it instantly goes to discord crash screen cant reach plugins folder

Plugins folder is located at `%APPDATA%\BetterDiscord\plugins`

**Comment by DiaxManPl** [comment]
I think it's not a problem with BetterDiscord. When I uninstalled bd and opened normal PTB, it worked fine until I tried to open direct messages. Then it crashed.

**Comment by EDM115** [comment]
+1 @DiaxManPl  
i renamed the plugins folder, discord opened up just fine, but as you say opening any PM lead to a crash

**Comment by maenDisease** [comment]
See https://github.com/BetterDiscord/BetterDiscord/commit/fbff8e2e52b8076cbab5e908ecdb2524665702e5, this commit should fix the crashing.

**Comment by maenDisease** [comment]
Crashing when entering a DM is likely a Discord issue as I have tested with BD uninstalled.

**Comment by Zorunel** [comment]
I can't confirm that.
I come to the DM as normal and can read and write there

**Comment by EDM115** [comment]
> See [fbff8e2](https://github.com/BetterDiscord/BetterDiscord/commit/fbff8e2e52b8076cbab5e908ecdb2524665702e5), this commit should fix the crashing. Either do a manual to apply or download the `betterdiscord.asar` from the commit artifact https://github.com/BetterDiscord/BetterDiscord/suites/11792215423/artifacts/615230861

I confirm that the new `asar` fixes both the plugins and PM crash  
also some plugins "reloaded" the interface while enabled/disabled (to apply I assume) and it scrolled the plugins list to the top. I notice that it's no longer the case, and that overall BD is more fluid  
All the team made a great job 🥰

**Comment by EDM115** [comment]
think to ship that new asar as an official release, as other people also faced it

**Comment by Leah96xxx** [comment]
> See [fbff8e2](https://github.com/BetterDiscord/BetterDiscord/commit/fbff8e2e52b8076cbab5e908ecdb2524665702e5), this commit should fix the crashing. Either do a manual to apply or download the `betterdiscord.asar` from the commit artifact https://github.com/BetterDiscord/BetterDiscord/suites/11792215423/artifacts/615230861

Can confirm that fixed it for me too. BD was also crashing instantly for me with a library plugin loaded before installing your asar.
