### ISSUE TITLE
[Bug] Downloading plugins crashes discord 

### ISSUE THREAD

**Issue by King-Zero-Kiryu** [BetterDiscord/BetterDiscord#1584]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Every time I try to install a plugin it crashes discord I have tried reinstalling bd and discord with no success. sometime it lets me reload and it works fine other times it wont.
Error type is Illegal invocation

### Expected Behavior

The plugins to load and work fine

### Steps To Reproduce

1. download a plug in from the betterdiscord website
2. put it into the plugin folder
3. discord crash

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.0

### Anything else?

[debug.log](https://github.com/BetterDiscord/BetterDiscord/files/11066738/debug.log)

**Comment by kirbodev** [comment]
This is a clone of #1583

**Comment by King-Zero-Kiryu** [comment]
> 

Did not see that when I was writing this
