### ISSUE TITLE
[Bug] Discord Crashes on Startup

### ISSUE THREAD

**Issue by KynarIE** [BetterDiscord/BetterDiscord#1590]
### Before Reporting

- [X] My issue is not caused by a plugin or theme

### Describe the Bug

The Discord application (with Betterdiscord installed, no themes, one plugin [Zere's Plugin Library]) crashes upon startup

![image](https://user-images.githubusercontent.com/114863156/227732574-0db659a5-33d4-4ee5-96c3-b4334d4fab4b.png)

### Expected Behavior

Start up Discord, discord application launches, usable

but that is not what had happened

### Steps To Reproduce

1. Open Discord
2. Discord loads for a second
3. Discord crashes
![image](https://user-images.githubusercontent.com/114863156/227732729-63187785-8af3-4215-96da-c19aaa2bea94.png)

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

Assumedly the latest version, can't get to settings for.. obvious reasons

**Comment by maenDisease** [comment]
Can you try reinstalling BD with a new installer

**Comment by KynarIE** [comment]
> Can you try reinstalling BD with a new installer

Did the repair option, seems to have fixed it, unsure of what caused it in the first place..
