### ISSUE TITLE
[Bug]Unable to close BetterDiscord Changelog

### ISSUE THREAD

**Issue by nak0604** [BetterDiscord/BetterDiscord#1591]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When BetterDiscord updates and I get that popup that tells me the changelog I have to completely quit Discord and repoen it to get the changelog to go away. Clicking out of the box on discord in the background doesn't do anything. There is no x in the corner (I have tried clicking along the top of the box). 

### Expected Behavior

Be able to click out of the changelog to make it go away, or click an x in the corner to make it go away.

### Steps To Reproduce

BetterDiscord gets an update with a changelog popup

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.9.1

**Comment by maenDisease** [comment]
Are you using a theme

**Comment by nak0604** [comment]
I was using a theme but I was not at the time of this happening. I had an issue with discord crashing on startup so I removed the plugins and themes to troubleshoot it. That is when I got this bug after it updated.

**Comment by Kathund** [comment]
> I was using a theme but I was not at the time of this happening. I had an issue with discord crashing on startup so I removed the plugins and themes to troubleshoot it (by removing them I mean I deleted the folders they were in after copying them elsewhere). That is when I got this bug after it updated.

Do you know what version you where updating from and what version you updated to
