### ISSUE TITLE
Mentioning bots with own name as a role doesn't work

### ISSUE THREAD

**Issue by gnomecore** [BetterDiscord/BetterDiscord#1592]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When trying to mention the bots Pokétwo or Crabstero in a server, it automatically defaults to the role of the same name instead of the bot. This is only happening with bots who have their own name as a role, and disappears when the role name is changed.

When I type "@Pokétwo" it brings up a menu above the typing box, where I can click on two options to mention either the bot Pokétwo (Profile picture, nickname and tag) or the role Pokétwo (only "@Pokétwo"). I click on the bot, but it automatically 'corrects itself' to the role instead. Copy-pasting "@Pokétwo#8236" instead fixes it and changing the bot's role name to something different fixes it.

### Expected Behavior

![image](https://user-images.githubusercontent.com/90390851/227735625-10d882dc-ef9b-484a-b667-66623206a70b.png)
![kjhkjreht Discord](https://user-images.githubusercontent.com/90390851/227735729-3ede60b0-9c03-4899-aaa8-448ea02def90.png)
![cszxsdsdfsdf](https://user-images.githubusercontent.com/90390851/227735927-a05eb720-6b27-4b4c-a0ab-958ceb3a42f2.png)

I expected that clicking "ROV Kiel" (the nickname for Pokétwo) would let me mention the bot instead of the role, but it 'corrects' itself to mention the role (similar to autocorrect). 

### Steps To Reproduce

1. Disable all themes, plugins and custom CSS
2. Have a bot (or regular user?) in your server with a role name that matches its username
3. Start typing @[bot name]
4. Select the bot, not the role, from the list
5. (Optional) send message

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v.1.9.0

### Anything else?

I'm the only one in the server using BetterDiscord and the only one experiencing this issue so I assumed it was related to BetterDiscord, but I'm not 100% sure. It's also not very important since it's easily circumvented but I didn't see any existing bug reports about it so I thought maybe I should write one anyway.

**Comment by maenDisease** [comment]
Have you tested with BetterDiscord uninstalled

**Comment by rauenzi** [comment]
I was not able to reproduce this
