### ISSUE TITLE
Discord Crashes upon start after opening a message or server[Bug]

### ISSUE THREAD

**Issue by thehorrorevent** [BetterDiscord/BetterDiscord#1594]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Essentially, all I do is open discord after a full task kill, and after it all loads and plugins etc load in, first time I open a message or server, Discord crashes and then prompts me to reload. After doing so, whatever message or server I opened prior to the crash, I can no longer send messages in, and sometimes the messages from anyone else doesn't update or show.

![image](https://user-images.githubusercontent.com/80074052/229329718-4ebf140b-863a-4c9d-9e62-4a18b8dbab1a.png)

### Expected Behavior

I expected it to just load like normal without having to restart over and over to get something to load correctly

### Steps To Reproduce

Unsure how to cause reproduction. Just simply crashes everytime.

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.1

**Comment by maenDisease** [comment]
Have you tested that this isn't a plugin issue

**Comment by thehorrorevent** [comment]
> Have you tested that this isn't a plugin issue

I check marked them, so yes. This only occurs with BD enabled. I had the issue before I even installed plugins.

**Comment by maenDisease** [comment]
Does this issue happen with an empty plugins folder
