### ISSUE TITLE
[Bug] Transparency not working again!

### ISSUE THREAD

**Issue by RafaelOzzy** [BetterDiscord/BetterDiscord#1597]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

I've tried the solution from the previous issue, but didn't work!

### Expected Behavior

The theme to be transparent

### Steps To Reproduce

not working even changing the css file

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

Core v1.9.1

**Comment by rauenzi** [comment]
Show your css? It sounds like it's a css issue and not a BD issue.
