### ISSUE TITLE
[Feature] Option to disable discord auto updates

### ISSUE THREAD

**Issue by lynrayy** [BetterDiscord/BetterDiscord#1598]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

Is it possible to make an option that disables the discord updates, the betterdiscord updates should auto done.
And if there is a new update for discord you get only a notification like when a plugin has an update.

So you can make the discord updates manually.

Advantage:

If discord makes an update that will crash betterdiscord or ban betterdiscord users, you can first check if the update do this before you done it finally.

### Anything else?

Maybe now you want to implement it?

**Comment by rauenzi** [comment]
I will not be preventing/disabling Discord's update system.
