### ISSUE TITLE
[Bug] Fresh install for better discord crashes when I try to switch from one place to another almost every time

### ISSUE THREAD

**Issue by HamBrick327** [BetterDiscord/BetterDiscord#1599]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

If I'm in one server, and I choose to switch to another server it gives me the "well this is awkward" error and I have to restart.

### Expected Behavior

It cleanly switches from one server to another

### Steps To Reproduce

1. windows 10 betterdiscord 1.9.3 fresh install no plugins or themes enabled.

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.3

**Comment by artchsh** [comment]
1. You sure that your better discord version is 1.9.3? Because the latest version is 1.9.1
2. Reinstall Discord and BetterDiscord
