### ISSUE TITLE
[Bug] Better discord causing lag in voice channels / streams

### ISSUE THREAD

**Issue by Blackhole883** [BetterDiscord/BetterDiscord#1603]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Random disconnects and massive lag spikes while using voice chat or streaming / watching streams in discord while no internet issues are present connection is stable and plenty of bandwidth, never had this issue before installing better discord

### Expected Behavior

No disconnects or lag spikes

### Steps To Reproduce

Join a voicechat
wait anywhere between 5 and 20 minutes 

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.1

**Comment by rauenzi** [comment]
As no one our team has been able to reproduce this we're going to close as can't fix. If you are still experiencing this and have more information to give feel free to comment again.
