### ISSUE TITLE
[Bug] Launching from taskbar shortcut can open second discord instance

### ISSUE THREAD

**Issue by dafzor** [BetterDiscord/BetterDiscord#1604]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

After having discord open for a while and closing the main window, clicking the taskbar pinned shortcut will open a second instance of discord.

This issue only seems to happen after a while (attempting to reproduce right after starting discord does not work) making it harder to pinpoint the cause.

I haven't been able to reproduce it while using discord without betterdiscord.

### Expected Behavior

Shortcut should always open the currently running instance of discord instead of starting a new one.

### Steps To Reproduce

1. Install discord in Manjaro linux KDE plasma
2. Pin discord shortcut to KDE Plasma taskbar
3. Start discord of taskbar
4. Use discord normaly
5. Close the discord window (leaving discord still running in system tray)
6. Click taskbar discord shortcut

### Operating System

Linux

### Discord Version

Stable

### BetterDiscord Version

v1.9.1

### Anything else?

- Manjaro is on unstable branch
- Remove minimal size is enabled

**Comment by Ya-boy-Jotaro-KuJo** [comment]
has v1.9.2 fixed the issue?

**Comment by dafzor** [comment]
will need time to validate, will install and report back in a day or two.

**Comment by Coder-Tavi** [comment]
Tested on Discord stable w/o BD installed. Issue doesn't appear (Although the cursor changes to "Working" for a second)

**Comment by noah427** [comment]
I think this is either a problem with discord itself or the plasma taskbar, I'm running arch with the plasma taskbar and it still happens. I'm using normal (unmodified discord)

**Comment by dafzor** [comment]
For the past few days I haven't had this issue with betterdiscord installed, so base system update or v1.9.2 seems to have fixed it.

**Comment by dafzor** [comment]
Upgraded discord to 0.27 and issue is back.

**Comment by noah427** [comment]
@dafzor I still have the same issue, any ideas for a fix?

**Comment by dafzor** [comment]
@noah427 in my case I just close discord after fresh startup and open it through the taskbar shortcut, after that it work normally.

**Comment by dafzor** [comment]
So both autostart and plasma task manager use systemd to start discord, with thow different units
![image](https://github.com/BetterDiscord/BetterDiscord/assets/1612206/85711ab1-0f7f-4a1a-95e6-3cad35629c47)

Each will start it's own independent instance of discord, one under systemd, another under plasmashell...

Still no idea if this is a systemd, plasmashell, discord or just configuration issue.
