### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Diva9979** [BetterDiscord/BetterDiscord#1605]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

plugins makes discord app crash

### Expected Behavior

crash

### Steps To Reproduce

click on plugin

https://user-images.githubusercontent.com/127594182/230798011-66942698-9408-413d-91cb-0e3059dbaca7.mp4

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.9.2

**Comment by Diva9979** [comment]
i think i fixed it sorry

**Comment by Ya-boy-Jotaro-KuJo** [comment]
> i think i fixed it sorry

if its fixed close the issue
