### ISSUE TITLE
[Bug] BetterDiscord won't install

### ISSUE THREAD

**Issue by GamezPlays** [BetterDiscord/BetterDiscord#1611]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

 Every time I try to install BetterDiscord it just shows the BetterDiscord logo and closes, and nothing installs, I already tried re-installing Discord but didn't work.
 I've had BetterDiscord before when I was in Windows 10 and it worked, I'm now in Windows 11 and it's not working can that be the issue?

### Expected Behavior

It opens the install menu and I can install it.

### Steps To Reproduce

1. Download the BetterDiscord installer from their website
2. Execute It

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

Not Installed

### Anything else?

Only thing it shows before closing:
![image](https://user-images.githubusercontent.com/100032589/232170951-325bc53a-0ab1-48e0-b92e-7359da232e10.png)

**Comment by maenDisease** [comment]
This repo is for issues with BD itself, https://github.com/BetterDiscord/Installer is more appropriate.

**Comment by GamezPlays** [comment]
> This repo is for issues with BD itself, https://github.com/BetterDiscord/Installer is more appropriate.

Thank you might have found a solution there
