### ISSUE TITLE
[Feature] Bring back old voice chat UI

### ISSUE THREAD

**Issue by 2b2tplayer** [BetterDiscord/BetterDiscord#1613]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

the new background/rectangles outside the circle pfp is just annoying and takes so much space, is there a way to bring back the old one?

images are for reference

### Anything else?

![image](https://user-images.githubusercontent.com/42143007/233129689-bc2d6f09-c71b-442d-b084-78546d241d3d.png)
![image](https://user-images.githubusercontent.com/42143007/233129739-b1b10974-4a5f-4738-9ca6-f25598d9cf04.png)

**Comment by rauenzi** [comment]
This is something a theme can do. Not something for BD to do
