### ISSUE TITLE
[Bug] Injector and Discord Core

### ISSUE THREAD

**Issue by cd-FileX** [BetterDiscord/BetterDiscord#1614]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When using [inject.js](https://github.com/BetterDiscord/BetterDiscord/blob/main/scripts/inject.js) to manually install BetterDiscord on Discord Canary 1.0.60, it throws the error `ENOENT: no such file or directory, scandir 'C:\Users\FlexGames\AppData\Local\DiscordCanary\app-1.0.60\modules'` which is obviously because the new Version (1.0.60) doesn't have a modules folder where it is searched for. 

### Expected Behavior

A normal installation

### Steps To Reproduce

1. Follow the manual installation manual
2. See that it's not working with Discord Canary 1.0.60
3. Search for the Discord Core and don't find it

### Operating System

Windows

### Discord Version

Canary

### BetterDiscord Version

Commit eb81416

### Anything else?

They seem to have moved it into some more secured place.
Discord Desktop Core is now imported through the exported function of './requireNative' which seems to actually just be `require`.
Code used for that is:
`Some unknown file`
```js
const requireNative = require('./requireNative');
...
      coreModule = requireNative('discord_desktop_core');
```

`requireNative.js`
```js
"use strict";

// require(), with paths specialized for requiring only native modules.
module.paths = [];
module.exports = require;
```
But in this case it seems that I don't have enough knowledge nor time to further trace it back.

**Comment by cd-FileX** [comment]
Seems like they have brought the modules back but I guess BetterDiscord will have to prepair for that case

**Comment by CanadaHonk** [comment]
Discord still uses that folder, there have been 0 changes. You probably just didn't start Discord again after it updated before trying to inject BD so it didn't exist yet.

**Comment by cd-FileX** [comment]
I have started Discord or rather my script has started discord before trying to inject. Also I tried it multiple times.
My script works the way that it firstly starts Discord and waits for it to start and after that it kills, injects and starts discord again.
The injection in this part failed and Discord was started. Restarting it manually had also no effect
