### ISSUE TITLE
[Bug] Custom CSS not applying to video/voice call pop out window

### ISSUE THREAD

**Issue by Schrodingers-Neko** [BetterDiscord/BetterDiscord#1617]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When modifying/hiding elements with custom css, rules to classes such as .buttonContainer-1sjtPU (the activities button) would apply in normal view, (i.e. not popped out) but not in popped out view.

### Expected Behavior

.buttonContainer-1sjtPU{
    display: none;
}

would hide the button in both normal view and popped out view

### Steps To Reproduce

1. Stable 191743 (b61e73b) Host 1.0.9012 (31760) Windows 10 64-Bit (10.0.22621) Core v1.9.2
2. Write the following in Custom CSS

```css

.buttonContainer-1sjtPU{
    display: none;
}

```

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.2

**Comment by rauenzi** [comment]
This is intended, BD does not touch popout windows
