### ISSUE TITLE
BetterDiscord Installer cannot kill discord [Bug]

### ISSUE THREAD

**Issue by Prospy006** [BetterDiscord/BetterDiscord#1619]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

The BetterDiscord installer has been stuck in trying to kill discord forever. I've tried closing discord, removing all the plugins, themes, and also turned on DND (so that I don't get notifications when it's trying to kill discord) which might interfere with the killing process. I had BD before, and I uninstalled it previously before installing it now, if that might interfere.

### Expected Behavior

I tried to alt+f4 discord when the process of killing discord was ongoing, after it being stuck for ages, to fasten the process, it doesn't work either. I have tried uninstalling discord and reinstalling it completely too. And deleting the discord files from %appdata% folder just in case it might disrupt the process of reinstalling discord. It seems to no help.

### Steps To Reproduce

1. Run BD and go to install BD.
2. Start the installation process and wait until it's stuck in trying to kill discord.
3. Write a review in github.com (I did the third step just now).

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.2.1

### Anything else?

![image](https://user-images.githubusercontent.com/74852993/235186930-0f19d4cf-d8c3-4fb8-9091-42b62f172b2c.png)

**Comment by maenDisease** [comment]
This repository is for issues with BD itself. https://github.com/BetterDiscord/Installer is for the installer

**Comment by Prospy006** [comment]
my bad
