### ISSUE TITLE
[Bug] Discord window is not snapping to corners

### ISSUE THREAD

**Issue by Gludek** [BetterDiscord/BetterDiscord#1621]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

By default window apps can be dragged to edge of screen for them to snap there and fill certain portion of the screen (top/bottom means 'fullscreen' and left/right halfscreen on specific side). Once I used BetterDiscord the windows lost this behaviour for the app.

### Expected Behavior

Once dragged to side/top the window should snap accordingly and filled specific screen space.

### Steps To Reproduce

1. Open discord
2. Put discord in window mode not covering full screen
3. Dragg window screen to the top of screen for full screen coverage or to side for half screen coverage

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.2

### Anything else?

I believe this also occurs at least up to v1.9.0, that's when I started using BetterDiscord

**Comment by fowlis** [comment]
This is a known issue, and is not exclusive to BetterDiscord -> https://github.com/BetterDiscord/BetterDiscord/issues/615#issuecomment-809813317

**Comment by rauenzi** [comment]
@Gludek check if you have window transparency mode enabled

**Comment by Gludek** [comment]
> @Gludek check if you have window transparency mode enabled

Ahh okay, thank you!
It is duplicate then
