### ISSUE TITLE
[Bug] Errors whilst using pnpm install

### ISSUE THREAD

**Issue by heckeroncrack** [BetterDiscord/BetterDiscord#1622]
### Before Reporting

- [x] I found no existing issues matching my bug
- [x] My issue is not caused by a plugin or theme

### Describe the Bug

![error](https://github.com/BetterDiscord/BetterDiscord/assets/124959846/1e251994-591f-4628-987d-278150c7c43b)
literally read the error on the image

### Expected Behavior

No error, asar exists and gets installed.

### Steps To Reproduce

1. git clone https://github.com/BetterDiscord/BetterDiscord.git
2. cdd BetterDiscord
3. npm install -g pnpm
4. pnpm install

### Operating System

Windows

### Discord Version

Canary

### BetterDiscord Version

Latest

**Comment by rauenzi** [comment]
This is more likely an issue with your setup or pnpm than something on our end.
