### ISSUE TITLE
[Feature] - Verified Plugin icon for installed plugins

### ISSUE THREAD

**Issue by Mantas-2155X** [BetterDiscord/BetterDiscord#1624]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

Display a verified symbol/icon next to installed plugins that came from [betterdiscord.app](https://betterdiscord.app/), making sure that the files are unmodified from the currently verified version on the website.

This will help quickly knowing which installed plugins are verified to be safe, allowing users to easier find plugins that were manually installed from unverified sources.

**Comment by rauenzi** [comment]
This is the same concept as #1391 going to condense them
