### ISSUE TITLE
[Bug] BdApi context menu patching doesn't work

### ISSUE THREAD

**Issue by Davilarek** [BetterDiscord/BetterDiscord#1631]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

BdApi context menu patching doesn't work on canary, clean install without plugins

### Expected Behavior

Trigger the callback of the patch

### Steps To Reproduce

Example:
```js
let a = BdApi.ContextMenu.patch('channel-context', (r, p) =>{ console.log(p); });
```
Rightclick on any channel, and see empty console

### Operating System

Windows

### Discord Version

Canary

### BetterDiscord Version

v1.9.2

**Comment by Salty-Coder** [comment]
Same issue here. Canary 203658

**Comment by Strencher** [comment]
This is caused by a self-shutdown implementation to prevent crashes. I've identified what the cause is and will submit a PR to adress this soon.

**Comment by Davilarek** [comment]
Yes, because the "fix" commit doesnt actually fix. This issue needs reopening.

**Comment by hexagon64** [comment]
yep, I have been having this for a while, no context menu added by a plugin shows up.
