### ISSUE TITLE
[Bug] Update 1.9.3

### ISSUE THREAD

**Issue by Wernoxx** [BetterDiscord/BetterDiscord#1636]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

**BetterDiscord is not updating...**

A video is better than a pamphlet:
*(video)*

### Expected Behavior

That it updates

### Steps To Reproduce

Update to BetterDiscord 1.9.3

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.2

### Anything else?

https://github.com/BetterDiscord/BetterDiscord/assets/124193640/5bd98198-6258-4279-9245-f5af149e65c5

**Comment by rauenzi** [comment]
Can you check the console for errors after updating? We've had multiple people try to reproduce this issue without success.

**Comment by Wernoxx** [comment]
Unfortunately not, as I uninstalled BetterDiscord and manually installed the new update and it worked fine.

**Comment by Grify** [comment]
I found the same issue. I am using betterdiscord built from source on macOS. I'm rebuilding.

**Comment by rauenzi** [comment]
If you're installing from source you have to update from source.
