### ISSUE TITLE
[Bug] Windows just release update KB5027215 (OS Builds 19044.3086 and 19045.3086) and it broke Better Discord

### ISSUE THREAD

**Issue by BrandiBlitz** [BetterDiscord/BetterDiscord#1637]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Windows force updated and it broke Better Discord's handling of themes as a whole. I tried reverting the theme to default, uninstalling and reinstalling, but better discord is not working for me anymore, despite the installation being "successful".

### Expected Behavior

Graphical and functionality bugs making better discord unusable.

### Steps To Reproduce

get windows 10 update KB5027215 (OS Builds 19044.3086 and 19045.3086) with better discord 1.9.3 installed prior to updating and use any plugin and theme. 

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.9.3

### Anything else?

please make updates to fix any potential bugs  for windows updates as well.

**Comment by TawapahDev** [comment]
I also just realized that Better Discord isn't running anymore, and I can see I have the same update. I tried a repair and reinstall but it's still not running. @BrandiBlitz have you rolled the update back to make it work again as a temporary solution?

**Comment by BrandiBlitz** [comment]
> I also just realized that Better Discord isn't running anymore, and I can see I have the same update. I tried a repair and reinstall but it's still not running. @BrandiBlitz have you rolled the update back to make it work again as a temporary solution?

The new better discord update fixed it, but pre-patch, I just straight up reinstalled discord and reinstalled better discord and that fixed it.

**Comment by TawapahDev** [comment]
@BrandiBlitz okay. I would like to be able to continue to use Windows 10 Pro, but I found out that update KB5027215 cannot be uninstalled under the update history. Do you maybe have an idea of another possible temporary solution, other than reinstalling an older version of Windows?

**Comment by BrandiBlitz** [comment]
> @BrandiBlitz okay. I would like to be able to continue to use Windows 10 Pro, but I found out that update KB5027215 cannot be uninstalled under the update history. Do you maybe have an idea of another possible temporary solution, other than reinstalling an older version of Windows?

If you had restore point activated before you updated, you could use that to "restore" to a previous state before it broke.

You can get the pro version and use a command script to activate win 10/11 pro for free.

**Comment by rauenzi** [comment]
BetterDiscord does not interact with windows directly, it is likely there is something else going on outside of our control.

**Comment by Riddim-GLiTCH** [comment]
>BetterDiscord version 1.9.3
Should be noted that BetterDiscord 1.9.6 has been released, updating BD-core might also fix the issue.
