### ISSUE TITLE
[Bug] BetterDiscord broke my whole Discord installation

### ISSUE THREAD

**Issue by Venus5687** [BetterDiscord/BetterDiscord#1638]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

BetterDiscord broke my whole Discord install in a few days, even if I reinstall Discord and uninstall BetterDiscord. Please fix this. I love BetterDiscord! (this happened before 1.9.3 was out)

### Expected Behavior

I expected for Discord to boot up.

### Steps To Reproduce

1. Install BetterDiscord.
2. Wait a few days, when done it will give you an error that Discord crashed.
3. You broke Discord. Even if you uninstall BetterDiscord or reinstall Discord.

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.2

**Comment by fowlis** [comment]
This is very likely to be an issue with one of your plugins, and it doesn't actually "break" Discord as much as you may think. None of your data is lost and the client doesn't get damaged.

**Comment by Venus5687** [comment]
I swear, I didn't install any plugins, only themes.

**Comment by SourCandy80** [comment]
reinstalling PROPERLY would fix any of these issues, so clearly something was done wrong here.

**Comment by THEFIGURE-BETTERDISCORD2** [comment]
Honestly. This also happens to me, but a different thing. BROKEN PLUGINS

**Comment by Venus5687** [comment]
I reinstalled discord and it fixed.
