### ISSUE TITLE
[Bug] ScreenShare not working on Hyprland

### ISSUE THREAD

**Issue by D3vil0p3r** [BetterDiscord/BetterDiscord#1639]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

ScreenShare is not working on Hyprland. I'm using `betterdiscord-git` and `discord` Arch packages.

### Expected Behavior

ScreenShare the entire screen shows blackscreen

### Steps To Reproduce

1. Install `betterdiscord-git` and `discord` packages in Arch Linux
2. Join a voice chat and share the entire screen.

### Operating System

Linux

### Discord Version

Stable

### BetterDiscord Version

-git package so the latest commit

**Comment by rauenzi** [comment]
Can you screenshare without BetterDiscord?

**Comment by D3vil0p3r** [comment]
> Can you screenshare without BetterDiscord?

No, I cannot because by using official Discord, Wayland (that is used on Hyprland), does not make screenshare working, but I read that BetterDiscord should solve this limitation on Wayland (in a similar manner as ArmCord does).

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r You can screenshare in both discord and betterdiscord with wayland, you need [the XDG portal](https://github.com/KDE/xdg-desktop-portal-kde).
> 
> Does better discord update the electron version used in any way?

But if @rauenzi said that message above, it means the screenshare is not supported (despite it could work by XDG portal).

**Comment by Morphexe** [comment]
I might have misread it, but I think what @rauenzi  was saying is that better discord is not aiming to fix Wayland compatibility. The main issue is that it doesnt support the wayland way of screensharing, that XDG Portal works around that, I managed to get Discord to screenshare with that but havent tried better discord yet, maybe worth a shot for you :)
