### ISSUE TITLE
dev tools crashing and logging out all connected accounts

### ISSUE THREAD

**Issue by byteslittlekitten** [BetterDiscord/BetterDiscord#1640]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

so basically everytime (i) use devtools it crashes my betterdiscord and when i reload it it just makes it so it logs out all of my connected accounts to the discord app and i have to re-sign into all of them again i dont know why it does this but please check on it.

### Expected Behavior

being able to actually use devtools but no it just crashes when i open dev tools

### Steps To Reproduce

1. Turn on devtools in betterdiscord
2. Click Control + Shift + i
3. and it just crashes but its 50/50

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.3

### Anything else?

crashing when using dev tools

**Comment by KontrollFreek** [comment]
From what I've experienced this is simply a bug with vanilla Discord, although it only happens on Windows for some reason.

**Comment by Vendicated** [comment]
The crashing is related to hitting the 2gb memory limit and running out of memory, because devtools use a lot of memory

the getting logged out is due to discord "hiding" your token when you open devtools to protect you from scams.
Hiding means that it removes all your tokens from all storages.
Normally, it would add them back when you close devtools again, but since you crashed, it never restored them and thus you get logged out

**Comment by Vendicated** [comment]
> although it only happens on Windows for some reason.

@KontrollFreek because Discord on Windows uses 32bit electron, whereas on Linux and Mac it uses 64bit. The 2gb memory cap only exists in 32bit chromium, so it only OOMs on Windows

**Comment by Vendicated** [comment]
no. this is a hard chromium limitation

**Comment by rauenzi** [comment]
It's exactly as Ven described. The Devtools causes a large increase in memory usage and with Discord itself being a hog you can easily hit the 2gb limit on Windows. The workaround is the setting in BD already noted.
