### ISSUE TITLE
Discord not found [Bug]

### ISSUE THREAD

**Issue by Nick-Kate** [BetterDiscord/BetterDiscord#1642]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

I am sitting on windows 11, and I want to install BetterDiscord, but it writes to me that it has not been found, and I do not know which path to specify.

I tried to find it through sources, I didn't find it, the maximum that I found is this:

%programdata%/%username%/Discord/app-1.0.9013/resources

Anyway, he writes that it is not found, what should I do? Which way should I point?

![image](https://github.com/BetterDiscord/BetterDiscord/assets/138406172/ca82b405-6c4e-4347-9033-2cda9835c8b8)

### Expected Behavior

Tried to upload, no files found

### Steps To Reproduce

Tried to upload, no files found

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.3.0

**Comment by fowlis** [comment]
This repo is for issues with the functionality of BetterDiscord itself, not the installer.
There is an available solution in [the Discord server](https://discord.gg/0Tmfo5ZbORCRqbAd) > [message link](https://discord.com/channels/86004744966914048/1019687030826999830/1019687030826999830).

**Comment by Nick-Kate** [comment]
> Этот репозиторий предназначен для устранения проблем с функциональностью самого BetterDiscord, а не установщика. В <a>сервере Discord</a> > <a>ссылка на сообщение</a> доступно решение.[](https://discord.gg/0Tmfo5ZbORCRqbAd)[](https://discord.com/channels/86004744966914048/1019687030826999830/1019687030826999830)

And which path should I specify so that I can install?

**Comment by fowlis** [comment]
You don't need to specify a path. Just reinstall Discord and rerun the installer.

**Comment by Nick-Kate** [comment]
> You don't need to specify a path. Just reinstall Discord and rerun the installer.

Thanks, I'll try

**Comment by Nick-Kate** [comment]
> Вам не нужно указывать путь. Просто переустановите Discord и повторно запустите программу установки.

Everything is established, thank you!
