### ISSUE TITLE
[Bug] BetterDiscord Activity Status Won't Properly Update

### ISSUE THREAD

**Issue by SerenityTime** [BetterDiscord/BetterDiscord#1643]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

![image_2023-07-03_004723778](https://github.com/BetterDiscord/BetterDiscord/assets/138430396/02ed8f46-5e58-4962-915b-6ab8e1305c2f)
 
As shown in the above image Persona 5 Royal is shown to be my current game activity however
![image_2023-07-03_004814932](https://github.com/BetterDiscord/BetterDiscord/assets/138430396/ff2edbdb-98d4-4c95-ba4d-1b0013fd8c91)
 Persona 5 Royal is not currently open on my PC. Whenever I close a game or open another the activity does not update until I completely restart Discord.

### Expected Behavior

With my clean copy of Discord PTB it works normally and the activity is updated as I close and open applications. So I expected BetterDiscord to work the same way after all it seemed to be doing that just fine before. 

### Steps To Reproduce

1. Open BetterDiscord
2. Run any game or activity that is registered.
3. The activity status should change but it does not.
There was nothing else that I did outside of running plugins. With the only one I can think of that may be a problem being the ShowAllActivites plugin.

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.3

### Anything else?

I hope I'm not just misunderstanding this section of the FAQ. 
![image](https://github.com/BetterDiscord/BetterDiscord/assets/138430396/6ff09df0-d1ac-44f5-8922-fc256a8b4e50)

If so, I apologize for the wasted time, but if not I hope to receive some assistance on this matter or to know if there is some other external reason as to why it isn't working properly. Either way thank you so much for the response!

**Comment by rauenzi** [comment]
Have you tried temporarily removing all plugins and seeing if the issue persists?

**Comment by SerenityTime** [comment]
> 

I just did Im assuming it was the DoNotTrack plugin which I thought didn't apply to the game tracking. But this worked so thank you!
