### ISSUE TITLE
A way to temporarily turn off the custom CSS 

### ISSUE THREAD

**Issue by NoLagJustHex** [BetterDiscord/BetterDiscord#1644]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

I would like to have a function that makes it possible to turn of the custom CSS code, just like a little switch on the top or something similar. 

I currently always have to delete the custom CSS code and insert it again later when I want to continue working on my theme.

**Comment by rauenzi** [comment]
![image](https://github.com/BetterDiscord/BetterDiscord/assets/6865942/606eddcb-6066-416e-896b-49a0c34d9af1)

this toggle does just that

**Comment by NoLagJustHex** [comment]
Ah, okay.

My bad
