### ISSUE TITLE
[Feature] Delete debug.log after certain amount of time

### ISSUE THREAD

**Issue by fowlis** [BetterDiscord/BetterDiscord#1648]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

The `debug.log` file has been known to take up to *gigabytes* of storage on users' computers, because they will enable it and then forget to disable it. Most of what will be in that file is likely useless to the user, so why not delete it?
Since every client load is marked with the date + time in the file, maybe BetterDiscord could check for logs older than 1-2 weeks and delete the ones older than that.

**Comment by rauenzi** [comment]
This log is meant for developers to use in short bursts during development. No one should be leaving this on long term, and developers should delete and disable when done debugging.

**Comment by fowlis** [comment]
While I understand this, I do think that the setting could either a. toggle itself off after a certain amount of time has passed or b. let the user know in some unobstructive way that the file is taking up an ungodly amount of space on their drive - and that they may want to delete it.
