### ISSUE TITLE
[Feature] Possibility to disable more than one instance

### ISSUE THREAD

**Issue by rizzini** [BetterDiscord/BetterDiscord#1650]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

I want to disable multiple instances. Every time I open Discord with an instance open another one is spawned and I find that annoying since I don't intend to use more than one.

**Comment by Huderon** [comment]
You're sure you've not added the `--multi-instance` flag to your shortcut? As far as I'm aware BD doesn't have multi-instance as a feature, and there are no currently supported plugins for enabling it

**Comment by rizzini** [comment]
Right on.. But it's weird I have that flag since I never intended to use multiple instances. Thank you.
