### ISSUE TITLE
Update strings on POEditor

### ISSUE THREAD

**Issue by PineappleSnackz** [BetterDiscord/BetterDiscord#1651]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

Some strings, like those for the emote system, aren't in BetterDiscord anymore but they're still on POEditor.

Also, there are strings such as "Changelog" on BetterDiscord that aren't on POEditor.

And, strings like "Date Added", "Date Modified", "Author", etc., have been translated on POEditor but these translations aren't showing up in the application.

**Comment by rauenzi** [comment]
The strings have been updated on POEditor, a fix for what you've pointed out will be in the next version of BD
