### ISSUE TITLE
[Bug] Bad Performance and Slow Loading Times

### ISSUE THREAD

**Issue by Robo798814** [BetterDiscord/BetterDiscord#1657]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When I installed Better Discord, the loading times and overall performance for my client had gotten slower than without BD installed. I looked into Task manager, and my CPU, Memory and GPU Utilization was at normal. I've even closed other programs in my OS, then set Discord.exe to high priority, and I still hadn't found improvement. 

### Expected Behavior

I expected that the performance and loading times would stay relatively the same between normal and BD Discord. In general, my browsing engines do not have long loading times, so I don't believe that my internet or RAM is the issue.

### Steps To Reproduce

1. Open Discord
2. Change to any channel or server (The loading times worsen when changing to a channel/server with large amounts of uploaded files or .gif)

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v.1.9.3

### Anything else?

Here are my specs: 

CPU: i5-3570k
GPU: GTX 1070 Ti
RAM: 16GB RAM
OS Hard Drive: SSD

If you need any more information, please let me know.

**Comment by rauenzi** [comment]
I would try cleaning out your Discord folders and reinstalling Discord first.

**Comment by UtterDonkey** [comment]
Might be too late but I have the same issue

**Comment by rauenzi** [comment]
This is unfortunately very vague and unclear what is happening. I would recommend you use the most recent 64 bit clients if possible. I've personally found that Canary generally has better performance.
