### ISSUE TITLE
[Bug] Cannot screenshare with audio

### ISSUE THREAD

**Issue by S0ULL355** [BetterDiscord/BetterDiscord#1659]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

On Windows 11 (at least in the preview release), it will not let me share the screen with audio working, it says I must go back to Windows 10 for it to work. When it works fine on normal Discord Canary. 

### Expected Behavior

I expected for it to work after a while but I understand I'm on a early version of Windows 11

### Steps To Reproduce

1. Just run BetterDiscord
2. Connect to a VC
3. Click "Share Screen"
4. Under the screen or window being shared, it'll say: "Audio sharing may not work on your Windows version. Please upgrade to the latest Windows 10."

### Operating System

Windows

### Discord Version

Canary

### BetterDiscord Version

v1.3.0

### Anything else?

BD Screenshot of sharing screen.

![Screenshot 2023-08-21 183212](https://github.com/BetterDiscord/BetterDiscord/assets/48848185/fdc8d0c9-3c16-4ced-9b5b-a807dea9e5a2)

Discord Canary screenshot of the same thing. 

![Screenshot 2023-08-21 183408](https://github.com/BetterDiscord/BetterDiscord/assets/48848185/d618e8e7-f73d-414a-8a5e-e49f46ca8fbe)

**Comment by fowlis** [comment]
Is this an issue only while BetterDiscord is installed? If not, then it's a Discord issue.

**Comment by S0ULL355** [comment]
It is indeed, however it works like normal on Canary.

**Comment by rauenzi** [comment]
So you've tried Canary both with BD installed and uninstalled? Or is this BD installed on Stable vs normal Canary?

**Comment by S0ULL355** [comment]
both canary, just installed vs uninstalled BD

**Comment by rPiranha** [comment]
since this is an old bug, i think it was just compatibility issues. older versions of bd can bug out on newer versions of discord. especially since soul was on 1.3.0 and the latest update at that time was 1.9.3

**Comment by zerebos** [comment]
@S0ULL355 If you still experience this with latest version of Discord and BetterDiscord let me know.
