### ISSUE TITLE
[Feature] Voice Chat Audio Normalization

### ISSUE THREAD

**Issue by bbogdn2** [BetterDiscord/BetterDiscord#1660]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

In voice chats you may often find yourself in a situation where someone's audio is either too high or too low so you have to manually adjust their volume. This can get very tedious especially when you're trying to balance multiple people all at once.

It would be great if it was possible to synchronize everyone's voices to the same volume and optionally have a panel that provides quicker access to the general output volume of discord so you can increase or decrease everyone's volume all at once.

**Comment by fowlis** [comment]
1. This is more of a plugin request, having this as a built in feature for BetterDiscord just creates more bloat.
2. As far as I'm aware, something like this isn't possible with how BetterDiscord's plugins work anyway. You can't access the voice/audio module needed to achieve this.

**Comment by rauenzi** [comment]
It's as they said above, we really are not able to mess with those modules.
