### ISSUE TITLE
[Bug] Jump links lead to wrong chat position

### ISSUE THREAD

**Issue by shamshitty** [BetterDiscord/BetterDiscord#1666]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When clicking on a message link that leads to a message outside of the current channel, you get sent far up the channel and way past the message you intended to view, and after enough clicks of the message link you'll eventually get to the top of the channel.
I've only seen this happen in a couple bigger servers, BD's own server for example, this doesnt seem to work in smaller "personal" servers with only a couple channels and such.

### Expected Behavior

I expect to get sent to the correct message and not further and further up the channel. With vanilla discord you do actually get sent to the correct message

### Steps To Reproduce

1. Find _(or send)_ a message link outside of the channel you are currently in
2. Click it
3. Watch as you get sent way up the channel

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.3

### Anything else?

Video evidence of it both working and not
_Although this does look like vanilla discord, BD is installed, it was just to prove that no plugins or themes caused this issue_

**Issue occurring in big servers**
https://github.com/BetterDiscord/BetterDiscord/assets/68004605/40005a7b-2998-41ea-9013-3f21330672c7
https://github.com/BetterDiscord/BetterDiscord/assets/68004605/67258f7b-a6c8-4abf-8e7d-2ac2a8f680a6

**Issue not occurring in a small server**
https://github.com/BetterDiscord/BetterDiscord/assets/68004605/7128d388-5cc5-4e96-9523-21b40e1e9256

**Comment by rauenzi** [comment]
I've been able to reproduce this with vanilla Discord before. It is more likely to occur with themes that mess with sizing in the chat area.

**Comment by shamshitty** [comment]
oh really? i tried to reproduce it with vanilla discord and i didnt get the same issue, thats weird

**Comment by Inve1951** [comment]
can confirm, vanilla issue, but happens more (always?) when message heights are changed - something to do with lazy scrolling miscomputing the offset or events firing out of order or something.

**Comment by shamshitty** [comment]
ah i see, sorry for opening the issue then
