### ISSUE TITLE
[Bug] Sending POST request to Discord webhook

### ISSUE THREAD

**Issue by YamikoHikariX** [BetterDiscord/BetterDiscord#1669]
### Before Reporting

- [X] My issue is not caused by a plugin or theme
- [X] I found no existing issues matching my bug

### Describe the Bug

I am writing a plugin that sends the selected message to the specified channel in a different server using Discord webhooks.  (Not sure if this is even allowed? I'm not planning on releasing it to public, just for my own quality of life. That way I don't have to switch between two servers when sharing memes). The plugin extracts the url of the attached image/video and tried to send a POST request to the webhook using fetch like this:
`try {
   const response = await fetch(webhookUrl, {
	   method: 'POST',
	   headers: {
		   'Content-Type': 'application/json',
	   },
	   body: JSON.stringify({content}),
           referrerPolicy: 'no-referrer',
	   mode: 'no-cors',
   }); 
   console.log('Webhook response:', response);
} catch (error) {
   console.error('Error sending webhook:', error);
}
`
The console gives the following error:
POST <webhook url> 400

I've already done it successfully in a chrome extension for example, so not sure why it's not working here. 
I've used Webhook Tester and TypedWebhook.tools to check if the requests are correct and they do seem so. 

Maybe there's a better way of interacting with Discord webhooks in a BD plugin? Or I'm just doing something incorrectly? Or this is just not allowed for security reasons?

### Expected Behavior

The code makes a POST request to the webhook and the discord webhook receives the content of the request and sends it into its respective discord channel

### Steps To Reproduce

1. Create a Discord webhook
2. Write code for the fetch request to the webhook in a BD plugin
3. When the request is made it fails with a 400 error

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.3

**Comment by Davilarek** [comment]
BD blocks webhook requests on purpose

**Comment by rauenzi** [comment]
This is intentional.

**Comment by YamikoHikariX** [comment]
Hm, I see. Thanks for the explanation, @Davilarek, @rauenzi. I suppose there isn't any other way around it, right? I guess I see how it would mostly be used for bad purposes, but it's kinda sad, cause there are good purposes after all... As I said, just not having to switch between servers (which messes up where you were in the channel on the server) when looking through and sharing stuff from a server. If this is not allowed, I'd like to ask please if you know any other, but allowed, ways of achieving this?

**Comment by Vendicated** [comment]
if this is only for your personal use, nothing is stopping you from installing betterdiscord from source and simply removing the webhook block
