### ISSUE TITLE
[Bug] My plugin is not getting started..

### ISSUE THREAD

**Issue by Adeekonn** [BetterDiscord/BetterDiscord#1670]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

I have made a simple plugin for bd. But it is for some reaosn not working. When i try to start to plugin it says "Uwufy could not be started".

`//META{"name":"Uwufy","displayName":"Uwufy"}*//

class Uwufy {
    getName() {
        return "Uwufy";
    }

    getDescription() {
        return "Uwufy your messages in Discord!";
    }

    getVersion() {
        return "1.0.0";
    }

    getAuthor() {
        return "AdiKan";
    }

    start() {
        this.injectUwufication();
        BdApi.showToast("Uwufy Plugin Started!", { type: "success" });
    }

    stop() {
        this.removeUwufication();
        BdApi.showToast("Uwufy Plugin Stopped!", { type: "info" });
    }

    injectUwufication() {
        const MessageContent = BdApi.findModuleByProps("MessageContent");
        const MessageParser = BdApi.findModuleByProps("createBotMessage");

        this._uwufyPatch = (data) => {
            if (data.methodArguments[0] && data.methodArguments[0].content) {
                data.methodArguments[0].content = this.uwufyText(data.methodArguments[0].content);
            }
        };

        BdApi.monkeyPatch(MessageContent, "type", {
            before: this._uwufyPatch,
        });

        BdApi.monkeyPatch(MessageParser, "createBotMessage", {
            after: (data) => {
                if (data.methodArguments[1] && data.methodArguments[1].content) {
                    data.methodArguments[1].content = this.uwufyText(data.methodArguments[1].content);
                }
            },
        });
    }

    removeUwufication() {
        const MessageContent = BdApi.findModuleByProps("MessageContent");
        const MessageParser = BdApi.findModuleByProps("createBotMessage");

        BdApi.unpatchAll("uwufy-plugin");

    }

    uwufyText(text) {
        return text.replace(/r/g, "w").replace(/l/g, "w").replace(/R/g, "W").replace(/L/g, "W");
    }
}

module.exports = Uwufy;
`

### Expected Behavior

Should turn sent messages into funny cute text ' uwufy ' 

### Steps To Reproduce

Put the code into uwufy.plugin.js file and try running it. ( make sure to put in right folder )

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

latest

**Comment by rauenzi** [comment]
Please take a look at the documentation, you are not creating a plugin correctly. https://docs.betterdiscord.app/plugins/introduction/structure

**Comment by Adeekonn** [comment]
> Please take a look at the documentation, you are not creating a plugin correctly. https://docs.betterdiscord.app/plugins/introduction/structure

okay thanks , will look into it.. can u tell me the part where i am going wrong?

**Comment by rauenzi** [comment]
Your meta comment is wrong and your class isn't right javascript-wise.
