### ISSUE TITLE
theme only applies to menu and not to chats and channels [Bug]

### ISSUE THREAD

**Issue by carbonaming** [BetterDiscord/BetterDiscord#1674]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

so i have a theme that applies to the menu but not to the channels and chats... it did before the latest update but for some reason now it doesnt and idk what caused it

### Expected Behavior

theme applies to all parts of discord

### Steps To Reproduce

open better discord
apply theme

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.9

**Comment by biast12** [comment]
Discord changed the class names, that's why your theme doesn't work,

also i'll like to remind you that you ticked "My issue is not caused by a plugin or theme" off

**Comment by carbonaming** [comment]
reread you statement... what caused the issue? not the theme... discord themselves caused the issue

**Comment by Riddim-GLiTCH** [comment]
Not a better discord issue. Please report with the theme developer instead of us.

**Comment by Riddim-GLiTCH** [comment]
> reread you statement... what caused the issue? not the theme... discord themselves caused the issue

To be more consise. Discord changed some elements in their CSS. Most themes expect most of these elements to exist. Some no longer exist. Thus breaking the theme. It is up to the theme developer to reinstate the functionality of the theme.
