### ISSUE TITLE
[Bug] Memory Leak on 1.9.4

### ISSUE THREAD

**Issue by ITCMD** [BetterDiscord/BetterDiscord#1678]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

With no plugins or themes enabled, discord.exe in task manager gains 0.1-0.2 mbps every second.
Additionally, the longer discord is open, the more it lags, usually taking 2-3 seconds to change channels.
I have also attempted repairing it with the installer, no luck.

### Expected Behavior

No lagging

### Steps To Reproduce

Install BetterDiscord 1.9.4

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.4

**Comment by ITCMD** [comment]
May be related to #1417

**Comment by rauenzi** [comment]
Is this without any plugins or themes installed?

I am currently not experiencing this.

**Comment by FailSafeNow** [comment]
I've also got issues with a memory leak. But I can't say whether they come from the ordinary Discord client, or from certain plugins. I'll try to find out more and get back to you.
