### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by itstoxicqt** [BetterDiscord/BetterDiscord#1680]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

[ UPDATE ] button upon click does nothing, does not produce and error in the log file either. I disabled all themes and plugins + checked to see if discord was fully updated.

### Expected Behavior

updatig

### Steps To Reproduce

not 100% sure since the button just doesn't seem to do anything

### Operating System

Arch Linux

### Discord Version

Stable

### BetterDiscord Version

v1.9.3

**Comment by ImAFrogOwO** [comment]
Manually reinstall. Discord removed the Buffer module BetterDiscord used so automatically updating it obviously won't work.

**Comment by itstoxicqt** [comment]
> Manually reinstall. Discord removed the Buffer module BetterDiscord used so automatically updating it obviously won't work.

Ah thank you i had posted on reddit seemed a few had the same issue since it only got upvoted and no response will update the post also thanks for the info
