### ISSUE TITLE
[Bug] all plugins disabled when repairing betterdiscord

### ISSUE THREAD

**Issue by aqtsalt** [BetterDiscord/BetterDiscord#1681]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

everytime betterdiscord is repaired (which often happens), all the plugins get disabled

### Expected Behavior

the plugins.json file should not be reset

### Steps To Reproduce

repair

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.9.3

**Comment by ImAFrogOwO** [comment]
Discord pushed an update which changes internals. Expect delay in BD update.

**Comment by rauenzi** [comment]
This is intended since repair is meant for when BD is failing and crashing. Use install to reinject BD after update.

**Comment by ItMeSarah** [comment]
This is an intended feature. Repairing disables addons. Reinstalling does not. And the above comment is true. Your addons(themes and plugins), and bits of BD are going to be broken for a little bit.
