### ISSUE TITLE
[Bug] Custom css not loading

### ISSUE THREAD

**Issue by n6v26r** [BetterDiscord/BetterDiscord#1682]
### Before Reporting

- [X] I found no existing issues matching my bug
- [x] My issue is not caused by a plugin or theme

### Describe the Bug

Discord doesn't load the custom css. I tried with multiple custom css files. None of them get loaded. The custom css worked until now. Other plugins get loaded and work fine.

### Expected Behavior

I expected it to work.

### Steps To Reproduce

Just add any custom css. It wont load.. :(

### Operating System

Linux

### Discord Version

Stable

### BetterDiscord Version

v1.9.4

**Comment by jovian12** [comment]
I'm having this issue with themes I have installed.  All of a sudden just stopped working yesterday, without coinciding with a Discord update or anything.  Toggling them on and off, repairing BD, etc. doesn't seem to fix it.

**Comment by n6v26r** [comment]
Yes. Noticed this today. Usually bd gets uninstalled with updates and has to be reinstalled. But now themes stopped working all of a sudden... 

I've also opened an issue in the catppuccin theme repo: https://github.com/catppuccin/discord/issues/232
All themes that I tried are either broken or don't work at all.

**Comment by Babbie** [comment]
Before today, I was using beautifuldiscord which also stopped working today, so presumably something changed on Discord's end.

**Comment by snoopi114** [comment]
Can also confirm issues with themes. It stopped working today when Discord seemingly updated to their Halloween theme I think. A few other 3rd party plugins are broken and won't load as well, specifically BetterBannedUsers, Enhanced CodeBlocks, Server Themes, and ZeresPluginLibrary.

**Comment by snoopi114** [comment]
> I also tried on a wm. Fresh install of discord and everything. BD, (installed with either the official appimage installer or the cli) fails to properly load themes. Is it a Linux thing or can someone confirm on windows? (Although I don't see how it could only affect 1 os.)

I can confirm issues I mentioned earlier are via Windows 11. I mainline Win11 on my system for game dev, so I am always using discord.

**Comment by n6v26r** [comment]
> I can confirm issues I mentioned earlier are via Windows 11. I mainline Win11 on my system for game dev, so I am always using discord.

Well... that settles it. The problem is with Discord :(.

**Comment by rauenzi** [comment]
This is going to be tracked under #1683
