### ISSUE TITLE
[Bug] Devtools crashes BetterDiscord

### ISSUE THREAD

**Issue by uetori** [BetterDiscord/BetterDiscord#1687]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Disabled all plugins and themes, ctrl+shift+i to open devtools/inspect element.
BetterDiscord will crash immediately.

### Expected Behavior

Devtools to work / no crashing

### Steps To Reproduce

1. BD v1.9.5
2. ctrl+shift+i
3. observe crash

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.5

**Comment by ejahdev** [comment]
I am also finding this as well on both the Stable and the PTB clients.

**Comment by ItMeSarah** [comment]
This is not a BetterDiscord issue, it is a Discord issue.

**Comment by rauenzi** [comment]
Please see the above comment, it is not something we can fix unfortunately. The issue will go away if Discord updates their electron or fixes their css.

**Comment by LoganDark** [comment]
> Please see the above comment, it is not something we can fix unfortunately. The issue will go away if Discord updates their electron or fixes their css.

can you explain how it is crashing?
