### ISSUE TITLE
[Bug] BetterDiscord no longer keeps you logged in when Discord crashes

### ISSUE THREAD

**Issue by LoganDark** [BetterDiscord/BetterDiscord#1688]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When Discord crashes (due to #1687 or otherwise) it now logs you out, which BetterDiscord used to (optionally?) prevent.

### Expected Behavior

This is a vanilla behavior that BetterDiscord used to (optionally?) prevent. Any option (if it existed) seems to have gone, and the behavior no longer works.

### Steps To Reproduce

1. Crash Discord
2. Observe that you've now been logged out

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.5

### Anything else?

This broke at #1683, but that issue is closed as resolved now, so I think it is appropriate to open an individual tracking issue for this feature.

**Comment by rauenzi** [comment]
Do you have devtools open when it crashes? I have not yet been logged out from any of my crashes

**Comment by LoganDark** [comment]
Yeah, it crashes from devtools and then I'm logged out. Alt+F4 doesn't log me out, but opening DevTools does:

![image](https://github.com/BetterDiscord/BetterDiscord/assets/4723091/e39f3adf-0291-420a-ae64-00c4f2ec5f2a)

and force-killing the process also does.

This is mildly infuriating for someone with a very long password and 2FA

**Comment by rauenzi** [comment]
Do you have this enabled?

![image](https://github.com/BetterDiscord/BetterDiscord/assets/6865942/15a76dd8-35e0-4f42-b27e-d5651cf0bd24)

**Comment by LoganDark** [comment]
> Do you have this enabled?
> 
> ![image](https://user-images.githubusercontent.com/6865942/278825856-15a76dd8-35e0-4f42-b27e-d5651cf0bd24.png)

Nope.

Here are the config files, if you have any other inquiries:

[emotes.json](https://github.com/BetterDiscord/BetterDiscord/files/13196342/emotes.json)
[misc.json](https://github.com/BetterDiscord/BetterDiscord/files/13196343/misc.json)
[plugins.json](https://github.com/BetterDiscord/BetterDiscord/files/13196344/plugins.json)
[settings.json](https://github.com/BetterDiscord/BetterDiscord/files/13196345/settings.json)
[themes.json](https://github.com/BetterDiscord/BetterDiscord/files/13196346/themes.json)

**Comment by rauenzi** [comment]
Enable that and you should be good. It's a side effect of that setting and not an intentional feature.

**Comment by LoganDark** [comment]
Weird how it's a side effect of that setting if I've never used that setting and still got the crash protection, but alright.

**Comment by Soulivan71** [comment]
Im having same issue, and Holdup option enable

**Comment by LoganDark** [comment]
> Im having same issue, and Holdup option enable

You should restart Discord after enabling it to make sure it's really enabled. After that it started working for me.

**Comment by Soulivan71** [comment]
Im still having crash not working for me

**Comment by LoganDark** [comment]
That isn't supposed to fix the devtools crash. That fixes you being *logged out* after the crash.

**Comment by Soulivan71** [comment]
Ok
