### ISSUE TITLE
[Bug] Opening devtools causes Discord to crash

### ISSUE THREAD

**Issue by GttMone** [BetterDiscord/BetterDiscord#1694]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

I enabled DevTools from Settings > BetterDiscord > Settings > Developer Settings. Then I pressed the shortcut Ctrl+Shift+I and they opened as usual, but after a few seconds my Discord crashes.

### Expected Behavior

Discord not to crash.

### Steps To Reproduce

1. Launch Discord
2. Open Settings
3. Go to the BetterDiscord section
4. Click on the "Settings" tab
5. Open the "Developer Settings" section
6. Enable the DevTools option
7. Close out of settings
8. Press Ctrl+Shift+I
9. Wait a few seconds
10. 💥Boom💥 - Discord crashed

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.5

### Anything else?

Log when opening the devtools:
[debug.log](https://github.com/BetterDiscord/BetterDiscord/files/13301487/debug.log)

**Comment by rauenzi** [comment]
Plesae see my comment on #1689

**Comment by GttMone** [comment]
Ah, thanks! It's weird because when searching for "Devtools" in the issues tab nothing showed up.

**Comment by Schleifenkratzer** [comment]
by default it only searches for open issue tickets
