### ISSUE TITLE
[Bug] Keep craashing after using devtools 

### ISSUE THREAD

**Issue by Soulivan71** [BetterDiscord/BetterDiscord#1695]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

![image](https://github.com/BetterDiscord/BetterDiscord/assets/36502190/41f4dcd7-aa2a-402b-a866-6c0ec52347b0)
I have aa problem well this is awkward everytime I restarting discord. 
This bug happened after I use this :
![image](https://github.com/BetterDiscord/BetterDiscord/assets/36502190/613688e9-7ed7-4564-b387-0de2542d678f)
So I don't think its caused by pl, cause I try to reinstal/install with installer and I have same issue (as first screen)

### Expected Behavior

.

### Steps To Reproduce

I don't remember which setting in devtools make me this bug

### Operating System

Windows

### Discord Version

PTB

### BetterDiscord Version

Last version

### Anything else?
![Uploading image.png…]()

_No response_

**Comment by fowlis** [comment]
This is not caused by BD, it's Discord itself.

**Comment by ImAFrogOwO** [comment]
As the person above said, Its a discord bug. As for a work-around. Before discord loads. Click on console or any other tab.
If you want a fix. you can beautify the CSS file. or use this. Copy paste this into console
```js
(()=>{
    var stylesheets = document.querySelectorAll('link[rel="stylesheet"]');
    stylesheets.forEach(function(existingLink) {
        var parent = existingLink.parentNode;
        var newLink = document.createElement('link');
        newLink.href = existingLink.href;
        newLink.rel = 'stylesheet';
        parent.replaceChild(newLink, existingLink);
    });
})()
```

**Comment by Riddim-GLiTCH** [comment]
Isn't this a duplicate of #1689?

**Comment by ImAFrogOwO** [comment]
/shrug. I didn't give a solution there.

Now there is one here.

**Comment by Riddim-GLiTCH** [comment]
> rauenzi says:
> This is an issue with base Discord/Electron. Discord has a very wonky (and massive) css build that appears to cause Electron/Chromium to crash if attempting to parse all at once. This is not BD's fault nor is it something BD can fix. 
> 
> One known workaround is to open DevTools as soon as Discord starts and leave it on the `console` tab until Discord is fully loaded. Then you can use the elements panel though you will notice the `Styles` section taking a bit to load in.

Zere mentions a workaround. And also how we can not fix it.

**Comment by ImAFrogOwO** [comment]
Of course there isnt a "fix". But there is many work-around and temporary fixes.

**Comment by Riddim-GLiTCH** [comment]
I wonder if the [OpenAsar](https://github.com/GooseMod/OpenAsar) project might be able to fix it. As discord does load it's app.asar before most things.

But considering Ducko is rather busy as of late, we might have to make that work ourselves.

**Comment by Riddim-GLiTCH** [comment]
> ### Before Reporting
> 
> - [X] I found no existing issues matching my bug
> - [X] My issue is not caused by a plugin or theme
> 
> ### Describe the Bug
> 
> ![image](https://github.com/BetterDiscord/BetterDiscord/assets/36502190/41f4dcd7-aa2a-402b-a866-6c0ec52347b0)
> I have aa problem well this is awkward everytime I restarting discord. 
> This bug happened after I use this :
> ![image](https://github.com/BetterDiscord/BetterDiscord/assets/36502190/613688e9-7ed7-4564-b387-0de2542d678f)
> So I don't think its caused by pl, cause I try to reinstal/install with installer and I have same issue (as first screen)
> 
> ### Expected Behavior
> 
> .
> 
> ### Steps To Reproduce
> 
> I don't remember which setting in devtools make me this bug
> 
> ### Operating System
> 
> Windows
> 
> ### Discord Version
> 
> PTB
> 
> ### BetterDiscord Version
> 
> Last version
> 
> ### Anything else?
> ![Uploading image.png…]()
> 
> _No response_

As for this, I feel like I should mention that while thorough, this issue report is very flawed.

Steps to reproduce requires you to explain what you did before the issue occured, an example would be what you did within devtools.

Discord version doesn't just ask for which branch. Build ID and Host version would be useful information to have as well.

BetterDiscord version being latest doesn't say much. The latest right now is 1.9.6, but in a few months we might be on 1.10.4 for example.

The anything else field has an image that did not finish uploading. This image could have contained useful information to see what the issue could have been. Be patient next time.

Finally, under operating system you mentioned you use Windows. Which Windows? Windows 7? Windows 8? Windows 10? Windows 11? And which build? Are you on 22H2? 23H2?

All of the above are critical information that can definitely help troubleshooting issues.

**Comment by Soulivan71** [comment]
> I wonder if the [OpenAsar](https://github.com/GooseMod/OpenAsar) project might be able to fix it. As discord does load it's app.asar before most things.
> 
> But considering Ducko is rather busy as of late, we might have to make that work ourselves.

Thats the thing Im using btw, and since the patch 1.9.3 I get issue with bd remove everytime my pc restart, but now I can't use at all :(

**Comment by Soulivan71** [comment]
Im on window 10 22H2

**Comment by Soulivan71** [comment]
Hmm thats strange but I juste restart my app and I get the devtool color option I mentionned, but now Im again in 1.9.3 and I need to do update. 
Im doing rn...

**Comment by Soulivan71** [comment]
Btw Im not speaking about this devtool : https://github.com/BetterDiscord/BetterDiscord/issues/1689

**Comment by Soulivan71** [comment]
And when I restart my pc and I lose bd, I use the manual install 
![image](https://github.com/BetterDiscord/BetterDiscord/assets/36502190/7ed25dd8-14b2-4bd0-b7e2-a66526e3f6a7)
but when I start discord I don't have the latest version. 
-> 
![image](https://github.com/BetterDiscord/BetterDiscord/assets/36502190/63829308-c575-4e68-80b9-c6eed3dc885b)

**Comment by Riddim-GLiTCH** [comment]
Did you pull the latest changes before rebuilding and reinjecting?

**Comment by Soulivan71** [comment]
I have an issue when I do build :
![image](https://github.com/BetterDiscord/BetterDiscord/assets/36502190/4832d1ae-3d79-41e5-8966-82b47a44d477)

**Comment by rauenzi** [comment]
You need to `pnpm install`

**Comment by Soulivan71** [comment]
Yes

**Comment by Soulivan71** [comment]
git pull
pnpm build
pnpm inject
after build ?

> You need to `pnpm install`

**Comment by Inve1951** [comment]
no, before. it downloads module dependencies necessary for the build step, like the one in your error message.

**Comment by Soulivan71** [comment]
Ok, thx

**Comment by Riddim-GLiTCH** [comment]
Im not sure why you marked this as completed. the solution given was to a problem unrelated to what you posted. But im glad you got things sorted.
