### ISSUE TITLE
[Bug] Can't install plugins. 

### ISSUE THREAD

**Issue by aljustiet** [BetterDiscord/BetterDiscord#1697]
### Before Reporting

- [X] I found no existing issues matching my bug
- [ ] My issue is not caused by a plugin or theme

### Describe the Bug

I've installed betterdiscord, then I downloaded the plugins in JS format. But when I moved them to the **plugins** folder, it didn't pop up that suggested a plugin that would help to make them work. Now the plugins are in the plugins folder, but they are not recognized by betterdiscord. I restarted the device, but it didn't help.

### Expected Behavior

To make plugins work.

### Steps To Reproduce

1. Move plugins to betterdiscord's plugins folder
2. Reload discord
3. Plugins not installed

### Operating System

MacOS

### Discord Version

Stable

### BetterDiscord Version

1.9.6

### Anything else?

https://github.com/BetterDiscord/BetterDiscord/assets/114720383/0f1f4a3a-da04-4dcc-a58e-7f17b2632573

**Comment by aljustiet** [comment]
Renaming <pluginname>.js > <pluginname>.plugin.js helped.

**Comment by Riddim-GLiTCH** [comment]
Where did you even find these plugins? They should already be renamed to `*.plugin.js` before downloading.

**Comment by aljustiet** [comment]
https://betterdiscord.app/plugin/ServerHider
https://betterdiscord.app/plugin/AutoIdleOnAFK

**Comment by rauenzi** [comment]
It seems your browser/download method messed with the file names, you'll unfortunately need to fix them manually
