### ISSUE TITLE
[Bug] "Open plugin directory" opens directory in background

### ISSUE THREAD

**Issue by pschaub** [BetterDiscord/BetterDiscord#1700]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When using the feature to open the plugin directory in Windows Explorer from within Discord, the directory currently opens in the background, behind the Discord application window. This behavior necessitates additional steps from the user to bring the directory window to the forefront.

### Expected Behavior

It would significantly improve user experience if the plugin directory, when opened, could automatically appear in the foreground, overtaking Discord's window. This change would streamline the process, allowing users immediate access to the directory without needing to manually adjust window positioning.

### Steps To Reproduce

1. Open Discord
2. Open settings
3. Click on tab "Plugins"
4. Click on button to open plugin directory

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.6

**Comment by Riddim-GLiTCH** [comment]
Windows issue. It happens on my installation too. Explorer on 11 is known to be extremely buggy for no reason at all.


Additional information on my end:
OS: Windows 11 Pro 22h2 Build 22621.2715
Kernel: 10.0.22621.0

**Comment by pschaub** [comment]
See also: https://github.com/electron/electron/issues/36765
