### ISSUE TITLE
Language Problem

### ISSUE THREAD

**Issue by juandi46XD** [BetterDiscord/BetterDiscord#1701]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

BetterDiscord doesn't load (The BetterDiscord icon appears in the corner of the discord window).

### Expected Behavior

When I change the discord language to Spanish LATAM (New language added today) and restart the app, BetterDiscord doesn't load. When I put other language and restart discord, BetterDiscord loads.

### Steps To Reproduce

1. Set the discord language as Spanish LATAM.
2. Restart Discord. 
3. BetterDiscord doesn't load.

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.6

**Comment by rauenzi** [comment]
Yeah well as you noted, it was added today so of course we aren't compatible with it yet.
