### ISSUE TITLE
[Bug] BetterDiscord version 1.9.6 doesn´t work

### ISSUE THREAD

**Issue by IdeLuxiz** [BetterDiscord/BetterDiscord#1704]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

BetterDiscord simbol appears on the bottom right, but when i enter my discord client my plugins are not appearing as loaded, and also when i go to my discord configuration there is only one section that is being display and i cannot interact with it (attached image)
![imagen_2023-12-18_131746390](https://github.com/BetterDiscord/BetterDiscord/assets/115427530/d42b3d47-f08c-4a52-8f34-3a55b57aba35)

### Expected Behavior

BetterDiscord 1.9.6 funcionality

### Steps To Reproduce

When trying to launch my Discord client with BetterDiscord installed.

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.6

### Anything else?

Even if i tried to reinstall, uninstall and install again, the issue is still there.

**Comment by fowlis** [comment]
You should join the support server, there are multiple solutions for this problem in the #known-issues channel.

**Comment by Riddim-GLiTCH** [comment]
You appear to be a Spanish LATAM viewer.
The team is already aware of this and a fix is already in the works.

For now, to use BD. Set your language to normal Spanish, and restart your client.

The issue is that BD isn't localized for LATAM Spanish yet. So it doesn't know what to render.

**Comment by IdeLuxiz** [comment]
> You appear to be a Spanish LATAM user. The team is already aware of this and a fix is already in the works. See [591823f](https://github.com/BetterDiscord/BetterDiscord/commit/591823f90e693ebb473dffa7769057ce79313e38)
> 
> For now, to use BD. Set your language to normal Spanish, and restart your client.
> 
> The issue is that BD isn't localized for LATAM Spanish yet. So it doesn't know what to render.

I did what you told me and BD works again, i hope it gets fix soon, thank you very much.
