### ISSUE TITLE
[Bug] Activating transparency in BD causes window snapping to break in Windows 10

### ISSUE THREAD

**Issue by gabzony** [BetterDiscord/BetterDiscord#1706]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Activating "window transparency" in BD and reloading Discord causes the window snapping feature to stop working, as seen in the video attached below.

- BD version: Core v1.9.7 (all themes and plugins switched OFF)
- Discord: Stable 256231 (96a39c5)
- OS: Windows 10 64-Bit (10.0.19045)

Thanks

### Expected Behavior

For window snapping to work like usual

### Steps To Reproduce

1. Switch "Enable Transparency" option ON under BetterDiscord settings
2. Restart Discord
3. After it restarts, try snapping the Discord window to any of the monitors edges to see that it no longer functions

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.7

### Anything else?

https://github.com/BetterDiscord/BetterDiscord/assets/143902524/9e983bbe-deda-4a16-abc3-6baa973c16ee

(The only reason for moving the Discord window to my other monitor after reloading was in order to navigate back to the settings menu, in order to hide my friends list and server list – I didn't change anything during that time)

**Comment by fowlis** [comment]
This is a problem with the way Electron handles transparency - it is not specific to BD.

**Comment by gabzony** [comment]
I see, thank you for the response.

**Comment by gabzony** [comment]
I see, thank you for the response.

**Comment by gabzony** [comment]
I see, thank you for the response.
