### ISSUE TITLE
[Bug] Cannot select directory on M1 Mac

### ISSUE THREAD

**Issue by Shavin257** [BetterDiscord/BetterDiscord#1708]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

So, whenever I click on Browse for the BetterDiscord installer for Discord PTB and try to select a directory, it doesn't work.

### Expected Behavior

It should register the directory

### Steps To Reproduce

1. On an M1 Mac
2. Download BetterDiscord and try to select directory

### Operating System

MacOS

### Discord Version

PTB

### BetterDiscord Version

?

**Comment by Riddim-GLiTCH** [comment]
I think you are trying to install BD on all options for BD injection.
PTB and canary are not required for BD to function. If you just use normal discord, you are completely fine installing on normal discord.

**Comment by rauenzi** [comment]
Does the selected directory actually contain Discord PTB?
