### ISSUE TITLE
[Bug] 1.9.7 betterdiscord 

### ISSUE THREAD

**Issue by linksanco** [BetterDiscord/BetterDiscord#1713]
### Before Reporting

- [X] I found no existing issues matching my bug
- [x] My issue is not caused by a plugin or theme

### Describe the Bug

I have installed better Discord but I can't see my plugins and themes 

### Expected Behavior

No lagging

### Steps To Reproduce

Install BetterDiscord 1.9.7

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.9.7

### Anything else?

No response

**Comment by fowlis** [comment]
Do you have the plugins and themes tab but you cannot see the individual addons within them? Or can you not see them at all?
Can you see *any* of the BetterDiscord tabs in settings? Why is your 'expected behaviour' "no lagging" rather than "can see my addons".

Please be more specific, we cannot solve vague issues.

**Comment by linksanco** [comment]
I can see it, it's the app's data, but I can't see it inside my Discord browser

**Comment by linksanco** [comment]
I was downloaded from their website So better discords where you can install it

**Comment by fowlis** [comment]
BetterDiscord is __only__ for the desktop app. The installer you get from https://betterdiscord.app will only install to the desktop app, it will not let you install to the web client, or anything other than the three desktop release channels; Stable, PTB and Canary.

I highly suggest you join the [support server](https://discord.gg/0Tmfo5ZbORCRqbAd) for better help with this, make a post in the #support channel and include any screenshots that help illustrate your issue.

**Comment by Riddim-GLiTCH** [comment]
I think they are trying to say that their discord is missing this 
![image](https://github.com/BetterDiscord/BetterDiscord/assets/87764384/3fab8753-4123-4721-8c19-a723461ad3f3)

**Comment by Riddim-GLiTCH** [comment]
> ### Describe the Bug
> 
> I have installed better Discord but I can't see my plugins and themes
> ### Expected Behavior
> 
> No lagging

To be fair, this is a really confusing issue report

> I can see it, it's the app's data, but I can't see it inside my Discord browser

And this is not very indicative of the BetterDiscord section in the settings panel.

**Comment by x0rp01s0n** [comment]
same for me
![image](https://github.com/BetterDiscord/BetterDiscord/assets/43322985/0efab72f-4ece-4a51-a29b-f9233b570579)

**Comment by fowlis** [comment]
> same for me

BetterDiscord is currently broken on Canary due to a version mismatch. This is not the same issue as what was described in this post.
