### ISSUE TITLE
[Bug] Broken on Canary/PTB

### ISSUE THREAD

**Issue by R1ddick** [BetterDiscord/BetterDiscord#1715]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

It seems that some latest updates on discord canary channel completely broke up better discord - after installing better discord over the latest discord canary it became unusable, lacking all the better discord features and I had to re-login to the already logged discord. After uninstalling better discord the vanilla discord canary becomes normal as it should be without any issues, but if I'm trying to reinstall better discord the described bug happens again and again. Please check it up and update core modules if possible.

Thanks!

### Expected Behavior

Better discord should be working without the issues that I've described above 

### Steps To Reproduce

Install better discord 1.9.7 over any latest discord canary version 

### Operating System

Windows

### Discord Version

Canary

### BetterDiscord Version

261973 (954e1a5) (discord canary's version) better discord 1.9.7

**Comment by Riddim-GLiTCH** [comment]
Canary is on a newer version of Electron at this point in time. BD does not yet account for this and misfires some things. This is a known issue that has been discussed within the Discord server already.
Wait for the BetterDiscord team to add compatibility for the new electron version and try again. Use Discord stable for the time being instead.

**Comment by R1ddick** [comment]
> Canary is on a newer version of Electron at this point in time. BD does not yet account for this and misfires some things. This is a known issue that has been discussed within the Discord server already. Wait for the BetterDiscord team to add compatibility for the new electron version and try again. Use Discord stable for the time being instead.

Thanks for the quick response. I'll switch to the stable version and stick with it until the BD is updated with a newer version.
