### ISSUE TITLE
Cant get transparency to work

### ISSUE THREAD

**Issue by Treeat** [BetterDiscord/BetterDiscord#1719]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Transparency doesn't work and I tried the * {transparency!important} command, but that just turns everything completely transparent and I can only see the buttons

### Expected Behavior

I'm looking for the transparency for themes but I cant find it, I'm pretty sure this is the one I'm looking for.

### Steps To Reproduce

just turn on transparency

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.7

### Anything else?

![image](https://github.com/BetterDiscord/BetterDiscord/assets/160085212/c6e454b6-fb59-4f20-9953-07dd7ffa8e5d)

**Comment by Riddim-GLiTCH** [comment]
I think I see a nitro theme in the background?
Forgive me if I'm wrong. But if that's the case, nitro themes have a solid background, so transparency will not work with those.

**Comment by Treeat** [comment]
> I think I see a nitro theme in the background? Forgive me if I'm wrong. But if that's the case, nitro themes have a solid background, so transparency will not work with those.

I got rid of it, still not working
![image](https://github.com/BetterDiscord/BetterDiscord/assets/160085212/8a9965f6-1013-4915-a025-142404fe0f49)

**Comment by Treeat** [comment]
Oh i fixed it, apparently my thing was just being weird and now its working.
