### ISSUE TITLE
Push Enabled plugins to bottom 

### ISSUE THREAD

**Issue by esifo** [BetterDiscord/BetterDiscord#1720]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

BD will refresh itself when enabling plugins and will put you back to the top. im not sure if theres a way for it not to do that but otherwise a setting to push plugins I have not enabled yet to the top of the list and push down the ones I already have enabled to the bottom

**Comment by Huderon** [comment]
At the top of the plugins tab there's some little drop down boxes titled 'Sort By:' and 'Order:', you want 'Sort By: Enabled' and 'Order: Descending'

**Comment by Riddim-GLiTCH** [comment]
I have only observed this behavior with Devilbro's plugins specifically. This is NOT a BetterDiscord issue. This is a Devilbro issue, due to the way Devilbros plugin library works. I presume it has something to do with the CSS file the plugin generates when started.

**Comment by rauenzi** [comment]
See above comment
