### ISSUE TITLE
[Bug] Unable to update to 1.9.8

### ISSUE THREAD

**Issue by PapaSmurf-ML64** [BetterDiscord/BetterDiscord#1723]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Attempting to update to 1.9.8 via in-app updater fails to update from 1.9.7 -> 1.9.8, manually swapping betterdiscord.asar file from releases does not update to 1.9.8, manually building and injecting does not update to 1.9.8 (with caveat).

Caveat: Was able to manually build and inject only after `git checkout tags/v1.9.8` as latest does not appear to be in main branch.

### Expected Behavior

Get notification to update, click update button, restart client for update to finish.

### Steps To Reproduce

Settings -> BetterDiscord -> Updates, click update button.

### Operating System

Linux

### Discord Version

Stable

### BetterDiscord Version

1.9.7

### Anything else?

I have resolved the issue for myself, but this could point to a bug somewhere in the chain and could point anyone else having the issue to a resolution.

**Comment by Riddim-GLiTCH** [comment]
I do believe this is a known issue. I am facing the same issues and have been told that the actual version string does not get updated by pulling the repo. I've also been told that this bugged behavior shouldn't affect BetterDiscord as a whole and that I can safely ignore the update banner for the time being.

**Comment by PapaSmurf-ML64** [comment]
It doesn't get updated by pulling the main repo because the commit that updated it isn't _**on**_ the main repo.

![image](https://github.com/BetterDiscord/BetterDiscord/assets/4394814/e0ce866c-9f9e-4b8a-9a64-b8d75c142dc4)

![image](https://github.com/BetterDiscord/BetterDiscord/assets/4394814/f408a380-033e-41c5-81f4-0c1fabe9fcb8)

If you're still getting the banner in the client, you are still on 1.9.7

**Comment by rauenzi** [comment]
To be clear, the commit is of course in this repository, but it is in a hotfix branch not in the main branch.

"Installing" via cloning and running the scripts should not be a primary method for users, it is ultimately meant for developers that know what they are doing. Users with problems with the actual installer can sometimes leverage these scripts. Perhaps I should spend some time to improve and document `bdcli` or even make a pure JS version.

**Comment by rauenzi** [comment]
For now, the main branch is once again aligned with the latest tag
