### ISSUE TITLE
[Feature] Toggle Deafen without also Muting Microphone

### ISSUE THREAD

**Issue by Golfview** [BetterDiscord/BetterDiscord#1724]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

I'd like to be able to use the "toggle deafen" button, or maybe a different setting, to be able to deafen myself while in a VC, but not end up with my microphone being muted as well. I'm a speedrunner, and when I get to a hard part in the run, it would be nice to be able to deafen but have the others in the call hear what I'm saying.

**Comment by fowlis** [comment]
I don't think this is feasible with BetterDiscord, as far as I know the ability to deafen but not mute is reserved for bots.

You could find a way to use a hotkey to mute Discord entirely temporarily with autohotkey or something similar.

**Comment by rauenzi** [comment]
Either way this is not something that would be integrated into the core, things like that should be left for addons.

**Comment by Riddim-GLiTCH** [comment]
You can also just do this

![Screenshot_20240305_010642.png](https://github.com/BetterDiscord/BetterDiscord/assets/87764384/a9659b11-1b0a-4361-baad-12018d5239ed)

Or make an auto hotkey script that just mutes the voice call process when a keybind is hit.
