### ISSUE TITLE
[Bug] Broken on PTB

### ISSUE THREAD

**Issue by Avakining** [BetterDiscord/BetterDiscord#1726]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

BetterDiscord does not install

### Expected Behavior

BetterDiscord installs

### Steps To Reproduce

1. Install BetterDiscord
2. Open Discord PTB
3. BetterDiscord is not installed

### Operating System

MacOS

### Discord Version

PTB

### BetterDiscord Version

v1.10.0

### Anything else?

Installer version 1.3.0
macOS Sonoma 14.4

**Comment by Riddim-GLiTCH** [comment]
This issue is known. Already discussed within the server. The devs are aware and will work on a fix soon. For now, use Discord stable.
