### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by BlooDerg** [BetterDiscord/BetterDiscord#1727]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When installing BetterDiscord, it wont apply to discord.

### Expected Behavior

Betterdiscord settings appear in settings, meaning it was installed

### Steps To Reproduce

Install betterdiscord
Open discord

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.10.0

### Anything else?

After betterdiscord normally stops working after a discord update, I went to go reinstall betterdiscord to get it to work. It simply wont apply. I've tried deleting every discord related folder in %appdata% and reinstalling after various google searches to find a solution, but no matter what I try, it simply wont apply to Discord. Has the app not been updated to support the current discord version yet?

ps, when I say it wont apply to discord, I mean that when I check settings, no Betterdiscord setting exists.

**Comment by Riddim-GLiTCH** [comment]
Are you on canary/ptb? Those are currently known to not work.
