### ISSUE TITLE
[Question] Does BetterDiscord have Discord Canary support?

### ISSUE THREAD

**Issue by PaperVb64** [BetterDiscord/BetterDiscord#1730]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

just asking, because I use Discord Canary on my computer instead of Regular Discord.

### Anything else?

nuh uh

**Comment by Riddim-GLiTCH** [comment]
It does.

**Comment by PaperVb64** [comment]
yay!
