### ISSUE TITLE
[Bug] Unable to launch on the latest version

### ISSUE THREAD

**Issue by EnisuVI** [BetterDiscord/BetterDiscord#1732]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When I launch Discord (latest version) on my Mac (MacOS 14.4.1), BetterDiscord tries to start and instantly crashes, so Discord starts without BetterDiscord. It worked perfectly 2 days ago before Discord updated the app.

### Expected Behavior

BetterDiscord doesn't start.

### Steps To Reproduce

1. Launch Discord
2. BetterDiscord launches
3. BetterDiscord crashes
4. Discord works but without BetterDiscord (menus for BD are still available)

### Operating System

MacOS

### Discord Version

Stable

### BetterDiscord Version

v1.3.0

### Anything else?

I tried to uninstall and reinstall BetterDiscord several times, even deleted BD and downloaded it again and it still doesn't work.

**Comment by SmolAlli** [comment]
Please confirm if using the "repair" feature from the BetterDiscord installer to disable your plugins fixes the issue.
Also, the best support is on the [Discord Server](https://discord.gg/0Tmfo5ZbORCRqbAd) rather than on the GitHub.

**Comment by EnisuVI** [comment]
Yes, I even tried to reinstall with the said feature and it didn't change anything.

**Comment by zerebos** [comment]
Please visit the support server for assistance.
