### ISSUE TITLE
[Bug] "0" is displayed on the top left of discord, inside the titlebar area

### ISSUE THREAD

**Issue by ShadowMonster99** [BetterDiscord/BetterDiscord#1733]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

"0" is displayed on the top left of discord, inside the titlebar area

### Expected Behavior

"0" to not be visible

### Steps To Reproduce

1. Run discord with BD

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.10.1

### Anything else?

I have removed a significant portion of the dom node and found it is caused by this style sheet
![image](https://github.com/BetterDiscord/BetterDiscord/assets/81448108/ec59874d-31ad-4750-ad3b-de5b9cb94a0c)

![image](https://github.com/BetterDiscord/BetterDiscord/assets/81448108/028d7375-c4e6-4900-bc89-d2d0c2ec9b0c)

**Comment by MJaroslav** [comment]
You are ahead of me, I just checked whether this error is a consequence of using any plugin. And.. no, it appears even without any plugin or theme enabled.

**Comment by Riddim-GLiTCH** [comment]
This is already fixed in https://github.com/BetterDiscord/BetterDiscord/pull/1731
Wait for merge.

**Comment by VisibleSampling** [comment]
Someone on Reddit figured out a temporary fix while we wait fro the next merge. 

https://www.reddit.com/r/BetterDiscord/comments/1btk1oz/wtf_is_this_annoying_0_thing_on_my_screen/ky0m6n1/

**Comment by bluedoomcapZZang** [comment]
병신다 니가 뭐네 할곳이 없어 남한테 테마를 뺏아 먹으냐 쫄라게 년 이네 악마년!!!****

**Comment by Riddim-GLiTCH** [comment]
can the above user be removed from the thread please?

**Comment by mak448a** [comment]
Can you rename the issue so that it's more clear about what's going on? I created a new issue because I couldn't find any similar issues, but then I found your issue. Thanks. @ShadowMonster99

**Comment by ShadowMonster99** [comment]
> Can you rename the issue so that it's more clear about what's going on? I created a new issue because I couldn't find any similar issues, but then I found your issue. Thanks. @ShadowMonster99 

I think it's pretty clear. However i'm open to suggestions! 

Cheers!

**Comment by mak448a** [comment]
I don't mean to be rude, but.... the issue name is literally [Bug]

**Comment by ShadowMonster99** [comment]
> I don't mean to be rude, but.... the issue name is literally [Bug]

Oh haha apologies. i'm viewing this on my phone and read the wrong title. I'll definitely fix it!

**Comment by mak448a** [comment]
Thanks.
