### ISSUE TITLE
Discord crashes when enabling any plugins

### ISSUE THREAD

**Issue by TuxBalazs** [BetterDiscord/BetterDiscord#1738]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When using both Linux and Windows when I try enabling any plugins it crashes Discord immadiately or when reloading the app (both snap and flatpak on Linux). Themes work though.

### Expected Behavior

I expect the plugins to start and not crash my client.

### Steps To Reproduce

On either Linux (Ubuntu) with the snap or flatpak version of Discord or on Windows 10 try enabling any plugin (there's a list of plugins I've tried on a picture) and go into a server or just simply reload the app you'll get the following error: 
![Screenshot from 2024-04-13 14-06-05](https://github.com/BetterDiscord/BetterDiscord/assets/154059049/5cf2abb8-4279-4655-a8d4-6f17b42ff6f4)
![Screenshot from 2024-04-13 14-06-52](https://github.com/BetterDiscord/BetterDiscord/assets/154059049/b7b35638-281c-4dd8-926d-6a5af6c18ebb)

### Operating System

Linux

### Discord Version

Stable

### BetterDiscord Version

v.1.10.1

**Comment by fowlis** [comment]
Remove JumpToTop.plugin.js. This is not an issue with BD itself and therefore should not have been posted on this GitHub.
You would have found your solution in the #known-issues channel of the support server.
![image](https://github.com/BetterDiscord/BetterDiscord/assets/84232621/0c770b42-445b-4584-8691-3129c4d13f44)

**Comment by TuxBalazs** [comment]
Sorry, didn't know about the server
