### ISSUE TITLE
[Bug] when i try downloading the Aplatformindicators, it crash and keeps crash looping 

### ISSUE THREAD

**Issue by etotspia11** [BetterDiscord/BetterDiscord#1739]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

when i enable platform indicator, it crashes and keeps crashing 

### Expected Behavior

it crashed

### Steps To Reproduce

ed

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

latest Version

### Anything else?

![Screenshot_42](https://github.com/BetterDiscord/BetterDiscord/assets/167068053/2fb2ce5f-4616-4d50-a378-66def402819b)

**Comment by fowlis** [comment]
This is not an issue that should be posted on this repo. The problem is with the plugin, and is actually known to the dev of said plugin. The #known-issues channel of the support server even has a post saying this plugin is causing crashes.

**Comment by fowlis** [comment]
> But how do fix it
Well, stop trying to use that plugin while its broken? There is an update pending approval for it so you can wait for that.
