### ISSUE TITLE
BetterDiscord appears to have @everyone tag broken [BUG]

### ISSUE THREAD

**Issue by 5238972389439239823787832** [BetterDiscord/BetterDiscord#1742]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

After looking for about 2 seconds in #issues, I have not found a issue which matches this. When using BetterDiscord, regardless of plugins of themes enabled, the @everyone tag in servers renders are #unknown-user. This does, in fact, mention everyone however.

Below are all the same two posts

*BetterDiscord*
![image](https://github.com/BetterDiscord/BetterDiscord/assets/165739041/c64bc626-9412-4d0f-8b90-bdee4aaf2308)

*BetterDiscord no plugins*
![image](https://github.com/BetterDiscord/BetterDiscord/assets/165739041/261a84a4-5ce3-4cf9-9052-e633af7d7a0f)

*Vencord (with FakeNitro)*
![image](https://github.com/BetterDiscord/BetterDiscord/assets/165739041/763e03c1-479a-4354-be27-4228b7c48be8)

### Expected Behavior

The @everyone tag in servers renders properly

### Steps To Reproduce

1. Open Discord with BetterDiscord
2. Go to any server and @mention everyone
3. Check if it says 'unknown-user'

### Operating System

Windows

### Discord Version

PTB

### BetterDiscord Version

v1.10.1

**Comment by itmesarah** [comment]
This happens without betterdiscord at all, seemingly just a Canary/ptb bug at this moment.

**Comment by thispanda1** [comment]
Ok
