### ISSUE TITLE
BetterDiscord just not installing on the latest Discord Version

### ISSUE THREAD

**Issue by CyberBonk** [BetterDiscord/BetterDiscord#1744]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

i just upgraded from the 32 bit to the new 64 bit discord version from the official site, after i installed it and reinstalled BetterDiscord i found that it is not working

### Expected Behavior

1) open BetterDiscord installer
2) install BetterDiscord
3) Launch Discord
4) Voila, modified discord

### Steps To Reproduce

1. install the newest 64 bit discord version
2. retry to install BetterDiscord from the installer
3. open Discord app
4. Check options to make sure that the discord app isn't modified
5. 

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.3.0

### Anything else?

![image](https://github.com/BetterDiscord/BetterDiscord/assets/125883082/ba6fe627-f7a3-47f0-9e87-0e6655438c5b)

**Comment by Riddim-GLiTCH** [comment]
This should be reported in the [installer Repo](https://GitHub.com/betterdiscord/installer)

**Comment by CyberBonk** [comment]
okay, imma repost it there
