### ISSUE TITLE
[Feature] ✨ BetterDiscord & Vencord United 

### ISSUE THREAD

**Issue by Legends-of-NGDB** [BetterDiscord/BetterDiscord#1745]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

So basically, I want BetterDiscord to have another menu in Discord settings, so a user can install both Vencord and BetterDiscord and have the best of both worlds!

### Anything else?

Not really. It is pretty clear.

**Comment by zrodevkaan** [comment]
no thanks. not compatible.

**Comment by TheHolySpaceChicken** [comment]
yes please. more options, more plugins, more everything

**Comment by rauenzi** [comment]
Nope.
