### ISSUE TITLE
[Bug] When i install TypingIndicator plugin there is nothing loading i tried it but it doesnt work 

### ISSUE THREAD

**Issue by etotspia11** [BetterDiscord/BetterDiscord#1746]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

the Typing Indicator is not working

### Expected Behavior

does nothing

### Steps To Reproduce

e

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

latest Version

### Anything else?

h

**Comment by rauenzi** [comment]
![image](https://github.com/BetterDiscord/BetterDiscord/assets/6865942/a93fcf98-f120-4d3f-a070-4396368791ff)
![image](https://github.com/BetterDiscord/BetterDiscord/assets/6865942/29a50f1b-e069-4e13-ac8d-a0af1a58c30b)
