### ISSUE TITLE
[Bug] Context menu caret icons peak through submenu

### ISSUE THREAD

**Issue by Eight-P** [BetterDiscord/BetterDiscord#1747]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

The caret icons from the Plugins and Themes menu option peak through and interfere with subsequent submenus.

This only happens when the app is too narrow to place them side by side, and it only seems to affect the carets from the Plugins and Themes options.

See the attached video (made them red for better visibility).

https://github.com/BetterDiscord/BetterDiscord/assets/29176216/d15ef079-56a3-4f12-aa8f-2123a6112916

### Expected Behavior

Subsequent submenus should fully overlap the previous ones.

### Steps To Reproduce

Use the context menu with a small enough Discord client.

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.10.1

**Comment by Huderon** [comment]
This is an issue with Discord's CSS. You can just unset the position property on `.iconContainer__5d61c` and it shouldn't be an issue anymore

**Comment by Riddim-GLiTCH** [comment]
I dont think they are supposed to be red, which makes me think it might be a custom theme issue.

**Comment by zerebos** [comment]
Are you still experiencing this? I'm currently unable to recreate.

**Comment by Huderon** [comment]
I can replicate it still. Have a go setting your window to min size and following this path on the settings context. This is in vanilla discord, though, so it's really not a BD issue. 

 ![Discord_ysouzezgte](https://github.com/user-attachments/assets/499def56-51be-4ea9-bc2f-afa185654a95)

**Comment by Eight-P** [comment]
Ah well, my bad. I didn't realize it was a vanilla Discord issue.
I don't know if this is something BD would care to fix then.
I'll leave this open, but feels free to close, I guess.

**Comment by Riddim-GLiTCH** [comment]
BD isn't really designed to fix issues with core discord. If the bugs exist in the Discord Client itself and aren't introduced by a client mod it is Discord's own problem to fix. One could potentially write a CSS snippet to fix it but it would not be a part of Core BD.
