### ISSUE TITLE
[Bug] "Check updates" doesn't work for plugins

### ISSUE THREAD

**Issue by nicola02nb** [BetterDiscord/BetterDiscord#1748]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When I go in `Settings -> Betterdiscord -> updates` section, and I click the button "Check for updates" on the top-right of the screen, it says that all plugin are updated even if some have newer versions .

### Expected Behavior

When clicking "Check for updates" on the top-right of the screen, it should add on th plugin section the plugins that needs to be updated with an attatched button to update them.

### Steps To Reproduce

1. Check that you have a plugin that needs to be updated
2. Go to `Settings -> Betterdiscord -> updates`
3. Click "Check for updates" on the top-right of the screen
4. See that no updates for plugins are found

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.10.1

### Anything else?

There you can see that there is a plugin that needs to be updarted:
![Screenshot 2024-05-10 105834](https://github.com/BetterDiscord/BetterDiscord/assets/61830443/6d4b4f21-5ee1-4879-8a85-13541cbeb20f)
There you can see that after clicking the "Check for updates" button the plugin that needs an update isn't diplayed:
![Screenshot 2024-05-10 105947](https://github.com/BetterDiscord/BetterDiscord/assets/61830443/fdaefceb-cb0a-4a27-93f0-3ba9684056c8)

**Comment by Riddim-GLiTCH** [comment]
Have you attempted to do any troubleshooting steps such as manually reinstalling the affected plugins?

**Comment by nicola02nb** [comment]
I tried with various plugins by changing the `@version` and the `config.info.name` in various plugins with an older version number, and some gets detected, someothers don't....
