### ISSUE TITLE
[Bug] BD crashes when opening a DM

### ISSUE THREAD

**Issue by NewbiePyDev** [BetterDiscord/BetterDiscord#1750]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Whenever I open a dm or a server, my bd crashes and shows "Well this is awkward"

### Expected Behavior

It should just work normally without crashing but it just crashes 

### Steps To Reproduce

Open BD
Open a DM or a Server
Crashes

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.10.1

### Anything else?

VM163 renderer_init:2 The vm module of Node.js is deprecated in the renderer process and will be removed.
s._load @ VM163 renderer_init:2
 [FAST CONNECT] wss://gateway.discord.gg/?encoding=etf&v=9&compress=zlib-stream, encoding: etf, version: 9
VM255 C:\Users\Saaad\AppData\Local\Discord\app-1.0.9147\modules\discord_desktop_core-1\discord_desktop_core\core.asar\app\node_modules\@sentry\utils\cjs\instrument.js:124 Initializing voice engine with audio subsystem: false
71586.bec48eead506f88a39f4.js:1 [default] [BUILD INFO] Release Channel: stable, Build Number: 295694, Version Hash: ffb1a11b2a92121a3614f809fc4aa9cc498efa6b
71586.bec48eead506f88a39f4.js:1 Window state not initialized undefined
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
71586.bec48eead506f88a39f4.js:1 [default] [NATIVE INFO] host 1.0.9147, modules: discord_media: 2, discord_erlpack: 1, discord_utils: 1, discord_cloudsync: 1, discord_voice: 2, discord_desktop_core: 1, discord_krisp: 2, discord_modules: 1, discord_overlay2: 1, discord_rpc: 1, discord_spellcheck: 1, discord_game_utils: 1, discord_dispatch: 1, discord_zstd: 1, build: 48018
VM255 C:\Users\Saaad\AppData\Local\Discord\app-1.0.9147\modules\discord_desktop_core-1\discord_desktop_core\core.asar\app\node_modules\@sentry\utils\cjs\instrument.js:124 Initializing krisp module
71586.bec48eead506f88a39f4.js:1 [Spellchecker] sh is not a valid locale.
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
71586.bec48eead506f88a39f4.js:1 [FAST CONNECT] connected in 775ms
71586.bec48eead506f88a39f4.js:1 [Spellchecker] Switching to en-US (available)
71586.bec48eead506f88a39f4.js:1 Uncaught (in promise) Error: Cannot find module './notosans-400-normalitalic.woff2'
    at 71586.bec48eead506f88a39f4.js:1:12247
    at async Promise.all (index 3)
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Remote~Require] The "request" module is marked as deprecated. Use BdApi.Net.fetch instead.
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Startup] Injecting BD Styles
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Startup] Initializing DataStore
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Startup] Initializing LocaleManager
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Startup] Initializing Settings
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Startup] Initializing DOMManager
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Startup] Waiting for connection...
71586.bec48eead506f88a39f4.js:1 [DEPRECATED] Please use `subscribeWithSelector` middleware
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
71586.bec48eead506f88a39f4.js:1 [GatewaySocket] [CONNECT] wss://gateway.discord.gg, encoding: etf, version: 9, compression: zlib-stream
71586.bec48eead506f88a39f4.js:1 [GatewaySocket] [FAST CONNECT] successfully took over websocket, state: Object
71586.bec48eead506f88a39f4.js:1 [GatewaySocket] [CONNECTED] wss://gateway.discord.gg/?encoding=etf&v=9&compress=zlib-stream in 0 ms
71586.bec48eead506f88a39f4.js:1 [GatewaySocket] [READY] took 622ms, as 9cedc47b310fa89e9e00b36fb7ae9e08
71586.bec48eead506f88a39f4.js:1 [Flux] Dispatching CONNECTION_OPEN
71586.bec48eead506f88a39f4.js:1 [DatabaseManager] removing database (user: 698954282346479618, database: undefined)
71586.bec48eead506f88a39f4.js:1 [NativeDispatchUtils] Tried getting Dispatch instance before instantiated
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
71586.bec48eead506f88a39f4.js:1 [MessageActionCreators] Fetching messages for 1124907927489237012 between undefined and undefined. jump={"jumpType":"ANIMATED"}
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Startup] Initializing Editor
71586.bec48eead506f88a39f4.js:1 [GatewaySocket] [READY_SUPPLEMENTAL] took 649ms
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Modals] Missing ModalActions module!
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Startup] Initializing Builtins
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [BDContextMenu] Enabled
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Custom CSS] Enabled
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Custom CSS] Starting to watch content.
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Startup] Loading Plugins
71586.bec48eead506f88a39f4.js:1 [BDFDB] (v3.6.5) Loading Library
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Remote~Require] The "request" module is marked as deprecated. Use BdApi.Net.fetch instead.
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
71586.bec48eead506f88a39f4.js:1 [ZeresPluginLibrary] version 2.0.19 has started.
71586.bec48eead506f88a39f4.js:1 [XenoLib] Loaded in 276ms
71586.bec48eead506f88a39f4.js:1 [XenoLib] version 1.4.15 has started.
71586.bec48eead506f88a39f4.js:1 [ActivityIcons] version 1.4.4 has started.
71586.bec48eead506f88a39f4.js:1 [AutoIdleOnAFK] version 0.4.0 has started.
71586.bec48eead506f88a39f4.js:1 [bdfdb-s] (v1.1.4) Loading Library
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Remote~Require] The "request" module is marked as deprecated. Use BdApi.Net.fetch instead.
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
71586.bec48eead506f88a39f4.js:1 [BetterVolume] (v2.5.0) Enabled
71586.bec48eead506f88a39f4.js:1 [BetterVolume] (v2.5.0) Experiments already loaded
71586.bec48eead506f88a39f4.js:1 [BetterVolume] (v2.5.0) Initial experiment bucket 1
71586.bec48eead506f88a39f4.js:1 [BetterVolume] (v2.5.0) Changing experiment bucket to 0
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Remote~Require] The "request" module is marked as deprecated. Use BdApi.Net.fetch instead.
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
71586.bec48eead506f88a39f4.js:1 [CallTimeCounter] version 0.0.6 has started.
71586.bec48eead506f88a39f4.js:1 [GuildAndFriendRemovalAlerts] version 3.2.1 has started.
71586.bec48eead506f88a39f4.js:1 main()
71586.bec48eead506f88a39f4.js:1 [HideDisabledEmojis] version 0.0.9 has started.
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [WebpackModules~getModule] Module filter threw an exception. m => {
                if (typeof(m) !== "object") return false;
                const keys = Object.keys(m);
                if (!keys.length) return false;
                for (let k = 0; k < keys.… TypeError: Method %TypedArray%.prototype.join called on incompatible receiver [object Object]
    at Object.join (<anonymous>)
    at Object.toString (<anonymous>)
    at eval (HideDisabledEmojis.plugin.js:109:39)
    at renderer.js:5:44435
    at l.getModule (renderer.js:5:45734)
    at Object.getModule (renderer.js:5:417422)
    at WebpackModules.getModule (0PluginLibrary.plugin.js:2983:32)
    at HideDisabledEmojis.onStart (HideDisabledEmojis.plugin.js:102:49)
    at HideDisabledEmojis.start (0PluginLibrary.plugin.js:3663:56)
    at N.startPlugin (renderer.js:5:29250)
    at N.startAddon (renderer.js:5:29043)
    at N.loadAddon (renderer.js:5:6806)
    at N.loadAddon (renderer.js:5:26460)
    at N.loadAllAddons (renderer.js:5:9469)
    at N.initialize (renderer.js:5:3284)
    at N.initialize (renderer.js:5:25573)
    at Object.startup (renderer.js:5:408848)
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Remote~Require] The "request" module is marked as deprecated. Use BdApi.Net.fetch instead.
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
71586.bec48eead506f88a39f4.js:1 [AppNotifications] version 1.1.5 has started.
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Remote~Require] The "https" module is marked as deprecated. Use BdApi.Net.fetch instead.
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Remote~Require] The "request" module is marked as deprecated. Use BdApi.Net.fetch instead.
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
71586.bec48eead506f88a39f4.js:1 [PermissionsViewer] version 0.2.9 has started.
71586.bec48eead506f88a39f4.js:1 [removeTrackingURL] version 1.0.6 has started.
71586.bec48eead506f88a39f4.js:1 [removeTrackingURL] Enabling removeTrackingURL!
71586.bec48eead506f88a39f4.js:1 [Timezones] version 1.1.2 has started.
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [WebpackModules~getModule] Module filter threw an exception. (m) => m.toString().includes("helpdeskArticleId") TypeError: Cannot read properties of undefined (reading 'map')
    at Module.R (71586.bec48eead506f88a39f4.js:1:7310690)
    at eval (UserVoiceShow.plugin.js:235:41)
    at renderer.js:5:44435
    at l.getModule (renderer.js:5:45734)
    at getModule (renderer.js:5:417422)
    at eval (UserVoiceShow.plugin.js:235:22)
    at buildPlugin (UserVoiceShow.plugin.js:342:4)
    at eval (UserVoiceShow.plugin.js:347:46)
    at N.requireAddon (renderer.js:5:28792)
    at N.loadAddon (renderer.js:5:6412)
    at N.loadAddon (renderer.js:5:26460)
    at N.loadAllAddons (renderer.js:5:9469)
    at N.initialize (renderer.js:5:3284)
    at N.initialize (renderer.js:5:25573)
    at Object.startup (renderer.js:5:408848)
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
71586.bec48eead506f88a39f4.js:1 [UserVoiceShow] version 1.1.6 has started.
71586.bec48eead506f88a39f4.js:1 [YABDP4Nitro] version 5.3.3 has started.
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [PluginManager] Starting to watch plugin addons.
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Startup] Loading Themes
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [ThemeManager] Starting to watch theme addons.
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Startup] Initializing Updater
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Startup] Removing Loading Icon
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Startup] Collecting Startup Errors
71586.bec48eead506f88a39f4.js:1 [MessageActionCreators] Fetched 50 messages for 1124907927489237012 isBefore:false isAfter:false
71586.bec48eead506f88a39f4.js:1 [ChannelMessages] loadComplete: resetting state for channelId=1124907927489237012, sending.length=0
UserVoiceShow.plugin.js:157 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'exports')
    at getModuleWithKey (UserVoiceShow.plugin.js:157:28)
    at UserVoiceShow.patchUserPopoutBody (UserVoiceShow.plugin.js:293:35)
    at UserVoiceShow.onStart (UserVoiceShow.plugin.js:284:10)
    at UserVoiceShow.start (0PluginLibrary.plugin.js:3663:56)
    at N.startPlugin (renderer.js:5:29250)
    at N.startAddon (renderer.js:5:29043)
    at N.loadAddon (renderer.js:5:6806)
    at N.loadAddon (renderer.js:5:26460)
    at N.loadAllAddons (renderer.js:5:9469)
    at N.initialize (renderer.js:5:3284)
    at N.initialize (renderer.js:5:25573)
    at Object.startup (renderer.js:5:408848)
api.github.com/repos/mwittrien/BetterDiscordAddons/contents/Library/_res/:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
api.github.com/repos/BetterDiscord/BetterDiscord/releases/latest:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
renderer.js:5 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'startsWith')
    at At.checkForUpdate (renderer.js:5:405028)
71586.bec48eead506f88a39f4.js:1 [RPCServer:WSS] Starting on 6463
71586.bec48eead506f88a39f4.js:1 [RPCServer:IPC] Starting on \\?\pipe\discord-ipc-0
71586.bec48eead506f88a39f4.js:1 [BetterDiscord] [Remote~Require] The "https" module is marked as deprecated. Use BdApi.Net.fetch instead.
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
api.github.com/repos/mwittrien/BetterDiscordAddons/contents/Library/_res/:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
71586.bec48eead506f88a39f4.js:1 Error: Menu API only allows Items and groups of Items as children. Received function f(e){return null} (object) instead
    at 71586.bec48eead506f88a39f4.js:1:571267
    at Array.reduce (<anonymous>)
    at e (71586.bec48eead506f88a39f4.js:1:569993)
    at A (71586.bec48eead506f88a39f4.js:1:571476)
    at eval (0BDFDB.plugin.js:2971:21)
    at aS (2160.5b1de8a086b42fe36070.js:12:899609)
    at u (2160.5b1de8a086b42fe36070.js:12:954820)
    at sB (2160.5b1de8a086b42fe36070.js:12:937835)
    at 2160.5b1de8a086b42fe36070.js:12:937701
    at sF (2160.5b1de8a086b42fe36070.js:12:937709)
    at sM (2160.5b1de8a086b42fe36070.js:12:934794)
    at r6 (2160.5b1de8a086b42fe36070.js:12:883484)
    at sk (2160.5b1de8a086b42fe36070.js:12:935298)
    at 2160.5b1de8a086b42fe36070.js:12:963360
    at uu (2160.5b1de8a086b42fe36070.js:12:963390)
    at t.render (2160.5b1de8a086b42fe36070.js:12:967088)
    at MyReact.render (0BDFDB.plugin.js:2955:40)
    at MyReact.hookCall (0BDFDB.plugin.js:2970:23)
    at loadLibrary (0BDFDB.plugin.js:7975:60)
    at parseData (0BDFDB.plugin.js:1206:24)
    at eval (0BDFDB.plugin.js:1175:8)
    at eval (0BDFDB.plugin.js:222:56)
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
71586.bec48eead506f88a39f4.js:1 [BDFDB] (v3.6.5) Finished loading Library
71586.bec48eead506f88a39f4.js:1 [GameActivityToggle] (v1.2.4) has been started
71586.bec48eead506f88a39f4.js:1 [ImageUtilities] (v5.4.3) has been started
71586.bec48eead506f88a39f4.js:1 [MessageUtilities] (v1.9.8) has been started
71586.bec48eead506f88a39f4.js:1 [PersonalPins] (v2.1.9) has been started
71586.bec48eead506f88a39f4.js:1 [PluginRepo] (v2.5.5) has been started
71586.bec48eead506f88a39f4.js:1 [ReadAllNotificationsButton] (v1.7.6) has been started
71586.bec48eead506f88a39f4.js:1 [ServerDetails] (v1.1.9) has been started
71586.bec48eead506f88a39f4.js:1 [SplitLargeMessages] (v1.8.2) has been started
71586.bec48eead506f88a39f4.js:1 [StaffTag] (v1.6.0) has been started
71586.bec48eead506f88a39f4.js:1 [Translator] (v2.6.2) has been started
raw.githubusercontent.com/minibox24/DCCon/6eed628298d950a6de0d1fd2aaafe8dccd0d076b/DCCon.plugin.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
71586.bec48eead506f88a39f4.js:1 [PluginRepo] (v2.5.5) Finished fetching Plugins
71586.bec48eead506f88a39f4.js:1 [MessageActionCreators] Fetching messages for 1034038220150800454 between undefined and undefined. jump={"jumpType":"ANIMATED"}
71586.bec48eead506f88a39f4.js:1 [Routing/Utils] transitionTo - Transitioning to /channels/778675959523835914/1034038220150800454
71586.bec48eead506f88a39f4.js:1 [BDFDB] (v3.6.5) ["Colors","Hovers","Looks"] [props] not found in WebModules
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
71586.bec48eead506f88a39f4.js:1 TypeError: Cannot read properties of undefined (reading 'BLANK')
    at BDFDB_ChannelTextAreaButton.render (0BDFDB.plugin.js:4972:54)
    at o_ (2160.5b1de8a086b42fe36070.js:12:914531)
    at og (2160.5b1de8a086b42fe36070.js:12:914329)
    at u (2160.5b1de8a086b42fe36070.js:12:955801)
    at sB (2160.5b1de8a086b42fe36070.js:12:937835)
    at 2160.5b1de8a086b42fe36070.js:12:937701
    at sF (2160.5b1de8a086b42fe36070.js:12:937709)
    at sC (2160.5b1de8a086b42fe36070.js:12:934460)
    at sM (2160.5b1de8a086b42fe36070.js:12:934849)
    at r6 (2160.5b1de8a086b42fe36070.js:12:883484)
    at sA (2160.5b1de8a086b42fe36070.js:12:935109)
    at eI (2160.5b1de8a086b42fe36070.js:12:852710)
    at rs (2160.5b1de8a086b42fe36070.js:12:873839)
    at tB (2160.5b1de8a086b42fe36070.js:12:859507)
    at tP (2160.5b1de8a086b42fe36070.js:12:859291)
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
71586.bec48eead506f88a39f4.js:1 [MessageActionCreators] Fetched 50 messages for 1034038220150800454 isBefore:false isAfter:false
71586.bec48eead506f88a39f4.js:1 [ChannelMessages] loadComplete: resetting state for channelId=1034038220150800454, sending.length=0
71586.bec48eead506f88a39f4.js:1 [MessageManager] Found expired attachment link, clearing messages
71586.bec48eead506f88a39f4.js:1 [MessageActionCreators] Fetching messages for 1034038220150800454 between undefined and undefined. jump={"jumpType":"ANIMATED"}
71586.bec48eead506f88a39f4.js:1 [MessageActionCreators] Fetched 50 messages for 1034038220150800454 isBefore:false isAfter:false
71586.bec48eead506f88a39f4.js:1 [ChannelMessages] loadComplete: resetting state for channelId=1034038220150800454, sending.length=0
71586.bec48eead506f88a39f4.js:1 Hold Up!
71586.bec48eead506f88a39f4.js:1 If someone told you to copy/paste something here you have an 11/10 chance you're being scammed.
71586.bec48eead506f88a39f4.js:1 Pasting anything in here could give attackers access to your Discord account.
71586.bec48eead506f88a39f4.js:1 Hold Up!
71586.bec48eead506f88a39f4.js:1 If someone told you to copy/paste something here you have an 11/10 chance you're being scammed.
71586.bec48eead506f88a39f4.js:1 Pasting anything in here could give attackers access to your Discord account.
71586.bec48eead506f88a39f4.js:1 Hold Up!
71586.bec48eead506f88a39f4.js:1 If someone told you to copy/paste something here you have an 11/10 chance you're being scammed.
71586.bec48eead506f88a39f4.js:1 Pasting anything in here could give attackers access to your Discord account.
71586.bec48eead506f88a39f4.js:1 Hold Up!
71586.bec48eead506f88a39f4.js:1 If someone told you to copy/paste something here you have an 11/10 chance you're being scammed.
71586.bec48eead506f88a39f4.js:1 Pasting anything in here could give attackers access to your Discord account.
71586.bec48eead506f88a39f4.js:1 Hold Up!
71586.bec48eead506f88a39f4.js:1 If someone told you to copy/paste something here you have an 11/10 chance you're being scammed.
71586.bec48eead506f88a39f4.js:1 Pasting anything in here could give attackers access to your Discord account.
71586.bec48eead506f88a39f4.js:1 Unless you understand exactly what you are doing, close this window and stay safe.
71586.bec48eead506f88a39f4.js:1 If you do understand exactly what you are doing, you should come work with us https://discord.com/jobs

**Comment by Huderon** [comment]
This isn't an issue with BetterDiscord, but rather one of your plugins. Run the installer again and select the 'repair' option. This will disable all your plugins. For the moment leave any plugins by DevilBro, as well as PasscodeLock disabled if you have that. You'll be able to safely enable them again after they're updated.

In future, make sure to run that repair option and verify it's not an issue with one of your plugins before opening an issue here.

**Comment by notfence** [comment]
I have the same thing. The above method helped, the problem is in one of the plugins. But I want to note that the bug appeared today

**Comment by Riddim-GLiTCH** [comment]
> I have the same thing. The above method helped, the problem is in one of the plugins. But I want to note that the bug appeared today. Edit: Translator plugin causes a crash

The bug appeared today because Discord pushed an update that some stuff in Devilbro's Library.
They won't rule himself reports. Devilbro himself claims that the issue had already been fixed so this thread can be closed.
