### ISSUE TITLE
[Bug] Lost activity icon

### ISSUE THREAD

**Issue by Guonejo** [BetterDiscord/BetterDiscord#1751]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

After the last update, the discord user activity icon has been lost. I tried reinstalling BetterDiscord and the plugins and it still does not appear.
![image](https://github.com/BetterDiscord/BetterDiscord/assets/82884497/01754080-572a-40c1-82ac-ce82f696dd45)

### Expected Behavior

Profile activity reappears

### Steps To Reproduce

Open BD
Go to a server
User activity does not appear

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.10.1

**Comment by Riddim-GLiTCH** [comment]
There is currently an experiment going on that completely disables member list activities. Perhaps you've been hit with that?

![Screenshot_20240524-094044](https://github.com/BetterDiscord/BetterDiscord/assets/87764384/c2e0f676-5c68-4b0a-8d01-863a85bb1c5e)

**Comment by rauenzi** [comment]
This appears to be some form of A/B testing as illustrated above.
