### ISSUE TITLE
[Bug] Installing on linux does nothing

### ISSUE THREAD

**Issue by 1Codealot** [BetterDiscord/BetterDiscord#1752]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Installing via appimage or from source does nothing. There is no change to the client.

### Expected Behavior

There should be some sort of change to the client (No better discord tab in user settings.)

### Steps To Reproduce

Use Debian 12 linux with discord (stable) installed via flatpak.

Build form source from this https://docs.betterdiscord.app/users/getting-started/installation#manual-installation.

No reported errors.

Or

download appimage from the site.
`chmod +x BetterDiscord.appimage` (or what ever the file is)
`./BetterDiscord.appimage`

Run the installer with no (reported) errors.

I also re ran the installer with repair and reinstalling and it didn't help.

### Operating System

Linux

### Discord Version

Stable

### BetterDiscord Version

v1.10.1 and latest git

### Anything else?

I also restarted not just discord, but my laptop each time.

**Comment by Riddim-GLiTCH** [comment]
Quick question, as this mistake is often made; do you already have any other injectors in place? (Eg vencord, shelter, replugged, etc.) Cuz combining anything with Betterdiscord will not work.

**Comment by fowlis** [comment]
The normal BD installer and presumably, the manual install instructions, do not work for Discord installs from your distro's appstore, flatpak, or the various methods of installing Discord other than from Discord's official site.

You would want to use [BetterDiscordCTL](https://github.com/bb010g/betterdiscordctl) for your flatpak install.

**Comment by 1Codealot** [comment]
> Quick question, as this mistake is often made; do you already have any other injectors in place? (Eg vencord, shelter, replugged, etc.) Cuz combining anything with Betterdiscord will not work.

No there is nothing else



> The normal BD installer and presumably, the manual install instructions, do not work for Discord installs from your distro's appstore, flatpak, or the various methods of installing Discord other than from Discord's official site.
> 
> You would want to use [BetterDiscordCTL](https://github.com/bb010g/betterdiscordctl) for your flatpak install.


Okay, I'll try that!

**Comment by 1Codealot** [comment]
Done!
