### ISSUE TITLE
[Bug] Right-Click not working in Windowed DevTools

### ISSUE THREAD

**Issue by lunatic-gh** [BetterDiscord/BetterDiscord#1758]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Whenever the DevTools window is used as an unpinned window, it doesn't accept right-click actions.
This makes some copy-actions and sources-related things entirely unusable.

### Expected Behavior

Right-Click works as expected, and opens the context menu for the clicked region

### Steps To Reproduce

- Open DevTools
- Put into external window mode (top-right dotted button -> select the left-most dock-side icon)
- DevTools doesn't accept right-click.

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.10.1

**Comment by itmesarah** [comment]
Works fine on my end, try restarting Discord or your computer.

**Comment by lunatic-gh** [comment]
i had this in the past on multiple reinstalls, both on windows 11 and on Arch Linux.

Also may be worth to note, this does not happen for example on Vencord, there it works totally fine. IDK if BD uses a different version of DevTools, or what's going on at all.

**Comment by rauenzi** [comment]
Neither BD or Vencord affect or really touch DevTools aside from adding React DevTools when requested by the user in settings. BD cannot directly affect DevTools like what is being suggested here. The DevTools are just part of the Chromium build and not supplied by the client mods. This is not something I can really fix.

**Comment by lunatic-gh** [comment]
I see. I thought about maybe trying out the "Inject local Devtools" to see if that may fix it, but how does one get such a local devtools install, that just smt you can install?

**Comment by Huderon** [comment]
This is an Electron issue. It is currently affecting stable, but the next electron bump should resolve it https://github.com/electron/electron/issues/38790

**Comment by rauenzi** [comment]
> I see. I thought about maybe trying out the "Inject local Devtools" to see if that may fix it, but how does one get such a local devtools install, that just smt you can install?

I'm not sure what exactly you mean by this, I'm not familiar with that option

**Comment by lunatic-gh** [comment]
![image](https://github.com/BetterDiscord/BetterDiscord/assets/80840951/7bc79d81-63f8-4f0f-b3e8-5d4490070cdb)
bottom one here. I personally couldn't find a way to "locally install it", all i know is the devtools that are included in all kinds of apps or browsers (discord, steam, chrome, etc)

**Comment by lunatic-gh** [comment]
> This is an Electron issue. It is currently affecting stable, but the next electron bump should resolve it [electron/electron#38790](https://github.com/electron/electron/issues/38790)

Interesting... in this case, Is this by any chance already fixed in the canary/ptb versions of discord?

**Comment by Huderon** [comment]
Yepyep. Was fixed in Electron 29, and PTB/Canary have already been bumped to 30. Shouldn't be long before stable gets updated too

**Comment by lunatic-gh** [comment]
awesome, thanks!

**Comment by Vendicated** [comment]
> Neither BD or Vencord affect or really touch DevTools aside from adding React DevTools when requested by the user in settings. BD cannot directly affect DevTools like what is being suggested here. The DevTools are just part of the Chromium build and not supplied by the client mods. This is not something I can really fix.

wrong actually, Vencord does fix this issue by disabling the Chromium feature that causes it: https://github.com/Vendicated/Vencord/blob/2f4e346e26d53b88998682672ba6d10a3460c06e/src/main/patcher.ts#L134-L146

**Comment by rauenzi** [comment]
> wrong actually, Vencord does fix this issue by disabling the Chromium feature that causes it

I mean... that sounds more like a workaround than a root cause fix, but sure.
