### ISSUE TITLE
[Bug] BetterDiscord broken after latest Discord update

### ISSUE THREAD

**Issue by Duffman3005** [BetterDiscord/BetterDiscord#1760]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

After todays Discord update Better Discord does not function correctly anymore, even after a repair/reinstall. There is no access to Better Discord settings as well.

### Expected Behavior

Normal functions of Better Discord, and access to its settings.

### Steps To Reproduce

Discord automatically updated upon opening, Discord finishes loading/opening up, confirmed Better Discord is not active nor showing its setting options.

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.10.1

### Anything else?

![Discord_6AXnvjfRXA](https://github.com/BetterDiscord/BetterDiscord/assets/330098/117fad0d-38ed-40ab-9170-4e4d9d2c15d6)

**Comment by fowlis** [comment]
This is already known. This has affected PTB and Canary since yesterday, it just hadn't hit Stable yet.

**Comment by B-Nerd** [comment]
it has hit stable

**Comment by Duffman3005** [comment]
> This is already known. This has affected PTB and Canary since yesterday, it just hadn't hit Stable yet.

I am on Stable currently, never tried or installed PTB or Canary.

**Comment by ajaxnotmeta** [comment]
has this been fixed?
