### ISSUE TITLE
[Bug] Betterdiscord settings are showing, but no plugins work

### ISSUE THREAD

**Issue by kiwinatorwaffles** [BetterDiscord/BetterDiscord#1761]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

I am aware that the recent Discord update caused BD to break. My friends all say that their BD has gone back to normal after the fix, but mine is still broken. None of my plugins are active despite having been turned on in the settings menu. However, the strangest thing is that my custom CSS works and I see notifications of my plugins needing updates. I've repaired, uninstalled, and reinstalled BD, but nothing seems to work.

### Expected Behavior

The plugins start up upon turning them on in the plugin settings.

### Steps To Reproduce

1. Open Discord with BD installed
2. Confirm BD is installed by opening user settings and scrolling down to see the BD settings
3. Confirm no plugins are active despite activating them in settings

### Operating System

MacOS

### Discord Version

Stable

### BetterDiscord Version

v1.3.0

### Anything else?

<img width="879" alt="bd example" src="https://github.com/BetterDiscord/BetterDiscord/assets/173343933/40871c05-1728-4050-ae8e-1c8727e9375b">
 The best example of this would be Channel Tabs. Despite it being activated, the tabs don't show at the top of the window.

**Comment by rauenzi** [comment]
Plugins that hit errors when starting up get automatically re-disabled. This is intentional to prevent further errors slowing down or breaking your client. Wait for updates for your plugins.
