### ISSUE TITLE
in app notification not working 

### ISSUE THREAD

**Issue by waffle-proxd** [BetterDiscord/BetterDiscord#1762]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

![Screenshot 2024-06-22 102115](https://github.com/BetterDiscord/BetterDiscord/assets/173523275/26d427b3-b234-4ad8-849b-9ab327edfcb3)
the notifications not working it shows there was an erroe to start this plugin and it wont send notification it just keep spamming that error notifiction

### Expected Behavior

i wants that app notification back like it was the clear normal notification. 
ty

### Steps To Reproduce

normally when i start it it shows the error

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.10.2

### Anything else?

need this plugin so do as soon as possible

**Comment by Huderon** [comment]
>  My issue is not caused by a plugin or theme

This isn't where you report issues with plugins. Go to the plugins page on the website and follow the link to its repo

**Comment by waffle-proxd** [comment]
> > My issue is not caused by a plugin or theme
> 
> This isn't where you report issues with plugins. Go to the plugins page on the website and follow the link to its repo

they removed this plugin from betterdiscord web

**Comment by Huderon** [comment]
In that case it's not supported by the BetterDiscord team regardless. If it was removed, it's likely because the dev gave up on maintaining it. Nothing to be done about that. If you want to make a plugin request, this isn't the place to do it. Join the Discord server and make a post in the suggestions/feedback forum
