### ISSUE TITLE
[Feature] Automatic theme switching for Nitro themes

### ISSUE THREAD

**Issue by jahirfiquitiva** [BetterDiscord/BetterDiscord#1763]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

Discord Nitro provide a set of custom themes, but it doesn't allow syncing them to the system theme.

I would like to be able to set a Discord Nitro theme for light system theme and one for dark system theme, and I'd expect it to be synced with the system theme.

Example:
- Light theme: Retro Raincloud
- Dark theme: Retro Storm

**Comment by rauenzi** [comment]
This is definitely not a feature BD will ever add, plugin developers are free to look into and consider.

**Comment by jahirfiquitiva** [comment]
@rauenzi is there a place I can give this idea to plugin developers?
