### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by Lionkid2251** [BetterDiscord/BetterDiscord#1765]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

Please. Please. Please. I’m begging you.. make a version for mobile/ipad😭
There is no other good discord plug-in that supports iPad😭

**Comment by Riddim-GLiTCH** [comment]
> There is no other good discord plug-in that supports iPad
There are plenty.

https://github.com/Discord-Client-Encyclopedia-Management/Discord3rdparties?tab=readme-ov-file#ios-clients--mods
