### ISSUE TITLE
[Feature] Add luau syntax in code block

### ISSUE THREAD

**Issue by 0xJWLabs** [BetterDiscord/BetterDiscord#1767]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

Since Luau (superset of Lua) is expanding, I'd like to see that BetterDiscord support their syntax in codeblock.

**Comment by Riddim-GLiTCH** [comment]
Do you mean the codeblocks as in the the container messages use for code?

```
This is an example codeblock.
```

**Comment by zerebos** [comment]
Codeblock syntax highlighting is handled by Discord itself. A plugin could extend it but it's not something BD itself will handle.

**Comment by 0xJWLabs** [comment]
I’ve seen Vencord able to use luau syntax in their codeblock though, that’s why I asked here if BetterDiscord able to do it too

**Comment by Riddim-GLiTCH** [comment]
Are you sure that wasn't just stock discord behavior? Because I'm pretty sure vencord doesn't touch codeblocks either. I know they have a plugin to enhance them but that plugin does not *add* extended language support.
