### ISSUE TITLE
[Bug] Maximizing BetterDiscord doesn't work as expected on Windows

### ISSUE THREAD

**Issue by Nivyan** [BetterDiscord/BetterDiscord#1772]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

If you maximize BetterDiscord on Windows, it doesn't behave like expected.

In Windows, when you maximize a window it's "locked" in place and cannot be moved unless you grab the top of a window. Additionally, you cannot resize the sides or bottom by dragging them. But BetterDiscord does and generally acts like a 'full-size'-window. But doesn't have the 'maximized state'.

### Expected Behavior

Here's a window' expected behavior, demonstrated with Edge, on betterdiscord.app' website:

https://github.com/user-attachments/assets/ea688303-fcbb-4943-94dd-01e9c4c7ee76

1. After maximizing the window, grabbing the top edge of the window 'unlocks' it and allows moving the entire window around.
2. Moving it to the top, maximizes the window again
3. Clicking the sides of the window and then dragging doesn't do anything
4. Double-clicking the top 'bar' puts the window in 'windowed' mode, double-clicking again maximizes it again.
5. Moving the mouse to the top-right corner is hovering over the 'close window' button. moving it to the top-left hovers over whatever is placed up there (in Edge, the user menu button)

### Steps To Reproduce

Here are the same steps done in BetterDiscord:

https://github.com/user-attachments/assets/a9effef3-5ffe-4c49-ad3d-a9b87f63790f

1. Grabbing the top bar in the windowed state correctly moves the window.
2. Maximizing the window and grabbing the top edge resizes the window instead of 'unlocking' it from the maximized state.
3. Doing the same from the side, also resizes the window instead of not doing anything.
4. Double-clicking the top bar doesn't do anything - neither in windowed or maximized state.
5. Moving the mouse to the top-right corner doesn't hover the 'close window' button and instead allows resizing the window. Same thing with the top-left side.

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.10.2

**Comment by zerebos** [comment]
Do you have window transparency enabled?

**Comment by Nivyan** [comment]
> Do you have window transparency enabled?

I did! Disabling window transparency fixed it! ♥ 

If this is intentional, I would've personally preferred this to be disabled by default on windows. Because it is the expected behavior.

**Comment by fowlis** [comment]
This is an issue with Electron, not something intentionally implemented by BD.

**Comment by Riddim-GLiTCH** [comment]
> This is an issue with Electron, not something intentionally implemented by BD.

Just to be clear here, this is neither BD's fault, not Discord's fault. Any other client mod will suffer from this issue because of this limitation in Electron, the platform used by discord, and many other services to bring their web applications to a desktop format. BD can not fix this, Neither can Discord. 


> This is an issue with electron/chromium and not something I can fix, sorry. https://bugs.chromium.org/p/chromium/issues/detail?id=854601
> _Originally posted by @zerebos in https://github.com/BetterDiscord/BetterDiscord/issues/362#issuecomment-638200707_

This issue has sadly not been adressed in years and it seems unlikely it will see any attention soon as the electron project has other priorities.

**Comment by zerebos** [comment]
Window transparency is disabled by default.

**Comment by Nivyan** [comment]
> Window transparency is disabled by default.

Thank you for figuring this out! I was looking through everything and couldn't find a culprit. Ie. a plugin or theme that enabled this option, but I must've done it myself and forgot about it.
