### ISSUE TITLE
[Bug] installer cannot find discord

### ISSUE THREAD

**Issue by mub-drk** [BetterDiscord/BetterDiscord#1774]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

![image](https://github.com/user-attachments/assets/9fc6f322-a200-42bd-83e7-47f65b18b2ba)
discord was installed in my pc and was working perfectly with BD  , after today's upgrade it's not working any more , i tried to repair BD but ***it didn't work***

### Expected Behavior

it should detect discord normally , I have updated discord and reinstalled BD before ,this didn't happed to me .

every time was perfect ,***but this discord update broke it***

### Steps To Reproduce

Discord ver : stable 335398 (5f5f9be) Host 1.0.9166 x64 (53429) Build Override: N/A Windows 11 64-bit (10.0.22631)

BD ver : stable ,v1.3.0

with this theme : https://github.com/mub-drk/discord-conf/blob/main/personal-green.theme.css
and plugin : theme repo, plugin repo

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.3.0

### Anything else?

i have tried this :https://docs.betterdiscord.app/users/getting-started/troubleshooting/   
but didn't work

**Comment by KingGamingYT** [comment]
Follow these steps.
![image](https://github.com/user-attachments/assets/bffd449c-e63f-4684-b363-bb6a31bb42c0)

**Comment by Riddim-GLiTCH** [comment]
Also this is the wrong repo to open this type of issue in. This should have been in [`BetterDiscord/Installer`](https://GitHub.com/betterdiscord/installer) instead.


Eyes are useful. Use them.
