### ISSUE TITLE
[Bug]I encountered an error while installing the Windows version of BetterDiscord

### ISSUE THREAD

**Issue by wstc1997** [BetterDiscord/BetterDiscord#1775]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

当我安装BatterDiscord的时候，它在下图所示的页面卡主无法进行下一步
————————————————————————————————
When I installed BatterDiscord, it got stuck on the page shown below and couldn't proceed to the next step

![image](https://github.com/user-attachments/assets/ebb12bcd-7f76-4694-adb4-e148b91f9410)

### Expected Behavior

我想要知道该如何操作来解决这个问题
——————————————————
I want to know how to solve this problem

### Steps To Reproduce

1.我的PC使用的是Windows11操作系统
2.能够准确的识别到Discord的安装目录
——————————————————
1. My PC uses Windows 11 operating system
2. Can accurately identify the installation directory of Discord

![image](https://github.com/user-attachments/assets/f1437466-a73e-46e2-8db4-267554c1a3c3)

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.3.0

**Comment by Riddim-GLiTCH** [comment]
First of all, this is not the installer repo. This issue should have been in [`BetterDiscord/Installer`](https://GitHub.com/betterdiscord/installer)

Someone please transfer this issue.

Second, this just seems like a slow network as you don't report any errors during the download step.
