### ISSUE TITLE
[Bug] the repos dont show in discord

### ISSUE THREAD

**Issue by Tenelux01** [BetterDiscord/BetterDiscord#1781]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

i redownloaded the repo files but i still cant see them. i can manage my plugins an themes in the app but the repos arent a visible option.  im sorry, i would LOVE to ask this in the discord, but apparently the ban is fr an not timed like the other servers i was able to rejoin. my acct was hacked an "i" was banned for spamming steam links. i fixed the prob within an hr too it was some mf in brazil

### Expected Behavior

possibly a reinstatement into the discord server along with some help with my repos?

### Steps To Reproduce

idk. this is a bug report when i just wanna ask a simple question, this is teh only way i see fit as of yet

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.10.2

### Anything else?

the prob has been there for how ever long it has idk. i just noticed it not working cause GameActivityToggle isnt working. the repo file were still in the plugins folder cause i chose to replace them

**Comment by zerebos** [comment]
This is not a feature of BD currently, it is your plugins that are broken.

**Comment by Tenelux01** [comment]
It was at least implemented in the past cause i would always search in the app for new stuff. so has it been taken out or is it actually, a problem with betterdiscord? the repo files are still fairly recent, september of 2024

**Comment by zerebos** [comment]
Plugin and Theme repo have never been a feature of BD.
