### ISSUE TITLE
[Bug] Disabeling a theme with invalid name will disable wrong theme if two or more exist

### ISSUE THREAD

**Issue by Night9072** [BetterDiscord/BetterDiscord#215]
**Describe the Bug**
Disabling a theme with invalid name while another theme with invalid name is active will disable the wrong theme due to the fact they both share the same ID ("-")

**To Reproduce**
* Create and enable 2 themes as shown in screenshot 1
* Disable the theme you enabled last (or bottom in dev-tools)

**Expected Behavior**
Expected behaviour would be to have the correct theme be disabled, but because both themes share their identifier, simply the first one in the DOM will be removed.

**Screenshots**
1:
![screenshot 1](https://user-images.githubusercontent.com/51855329/59802436-5b66a680-92e9-11e9-9b94-c3c1d0678113.png)

2:
![screenshot 2](https://user-images.githubusercontent.com/51855329/59802513-7507ee00-92e9-11e9-8e88-f2068ab0a616.png)

**Discord Version**
Stable, not tested on others

**Additional Context**
A proposed fix would be to ensure all themes have a unique identifier, so only the correct theme will be removed.

**Comment by rauenzi** [comment]
I'm okay with this--don't use bad names for themes.

**Comment by MasicoreLord** [comment]
To further discourage bad theme names, just reject loading them and make it show an error similar to what happens when the meta is missing.
