### ISSUE TITLE
[Feature] Allow BD on popouts and overlay

### ISSUE THREAD

**Issue by jerkhouri** [BetterDiscord/BetterDiscord#464]
**Describe the Bug**
I want to change the background of the pop out of to green for my stream.
But that only works on discord app, when I click on the pop out, it's seems that the betterdiscord doesn't modify the new windows named "Pop Out".

**To Reproduce**
Add this code into the custom CSS and normally in the web version of discord its working, but not in the discord desktop app.
```
.wrapper-2qzCYF.popout-1MBou-{
    background-color:green;
}
```

**Expected Behavior**
I want to edit the pop out like I do with the discord desktop app.

**Screenshots**
This is the web application with the CSS edits manually
![Screenshot_3](https://user-images.githubusercontent.com/39912632/95838427-0c484e80-0d42-11eb-81a8-f7ddf60128c1.png)

This is the desktop app with the CSS edit in the CSS editor
![Screenshot_4](https://user-images.githubusercontent.com/39912632/95838634-4b769f80-0d42-11eb-9539-d51389dc2f4f.png)

**Discord Version**
Stable 68815 (fdca70b)
BBD 0.3.5
Host 0.0.308
Injector 0.6.2
Windows 10 64-Bit (10.0.18362)

**Additional Context**
It seems that the better discord don't work with pop out..

**Comment by NFLD99** [comment]
As far as I'm aware bbd doesn't inject to popouts or overlays, iirc it's due to how bd runs and having those inject it causes issues.

**Comment by jerkhouri** [comment]
I really hope than can be fixed..  because I use it for my stream :(

**Comment by NFLD99** [comment]
> I really hope than can be fixed.. because I use it for my stream :(

you can use whatever you streaming with to chroma key it out

**Comment by jerkhouri** [comment]
> > I really hope than can be fixed.. because I use it for my stream :(
> 
> you can use whatever you streaming with to chroma key it out

You right, but with a black chroma key, all the shadows in the webcam will be transparent too..
If I use green background-color, the problem can be fixed.

**Comment by jerkhouri** [comment]
> This is not a bug because as @NFLD99 mentioned, BD intentionally does not inject into popouts or the overlay. I'll leave this open as a feature request.

Ok thanks for your answer.. 

So now I can't change the style of the pop out discord ?

**Comment by rauenzi** [comment]
> So now I can't change the style of the pop out discord ?

Correct, BD never allowed for this. I'm not sure if this is even something I will add because BD as a whole would not work in the overlay or popouts. I would essentially need to create a mini-mod that just loads a specific theme.

**Comment by rauenzi** [comment]
This is going to be closed as not-planned

**Comment by DrMcCoy** [comment]
Yeah, I'm going to ask you to please reconsider this decision. This is something I've been looking for for ages, because I actually want to remove the borders/margins in the popout

I'm using Discord for my RPG games, with Foundry VTT as the virtual tabletop and Discord providing voice and video chat. I use the popout window to have both Foundry VTT and my players visible at the same time on the same monitor, but all the wasted black space on the Discord popout has been driving me crazy for the last years. :(
