### ISSUE TITLE
[Feature] Support Discord Development release

### ISSUE THREAD

**Issue by ObserverOfTime** [BetterDiscord/BetterDiscord#520]
**Is your feature request related to a problem? Please describe.**

Bandaged BD does not support the Discord Development release:
```
Uncaught (in promise) TypeError: Cannot read property 'settings' of undefined
    at Object.getSettingGroup (remote.js:1)
    at Dt.initSettings (remote.js:1)
    at Dt.init (remote.js:1)
    at remote.js:1
```

**Describe the feature you'd like**

From a quick look at the codebase, it should be easy to support it.
Here are some patches for `master` and `development` respectively:

```diff
diff --git i/src/modules/dataStore.js w/src/modules/dataStore.js
index f3f81de..b555354 100644
--- i/src/modules/dataStore.js
+++ w/src/modules/dataStore.js
@@ -25,8 +25,8 @@ export default new class DataStore {
             if (!fs.existsSync(this.settingsFile)) return;
             let settings = __non_webpack_require__(this.settingsFile);
             fs.unlinkSync(this.settingsFile);
-            if (settings.hasOwnProperty("settings")) settings = Object.assign({stable: {}, canary: {}, ptb: {}}, {[releaseChannel]: settings});
-            else settings = Object.assign({stable: {}, canary: {}, ptb: {}}, settings);
+            if (settings.hasOwnProperty("settings")) settings = Object.assign({stable: {}, canary: {}, ptb: {}, development: {}}, {[releaseChannel]: settings});
+            else settings = Object.assign({stable: {}, canary: {}, ptb: {}, development: {}}, settings);
             this.setBDData("settings", settings);
         }
         catch (err) {
```

```diff
diff --git i/src/modules/datastore.js w/src/modules/datastore.js
index 6516bb9..7bad07a 100644
--- i/src/modules/datastore.js
+++ w/src/modules/datastore.js
@@ -9,7 +9,7 @@ const releaseChannel = DiscordNative.globals ? DiscordNative.globals.releaseChan
 // =======================
 // %appdata%\BetterDiscord
 //     -> data
-//         -> [releaseChannel]\ (stable/canary/ptb)
+//         -> [releaseChannel]\ (stable/canary/ptb/development)
 //             -> settings.json
 //             -> plugins.json
 //             -> themes.json
@@ -45,7 +45,7 @@ export default new class DataStore {
         const oldData = __non_webpack_require__(oldFile); // got the data
         fs.renameSync(oldFile, `${oldFile}.bak`); // rename file after grabbing data to prevent loop
         const setChannelData = (channel, key, value, ext = "json") => fs.writeFileSync(path.resolve(this.baseFolder, channel, `${key}.${ext}`), JSON.stringify(value, null, 4));
-        const channels = ["stable", "canary", "ptb"];
+        const channels = ["stable", "canary", "ptb", "development"];
         let customcss = "";
         let favoriteEmotes = {};
         try {customcss = oldData.bdcustomcss ? atob(oldData.bdcustomcss) : "";}
```

**Additional context**

Here's the download link for [Linux](https://discord.com/api/development/download?platform=linux&format=tar.gz).

**Comment by Tropix126** [comment]
Might add that it's also available through windows and macOS. Just hidden behind an obscure api download link: [https://discordapp.com/api/download/development?platform=win](https://discordapp.com/api/download/development?platform=win)

**Comment by ObserverOfTime** [comment]
So they have both `download/{channel}` and `{channel}/download` but the latter is missing the development builds for Windows & MacOS? :thinking:

**Comment by Tropix126** [comment]
Another thing: I think that at the moment their public version of development just leads to the canary endpoint ultimately. You can tell by looking at the build info in settings and I recall reading an official twitter post saying it's abandoned.

**Comment by Tropix126** [comment]
If anyone want's to verify or disprove this feel free to.

**Comment by NeonOverflow** [comment]
> 
> 
> Another thing: I think that at the moment their public version of development just leads to the canary endpoint ultimately. You can tell by looking at the build info in settings and I recall reading an official twitter post saying it's abandoned.

Yeah, that's correct.

**Comment by ObserverOfTime** [comment]
That may be so but some people could be using it.
For what it's worth, it's available via [winget](https://github.com/microsoft/winget-pkgs/tree/master/manifests/Discord/DiscordDevelopment) on Windows and the [AUR](https://aur.archlinux.org/packages/discord-development) for Arch Linux.

**Comment by NeonOverflow** [comment]
I made a [pull request](https://github.com/rauenzi/BBDInstaller/pull/19) that should work with development. The only issue is that you have to remove your settings file otherwise it doesn't work. This is because the settings file doesn't contain an entry for development.

**Comment by rauenzi** [comment]
I do not see the need to support an abandoned build.

**Comment by NeonOverflow** [comment]
> 
> 
> I do not see the need to support an abandoned build.

The build isn't abandoned, it just forks back to Canary. No real reason not to support it, basically no additional effort is required.

**Comment by rauenzi** [comment]
> it just forks back to Canary

Does this mean it has no difference from Canary?

**Comment by Tropix126** [comment]
> > it just forks back to Canary
> 
> Does this mean it has no difference from Canary?

As far as I know they're identical, although I don't see much harm in adding support through manual injection.

**Comment by Kyza** [comment]
The only difference should be the Electron version or native module versions iirc. Otherwise it runs off of Canary's endpoints.

**Comment by rauenzi** [comment]
> The only differences should be the Electron version or native module versions iirc. Otherwise it runs off of Canary's endpoints.

So a release channel that is barely used and is essentially a carbon copy of another channel?

**Comment by Kyza** [comment]
> > The only differences should be the Electron version or native module versions iirc. Otherwise it runs off of Canary's endpoints.
> 
> So a release channel that is barely used and is essentially a carbon copy of another channel?

Yep. Discord themselves say it's discontinued which is kinda strange since they still update it separately from Canary.

**Comment by xHyroM** [comment]
> I made a [fork of the installer](https://github.com/OCsonic/Installer) that adds it as an option. I've not tested this on Windows, But it works fine on Arch GNU/Linux

It works fine, but when I turn on the client, BetterDiscord crashes immediately.

**Comment by rauenzi** [comment]
As this is unsupported by Discord, I will not be officially supporting it
