### ISSUE TITLE
[Suggestion] github bug reports and feature requests template enhancements

### ISSUE THREAD

**Issue by developomp** [BetterDiscord/BetterDiscord#613]
**Is your feature request related to a problem? Please describe.**
I see a lot of people creating duplicate gh issues. This could be prevented by adding a simple request in the gh issue template.

**Describe the feature you'd like**
A simple message will be added on top of the current gh issue template:

> Before making a suggestion/Bug report, make sure no one else has created a similar issue before. If you have anything to add, kindly head to the corresponding issue page and add a comment/reaction. This make everything organized and make the lives of the developer much easier. Thank you for your help at making BBD better :D
You may delete this text before submitting the issue

**Additional context**
None

**Comment by developomp** [comment]
Also, I want to say thank you to the amazing developers who maintains this project. This is definitely one of the most useful projects on github.

**Comment by rauenzi** [comment]
Try to install BetterDiscord using this new beta installer: https://github.com/BetterDiscord/Installer

**Comment by developomp** [comment]
@rauenzi thank you for your feedback but that is not what my issue was about. Please consider taking a moment to read my suggestion when you're done handling BD restructuring. Thank you for your work :)

**Comment by rauenzi** [comment]
Sorry for misreading, I ended up just spamming through all the duplicates.

Unfortunately knowing the "community" around this project, I don't believe having a message there to check for duplicates will cause them to do anything. However it is probably good practice to add nonetheless

**Comment by rauenzi** [comment]
Issue templates have been refreshed
