### ISSUE TITLE
[Bug] better discord not appear in the discord settings Mac

### ISSUE THREAD

**Issue by pipebaco** [BetterDiscord/BetterDiscord#676]
when i install better discord, then i open discord and it doesnt appear the settings for better discord
![Captura de pantalla 2021-04-09 a las 12 11 45 a m](https://user-images.githubusercontent.com/82193618/114123359-86f4bf80-98c8-11eb-933f-a02edf781925.png)

**Comment by pipebaco** [comment]
Starting Install...

Creating required directories...
✅ Directory exists: /Users/rolo/Library/Application Support/BetterDiscord
✅ Directory exists: /Users/rolo/Library/Application Support/BetterDiscord/data
✅ Directory exists: /Users/rolo/Library/Application Support/BetterDiscord/themes
✅ Directory exists: /Users/rolo/Library/Application Support/BetterDiscord/plugins
✅ Directories created

Downloading asar file
✅ Package downloaded

Injecting shims...
Injecting into: /Applications/Discord.app/Contents/Resources
✅ Injection successful
✅ Shims injected

Restarting Discord...
Attempting to kill Discord
✅ Discord restarted

Install completed!

**Comment by rauenzi** [comment]
Fully close Discord manually and relaunch it.

**Comment by pipebaco** [comment]
i tried twice but nothing happens

**Comment by pipebaco** [comment]
> Fully close Discord manually and relaunch it.

i tried twice but nothing happens

**Comment by rauenzi** [comment]
Please reinstall

**Comment by pipebaco** [comment]
> Please reinstall

i tried too but nothing happen

**Comment by rauenzi** [comment]
Please show some more info if you'd like this debugged. Things like the console logs, versions, etc.

**Comment by pipebaco** [comment]
> Please show some more info if you'd like this debugged. Things like the console logs, versions, etc.

Better dicord 1.1.1 
Mac 1.11.6
Discord 69.0

**Comment by rauenzi** [comment]
Is this issue still valid with the latest version?

**Comment by pedro9006** [comment]
Yes, this is still valid with the latest version of BetterDiscord. It's happening to me too. I tried using BandagedBD, but that only made me unable to use my microphone, and made me unable to screenshare.

**Comment by pedro9006** [comment]
I've also tried reinstalling BetterDiscord, reinstalling BandagedBD, Repairing Betterdiscord, Repairing BandagedBD, running discord as an administrator, logging out and back into my account, and restarting discord, all of which didn't fix the problem. I had to uninstall BandagedBD to get my microphone and screenshare working again.

**Comment by rauenzi** [comment]
> reinstalling BandagedBD

BandagedBD is long dead, any use of that installer now can drastically mess up your install
