### ISSUE TITLE
[Bug] mediainfo.js library isn't working with BD

### ISSUE THREAD

**Issue by arg0NNY** [BetterDiscord/BetterDiscord#765]
I'm trying to use `mediainfo.js` library in my plugin through command `BdApi.linkJS('mediainfoJS', 'https://unpkg.com/mediainfo.js/dist/mediainfo.js');`, but can't access `MediaInfo()` function not from a plugin, not from DevTools.

![Discord_7AoJSqaXhW](https://user-images.githubusercontent.com/52377180/117552598-a113f000-b076-11eb-9443-419b4a1d1b59.png)
![Discord_BbOb8oKkXm](https://user-images.githubusercontent.com/52377180/117552604-a83afe00-b076-11eb-9a74-369288f95c82.png)
mediainfo.js is also shows up in Sources panel in DevTools, but inaccessible for some reason.

I tested this library without BD enabled and was able to access `MediaInfo()` function. What could be the problem?

**Comment by rauenzi** [comment]
Looks like the injection script is trying to use Monaco's in-built amd module loader.

**Comment by Argonn2048** [comment]
I think this monaco script is used by some of my other installed plugins and not related to mediainfo.js.

I also tried to disable all my other plugins to eliminate the possibility of a plugin conflict, but that didn't help.

This is some conflict with BD i think.

**Comment by Argonn2048** [comment]
Any ideas how can i get through this?

**Comment by rauenzi** [comment]
> I think this monaco script is used by some of my other installed plugins and not related to mediainfo.js.

Monaco is the css editor used in BD


> Any ideas how can i get through this?

I would recommend using your own bundle of it, but I don't understand the need for it.

**Comment by Jkmcameron** [comment]
I have never once gotten `BdApi.linkJS` to work. I have verified using javascript file that I hosted myself that when the appropriate url is sued in a browser the http get request is received by the server and the file is delivered while on the other hand `BdApi.linkJS` adds the script tag to the header as you've shown here there is never an http get request sent to the server and the file is never delivered
