### ISSUE TITLE
[Feature] Plugin/Theme Embed Sharing

### ISSUE THREAD

**Issue by ThatsNotAName** [BetterDiscord/BetterDiscord#771]
**Is your feature request related to a problem? Please describe.**
Sharing plugins can be confusing and sometimes plugins/themes are named similarly to others and when talking about them people could find the wrong one. Over all it's just a QOL feature not too important if it can't be done. Especially how the plugin repo only currently has a little over 100 plugins.

**Describe the feature you'd like**
It'd be really nice to be able to share plugins/themes with people that also have Better Discord from the plugin/theme repo so you can use some format of text or a share button that lets you send interactable plugin/theme embeds just like how they look in the plugin repo. For people without Better Discord I'd imagine they would just look like a bunch of text depending on how you'd go about implementing the feature.

**Additional context**
Here's a conversation my friend and I had about it that shows visually kind of what I'm talking about

 ![image](https://user-images.githubusercontent.com/32344342/117826812-74aad000-b23e-11eb-8461-7d2f35cb997d.png)

**Comment by Tropix126** [comment]
This is a neat little idea, but it'd have to wait for the store to be released probably since that's higher priority atm. Also, you can *sort* of do this with current embeds to a theme on http://betterdiscord.app/, since it has a basic thumbnail/description. I also plan to add a like/download counter on the embed itself through the site 👍.

**Comment by ThatsNotAName** [comment]
> This is a neat little idea, but it'd have to wait for the store to be released probably since that's higher priority atm. Also, you can _sort_ of do this with current embeds to a theme on http://betterdiscord.app/, since it has a basic thumbnail/description. I also plan to add a like/download counter on the embed itself through the site 👍.

Oh that's super cool to know. I didn't know there was a store coming soon either.
Could you go into a little more detail about how you might do it with the themes? I briefly looked at the site and the themes on it but didn't catch a quickly intuitive way to grab something and paste it. Is it a little more complicated than that?

**Comment by Tropix126** [comment]
> > This is a neat little idea, but it'd have to wait for the store to be released probably since that's higher priority atm. Also, you can _sort_ of do this with current embeds to a theme on http://betterdiscord.app/, since it has a basic thumbnail/description. I also plan to add a like/download counter on the embed itself through the site 👍.
> 
> Oh that's super cool to know. I didn't know there was a store coming soon either.
> Could you go into a little more detail about how you might do it with the themes? I briefly looked at the site and the themes on it but didn't catch a quickly intuitive way to grab something and paste it. Is it a little more complicated than that?

![image](https://user-images.githubusercontent.com/42101043/117830493-4d9dcf80-b239-11eb-8a84-7f2c4dd09677.png)
There's no way to instantly download it of course, but you get a basic preview of the theme and some details about it. I'm also going to add likes/download stats.

**Comment by rauenzi** [comment]
Realistically this could be done as an extension of what @Tropix126 showed there, BD could simply modify the embed of plugin and theme links to our website to include buttons like "Install Now"

**Comment by rauenzi** [comment]
Included in #758
