### ISSUE TITLE
[Feature] Overview of Plans for Better Discord

### ISSUE THREAD

**Issue by siltentassasin** [BetterDiscord/BetterDiscord#819]
Can you maybe make a roadmap for Better Discord for the Plans and in which version which commes?

**Comment by rauenzi** [comment]
You can now view a current roadmap of what features and bugs we are working on through GitHub Projects. https://github.com/orgs/BetterDiscord/projects/2

We will not be providing any guarantees about which things will come in which versions beyond "seeing it in done means it has been fully integrated for next version"

Keep an eye on our projects page for when we publicize our plans for the BD refactor.
