### ISSUE TITLE
[Bug] Discord Canary LastUpdate JavaScript Error

### ISSUE THREAD

**Issue by Danik2343** [BetterDiscord/BetterDiscord#821]
**Describe the Bug**

Last Canary Update JavaScript Error
**To Reproduce**

Update Canary to the Last Version
**Expected Behavior**
Discord Canary  with BetterDiscord started without errors and e.t.c

**Screenshots**

Screenshot:http://yapx.ru/u/MiZPT
**Discord Version**

Canary
**Additional Context**
I updated the discord and an error appeared, now the Canary version with BetterDiscord does not work, please fix the error.

**Comment by koumaza** [comment]
It happened on my device too.
![screenshot](https://user-images.githubusercontent.com/44153315/120687825-5b174400-c4dd-11eb-98a0-f506a1b3787f.png)

**Comment by cyckl** [comment]
Can reproduce, latest canary as well

**Comment by trueblue222** [comment]
![image](https://user-images.githubusercontent.com/55673470/120690436-34bcbe80-c473-11eb-9354-764237f12927.png)

**Comment by trueblue222** [comment]
I think this is part of it? i'm on canary too and it gives me this error

**Comment by cyckl** [comment]
Probably just some change on the electron side looking at the error, will likely require some change in the BD code to fit the new change, looks pretty straight forward

**Comment by rauenzi** [comment]
Discord's latest update includes pushing Electron 13, please be patient while fixes are made. In the meantime use stable or just uninstall BD on Canary.

**Comment by DriverPneuma** [comment]
![Error 6_3_2021 6_51_52 PM](https://user-images.githubusercontent.com/77202554/120726235-3a2efe80-c49d-11eb-9d51-ffa2bd9cb98d.png)
I also have this issue

**Comment by SSDMT-DEV-HARLEY** [comment]
Same issue Here I reinstalled and tried running it again but all the error mentioned above is exactly the same on my end :D

**Comment by VistaOnTen2007** [comment]
looks like we had to stick on ptb for now...
![Screenshot_12](https://user-images.githubusercontent.com/60382442/120754479-ed980180-c536-11eb-8776-db2e04767c0f.png)

**Comment by rauenzi** [comment]
If you are also experiencing the same issue react with 👍 to the original issue, everyone posting the same issue and the word "same" is not helpful.

**Comment by czSmoG** [comment]
i have the same issue
but i have latest canary version
