### ISSUE TITLE
[Feature] Adding emotes via API

### ISSUE THREAD

**Issue by Lombra** [BetterDiscord/BetterDiscord#824]
**Is your feature request related to a problem? Please describe.**
Part of the reason I submit this is that the bundled emotes don't seem to get updated since some time back.

**Describe the feature you'd like**
Add arbitrary emotes, providing a keyword and an image URL for each. Much preferably (due to the aforementioned reason) in a emote category that takes precedence over the default categories.

**Comment by rauenzi** [comment]
We don't own the emote repositories, so this is not something we can do
