### ISSUE TITLE
[Enhancement] Assets folder for themes and plugins

### ISSUE THREAD

**Issue by developomp** [BetterDiscord/BetterDiscord#835]
**Is your feature request related to a problem? Please describe.**
Themes have to load images from the URL every time discord is opened/reloaded. This is both unreliable and slow. A better way is to load images from local storage.

**Describe the feature you'd like**
When we install themes, we should be able to install them either as a folder or a file. For folders, it should end with `.theme`, just like files have to end with `.theme.css`. In the folder, there is a main.css file that will be loaded and other assets that can be loaded in CSS using relative paths.

Example:
```
myTheme.theme/
├── customFont.ttf
├── background.png
└── main.css
```

**Additional context**
This could be used to add README.md files, put variables in a separate file, make themes modular so each part can be toggled by commenting out a single line in main.css, and so much more.

+EDIT
This also makes quickly testing themes much easier.

**Comment by rauenzi** [comment]
This seems a duplicate of #658, no?

**Comment by developomp** [comment]
> This seems a duplicate of #658, no?
No, it is not. Suggestion #658 is a purely front-end grouping whereas my suggestion is purely back-end. That is, it creates an actual directory in the file system.

To add to my suggestion, the main reason why I am suggesting this feature is to make themes more reliable by removing the need for images to be uploaded on the internet for themes to work. So basically, I am proposing a change of structure from one-file-per-theme to one-folder/file-per-theme. The same applies to plugins too.

**Comment by Puv1s** [comment]
This would need major rewrite of the addon system both in core BD and the new website and upcoming store. Though it's an viable idea i don't think BD will be doing change like this any soon

**Comment by developomp** [comment]
The fact that there is little to no demand for this feature does not help either : (

**Comment by rauenzi** [comment]
Sorry I should have linked #549

**Comment by developomp** [comment]
It is indeed a duplicate. Will close it now.
