### ISSUE TITLE
[Bug] Cannot Hide Gift and GIF Buttons

### ISSUE THREAD

**Issue by cinerea0** [BetterDiscord/BetterDiscord#841]
**Describe the Bug**
Enabling the "Hide Gift Button" and "Hide GIF Button" options does not actually hide those buttons.

**To Reproduce**
Use BetterDiscord v1.1.1 with Discord v0.15 on Linux and enable the above listed options.

**Expected Behavior**
The Gift and GIF buttons should be hidden when their respective options are enabled.

**Screenshots**
![bd_error](https://user-images.githubusercontent.com/49368915/122597551-09cd8f80-d05b-11eb-82a0-8e2c5c3b61d6.png)

**Discord Version**
Stable

**Comment by smowtenshi** [comment]
Try https://github.com/rauenzi/BetterDiscordApp/issues/559#issuecomment-838392345

**Comment by GuardianLiarus** [comment]
can confirm the option doesn't work here as well.

**Comment by dav1312** [comment]
### Use [RemoveChatButtons](https://betterdiscord.app/plugin/RemoveChatButtons)

**Comment by cinerea0** [comment]
@dav1312 Can confirm this works as long as the "CSS-Only Mode" option is enabled. Since it seems like the main devs are unlikely to fix this, I'm going to close this with the above as the best solution.

**Comment by dav1312** [comment]
> I'm going to close this with the above as the best solution.

Please do not close it. Until it gets fixed or the options get removed it should still be open.

**Comment by smowtenshi** [comment]
It was removed in [1.5.0](https://github.com/BetterDiscord/BetterDiscord/blob/main/CHANGELOG.md#removed-1), I think it's fair to close it.

**Comment by cinerea0** [comment]
Fair enough.
