### ISSUE TITLE
[Bug] Ctrl Commands Crash BD

### ISSUE THREAD

**Issue by ItzYaBoiMythOfMine** [BetterDiscord/BetterDiscord#851]
**Describe the Bug**
When better discord is open, im in a vc, and in a game, Ctrl+ commands crash Better Discord. 

**To Reproduce**
Get in a vc, go into a game, and press Ctrl + any key (for me it happened with Ctrl+Shift and Ctrl+Tab

**Expected Behavior**
Better discord doesnt crash? 

**Discord Version**
Stable

**Comment by rauenzi** [comment]
This is not occurring for me, can you provide the versions in the bottom left of settings?

**Comment by ItzYaBoiMythOfMine** [comment]
> This is not occurring for me, can you provide the versions in the bottom left of settings?

My better discord is in version 1.1.1

**Comment by rauenzi** [comment]
I need all the versions there please.
