### ISSUE TITLE
[Bug] FPS drop as soon as I installed it

### ISSUE THREAD

**Issue by vvlup** [BetterDiscord/BetterDiscord#855]
Before I installed betterdiscord, I could run Minecraft at 180-190 FPS. After I installed betterdiscord, my frames fluctuate from 100-190. It’s stable for 10 seconds then drops down, then will randomly shoot back up. I’ve completely uninstalled betterdiscord and still have this FPS issue.

Discord version - Stable

**Comment by rauenzi** [comment]
If you've uninstalled BD (and confirmed as such) it is unlikely BD is the culprit. Have you checked your hardware acceleration setting in Discord's settings?
