### ISSUE TITLE
[Bug] BetterDiscord on stable tends to build up lag before crashing when left open for long periods

### ISSUE THREAD

**Issue by k4zo** [BetterDiscord/BetterDiscord#859]
**Describe the Bug**
When leaving Discord open with BD installed for long periods of time (1 day or more, since I keep my PC on overnight), it tends to get more and more slow before outright crashing

**To Reproduce**
Have at least 15 or so plugins, even if none of them take up many resources
Leave Discord running for at least 24 hours, some time after 24 hours the client will be extremely slow compared to when it was first opened
Attempt to switch servers or channels very quickly or scroll a channel very rapidly, the client will crash
Upon restarting, you have to kill Discord and start it again to get BetterDiscord back up since BD will disable itself

**Expected Behavior**
The client remains at a steady performance level no matter how long ago it was opened

**Screenshots**
N/A, just the standard "BetterDiscord crashed your client and has disabled itself" message

**Discord Version**
Stable

**Additional Context**
When my client started to get very slow, I tried to disable the most resource-hogging plugins to attempt to fix it, but it seems it happens no matter which plugins are on or off

**Comment by ogoidmatos** [comment]
By the sound of it, maybe a memory leak in the main app or one of the plugins?

**Comment by ImSkully** [comment]
Can confirm, been experiencing this for the past few days with BD, specifically when screen sharing - I've monitored the Discord process on task manager and the build up of memory raises up towards 5GB after extensive usage and Discord itself becomes very unresponsive.

**Comment by snessim** [comment]
Can confirm that this occurs with no plugins or themes loaded. Having plugins loaded, however, seems to significantly exacerbate the problem leading to lag in under 10 minutes and crashes in under an hour. The most significant contributors I've seen are DB's plugin/theme repos, which seem to store repo data in memory.

**Comment by HotMonkeyWings** [comment]
Bumping this again, its really bad right now and I'm even considering uninstalling BD till its fixed. Its kind of annoying to have to restart discord mid-call.

**Comment by StayALIV3** [comment]
I think I am also experiencing lag spikes and crashing tendencies that correlate with time. It's likely that I am also experiencing memory leaks.

**Comment by Astropulse** [comment]
Bumping, crashes every couple of hours in the way described above, disabling/removing plugins does not fix the issue, only slightly increases the duration between lag buildups and crashes. Hoping for a concrete solution/official patch for this soon.

**Comment by ShanaGartrex** [comment]
Experiencing this issue as well that last few days. Still searching for a solution as I want to keep using BD instead of the base client.

**Comment by k4zo** [comment]
bumping again because it went from every couple days to at least every 2 or so hours

**Comment by GaiaB0t** [comment]
additional bump, happens for me repeatedly, sometimes within an hour crashes
also seems to happen faster if you change channels often

**Comment by soHa3aven** [comment]
Bumping AGAIN, the crash time has shortened exponentially once again (crashes in about 5-10 minutes). I have a plugin enabled to force-refresh discord when it starts to crash out but calls and even normal messaging are incredibly unstable. Switching between servers/channels/DMs is incredibly slow and causes crashes. Happens with plugins or without.

**Comment by k4zo** [comment]
bumping appears to do absolutely nothing so i just opened a new issue with the same problem

**Comment by rauenzi** [comment]
> bumping appears to do absolutely nothing so i just opened a new issue with the same problem

Neither "bumping" nor opening a new issue changes anything. If I cannot find the source of the issue, I cannot fix it.

**Comment by seirdotexe** [comment]
Been having the same issue suddenly, 1.5GB of ram being used. I just uninstalled.

**Comment by PinguLinux** [comment]
1 year since this issue was created and still no signs of any fix...

**Comment by GaiaB0t** [comment]
> > bumping appears to do absolutely nothing so i just opened a new issue with the same problem
> 
> Neither "bumping" nor opening a new issue changes anything. If I cannot find the source of the issue, I cannot fix it.

well unfortunately for all of us, there isnt exactly anything we can provide for reasoning/cause of it other than mem leak _somewhere_ in BD

**Comment by psouza4** [comment]
Yeah, a developer myself and there's just no tools to produce any meaningful data to report with.  No plugins, no themes/skins, it'll lag the heck out of Discord and eventually crash.

**Comment by GaiaB0t** [comment]
fun fact
this bug indeed still happens even when BD is fully borked as it is at this time
BD doesnt load at all visually, but the crash eventually builds up as you switch servers often enough, and then boom the same "Betterdiscord has disabled itself" message pops up, despite seeming that BD isnt loaded

**Comment by GaiaB0t** [comment]
as of 1.8.0 I have yet to have any crashes, so they've certainly *reduced* the issue, if they have not completely fixed it.
over the next few days I will report if I get any crashes at all

**Comment by rauenzi** [comment]
This should hopefully be resolved with 1.8.0, we spent a lot of time tracking down and fixing these types of issues. Plugins may still have issues though.
