### ISSUE TITLE
[Bug] Emotes like "voltz" should follow discord system

### ISSUE THREAD

**Issue by josh-65** [BetterDiscord/BetterDiscord#860]
**Describe the Bug**
When typing voltz in discord it will change an emote

**Expected Behaviour**
It should only change if using :voltz: or at least have an option

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/124308065-9c445780-db60-11eb-9ddd-d5e2be4c7f16.png)

**Discord Version**
Stable 89294 (f4e00f9)

**Comment by rauenzi** [comment]
The intention is for them to work like Twitch where `:` is not needed. If you don't want the emotes, simply disable them.
