### ISSUE TITLE
[Bug] Crash client with fullscreen application streams

### ISSUE THREAD

**Issue by Sheodar** [BetterDiscord/BetterDiscord#861]
**Describe the Bug**
When streamer which u see just now press alt-tab, u'll insta crash. It works only with FULLSCREEN application mode (not BORDERLESS)

**To Reproduce**
1) Open any stream with FULLSCREEN application (not BORDERLESS).
2) Streamer press alt+tab and i'm crashing
*I tested this in Dota 2*

**Expected Behavior**
Discord shouldn't crash

**Discord Version**
Stable 89496 (99f4f91)

I could send logs, but i don't know where i can found this.

**Comment by IGP** [comment]
Having this happen as well. Same circumstances and version. Disabled every plugin that has updated since it started occurring (2-3 days ago) but the behavior persists.

**Comment by Sheodar** [comment]
Yeah, It works with exit the game too. Tested this just now.
One more thing: I remove betterdiscord fully (uninstall + removed from %appdata% + clear registry).  Clean install didn't help me.

**Comment by patrickh39** [comment]
Repaired BetterDiscord/reinstalled, and disabled all plugins as well but still faced with the issue.

**Comment by dav1312** [comment]
Do you have this issue without BetterDiscord installed too?

**Comment by Sheodar** [comment]
Only with BetterDiscord. When i uninstalled this fully - discord wan't crash.

**Comment by dav1312** [comment]
This may also happen when the other user enables his camera

**Comment by xNightWulf69** [comment]
This also happens sometimes, but not all the time, when 2 or more people have their camera on at the same time.
For instance, in a call with someone, they have their camera on, I'll turn mine on and their Discord will insta crash
or if I have my camera on, and they then turn theirs on, mine will crash (Both me and the other people have BD installed)

**Comment by Adrian0508** [comment]
Same, currently i even cannot Activate it again :/

**Comment by Don-Laliberte** [comment]
I have this exact problem as well repairing did nothing

**Comment by dav1312** [comment]
## If you have this issue just wait patiently while the developers look into it

### There isn't a solution for the moment other than not watch streams

### If you have the same problem, react with 👍 to the first post. Avoid comments like "same" or "me too". Thank you.

**Comment by ImDavyd** [comment]
Yup this is a big issue lol.
Hope the devs are gonna fix it asap cuz it's annoying af.

**Comment by PeriPerry** [comment]
The camera facet of this issue also happens regardless if you have the person's camera disabled when they turn it on.

**Comment by mwittrien** [comment]
if you are expierencing crash issues while being in a voice call or streamsharing do this (this will also fix BD not working on canary)

1. Go to `%appdata%/betterdiscord/data`
2. Download this file
https://cdn.discordapp.com/attachments/820640899712286740/861688652890898473/betterdiscord.asar
3. Move it to the data folder replacing the old `betterdiscord.asar` file
4. Restart Discord

Done by Strencher

**Comment by rauenzi** [comment]
The fix linked above was integrated
