### ISSUE TITLE
[Feature] NDI Support

### ISSUE THREAD

**Issue by mannaggacardarell** [BetterDiscord/BetterDiscord#862]
Hi, is there a possibility to add NDI to discord? https://www.newtek.com/ndi/
Integrating NewTek's NDI into discord would make recording video calls a lot easier, especially with overlays, since the positions of people in the call wouldn't jump around all the time. It's a niche feature, but skype has it so I figured I'd ask

**Comment by Technetium1** [comment]
@mannaggacardarell what exactly is the hypothetical end goal of integration?

**Comment by mannaggacardarell** [comment]
A lot of ppl use discord to make some videoalls, expecially in live streaming. With ndi u have the total controll of cameras. For example, a big problem is if someone crashed and so camera positioning change. With ndi you have every single camera, and u should just capture the discord windows and crop it, u have the total control of every camera.

**Comment by Technetium1** [comment]
It seems like the easiest solution would be to create a plugin to manually change the camera's position, or allow dragging them around. At first glance it seems like it would be a large pain to add this via betterdiscord. (see https://www.ndi.tv/sdk & https://github.com/nariakiiwatani/ofxNDI & https://github.com/leadedge/ofxNDI )

In the meantime, you can vote for the feature here https://support.discord.com/hc/en-us/community/posts/360034176212-Please-add-NDI-Support-to-Discord

**Comment by rauenzi** [comment]
This something for Discord to implement.
