### ISSUE TITLE
[Bug] Edit button for Themes and Plugins freezes when opened

### ISSUE THREAD

**Issue by jacobvillorente** [BetterDiscord/BetterDiscord#864]
**Describe the Bug**
When the Edit button for a plugin or theme is clicked, the window to edit opens, but is blank and freezes on the window. The buttons are not functional and the window cannot be moved, resized, or closed. The edit window is blank and has no place for text input. 

**To Reproduce**
1. Open Discord settings
2. Click "Plugins" or "Themes"
3. Click the Edit icon (looks like a pencil) on any theme or plugin

**Expected Behavior**
When the Edit button is pressed,t he user should be able to edit the code of the theme or plugin to the user's desire. 

**Screenshots**
[https://drive.google.com/file/d/17W5gGd2dWirilQySEPpm_E2TvZonqfND/view?usp=sharing](url)

**Discord Version**
Discord Stable Build 89550
Windows 10 64-bit

**Additional Context**
BetterDiscord v1.1.1

**Comment by dav1312** [comment]
![image](https://user-images.githubusercontent.com/63931154/124480253-5b8a4f80-dda7-11eb-9791-68de9eec2d29.png)
![image](https://user-images.githubusercontent.com/63931154/124480312-6ba22f00-dda7-11eb-9d10-1556635193c0.png)

**Comment by jacobvillorente** [comment]
Didn't know you could do that, thanks so much!

**Comment by dav1312** [comment]
Please do not close this issue. 
This still needs to be fixed so you don't need to enable custom css for it to work.
