### ISSUE TITLE
[Bug] Better Discord crashes client when another user in a VC quickly toggles their camera on and back off

### ISSUE THREAD

**Issue by osc1997** [BetterDiscord/BetterDiscord#867]
**Bug Description**

Better Discord crashes the Discord client when you are in a voice channel with another user (they don't have to be using Better Discord), and the other user quickly toggles their camera on and off before their camera has time to load on your end.
This issue also occurs if the other user has their camera on before you join the voice channel, and then turn it off quickly after you join (before it has time to load on your end).
This issue no longer occurs once the camera of the other user successfully loads on your end and will now work as expected if the other user quickly toggles their camera. The issue returns when you disconnect and reconnect to the voice channel.
I know this is quite wordy. I recommend watching the video below for a visual explanation.

**Additional Information**

- When Better Discord crashes your Discord client, it automatically disables itself temporarily. However, the issue still occurs even after this temporary disablement.
- This issue does not occur without Better Discord installed.
- This issue still occurs without any plugins installed.

**Steps To Reproduce**

1. Join a voice channel using a Discord client with Better Discord installed on it
2. Have another user in the voice channel toggle their camera on and back off before it has time to load properly
3. Better Discord will crash your Discord client

**Expected Behaviour**

Better Discord shouldn't crash your Discord client.

**Discord Version**

Stable 89550 (3c2108a) Host 1.0.9002
BetterDiscord 1.1.1

**Operating System**

Windows 10 64-Bit (10.0.19041)

**Video**

https://user-images.githubusercontent.com/62695023/124508492-f561f480-ddc7-11eb-93e9-cd2d68b4fe05.mp4

_Apologies for the excessive amount of censoring in the video. I just don't want to leak anything lol._

**Comment by dav1312** [comment]
Fix for Windows can be found [here](https://github.com/rauenzi/BetterDiscordApp/issues/861#issuecomment-874667842)

**Comment by rauenzi** [comment]
Please install to the latest version and see if this insists
