### ISSUE TITLE
[Bug] Crash when maximize the app

### ISSUE THREAD

**Issue by Msadr471** [BetterDiscord/BetterDiscord#868]
**Crash when maximizing the app**
when I try to maximize the app, it crashes and stays maximizing and won't return to the previous state!

**Screenshots**
![image](https://user-images.githubusercontent.com/49529241/124509386-1d148500-dde7-11eb-8573-2bd33c069d5d.png)
![image](https://user-images.githubusercontent.com/49529241/124509393-1f76df00-dde7-11eb-9e76-e39b97f995a4.png)

**Discord Version**
Stable

**Comment by rauenzi** [comment]
Please update to the latest version and see if this persists

**Comment by Msadr471** [comment]
yes still persists

**Comment by Msadr471** [comment]
![Uploading 2.png…]()

**Comment by rauenzi** [comment]
Do you have transparency enabled?

**Comment by Msadr471** [comment]
> Do you have transparency enabled?

YES, it was.😁 after I disable it's working very well. 
thank you sir 👍
