### ISSUE TITLE
[Bug] Discord client crashes when another user in VC ends their stream by closing the streamed app.

### ISSUE THREAD

**Issue by 0ZeroFive5** [BetterDiscord/BetterDiscord#870]
**Describe the Bug**
The bug results in a crash when a stream watched on a client with BetterDiscord gets ended by the streamed application getting closed

**To Reproduce**

1. Get someone in a VC to start a stream of any app.
2. Start watching the stream.
3. The person streaming closes the app being streamed.
4. Discord crashes and restarts without BetterDiscord.

**Expected Behavior**

The stream ends without any crashes

**Discord Version**

Stable

**Comment by dav1312** [comment]
Duplicate of #861
