### ISSUE TITLE
[Bug] FrankerFaceZ emojis doesnt work

### ISSUE THREAD

**Issue by T0biasCZe** [BetterDiscord/BetterDiscord#872]
**Describe the Bug**
FrankerFaceZ emojis dont work. When you write a word that is frankerfacez emoji, it should show the emoji instead of it, but it just shows this image instead:  
![obrazek](https://user-images.githubusercontent.com/44525446/124641535-1ccfc480-de8f-11eb-9b6f-9a05a725d717.png)

**To Reproduce**
enable FrankerFaceZ emojis in settings
write some word, for example "gameboy"
it shows emoji missing icon (image above)
when you disable FrankerFaceZ it shows normally as gameboy

**Expected Behavior**
It will show the gameboy image

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/44525446/124641417-f90c7e80-de8e-11eb-8044-48eff890e005.png)

**Discord Version**
Stable

**Comment by rauenzi** [comment]
Does this occur for all emotes or only a subset?

**Comment by rauenzi** [comment]
Then closing this as NCO. At some point I will dig up my old script to update the emote DBs
