### ISSUE TITLE
[Bug] BetterDiscord Crashing On Opening.

### ISSUE THREAD

**Issue by MaxIsDumbLoL** [BetterDiscord/BetterDiscord#873]
**Describe the Bug**
When installing BetterDiscord, and opening it, it automatically closes.

**To Reproduce**
Install and execute discord.

**Comment by LittleWhole** [comment]
Can reproduce bug. Same thing happens to me. I'm on Discord Canary v0.0.126 on Ubuntu 21.04.

**Comment by ItsdMeSoFYou** [comment]
Strencher already made a fix, but it's not been approved by raunzi yet. https://github.com/rauenzi/BetterDiscordApp/pull/869/commits/a512fb115e727f97ba29d63a6e86a08142a8101e

Just go into this dudes BD repository and replace the index.js and preloader.js in your BD install with the ones from his repository. I've tried it and it works

**Comment by rauenzi** [comment]
Please reinstall to the latest version
