### ISSUE TITLE
[Bug] BD Github API fails the Content Security Policy

### ISSUE THREAD

**Issue by BadCarrot** [BetterDiscord/BetterDiscord#876]
**Describe the Bug**
BD is failing to connect to the BD Github API because it violates Content Security Policy

**To Reproduce**
No idea how to reproduce this.

**Expected Behavior**
BetterDiscord should have access to the Github API repository

**Screenshots**
![image](https://user-images.githubusercontent.com/57045703/124843869-8806bd00-df9b-11eb-99eb-258c90c08841.png)
![image](https://user-images.githubusercontent.com/57045703/124843921-ae2c5d00-df9b-11eb-869b-9e574c3d701c.png)
![image](https://user-images.githubusercontent.com/57045703/124845535-99ea5f00-df9f-11eb-9dfa-451f6161a378.png)

**Discord Version**
Stable

**Comment by rauenzi** [comment]
This seems to only happen with odd system setups whether it be with aggressive antiviruses, network policies, or unregistered OS copies. These types of issues I am unable to circumvent.
