### ISSUE TITLE
1.2 Installation tries to download .asar file from wrong url

### ISSUE THREAD

**Issue by SHTDJ** [BetterDiscord/BetterDiscord#882]
**Describe the Bug**
Error:
Starting Install...

Creating required directories...
✅ Directory exists: C:\Users\nikla\AppData\Roaming\BetterDiscord
✅ Directory exists: C:\Users\nikla\AppData\Roaming\BetterDiscord\data
✅ Directory exists: C:\Users\nikla\AppData\Roaming\BetterDiscord\themes
✅ Directory exists: C:\Users\nikla\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
❌ Failed to download package https://api.github.com/repos/rauenzi/BetterDiscordApp/releases
❌ Cannot read property 'assets' of undefined

The install seems to have failed. If this problem is recurring, join our discord community for support. https://discord.gg/0Tmfo5ZbORCRqbAd

**Comment by rauenzi** [comment]
Duplicate of this issue https://github.com/BetterDiscord/Installer/issues/174
