### ISSUE TITLE
[Bug] installing last update ( 1.2.0 ) git API 

### ISSUE THREAD

**Issue by PsykoDev** [BetterDiscord/BetterDiscord#884]
**Describe the Bug**
try install on win11 last update

**To Reproduce**
just launch install

**Screenshots**
![Screenshot 2021-07-09 111114](https://user-images.githubusercontent.com/45910905/125054894-f7b59e80-e0a6-11eb-8f43-47e9c53bdd41.png)

**Discord Version**
Stable

**Comment by rauenzi** [comment]
Please use the latest hotfix release of the installer.
