### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by SiiliFin** [BetterDiscord/BetterDiscord#885]
**Describe the Bug**
When my friend stops streaming my betterdiscord crashes my discord client

**To Reproduce**
1. Go to discord call
2. Ask your friend to stream his game or somthing
3. Then go watch it
4. Then go fullscreen
5. Then ask your friend to stop the stream
6. Then your betterdiscord crashes your discord client

**Expected Behavior**
Well...  I wish this will get fixed as soon as possible be cause this is anoying

**Screenshots**
Dont have any of those

**Discord Version**
I think stable

**Comment by QbDesu** [comment]
There is a new BetterDiscord update out, alongside a new installer.
Download the installer from https://github.com/BetterDiscord/Installer/releases/tag/v1.0.0-hotfix and install again, that should fix the issue.

**Comment by SiiliFin** [comment]
ok
