### ISSUE TITLE
[Feature] allow replacing usernames with custom nicknames

### ISSUE THREAD

**Issue by aspiers** [BetterDiscord/BetterDiscord#887]
**Is your feature request related to a problem? Please describe.**

One of Discord's most annoying features is that when any of your contacts have chosen cryptic usernames (nicknames), you basically have to remember which username corresponds to which person.

**Describe the feature you'd like**

I have written a solution to this problem as a browser-based userscript:

https://github.com/aspiers/Discord-custom-nicks-userscript

It works purely client-side in the browser.  Please follow that link for all the details.

The purpose of filing this issue is to ask whether there would be any interest from the BetterDiscord side in collaborating on integrating this code into BetterDiscord.  I won't be able to do it by myself, but I would be very happy to work with someone who knows the BetterDiscord codebase in order to achieve it together.

If there is no interest, that's fine, but I thought I should at least make the offer ;-)

P.S. even though I put a GPLv3 license on my code, I would be happy to dual-license it if that is required for integration.

**Comment by rauenzi** [comment]
There is already a plugin called EditUsers that lets you change the username for a user locally. You can check it out here https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/EditUsers

**Comment by aspiers** [comment]
Ah, good to know, thanks!
