### ISSUE TITLE
[Bug] Attempting to update ZeresPluginLibrary crashes discord

### ISSUE THREAD

**Issue by k4zo** [BetterDiscord/BetterDiscord#888]
**Describe the Bug**
Attempting to update ZeresPluginLibrary restarts Discord and disables BD

**To Reproduce**
Have the latest version of BD
Attempt to update the ZeresPluginLibrary plugin

**Expected Behavior**
it updates

**Screenshots**
![image](https://user-images.githubusercontent.com/40926602/125144151-f8702400-e0ea-11eb-878d-794e74c9ad78.png)

**Discord Version**
Stable

**Additional Context**
N/A

**Comment by doggybootsy** [comment]
Redownload ZeresPluginLibrary he just fixed it

**Comment by dav1312** [comment]
Thats not an issue with Betterdiscord
Manually redownload the plugin, the update that appeared was to literally fix that

**Comment by iamqw3rty** [comment]
> Thats not an issue with Betterdiscord
> Manually redownload the plugin, the update that appeared was to literally fix that

Even after reinstalling the plugin, it's still crashing

**Comment by rauenzi** [comment]
Please see the above, this was already fixed.

**Comment by phoenix277yt** [comment]
Hi, I'm on mac can i have the path for the plugin folders please?
