### ISSUE TITLE
[Bug] Screenshare on Discord Stable on MacOS crashes Discord 

### ISSUE THREAD

**Issue by SynergyBest** [BetterDiscord/BetterDiscord#889]
**Describe the Bug**

Whenever I try to stream my entire stream it just ends the stream instantly.

**To Reproduce**

Stream entire screen on betterdiscord macOS
**Expected Behavior**

I expect for the stream to close instantly when trying to stream entire stream
**Screenshots**

**Discord Version**

Stable
**Additional Context**

Whenever I stream just one application it just doesn't load (this may be my mac though)

**Comment by rauenzi** [comment]
What version of BD are you using?

**Comment by weejiaquan** [comment]
This issue is happening with v1.2.0 of BD

**Comment by rhysperry111** [comment]
I recently helped a friend get BD and he is having the same issue. He also uses macOS

**Comment by Migdf** [comment]
Is there a way to download non v1.2.0 to use screen share?

**Comment by hypixels** [comment]
Same here. Do we just have to wait for version 1.2.1?

**Comment by rauenzi** [comment]
> 
> 
> Is there a way to download non v1.2.0 to use screen share?

If you know how to use github and such, yes.

**Comment by rauenzi** [comment]
The best workaround at this time is to use Discord Canary instead

**Comment by hypixels** [comment]
> The best workaround at this time is to use Discord Canary instead

Alright, I'll try that. Thanks!

**Comment by SynergyBest** [comment]
> What version of BD are you using?

v1.2.0, apologies for the late response I was out with family.

**Comment by Kief5555** [comment]
This affects pbt too.

**Comment by lmf-git** [comment]
Screensharing no longer works on Mac after discord updated. Worked fine in the past. It has the permissions it needs, just closes instantly without working.

I tried disabling hardware acceleration, tried to use the native Mac window select setting, restarted device. I'll reinstall discord manually now which seems excessive.
