### ISSUE TITLE
Transparency seems to stop working after so many reloads and theme refreshs

### ISSUE THREAD

**Issue by doggybootsy** [BetterDiscord/BetterDiscord#892]
**Describe the Bug**
Instead of being discord transparent its white

**To Reproduce**
Reload discord a couple times or edit a theme a couple times

**Expected Behavior**
To be transparent

**Screenshots**
https://i.imgur.com/FXSfHw1.png

**Discord Version**
Stable

**Additional Context**
Redownloading bd does fix it, its just pain

**Comment by doggybootsy** [comment]
Reinstalling is the only fix I could find even fully restarting discord doesn't fix it

I wasn't trying to reload to fix it, I was reloading because I was working on a plugin (I have hot load disabled)

**Comment by rauenzi** [comment]
I've attempted this again and am unable to reproduce.

**Comment by doggybootsy** [comment]
I do use macos, so that might play a factor
but it still continues to happen

**Comment by rauenzi** [comment]
But effectively, a reinstall would not change anything other than overwrite the asar. After reinstalling, do you have to reenable the transparency setting?

**Comment by doggybootsy** [comment]
![Screen Shot 2021-08-31 at 6 24 16 PM](https://user-images.githubusercontent.com/71196819/131596618-78fb72e4-a283-41e2-b8b4-53cdc7fefe8e.png)

Yes

**Comment by rauenzi** [comment]
So you reinstall BD. The setting _shows_ as checked, but you have to uncheck and recheck it for it to take effect?

**Comment by doggybootsy** [comment]
The next time is does the white background thing ill try unchecking and checking the error
