### ISSUE TITLE
[Bug] Downloader fails to find asar file when repairing BD client...

### ISSUE THREAD

**Issue by Electrocute4u** [BetterDiscord/BetterDiscord#893]
**Describe the Bug**
Trying to repair the BetterDiscord after a plugin crashes the BD client and then fails to fetch the asar file upon repair from [here](https://api.github.com/repositories/105473537/releases).

**To Reproduce**
Have the latest BD client with "ZerefPluginLibrary", trying to relaunch, gets "BetterDiscord has automatically disabled itself temporarily. Try removing all your plugins then restarting Discord" <= Following this step, did not work either.

**Expected Behavior**
A clean re-install of BetterDiscord without the core issue(s) mentioned in #890  being the "ZerefPluginLibrary" plugin.
And a chill afternoon with my anime waifu wallpaper of [Kuuko](https://nyaruko.fandom.com/wiki/Kuuko) uwu

**Screenshots**
![Discord crash message](https://i.imgur.com/IoQbU2e.png)
![Discord re-install message](https://i.imgur.com/tHw5SWH.png)

**Discord Version**
Stable

**Additional Context**
Even after manually re-installing the plugin "ZerefPluginLibrary", which was mentioned in #890 the client still won't open.
Discord resolves to not even initiate the client, and I suppose I got no choice but to reinstall all plugins.

**Comment by doggybootsy** [comment]
Zerebos — Yesterday at 12:09 AM
If you are having issues with installing or updating, GitHub is currently having issues. Please download this installer hotfix https://github.com/BetterDiscord/Installer/releases/tag/v1.0.0-hotfix
Zerebos — Yesterday at 4:43 PM
For issues updating plugins, you need to manually reinstall the latest ZeresPluginLibrary https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js

In the announcement channel

**Comment by Electrocute4u** [comment]
> Zerebos — Yesterday at 12:09 AM
> If you are having issues with installing or updating, GitHub is currently having issues. Please download this installer hotfix https://github.com/BetterDiscord/Installer/releases/tag/v1.0.0-hotfix
> Zerebos — Yesterday at 4:43 PM
> For issues updating plugins, you need to manually reinstall the latest ZeresPluginLibrary https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js
> 
> In the announcement channel

Cheers, not really part of the BDDiscord server so I haven't really found this info yet.
Mainly since I'm already part of like a billion other servers and keeping track of each and every one of them is a pain.
Appreciate the fast reply.
