### ISSUE TITLE
Duplicated letter in text translations

### ISSUE THREAD

**Issue by TeusDev** [BetterDiscord/BetterDiscord#895]
![image](https://user-images.githubusercontent.com/45436136/125162700-59354600-e157-11eb-8e37-069b4a944cb9.png)
![image](https://user-images.githubusercontent.com/45436136/125162708-5cc8cd00-e157-11eb-9361-26ba1e840ffb.png)

**Comment by rauenzi** [comment]
This is not exclusive to that translation
