### ISSUE TITLE
[Bug] BD can't open Finder on Mac

### ISSUE THREAD

**Issue by Whitelisted1** [BetterDiscord/BetterDiscord#896]
**Describe the Bug**
When you try to open the plugins folder on Mac, it says "The application Finder can't be opened"

**To Reproduce**
use BD on a mac, and try to open the plugins folder

**Expected Behavior**
Open the BD plugins folder in finder

**Screenshots/Video**
Video Here: https://user-images.githubusercontent.com/77711834/125179158-ec4a9c00-e1a8-11eb-9de0-0333e4b90c05.mov

**Discord Version**
Stable

**Comment by doggybootsy** [comment]
Heres the file path until its fixed `~/library/application support/betterdiscord/`

**Comment by rauenzi** [comment]
This is known, but currently works on Discord Canary.

**Comment by rauenzi** [comment]
Reopening as this bug is still technically valid on Stable

**Comment by ac4man** [comment]
I don't even have a better discord folder for some reason, any suggestions?

**Comment by rauenzi** [comment]
This has the same root issue as #889

**Comment by LazarusDrax** [comment]
hello I have precisely that same problem, which tells me that I cannot open the finder to be able to enter new plugins, and I searched for the path manually and I did not even get the betterdiscord folder.

If anyone knows how to solve this error I would appreciate it!

**Comment by jakoritarleite** [comment]
> hello I have precisely that same problem, which tells me that I cannot open the finder to be able to enter new plugins, and I searched for the path manually and I did not even get the betterdiscord folder.
> 
> If anyone knows how to solve this error I would appreciate it!

You need to change some details on the path that @doggybootsy provided:

`~/Library/Application\ Support/BetterDiscord`

that way you can open the folder on Finder using the `open` command.

**Comment by Macintosh-Fan** [comment]
![image](https://user-images.githubusercontent.com/50642934/125849118-4718a7e9-c009-4c19-ae35-5abcac9b7b05.png)

I'm also experiencing this issue.

**Comment by rauenzi** [comment]
@Macintosh-Fan in the future please just give a 👍 to the original issue if you are experiencing the same issue unless you have further insight/information to provide.

**Comment by Macintosh-Fan** [comment]
> @Macintosh-Fan in the future please just give a 👍 to the original issue if you are experiencing the same issue unless you have further insight/information to provide.

There was no photo evidence before, so that's why I sent it.

**Comment by rauenzi** [comment]
There's literally a video linked in the original issue

**Comment by raymond-1227** [comment]
> > hello I have precisely that same problem, which tells me that I cannot open the finder to be able to enter new plugins, and I searched for the path manually and I did not even get the betterdiscord folder.
> > If anyone knows how to solve this error I would appreciate it!
> 
> You need to change some details on the path that @doggybootsy provided:
> 
> `~/Library/Application\ Support/BetterDiscord`
> 
> that way you can open the folder on Finder using the `open` command.

hello, how do i make the button to open in the correct location?

**Comment by Kief5555** [comment]
Same here
