### ISSUE TITLE
[Bug] Install Button Not working

### ISSUE THREAD

**Issue by Pixelsuft** [BetterDiscord/BetterDiscord#900]
**Describe the Bug**
When I'm running installer and selecting discord folder I can't press 'Install' Button

**Screenshots**
![image](https://user-images.githubusercontent.com/68371847/125394617-2481f280-e3d4-11eb-8e1a-c47027962dd7.png)

**Comment by doggybootsy** [comment]
Did you select stable?
in the photo you didnt

**Comment by QbDesu** [comment]
![gif](https://cdn.discordapp.com/attachments/542030029861814284/828696240786636811/SelectDiscordVersion.gif)

**Comment by Tropix126** [comment]
See Qb's comment.

**Comment by Pixelsuft** [comment]
Oh Thanks!
