### ISSUE TITLE
[Bug] Can't stream at all on macOS - Discord Stable

### ISSUE THREAD

**Issue by pistou** [BetterDiscord/BetterDiscord#901]
I'm on macOS Big Sur v11.4, and BD v1.2.0, using Discord Stable

And as mentionned in #889, in MacOS we can't stream fullscreen.

I can't stream an isolated application either. The stream launches, yet it loads forever and says it has quality issues.
As soon as I uninstall BD, it works perfectly.

**Comment by rauenzi** [comment]
I'm assuming this is Discord stable? Can you try on Canary?

**Comment by pistou** [comment]
It was indeed on Stable version
Looks like everything work fine on Canary

**Comment by rauenzi** [comment]
Then this looks like the same as #889
