### ISSUE TITLE
Discord Crashes even after Reinstallation of BetterDiscord [Error]

### ISSUE THREAD

**Issue by Schattenfee69** [BetterDiscord/BetterDiscord#903]
--Description--
I tried to open Discord to talk to a friend but when i open it, Discord crashes with the Message "BetterDiscord crashed your Discord Client" and even after repairing BD with the Installer (GitHub troubleshoot Hotfix Version) it still keeps Crashing on relaunch...

--Reproduction--
I don't know how to reproduce this Problem but some people have reported similar problems on MacOS...
this won't fix my problem because my PC runs on Windows 10 x64 21H1 Update...

--Expected Behavior--
I Expected Discord to Launch without any Issues but if it keeps Crashing, i could probably think about your Hotfix Installer could be Hacked or something else has happened because this Behavior isn't normal (or at least did it never occur on my PC until today)

--Screenshots--
-Better Discord Crash Message-
![BDCrashMsg](https://user-images.githubusercontent.com/87497259/125843117-19ae33f5-a5a5-4537-acb0-fbb1f7195bca.png)
-In case you want to Contact Me on Discord (without BD enabled on my PC) to clarify things i can do against this error-
![ContactMeIfNeeded](https://user-images.githubusercontent.com/87497259/125843149-eba2a7a3-fa7e-4e25-a7ab-8b78e318a8f2.png)
-Discord Version (Stable)-
![DiscordVer](https://user-images.githubusercontent.com/87497259/125843172-5cb5def4-dd28-4c4d-88cb-0de6709f41af.png)

--Discord Version--
Stable 90136 (3507a4c) on Host 1.0.9002 using Windows 10 64-Bit (10.0.19043)

Thanks for Reading and (if possible) helping me out to solve this issue

**Comment by doggybootsy** [comment]
Do have you have bdfdb 
If so remove it

**Comment by dav1312** [comment]
You just have to read the warning and follow its instructions.

**Comment by snappyapple632** [comment]
It seems several plugins were causing the crashes.

**Comment by Schattenfee69** [comment]
The Problem is that i have no plugins at all, not even BDFDB, and this is the point where it's getting weird and annoying...

Bc, why is it able to crash and say it was a problem with the plugins if there were no plugins installed in the first place?

**Comment by Schattenfee69** [comment]
![BDPluginFolder](https://user-images.githubusercontent.com/87497259/125849332-b31ffe1c-31ed-4cac-ac87-581225eddb1e.png)

how is this folder able to crash anything? please explain where the plugins are that cause crashes...

exactly! nowhere... that was my first reaction to this crash too, that's why i asked how to fix it...

**Comment by rauenzi** [comment]
Try reinstalling BD. I can't tell what version you are using.

**Comment by zpar-ky** [comment]
BDFDB was updated an hour ago, after updating discord and getting crashes I updated BDFDB to 1.7.7 and it no longer crashes.

**Comment by LadyMillaMaxwell** [comment]
I don't know what to do now 
![image](https://user-images.githubusercontent.com/56988113/125857146-ceb97c5b-0d0b-4407-9e74-293c7cf215e2.png)

**Comment by RyzerG** [comment]
> BDFDB was updated an hour ago, after updating discord and getting crashes I updated BDFDB to 1.7.7 and it no longer crashes.

Works for me as well. Download the updated version and place in plugins folder.

**Comment by RyzerG** [comment]
> I don't know what to do now
> ![image](https://user-images.githubusercontent.com/56988113/125857146-ceb97c5b-0d0b-4407-9e74-293c7cf215e2.png)

Re-install and get the new version of BDFDB from the better discord site.

**Comment by MaartenBl** [comment]
- Go to your Better Discord Folder:
 ``C:\Users\...\AppData\Roaming\BetterDiscord\plugins``
- Remove all the files with BDFDB
![image](https://user-images.githubusercontent.com/19569456/125858359-a14f3537-4f53-469b-b211-69b8eeffd6b8.png)
- Restart discord
- It will ask you to install missing plugins
- Fixed

**Comment by kyeondiscord** [comment]
> * Go to your Better Discord Folder:
>   `C:\Users\...\AppData\Roaming\BetterDiscord\plugins`
> * Remove all the files with BDFDB
>   ![image](https://user-images.githubusercontent.com/19569456/125858359-a14f3537-4f53-469b-b211-69b8eeffd6b8.png)
> * Restart discord
> * It will ask you to install missing plugins
> * Fixed

Thanks, it worked :) 👍

**Comment by olegatronik12** [comment]
> * Go to your Better Discord Folder:
>   `C:\Users\...\AppData\Roaming\BetterDiscord\plugins`
> * Remove all the files with BDFDB
>   ![image](https://user-images.githubusercontent.com/19569456/125858359-a14f3537-4f53-469b-b211-69b8eeffd6b8.png)
> * Restart discord
> * It will ask you to install missing plugins
> * Fixed

Thanks, it worked

**Comment by Schattenfee69** [comment]
I guess I'll try it today at 6PM (Berlin Time) because I go to sleep now...
I tell y'all if it worked or not...

But the fact that it worked for everyone in this discussion is letting me hope that it will work for me too

**Comment by Ja-Crispy** [comment]
> I don't know what to do now
> ![image](https://user-images.githubusercontent.com/56988113/125857146-ceb97c5b-0d0b-4407-9e74-293c7cf215e2.png)

Same here, can't repair or reinstall better discord

**Comment by BlackusPL** [comment]
> * Go to your Better Discord Folder:
>   `C:\Users\...\AppData\Roaming\BetterDiscord\plugins`
> * Remove all the files with BDFDB
>   ![image](https://user-images.githubusercontent.com/19569456/125858359-a14f3537-4f53-469b-b211-69b8eeffd6b8.png)
> * Restart discord
> * It will ask you to install missing plugins
> * Fixed

Working thx
