### ISSUE TITLE
BD crashes when i put the plugin library in the pluging folder

### ISSUE THREAD

**Issue by ains12** [BetterDiscord/BetterDiscord#904]
the BD crashes and just goes back to normal discord

put the library plugin in the plugin folder

it loads up but when its done it crashes and return to normal discord 

stable

**Comment by doggybootsy** [comment]
Remove bdfdb.

**Comment by dav1312** [comment]
You just have to read the warning that appears when betterdiscord crashes and follow its instructions.

**Comment by ains12** [comment]
> You just have to read the warning that appears when betterdiscord crashes and follow its instructions.

i did but some of my plugins are left out does that i mean that i just have to find them and download manually

**Comment by ains12** [comment]
it also says this https://i.imgur.com/gc0Bjzp.png when i try to download some plugins and when i download the library it crashes

**Comment by siren15** [comment]
Just gonna post this here https://github.com/mwittrien/BetterDiscordAddons/issues/950 it's an issue with bdfdb
