### ISSUE TITLE
[Bug] "Theres was an unexpected Error. Click to open console for more details"

### ISSUE THREAD

**Issue by v4l3r0** [BetterDiscord/BetterDiscord#905]
One of the plugins I use is not loading me. Before that I had crashing errors, reinstalled the betterdiscord and now that pluggin does not load me.

**Comment by dav1312** [comment]
This is not an issue with BetterDiscord

**Comment by v4l3r0** [comment]
![image](https://user-images.githubusercontent.com/87498688/125847921-8bd96955-c70d-477f-a1b9-e177e4247dbd.png)

**Comment by rauenzi** [comment]
See comment from dav

**Comment by lxeo-rgb** [comment]
how do we fix it?
