### ISSUE TITLE
[Feature] Expose Editor (+ other Components) to the API

### ISSUE THREAD

**Issue by QbDesu** [BetterDiscord/BetterDiscord#909]
**Is your feature request related to a problem? Please describe.**
Wanting to have a BD-like editor component in your plugin would mean having to rewrite most parts of it.

**Describe the feature you'd like**
Expose the Editor and the components related to it like FloatingWindow and the Wrappers for buttons etc to the API. Maybe by having these components in a `BdApi.Components` module, maybe with further submodules for organiational purposes.
The things I would consider useful components to expose would be:
* editor and related thing's like floating window
* the icon components
* error boundary + settings input components (although I know ZLibrary provides these as well) 

There it might also be possible to expose them another way but I think since they are React components already exposes them as such would be easier, and looking at the current state of plugins most of them try to patch the Discord's components anyway, so not having to wrap stuff in a component would come in handy.

**Comment by rauenzi** [comment]
Will not be expanding the API like this at this time
