### ISSUE TITLE
[Feature] In-game overlay for Mac

### ISSUE THREAD

**Issue by Whitelisted1** [BetterDiscord/BetterDiscord#910]
**Is your feature request related to a problem? Please describe.**
Can't use discord overlay on Mac

**Describe the feature you'd like**
Discord has put off making an official in-game overlay for mac for quite a while, so I think it would be a good idea to make it for BD 

(I'm not sure about the limitations of BD plugins, but if it's possible to make this with a plugin this is a suggestion to them as well)

**Comment by PreciousWarrior** [comment]
+1. Also please implement it for linux as well.

**Comment by 3nt3** [comment]
For Linux there exists [Discover](https://github.com/trigg/Discover). It should probably also work for mac but I haven't tried, since I don't own one @PreciousWarrior. Perhaps that python package could somehow be included in betterdiscord?

**Comment by Whitelisted1** [comment]
Thanks for the reply, I'll check it out when I have time

**Comment by Whitelisted1** [comment]
> For Linux there exists [Discover](https://github.com/trigg/Discover). It should probably also work for mac but I haven't tried, since I don't own one @PreciousWarrior. Perhaps that python package could somehow be included in betterdiscord?

The install didn't work, which I assume is to be expected

**Comment by rauenzi** [comment]
This is not a feature we are looking to add to BD at this time, that is a larger-scale project than what most people realize.
