### ISSUE TITLE
[Bug] License is Contradictory

### ISSUE THREAD

**Issue by dabockster** [BetterDiscord/BetterDiscord#912]
**Describe the Bug**
The license contradicts itself with regards to redistribution and derivative works.

**To Reproduce**
View the license.

**Additional Context**
The license begins with a clear statement regarding redistribution and derivative works then contradicts itself with a statement that is opposite the one at the beginning.

> All rights reserved. Code may not be modified and redistributed, or otherwise
used for derivative works and redistributed without explicit permission.

> Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the “Software”), to deal
in the Software, including without limitation the rights to use, copy, and
distribute unmodified copies of the Software

It seems that the license began as the common MIT license, but then was added onto. It should be cleaned up.

**Comment by dav1312** [comment]
> Code may not be modified and redistributed 

if you modify it, you can't redistribute it

> or otherwise used for derivative works and redistributed 

you can't use it in derivative works and redistribute those works

> without limitation the rights to [...] distribute unmodified copies of the Software 

you can distribute it if its unmodified

--- 
Thats what I personally understand

**Comment by rauenzi** [comment]
Yes what @dav1312 explained above is correct.

**Comment by comradekingu** [comment]
@rauenzi
It isn't a libre license https://hosted.weblate.org/hosting/

Why not just run ISC?
