### ISSUE TITLE
[Bug] Crashing

### ISSUE THREAD

**Issue by tofonek** [BetterDiscord/BetterDiscord#914]
**Describe the Bug**
When i start discord it crashes and start again without betterdiscord when i try run it wihout all plugins still crashes

**Discord Version**
Stable

**Comment by mrmmg** [comment]
same for me

**Comment by EliteAsian123** [comment]
Seems to be something with BDFDB (for me anyways). Deleting BDFDB and reinstalling the newest version fixed the crashes for me.

**Comment by identity7** [comment]
BDFDB is likely crashing you. If you haven't already, delete the existing 0BDFDB.plugin.js and download the new one from https://mwittrien.github.io/downloader/?library

**Comment by Gyrohammer** [comment]
> BDFDB is likely crashing you. If you haven't already, delete the existing 0BDFDB.plugin.js and download the new one from https://mwittrien.github.io/downloader/?library

This worked for me as well. I'll write out the steps below to be more specific:

AppData > Roaming > betterdiscord > plugins

**Comment by NeverEndingCycle** [comment]
This also solved it for me.

**Comment by master3395** [comment]
> BDFDB is likely crashing you. If you haven't already, delete the existing 0BDFDB.plugin.js and download the new one from https://mwittrien.github.io/downloader/?library

This seems to have fixed the issue for me also.

**Comment by rauenzi** [comment]
For anyone coming across this please see the above
