### ISSUE TITLE
[Bug] ZeresPluginLibrary crashes on update

### ISSUE THREAD

**Issue by JSkes** [BetterDiscord/BetterDiscord#917]
**Describe the Bug**
ZeresPluginLibrary crashes whenever I try to update

**To Reproduce**
Step 1: Get the notification to update ZeresPluginLibrary
Step 2: Click Update
Step 3: Crash

**Expected Behavior**
ZeresPluginLibrary updates like usual

**Screenshots**
![image](https://user-images.githubusercontent.com/71411219/126052019-3d932030-c89e-4476-996d-9ee9d44eb56f.png)
![image](https://user-images.githubusercontent.com/71411219/126052024-19fc783f-944b-492d-956e-ca5c18501c70.png)

**Discord Version**
Stable

**Additional Context**
So far I've tried this on all my friends and 4 crashed and 2 didn't

**Comment by dav1312** [comment]
Duplicate of #888

**Comment by Luck100** [comment]
I can't install the Bette discord doesn't show up in the settings and the error
