### ISSUE TITLE
[Bug] Mac client cannot detect running apps with BD installed

### ISSUE THREAD

**Issue by Iritscen** [BetterDiscord/BetterDiscord#918]
**Describe the Bug**
When BetterDiscord is installed, the macOS Discord client cannot see running apps. This disables the ability to have "added games" appear in your activity status.

**To Reproduce**
1. Without BD installed, add a "game" (any app) to the list of Added Games in Discord's User Settings > Activity Status by clicking the "Add it!" button and choosing a running app.
2. Observe that your activity status says "Playing [app you chose]".
3. Close Discord and install BetterDiscord.  Re-open Discord.
4. Observe that you no longer have an activity status based on the added app which is still running. Relaunching said app will not help. When going to Activity Status and clicking "Add it!", the popup menu is empty because no running apps can be detected.

**Expected Behavior**
That Activity Status would continue to function as usual.

**Screenshots**
<img width="709" alt="Screen Shot 2021-07-19 at 9 38 12 AM" src="https://user-images.githubusercontent.com/1541542/126169026-f0183039-2870-4556-a84d-cf0bc41831c0.png">

**Discord Version**
Stable

**Additional Context**
This is a recent regression. As seen in the screenshot, my added apps were last detected 12 days ago (the 3-days-ago app was detected when I uninstalled BD as a test).

**Comment by hxrrr666** [comment]
i fucking hate niggers

**Comment by haydenfordz** [comment]
can confirm this happens on MacOS stable AND PTB, but does not on Canary. 
<img width="1920" alt="Screenshot 2021-07-20 at 16 44 01" src="https://user-images.githubusercontent.com/77495158/126354470-9ed7f2a1-9cd7-4fc0-869c-f0b797c3c2e5.png">
^^This is Discord PTB

**Comment by rauenzi** [comment]
This is the same root issue as #889
