### ISSUE TITLE
Microphone and audio doesn't work on OS X [Bug]

### ISSUE THREAD

**Issue by q25x** [BetterDiscord/BetterDiscord#935]
When i installed BD my mic&audio did not work.
Yes, i checked everything else, it just doesn't work on BD.

![obraz](https://user-images.githubusercontent.com/87657871/126177559-cf948120-5c90-4c48-aa71-284e9aa38e0f.png)

It doesn't work on any version of discord

**Comment by sausha1999** [comment]
Try going into your discord settings, audio & voice setting and hit reset audio settings at the bottom and also make sure the right mic is selected. If it doesn't fix, try your mac settings and permissions.

**Comment by q25x** [comment]
> I assume you have tried to solve this issue, but try going into your discord settings, audio & voice setting and hit reset audio settings at the bottom and also make sure the right mic is selected. If it doesn't fix, try your mac settings and permissions. Try and troubleshoot with your mic as well.

I already did it all, and stilo doesn't work.

**Comment by Kief5555** [comment]
Try a reinstall, or test if your microphone is working. go to settings>sound>input and talk into your mic. See if the bar indicates your talking

**Comment by q25x** [comment]
> I assume you have tried to solve this issue, but try going into your discord settings, audio & voice setting and hit reset audio settings at the bottom and also make sure the right mic is selected. If it doesn't fix, try your mac settings and permissions. Try and troubleshoot with your mic as well.

I already did it all, and stilo doesn't work

**Comment by sausha1999** [comment]
Could be worth reinstalling.

**Comment by q25x** [comment]
> Could be worth reinstalling.

I already tried reinstalling everything, but it still doesn't work.

**Comment by sausha1999** [comment]
> I already tried reinstalling everything, but it still doesn't work.

Try and uninstall and reinstall your Discord Client and see if that fixes. I don't believe it's an issue with BD, rather your Mac.

**Comment by q25x** [comment]
> > I already tried reinstalling everything, but it still doesn't work.
> 
> Try and uninstall and reinstall your Discord Client and see if that fixes. I don't believe it's an issue with BD, rather your Mac.

I tried re-installing EVERYTHING, micro doesn't work on older systems i guess.

**Comment by rauenzi** [comment]
A new version has been released to address this, please try with the new version
