### ISSUE TITLE
[Bug] multiple better discord settings bar

### ISSUE THREAD

**Issue by nsjsjjsja** [BetterDiscord/BetterDiscord#944]
**Describe the Bug**
 mutiple better discord bars in my settings

**To Reproduce**
 hmm idrk it just showed-up after the new update for discord

**Screenshots**
 https://imgur.com/Ezvy9eD

**Discord Version**
 stable

**Comment by Overimagine1** [comment]
Try refreshing discord (`Ctrl R`)

**Comment by nsjsjjsja** [comment]
works ty

**Comment by sausha1999** [comment]
Close this issue as it has been solved.
