### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by fowlis** [BetterDiscord/BetterDiscord#945]
**Describe the Bug**
GitHub link on the installer is typed wrong, doesn't direct to the GitHub repo
(Might only be on the Windows installer)

**To Reproduce**
Run the current BetterDiscord installer for Windows, and try click on the GitHub button
It leads to: "https://github.com/BetterDiscord/BetterDiscor" - so it doesn't work correctly

**Expected Behavior**
The GitHub button should open the correct link: https://github.com/BetterDiscord/BetterDiscord

**Screenshots**
![Location of GitHub button on the installer](https://user-images.githubusercontent.com/84232621/126306958-ecefe023-8a9d-436d-8f72-be71555ff8ca.png)

**Discord Version**
Any(?)

**Additional Context**
N/A

**Comment by fowlis** [comment]
Forgot to add a title, my mistake

**Comment by dav1312** [comment]
If this is an installer issue you should open it in https://github.com/BetterDiscord/Installer

**Comment by dav1312** [comment]
> Forgot to add a title, my mistake

@fowlis You can edit the title

**Comment by fowlis** [comment]
> If this is an installer issue you should open it in https://github.com/BetterDiscord/Installer
> But the issue is already fixed in the development branch of the installer so it will be fixed in the next update

Ah, my bad. I'll close this issue now, thanks for letting me know :)
