### ISSUE TITLE
[Bug] Laggy navbar

### ISSUE THREAD

**Issue by Craftzman7** [BetterDiscord/BetterDiscord#946]
**Describe the Bug**
The NavBar is laggy when moving mouse on it

**To Reproduce**

Reload Better Discord (You may have to wait a second)

**Expected Behavior**

NavBar speed does not change

**Screenshots**

![9xQibg4LlAALXyorLdvNhmihFZFCnf2Xv2N9TVTJBXyhz9ISPZkBgEkWNTjYyse0Lkylu](https://user-images.githubusercontent.com/70068692/126371212-c879857e-fd15-41e7-8f39-672b1112f7e7.gif)

**Discord Version**

Canary

**Additional Context**

I tested with all plugins disabled and same result

**Comment by dav1312** [comment]
Cannot reproduce

**Comment by Craftzman7** [comment]
> 
> 
> Cannot reproduce

Fixed by repairing the installation.
