### ISSUE TITLE
Custom CSS not working

### ISSUE THREAD

**Issue by VsQgmnsldkH2** [BetterDiscord/BetterDiscord#949]
It doesn't open when I click on custom css in the settings. It says I can click it but nothing opens. The stable is 90699 and betterdiscord is 1.2.0.

**Comment by fowlis** [comment]
Known issue, current workaround is going to the settings.json file and making this change: 

```
"customcss": {
    "customcss": true;
    "liveUpdate": false;
    "openAction": "settings" <<-- change settings to detached
},
```

Save the settings.json file and it should work.

Alternatively, edit the custom.css file itself and save it then reload Discord.

**Comment by rauenzi** [comment]
A fix has been merged and will be available next release
