### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by korexx** [BetterDiscord/BetterDiscord#951]
whenever i try and install better discord it either shuts down my discord app, or it doesn't process into my discord app

<img width="548" alt="Screenshot 2021-07-22 at 9 29 48 PM" src="https://user-images.githubusercontent.com/87840925/126731073-492f0988-1d81-429b-adea-39f00a194820.png">

the discord version is stable

**Comment by doggybootsy** [comment]
Redownload the installer

**Comment by DarexSyntrex** [comment]
this is fixed by getting the latest installer from https://betterdiscord.app

**Comment by korexx** [comment]
> this is fixed by getting the latest installer from https://betterdiscord.app

<img width="256" alt="Screenshot 2021-07-22 at 9 37 49 PM" src="https://user-images.githubusercontent.com/87840925/126731518-0ec833e9-3e70-49c2-b9a0-80b4d38227c9.png">

**Comment by doggybootsy** [comment]
Reinstall bdfdb

**Comment by dav1312** [comment]
This is an issue with the installer (that has already been fixed) not with BetterDiscord.
Close this issue.

**Comment by DarexSyntrex** [comment]
Close this issue, you haven't even tried getting help in the discord server. All these issues are fixed but you won't try to get it fixed. Go to the discord server for help
