### ISSUE TITLE
[Bug] Javascript error

### ISSUE THREAD

**Issue by P4R4NORM4L** [BetterDiscord/BetterDiscord#952]
![image](https://user-images.githubusercontent.com/17122685/126910926-3d15008c-fc73-4eff-85dc-999fdd8344d5.png)

hopefully this is enough for the bug report other than tried installing it everything is up-to-date, and when i try to start Discord this is what shows up on my screen!

**Comment by Strencher** [comment]
Your discord installation is outdated. Reinstall it and inject bd again.

**Comment by P4R4NORM4L** [comment]
So completely uninstall Discord and try again? I just did that, maybe I'm doing something wrong.

**Comment by Strencher** [comment]
I see. I think your issue is that your `%AppData%\discord` and `%LocalAppData%\Discord` folders don't get deleted. Delete them manually and install discord again.

**Comment by P4R4NORM4L** [comment]
Ah ok gotcha thanks

**Comment by P4R4NORM4L** [comment]
That worked! Thank you so much !
