### ISSUE TITLE
[Feature] Safe Mode

### ISSUE THREAD

**Issue by gb85150** [BetterDiscord/BetterDiscord#962]
**Is your feature request related to a problem? Please describe.**
When BDD crashes you must remove any cuztomisations by going into BDD folder. I think it's not very user friendly.
**Describe the feature you'd like**
A safe mode which disable all plugins and themes.

**Additional context**
It can be suggested when the BDD crashing popup appears. Like This :
![image](https://user-images.githubusercontent.com/46113547/127181773-a5193997-f243-47d3-87fc-e77fadd44ec4.png)

**Comment by identity7** [comment]
That’s effectively what it does though. It reloads and disables itself so that it doesn’t go into a crash loop.

**Comment by rauenzi** [comment]
This is exactly what I mentioned over here https://github.com/BetterDiscord/BetterDiscord/pull/897#issuecomment-886734985

**Comment by rauenzi** [comment]
Merging this into #482
