### ISSUE TITLE
[Bug] After PC restart, BetterDiscord won't work even if repaired/ reinstalled

### ISSUE THREAD

**Issue by ND-64** [BetterDiscord/BetterDiscord#965]
**Describe the Bug**

After Win10 restart BD stopped working (or at least the background func), in repair it asked to reinstall BD but failed
**To Reproduce**

restart Win10, try to repair/ uninstall-reinstall BD
**Expected Behavior**

BD should have been repaired
**Screenshots**

![BD fail](https://user-images.githubusercontent.com/80389748/127275353-7383cac5-b4c5-4757-bef7-1f8251072531.JPG)

**Discord Version**

Stable
**Additional Context**

**Comment by dav1312** [comment]
### This is not an issue with BetterDiscord.
It's an **already fixed issue** with the installer.
https://github.com/BetterDiscord/Installer/issues/174

**Comment by ND-64** [comment]
only now the problem is that it won't let me agree to the license, i click the button and nothing happens

**Comment by dav1312** [comment]
> only now the problem is that it won't let me agree to the license, i click the button and nothing happens

https://github.com/BetterDiscord/Installer/issues/177
