### ISSUE TITLE
[Bug] Audio graining after new update

### ISSUE THREAD

**Issue by ClearoGG** [BetterDiscord/BetterDiscord#966]
**Describe the Bug**
Audio graining after update to new better discord client

**To Reproduce**
install new client

**Expected Behavior**
No graining

**Screenshots**

**Discord Version**
Stable

**Additional Context**
I've gone through pretty much everything that could have changed since the update and found it to be the BD update itself.
I do use voicemeeter banana so I thought it might be that but the graining is exclusive to discord voice (video audio through discord not affected) and happens regardless of server region (thought it could be ping related) or volume of person speaking. I've gone through all audio related settings in discord and none get rid of it when BD is installed. If I uninstall the client as I have the audio returns to normal and does not grain anymore

**Comment by rauenzi** [comment]
What operating system (and version) is this?

**Comment by ClearoGG** [comment]
This is on Windows 10 Pro 1903

**Comment by rauenzi** [comment]
That's weird, I did not make any change in this are for Windows... One thing you can try is locating the BD asar (`%appdata%\BetterDiscord\data\betterdiscord.asar`) and replace it with the asar from the previous version https://github.com/BetterDiscord/BetterDiscord/releases/download/v1.2.0/betterdiscord.asar

Then restart Discord and ignore the update notice. See if the issue disappears.

**Comment by ClearoGG** [comment]
I've tried what you've said and it seems to have fixed the issue. No more graining
