### ISSUE TITLE
[Bug] Wallpaper doesn't load after updating to 1.2.1 and even repair doesn't help

### ISSUE THREAD

**Issue by HeNrY7107** [BetterDiscord/BetterDiscord#967]
**Describe the Bug**
The walllpaper just does't load anymore. I even recreated the css theme but it doesn't work.

**To Reproduce**
I updated and it straight happens.

**Comment by doggybootsy** [comment]
This isn't a bd issue, it's a theme issue

**Comment by HeNrY7107** [comment]
> This isn't a bd issue, it's a theme issue

But it happens after I updated to 1.2.1 tho.
I am gonna go check at the theme's site nevertheless.

**Comment by identity7** [comment]
> > This isn't a bd issue, it's a theme issue
> 
> But it happens after I updated to 1.2.1 tho.
> I am gonna go check at the theme's site nevertheless.

Gibbu is shifting his repo around. You can either redownload the theme, or just update the imports in your existing theme.

Change his imports to @import url('https://discordstyles.github.io/[ThemeName]/dist/[ThemeName].css'); (Remove the brackets)

**Comment by HeNrY7107** [comment]
> > > This isn't a bd issue, it's a theme issue
> > 
> > 
> > But it happens after I updated to 1.2.1 tho.
> > I am gonna go check at the theme's site nevertheless.
> 
> Gibbu is shifting his repo around. You can either redownload the theme, or just update the imports in your existing theme.
> 
> Change his imports to @import url('[https://discordstyles.github.io/[ThemeName]/dist/[ThemeName].css](https://discordstyles.github.io/%5BThemeName%5D/dist/%5BThemeName%5D.css)'); (Remove the brackets)

It doesn't work. When I redownload the themes the import still has the old URL and not the one you mentioned and changing it myself just disables the theme completely.
I am using Basic Background btw.

**Comment by rauenzi** [comment]
As said, this is something to do with the theme rather than BD itself. You're better off seeking support for an issue like this on the support servers.
