### ISSUE TITLE
[Feature] Add a way for theme to get windows accent colour

### ISSUE THREAD

**Issue by Josh65-2201** [BetterDiscord/BetterDiscord#970]
**Is your feature request related to a problem? Please describe.**
Currently I'm trying to make a windows look theme for discord but I cant pull the accent colour from windows to make it dynamic like other windows apps.

**Describe the feature you'd like**
Mabey make a variable so that theme can use it like var(--winAccent)

**Comment by programmer2514** [comment]
Although I don't think you can access it from a theme, Electron does have an [API to do just this](https://www.electronjs.org/docs/api/system-preferences), so it would probably be pretty easy to implement either BD-side or with a plugin.

**Comment by Inve1951** [comment]
This should work:
https://www.w3.org/TR/css-color-adjust/#color-scheme-prop
https://www.w3.org/TR/css-color-4/#css-system-colors

**Comment by josh-65** [comment]
> This should work: https://www.w3.org/TR/css-color-adjust/#color-scheme-prop https://www.w3.org/TR/css-color-4/#css-system-colors

That seem to get the browsers state of dark and light mode only not Windows current accent color.
