### ISSUE TITLE
[Bug] - screenshare

### ISSUE THREAD

**Issue by lolpowerluke** [BetterDiscord/BetterDiscord#971]
**Describe the Bug**
bd crashes when screensharing in voicecalls

**To Reproduce**
go in a voicecall and share you screen

**Expected Behavior**
bd crashes and restarts as normal discord

**Discord Version**
![image](https://user-images.githubusercontent.com/47672899/127679805-54ec857a-d55e-43ac-b465-0d8f809c067f.png)
+ bd v1.2.1

**Comment by Error-Cezar** [comment]
couldn't reporduce the bug
![image](https://user-images.githubusercontent.com/64325581/127693349-7cf3e369-70db-4452-a2da-118dfec29557.png)

**Comment by lolpowerluke** [comment]
hmm, weird, because both me and my friend who was also in the call had the same problem
also, my friend doesnt have any plugins, only a theme

**Comment by rolledev** [comment]
i have had this before and i think this is a known bug.

**Comment by lolpowerluke** [comment]
well, I tried it again with my alt and it doesnt happen anymore, maybe it was just a thing that happened that moment

**Comment by Mr-Foxtrot** [comment]
can confirm that this was happening to me as well, however it doesn't seem to be tied to a specific client mod. Regardless if you use BetterDiscord or powercord, it can happen. From what I read in the console it says something about an unknown resolution being selected.
