### ISSUE TITLE
[Suggestion]Change the invite link in the installer

### ISSUE THREAD

**Issue by identity7** [BetterDiscord/BetterDiscord#972]
**Is your feature request related to a problem? Please describe.**
In the installer, the discord invite link does work fine, however you join into offtopic instead of support or announcements. This normally wouldn't be an issue, however, as many of us who have been on the betterdiscord server for more than a week have experienced, some people have issues using their eyes.

**Describe the feature you'd like**
The link to be changed so that you join into support or announcements

**Additional context**
This is the invite link currently in the installer
https://discord.gg/0Tmfo5ZbORCRqbAd

**Comment by dav1312** [comment]
Shouldn't this be posted in the installer repo?

**Comment by identity7** [comment]
> Shouldn't this be posted in the installer repo?

Guess I can't use my eyes either. Ty
