### ISSUE TITLE
JavaScript error on Windows

### ISSUE THREAD

**Issue by anonyng** [BetterDiscord/BetterDiscord#974]
**Describe the Bug**
I was browsing the world of discord, when suddenly ... BetterDiscord becomes very slow and a minute after waiting I get a JavaScript error.

**To Reproduce**
I don't know what to write here, I don't speak English.

**Expected Behavior**
Keep using Discord normally.

**Screenshots**
The error looks like this:
![image](https://user-images.githubusercontent.com/83776248/127949757-f0969c16-c89f-42ee-9be2-1f473e64c166.png)

**Discord Version**
PTB

**Additional Context**
BetterDiscord is very slow.

**Comment by anonyng** [comment]
El error es parecido a este:
![image](https://user-images.githubusercontent.com/83776248/127949648-038ae763-7215-4bb3-ac3d-1054cee4b14a.png)

**Comment by dav1312** [comment]
1) Make sure that you are using the latest version of BetterDiscord (v1.2.1) because this issue was already fixed in v1.2.0
2) Your Discord is outdated (latest version is 1.0.37)
3) You are not using PTB, you are using Canary

**Comment by anonyng** [comment]
@dav1312 
![image](https://user-images.githubusercontent.com/83776248/128103491-2236dca7-a551-4b0f-9e65-24e7b16c043d.png)
I always keep everything updated.

**Comment by dav1312** [comment]
> ![image](https://user-images.githubusercontent.com/83776248/127949757-f0969c16-c89f-42ee-9be2-1f473e64c166.png)
> ![image](https://user-images.githubusercontent.com/83776248/128103491-2236dca7-a551-4b0f-9e65-24e7b16c043d.png)

In your first screenshot an outdated Discord Canary appeared, now its PTB.
Send a screenshot like the first one but with PTB, not Canary.

**Comment by anonyng** [comment]
@dav1312 
The first screenshot is similar, however, it is not the same at all

But hey, the error has not happened to me anymore.

**Comment by anonyng** [comment]
@dav1312 
The first screenshot is similar, however, it is not the same at all

But hey, the error has not happened to me anymore.
