### ISSUE TITLE
windows 11

### ISSUE THREAD

**Issue by jthenderson00** [BetterDiscord/BetterDiscord#975]
ive tried to install BetterDiscord on my windows 11 official beta device and it doesnt have any errors installing. i go to open up disocrd, and it opens up as if nothing happened. ive used better discord before, so i know it isnt working. any tips? 

![image](https://user-images.githubusercontent.com/79734409/128024987-ef9cdf10-a62f-4542-8fc9-bcf4d8a26e82.png)

**Comment by dav1312** [comment]
You are installing BetterDiscord in app-0.0.308 but your Discord is in Host 1.0.9002
This is not an issue with Windows 11

**Comment by jthenderson00** [comment]
> 
> 
> You are installing BetterDiscord in app-0.0.308 but your Discord is in Host 1.0.9002
> This is not an issue with Windows 11

so... uh... what do i do?

**Comment by dav1312** [comment]
The most probable cause is that your Discord is now installed in programdata
Click Browse in the installer 
Navigate to: `%programdata%\%username%\Discord\app-1.0.9002\resources`
Video tutorial:
![Video Tutorial](https://cdn.discordapp.com/attachments/542030029861814284/863124888974000198/programdata.gif)

**Comment by rauenzi** [comment]
Pleasee see the very helpful comment from dav above, he's exactly right
