### ISSUE TITLE
[Feature] Move public servers into discord discovery page

### ISSUE THREAD

**Issue by josh-65** [BetterDiscord/BetterDiscord#977]
**Describe the feature you'd like**
The current public servers button under the Friends button should be move to discord own discovery page

**Comment by rauenzi** [comment]
This is a feature that we want to keep separate and distinguished from Discord's discovery feature. Discord's feature is focused on large official or partnered servers. The Public Servers listing allows anyone to have equal shot at appearing in a search and does not have minimum size requirements.
