### ISSUE TITLE
Remove Nazi Symbolism

### ISSUE THREAD

**Issue by getgle** [BetterDiscord/BetterDiscord#978]
Hello, I notice that in the "BetterDiscord" client when you type BASED it automatically replaces it with the incel frog in tuxedo emoticon,  which is created and used by racists and transphobes.   It's really weird to have this as a silently added feature in BetterDiscord, please remove this. :/
![frog](https://user-images.githubusercontent.com/26177157/128293120-e0273735-4558-4533-8f6a-ff934df03b07.PNG)

How to reproduce:  type BASED and send the message

**Comment by fowlis** [comment]
You know there's an option to disable BD's emote system, so you won't see these, right?
![image](https://user-images.githubusercontent.com/84232621/128293361-20515514-c2c1-4cd7-bc63-54679c5775d5.png)
It's also not exactly a "silently added feature", it's just a part of the emote system that BD has. I believe the emotes are from 
FrankerFaceZ and/or BetterTTV.

**Comment by getgle** [comment]
Why are there Nazi Symbols included with this software and enabled by default, though?

**Comment by fowlis** [comment]
Because that's how you interpret them, the emojis were never created as "Nazi Symbols". It just so happens that some of these Nazis use them and that's what you associate them with. The wider usage of the emoji has never been a symbol of Nazism.

I don't see how a little cartoon frog in a suit and tie is a symbol of Nazism anyway.

**Comment by qwerasd205** [comment]
Either way, they're Twitch/FrankerFaceZ/BetterTTV emotes, they're not created or curated by BetterDiscord. And, as fowlis points out, the use of Pepe as a Nazi symbol is very context dependent. Even the ADL, who are notoriously loose with their qualifications of hate symbols, finds it prudent to include
> However, because so many Pepe the Frog memes are not bigoted in nature, it is important to examine use of the meme only in context. The mere fact of posting a Pepe meme does not mean that someone is racist or white supremacist.

on [their page about Pepe](https://www.adl.org/education/references/hate-symbols/pepe-the-frog).

**Comment by qwerasd205** [comment]
I disagree with the outrage, but perhaps there is some merit to adding it to the [blocklist](https://github.com/BetterDiscord/BetterDiscord/blob/main/assets/emotes/blocklist.json) on the basis of being a common word.

**Comment by rauenzi** [comment]
While in general I agree the default blocklist should be updated, the OP is a troll as evidenced by their "website".
