### ISSUE TITLE
[Bug] BD Launches normal discord.

### ISSUE THREAD

**Issue by EmeraldWolfYT** [BetterDiscord/BetterDiscord#980]
**Describe the Bug**
If I try launching Better Discord, it launches the normal client, everything is like normal discord, I have tried to repair it, uninstall and reinstall it, etc. No matter what, I have the default settings, Gui, everything. (It wasn't always like this, it was like normal BD at first but then I had to reinstall discord and then it popped up.)

**To Reproduce**
Delete and reinstall normal discord and BD will stop working, may I note that this happened on 6/11/2021, and I tried to check again today since discord had updated since then but to no avail, I don't know the exact discord version I had then nor what I have now but it was before stickers.

**Expected Behavior**
For better discord to run like normal.

**Screenshots**
I don't really know how I would show that in a screenshot, it looks the same either way.

**Discord Version**
Stable.

**Additional Context**
I don't really have anything else to say.

**Comment by doggybootsy** [comment]
try this its from pinned messages in #support
> BetterDiscord doesn't appear
Click Browse in the installer 
Navigate to: %programdata%\%username%\Discord\app-1.0.9002\resources
And try installing BD there
Make sure that you installed it in programdata before complaining that it doesn't work
Video tutorial: https://cdn.discordapp.com/attachments/542030029861814284/863124888974000198/programdata.gif

**Comment by EmeraldWolfYT** [comment]
Thanks! I will see if it worked.

**Comment by EmeraldWolfYT** [comment]
It worked, I feel kinda stupid now, but thanks for the help!
