### ISSUE TITLE
[Bug]cannot excute installer

### ISSUE THREAD

**Issue by LPMINO** [BetterDiscord/BetterDiscord#982]
**Describe the Bug**
When I execute installer, it soon disappears from the Task Manager.

**To Reproduce**
just execute installer

**Expected Behavior**
Normally execute

**Screenshots**
https://cdn.discordapp.com/attachments/403405715080740874/873770404798410802/Honeycam_2021-08-08_12-30-26.gif

**Discord Version**
Stable

**Additional Context**

**Comment by doggybootsy** [comment]
This would be for the installers repo
In the support channel there should be a fix

**Comment by LPMINO** [comment]
if you are saying about discord support channel, it doesn't help me.

**Comment by LPMINO** [comment]
ok i got it
