### ISSUE TITLE
[Bug] Discord freezes with massive errors in console

### ISSUE THREAD

**Issue by TetraTheta** [BetterDiscord/BetterDiscord#983]
# **Describe the Bug**
Even though disabling 'Emote System' in Settings, Discord(with BD) still hangs about 5 seconds right after starting

# **To Reproduce**
1. Install Discord
2. Install BetterDiscord
3. Start Discord
4. Open Console with <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>
5. Face massive amount of warning logs

# **Expected Behavior**
Since 'Emote System' is disabled, Discord should not freeze when startup

# **Screenshots**
Not available

# **Discord Version**
Stable 93033 (38018b9)  
BetterDiscord 1.2.1  
Host 1.0.9002 Windows 10 64-Bit (10.0.19043)

# **Additional Context**
Here is log from Console which is redacted. I deleted some string that seem to be my token thing.  
https://paste.gg/p/anonymous/bf46d6bd62484e3b94221b56ff90e004

Most of them was about 'Failed parsing intl key blablah in locale' but I think this amount of error/warning can slow down or hang Discord, especially with logger.

**Comment by identity7** [comment]
The emote system isn’t the only thing it needs to load. It also needs to load all your themes and plugins, amoung other things, so a short freeze is to be expected.

**Comment by TetraTheta** [comment]
> The emote system isn’t the only thing it needs to load. It also needs to load all your themes and plugins, amoung other things, so a short freeze is to be expected.

If then, I think there should be a way to disable them. It would be waste to load things that user don't want to use ever.  
Currently, only 'Emote System' can be disabled in Settings. Downloading emotes can be disabled in `emotes.json`, `general.download`. 'Custom CSS' can be disabled in `settings.json`, `customcss.customcss`. Theme cannot be disabled even in config file.

If user wants only plugin thing, other things would be 'dead weight' to him. Maybe later, he can play with them later but it should be his choice of whether he would use it or not, not forcebily load them.

**Comment by rauenzi** [comment]
Is this happening consistenly? The log you posted is showing a lot of errors from Discord and not BD which give me pause as to diagnosing your performance issue.

**Comment by TetraTheta** [comment]
> Is this happening consistenly? The log you posted is showing a lot of errors from Discord and not BD which give me pause as to diagnosing your performance issue.

Yes, I've tried to remove BD and re-install BD, but problem still exists. This happens everytime Discord starts.  

It is relief that those errors are from Discord, not BD.

I will comment again after this tests: Uninstall Discord and BD, restart PC, install Discord and BD again.

**Comment by rauenzi** [comment]
Have you tried uninstalling BD and just seeing how Discord performs?

**Comment by TetraTheta** [comment]
> Have you tried uninstalling BD and just seeing how Discord performs?

Yes, Discord didn't hang/freeze if BD was not installed.

Also, I can confirm that this was 'BDFDB' plugin library's fault. I tested with many combination, but when BDFDB exists, Discord hangs.  
Moreover, BDFDB enables itself even though user disabled it before and this still happens when there is no plugin that relies on that library. This is highly suspecious.

So, my conclusion is, this is not BD's fault: its BDFDB's. Thanks for your help.
