### ISSUE TITLE
Bug Transparent Background Setting

### ISSUE THREAD

**Issue by TheL3one** [BetterDiscord/BetterDiscord#984]
Hi,
the transparent backgroud setting is not working, even with a theme.
![Capture1](https://user-images.githubusercontent.com/88794793/129077515-c777de92-21fd-4942-9278-f74b4fa4cf9f.PNG)
I tried to type *{background: transparent!important;} in the custom css but i got this
![Capture2](https://user-images.githubusercontent.com/88794793/129077705-331ece77-eac6-420c-b853-11b8b941ec13.PNG)

Im on last version of Discord stable and last Better Discord too
I need some help
pls <3

**Comment by doggybootsy** [comment]
This isn't a bd bug, it would be a theme bug

**Comment by rauenzi** [comment]
See above, the screenshots you provided show it working as intended

**Comment by TheL3one** [comment]
But it supposed to be transparent when there is no background like images
No?

**Comment by rauenzi** [comment]
The BD setting allows the window itself to become see-through as seen in the second screenshot you posted

**Comment by TheL3one** [comment]
The thing i try to say is that i saw on youtube that discord can be like this
![Screenshot_2021-08-11-20-39-24-394_com.google.android.youtube.jpg](https://user-images.githubusercontent.com/88794793/129087484-10d0f20a-d3fb-4434-b803-a5538b96b6a1.jpg)

When i use a theme without background, the discord window is not transparent like it should be

What am i suppose to do to get my discord like this

**Comment by rauenzi** [comment]
You need to have a compatible theme that is meant to do that, you can also emulate it with
```css
:root {
    opacity: 0.7;
}
```

**Comment by TheL3one** [comment]
Doesnt work too
My Windows version too old i guess

**Comment by rauenzi** [comment]
What happens when you try that? It has nothing to do with Windows.

**Comment by TheL3one** [comment]
Oh ok but it makes the whole discord Window transparent. Is this possible only the background ?

**Comment by rauenzi** [comment]
> You need to have a compatible theme that is meant to do that

**Comment by TheL3one** [comment]
Its finally works
The theme wasnt compatible like i thought
