### ISSUE TITLE
"download" download

### ISSUE THREAD

**Issue by idkman2021** [BetterDiscord/BetterDiscord#986]
what does download download
it says betterdiscord enchances discord
and discord is a website
so why does it download an exe

**Comment by lolpowerluke** [comment]
the exe file you download is the installer we use to inject bd in discord
also, you can go to the support server for that type of questions 
https://discord.gg/sbA3xCJ

**Comment by rauenzi** [comment]
BetterDiscord is an extension for the desktop version of Discord, not for the web version. Hope that helps!
