### ISSUE TITLE
[Bug] Better Discord crash on more menu from messages

### ISSUE THREAD

**Issue by Error-Cezar** [BetterDiscord/BetterDiscord#990]
**Describe the Bug**
When Cakey Bot is in a server while you have Better Discord on and go to the more option of a message Discord will crash from a fatal error.

**To Reproduce**
1. Add [Cakey Bot](https://cakeybot.app/invite) to a server or go to a server with the bot.
2. go to any message.
3. discord crash after a few second

**Expected Behavior**
Discord should show the more menu without any problem.

**Screenshots**
without Better Discord:
![image](https://user-images.githubusercontent.com/64325581/129395404-7bc487dd-6d1f-4630-afa2-b96da0bb57f9.png)

with Better Discord:
![Crash-BD](https://user-images.githubusercontent.com/64325581/129395781-d3f78de3-72d0-4e97-8084-15341bb8bc59.gif)

Error: 
![image](https://user-images.githubusercontent.com/64325581/129395878-2c14a7e1-831b-447a-b7dd-5665e5ace7b0.png)

**Discord Version**
Stable 93452 (1cdfadd) (with the lastest version of Better Discord)

**Additional Context**
All the plugin I have are updated.
The app menu is from the bot itself

**Comment by rauenzi** [comment]
Can you try removing all the plugins from the plugin folder and reloading to see if it reproduces?

**Comment by dav1312** [comment]
> Can you try removing all the plugins from the plugin folder and reloading to see if it reproduces?

You can also rename the plugins folder to something else if you don't want to delete it

**Comment by dav1312** [comment]
The issue might be caused by the plugin CopyRawMessage by DevilBro

**Comment by Xhylo** [comment]
I recreated the steps on my OS and the issue did not occur and CopyRawMessage by DevilBro did not cause that crash as well.
I assume it could be something else causing the crash, because it's neither of them both.

**Comment by Error-Cezar** [comment]
> The issue might be caused by the plugin CopyRawMessage by DevilBro

I dont have this plugin

**Comment by Error-Cezar** [comment]
> Can you try removing all the plugins from the plugin folder and reloading to see if it reproduces?

removing all the plugin work so it must be a issue with one of my plugin

**Comment by Error-Cezar** [comment]
I may got the plugin that cause the error

**Comment by Error-Cezar** [comment]
the plugin that make the error is QuickMention by DevilBro

here is the test with the plugin
![gotem](https://user-images.githubusercontent.com/64325581/129411023-43b301b9-a00f-4fab-bfe1-9de37398dcd9.gif)

**Comment by rauenzi** [comment]
Then I would suggest bringing the issue over to his repo https://github.com/mwittrien/BetterDiscordAddons
