### ISSUE TITLE
[Bug] Transparency Disables Minimize Mode

### ISSUE THREAD

**Issue by Queenite** [BetterDiscord/BetterDiscord#993]
**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by dav1312** [comment]
Please at least fill the form properly

**Comment by Xhylo** [comment]
lol

**Comment by Queenite** [comment]
> Please at least fill the form properly

I fixed it myself. Also, didn’t realize the brackets would cause the text to not show.
