### ISSUE TITLE
[Question] Is there any way to read why the Discord client crashed?

### ISSUE THREAD

**Issue by LoneDev6** [BetterDiscord/BetterDiscord#994]
Is there any way to read why the Discord client crashed?
The log file is empty and this message is useless.
![immagine](https://user-images.githubusercontent.com/27242001/129899571-163576aa-c4a4-4729-aa9a-678b42242aea.png)

Thanks

EDIT:
Solution for my particular crash issue: https://github.com/BetterDiscord/BetterDiscord/issues/994#issuecomment-901198533

**Comment by dav1312** [comment]
Why do you think that is useless? Have you tried removing all of your plugins to see if it still crashes like the message tells you to do?

**Comment by LoneDev6** [comment]
It doesn't crash, yes I've tried to remove plugins.
The problem is that even if I add only one libs it crashes, so I'd like to check what is the cause and possibly fix it myself.

![immagine](https://user-images.githubusercontent.com/27242001/129901460-3800d6c0-d979-46cc-b19a-063f19dabfb6.png)

**Comment by GhostzinRs** [comment]
Starting Install...

Creating required directories...
✅ Directory exists: C:\Users\mc201\AppData\Roaming\BetterDiscord
✅ Directory exists: C:\Users\mc201\AppData\Roaming\BetterDiscord\data
✅ Directory exists: C:\Users\mc201\AppData\Roaming\BetterDiscord\themes
✅ Directory exists: C:\Users\mc201\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
❌ Failed to download package https://api.github.com/repos/rauenzi/BetterDiscordApp/releases
❌ Cannot read property 'assets' of undefined

The install seems to have failed. If this problem is recurring, join our discord community for support. https://discord.gg/0Tmfo5ZbORCRqbAd     
 Help Pls

**Comment by dav1312** [comment]
@GhostzinRs That is unrelated to this issue

**Comment by MrTucks** [comment]
@LoneDev6 The cause of this particular crash is probably "0PluginLibrary.plugin.js". Just delete it and install any plugin that uses it. Then you will get a pop-up telling where you can click "install" to install the latest version of that library, which has the crash bug fixed. Many users had a crash today and this is what fixed it.

But I agree, it would be nice if there was a crash log directly telling you which plugin has caused the crash.

**Comment by Amenofisch** [comment]
> @LoneDev6 The cause of this particular crash is probably "0PluginLibrary.plugin.js". Just delete it and install any plugin that uses it. Then you will get a pop-up telling where you can click "install" to install the latest version of that library, which has the crash bug fixed. Many users had a crash today and this is what fixed it.
> 
> But I agree, it would be nice if there was a crash log directly telling you which plugin has caused the crash.

This fixed it for me. Thanks for the Help :)

**Comment by kamekku14** [comment]
> The cause of this particular crash is probably "0PluginLibrary.plugin.js". Just delete it and install any plugin that uses it. Then you will get a pop-up telling where you can click "install" to install the latest version of that library, which has the crash bug fixed. Many users had a crash today and this is what fixed it.

Well, that's right. Hope this works for me! And for reference: <https://github.com/rauenzi/BDPluginLibrary/pull/94>

**Comment by MaartenBl** [comment]
> @LoneDev6 The cause of this particular crash is probably "0PluginLibrary.plugin.js". Just delete it and install any plugin that uses it. Then you will get a pop-up telling where you can click "install" to install the latest version of that library, which has the crash bug fixed. Many users had a crash today and this is what fixed it.
> 
> But I agree, it would be nice if there was a crash log directly telling you which plugin has caused the crash.

Related to the crash issue, ZeresPluginLibrary pops up with error log
![image](https://user-images.githubusercontent.com/19569456/129949448-e614fe84-ce47-487d-8839-0b594c2263d2.png)

**Comment by Drflash55** [comment]
> Related to the crash issue, ZeresPluginLibrary pops up with error log
That's not actually an error log.

That's just what rauenzi made as an explanation for what was going on last time, in the form of a notification used for Discord Updates.

**Comment by KK-Designs** [comment]
> Starting Install...
> 
> Creating required directories...
> ✅ Directory exists: C:\Users\mc201\AppData\Roaming\BetterDiscord
> ✅ Directory exists: C:\Users\mc201\AppData\Roaming\BetterDiscord\data
> ✅ Directory exists: C:\Users\mc201\AppData\Roaming\BetterDiscord\themes
> ✅ Directory exists: C:\Users\mc201\AppData\Roaming\BetterDiscord\plugins
> ✅ Directories created
> 
> Downloading asar file
> ❌ Failed to download package https://api.github.com/repos/rauenzi/BetterDiscordApp/releases
> ❌ Cannot read property 'assets' of undefined
> 
> The install seems to have failed. If this problem is recurring, join our discord community for support. https://discord.gg/0Tmfo5ZbORCRqbAd
> Help Pls

Uninstall and reinstall the installer. It worked for me

**Comment by LoneDev6** [comment]
> 
> 
> @LoneDev6 The cause of this particular crash is probably "0PluginLibrary.plugin.js". Just delete it and install any plugin that uses it. Then you will get a pop-up telling where you can click "install" to install the latest version of that library, which has the crash bug fixed. Many users had a crash today and this is what fixed it.
> 
> But I agree, it would be nice if there was a crash log directly telling you which plugin has caused the crash.

Thanks! Working perfectly :D

**Comment by tipakA** [comment]
> Why do you think that is useless? Have you tried removing all of your plugins to see if it still crashes like the message tells you to do?

...Because that is useless. It tells you only the most obvious thing: "something caused a crash, try removing everything so it doesn't crash".

It does not tell you *why* it crashed, it doesn't give you any info at all beyond stating the obvious you notice without the popup as soon as discord's window goes blank.
Additionally, you can't even restart with dev tools open, cause they close as well, and there are no actual logs that could help you, so you are actually stuck with "does this one crash? does this one?"

Now, i get that it might be difficult to create a log of a crash when it occurs in this case, but nonetheless the popup is quite useless in its current form.

**Comment by josephworks** [comment]
I don't see why this has closed, this issue still exists today.

**Comment by terax6669** [comment]
@josephworks same.
We need the exception and trace to figure out the plugin that's causing the issue. My Discord crashes about once per day and I'm not going to disable all plugins and then re-enable one every 2-3 days to make sure it's stable, lol. Just give us the error please.

**Comment by josephworks** [comment]
@dav1312 could you reopen this issue?

**Comment by auroraisluna** [comment]
> 

+1

**Comment by auroraisluna** [comment]
> @josephworks same. We need the exception and trace to figure out the plugin that's causing the issue. My Discord crashes about once per day and I'm not going to disable all plugins and then re-enable one every 2-3 days to make sure it's stable, lol. Just give us the error please.

+1 to this.

**Comment by Daxorinator** [comment]
Why is this closed? There should be the option for real logging and exceptions and traces to figure out stuff like this. My discord is also crashing every 6 or so hours and I don't want to go through and add one plugin at a time until I stop getting a crash...

**Comment by Tropix126** [comment]
Agree that this should probably be reopened, but just as a heads up these errors leave *no traces*. Renderer crashes are caused by v8 itself due to the context leak that BD uses and the error's origins aren't traceable.

**Comment by Daxorinator** [comment]
> Agree that this should probably be reopened, but just as a heads up these errors leave _no traces_. Renderer crashes are caused by v8 itself due to the context leak that BD uses and the error's origins aren't programatically traceable.

Is there any way at all then to tell what causes these crashes or are we just screwed

**Comment by Snoresville** [comment]
Would like to see more discussion on this topic, this is still a real issue

**Comment by josephworks** [comment]
Yeah, why is this closed?

**Comment by josephworks** [comment]
Just checked and I have asked previously for this to be reopened, but it doesn't appear that that has been heard.

**Comment by GGuyX** [comment]
Wow. Seriously? This has been going on for so long and no one at BetterDiscord's team cares at all to give us some proper information? I love BD but that is a bad joke.

**Comment by rauenzi** [comment]
There is no log generated in a full crash like that, there's not really much information I can provide. You can sometimes see the cause of the error if you run Discord through the command line, then errors will sometimes be shown in the terminal.

**Comment by Drflash55** [comment]
> rauenzi said:
> There is no log generated in a full crash like that, there's not really much information I can provide. You can sometimes see the cause of the error if you run Discord through the command line, then errors will sometimes be shown in the terminal.

Yikes... that's unfortunate. Guess only trial-and-error can solve it, which is a pain to do.

**Comment by rauenzi** [comment]
It's very unfortunate, it makes debugging these kinds of errors nearly impossible.
