### ISSUE TITLE
[Bug] BetterDiscord Crashing

### ISSUE THREAD

**Issue by A983Hub** [BetterDiscord/BetterDiscord#995]
**Describe the Bug**
I was trying to use Discord + With BetterDiscord like normal, until an error appeared saying:
"BetterDiscord seems to have crashed your Discord Client.
BetterDiscord has automatically disabled itself temporarily. Try removing all your plugins then restarting Discord."

**To Reproduce**
Just use Discord with BetterDiscord.

**Expected Behavior**
The Error to not show up.

**Discord Version**
Stable

**Additional Context**
I tried re-installing BetterDiscord, nothing happened. Is it because of a plugin or theme?

**Comment by TheAleLeaks3** [comment]
me too pls help

**Comment by fowlis** [comment]
Please take the time to redownload this plugin: https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js
Hit `Ctrl` + `S` to save the page, and it will save a .js file. Put that file in your plugin folder and reload Discord.

**Comment by doggybootsy** [comment]
Isn't a bd issue since it's your plugins. Look in the support channel for a fix

**Comment by A983Hub** [comment]
> Please take the time to redownload this plugin: https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js
> Hit `Ctrl` + `S` to save the page, and it will save a .js file. Put that file in your plugin folder and reload Discord.

It does work, and my BetterDiscord is now fully working as intended. Thanks, man!

**Comment by TheAleLeaks3** [comment]
> Please take the time to redownload this plugin: https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js
> Hit `Ctrl` + `S` to save the page, and it will save a .js file. Put that file in your plugin folder and reload Discord.

thx it work <3

**Comment by thomasbnt** [comment]
> Please take the time to redownload this plugin: [rauenzi/BDPluginLibrary@`master`/release/0PluginLibrary.plugin.js (raw)](https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js)
> Hit `Ctrl` + `S` to save the page, and it will save a .js file. Put that file in your plugin folder and reload Discord.
> 
> How to get to your plugin folder:
> • For Windows: Press `Win` + `R`, and paste: `%appdata%/betterdiscord/plugins`
> • For Mac: Press `Shift` + `Command` + `G` (or open Finder) and paste: `~/Library/Application Support/betterdiscord/plugins`
> • For Linux: navigate to `~/.config/BetterDiscord/plugins`
> 
> Make sure when you're adding the plugin, that you replace any other versions of it and that the filename is exactly: `0PluginLibrary.plugin.js`

Work! Thanks!

**Comment by hk3wx** [comment]
> Please take the time to redownload this plugin: https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js
> Hit `Ctrl` + `S` to save the page, and it will save a .js file. Put that file in your plugin folder and reload Discord.
> 
> How to get to your plugin folder:
> • For Windows: Press `Win` + `R`, and paste: `%appdata%/betterdiscord/plugins`
> • For Mac: Press `Shift` + `Command` + `G` (or open Finder) and paste: `~/Library/Application Support/betterdiscord/plugins`
> • For Linux: navigate to `~/.config/BetterDiscord/plugins`
> 
> Make sure when you're adding the plugin, that you replace any other versions of it and that the filename is exactly: `0PluginLibrary.plugin.js`

This solve the issue ;D

**Comment by CorneliusCornbread** [comment]
Protip: whenever Discord updates and it breaks all your plugins do the following
1. Go to AppData/Roaming/BetterDiscord
2. Rename your plugins folder to something else
3. Start BetterDiscord, if it still crashes, also rename your themes folder
4. Go through your plugins folder and only transfer over plugins that aren't libraries, it should be fairly obvious because they'll have a name that roughly describes what feature they add
5. Whenever you get a popup for installing a missing library, add it
6. Delete all your old libraries/old plugins folder
7. Enjoy your now working Discord

**Comment by NanKillTV** [comment]
> Please take the time to redownload this plugin: https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js
> Hit `Ctrl` + `S` to save the page, and it will save a .js file. Put that file in your plugin folder and reload Discord.
> 
> How to get to your plugin folder:
> • For Windows: Press `Win` + `R`, and paste: `%appdata%/betterdiscord/plugins`
> • For Mac: Press `Shift` + `Command` + `G` (or open Finder) and paste: `~/Library/Application Support/betterdiscord/plugins`
> • For Linux: navigate to `~/.config/BetterDiscord/plugins`
> 
> Make sure when you're adding the plugin, that you replace any other versions of it and that the filename is exactly: `0PluginLibrary.plugin.js`

Thanks
