### ISSUE TITLE
[Feature] Check for plugin updates at launch before initializing plugins

### ISSUE THREAD

**Issue by CorneliusCornbread** [BetterDiscord/BetterDiscord#996]
**Is your feature request related to a problem? Please describe.**
As I'm sure you're well aware, when big updates to Discord happen it breaks plugins in a frustratingly difficult to fix way. Requiring the user to go through and manually update all their plugins.

**Describe the feature you'd like**
At startup, before initializing the plugins, check for updates for all of them and allow them to update the plugins before initializing them. This allows people to easily update their plugins in a user-friendly way and should avoid future bug reports of people's BD crashing because they don't have some library updated.

**Comment by Inve1951** [comment]
The current update systems are all either implemented in plugins directly or the plugin calls into library code to perform update checks and download. Meaning that at this time it's impossible to perform update checks ahead of loading the individual plugin. Checking themes for updates is also performed by plugins.

That said, it's on the project roadmap to implement a safe, uniform update system in cooperation with the new website.

**Comment by TheByKotik** [comment]
Only i suppose this can be optimized to "update before initializing **after crash / fail to plugin start**".
This should prevent booting from taking too long.

**Comment by rauenzi** [comment]
Yes please see what Inve1951 said.
