### ISSUE TITLE
Discord themes locking the scroll bar in settings

### ISSUE THREAD

**Issue by modemmaximum** [BetterDiscord/BetterDiscord#997]
**Describe the Bug**
When a them is applied in the them tab or a custom css is input the settings become locked. Locked as in you can no longer scroll. So if "My Account" to better discord "settings" were shown at the time of application and you need to scroll down to other tabs? No dice.  The themes (at least the ones I use) are also far bigger than they used to be just days ago. 

**To Reproduce**
Set a theme in the theme or css tabs. Then attempt to scroll in the settings menu. (The one on the left that shows all of the tabs like "my account" and so on.)

**Expected Behavior**
Scrolling becomes impossible on the left side settings menu.

**Screenshots**
Before
![image](https://user-images.githubusercontent.com/89167669/129982892-57911295-8f95-4694-b24a-8f0561a82bbe.png)
After
![image](https://user-images.githubusercontent.com/89167669/129982982-b94ec9d3-5d25-47c2-ac14-38fb3baf8ddc.png)

**Discord Version**
Not entirely sure, or how to check. Whatever the most common is because I download the first link that comes up on chrome when you type "discord download"

**Additional Context**

Between those 2 images I did 0 scrolling or anything but changing my theme. It just locked it at the top with scrolling becoming impossible. I'm not active anywhere but Discord so if this is resolved or anything of the sort let me know sora#7999

**Comment by doggybootsy** [comment]
This a theme issue not a bd issue

**Comment by dav1312** [comment]
You shouldn't be using themes from vsthemes, you should be using official themes from the BetterDiscord website

**Comment by modemmaximum** [comment]
I've used official ones too for it. I could edit the thread with pics of
official themes if you'd like?

**Comment by rauenzi** [comment]
This is something that the themes do, not something BD does as you can scroll just fine without a theme.

**Comment by modemmaximum** [comment]
Ah I understand now, so is there no way to get it fixed in that case?

**Comment by Inve1951** [comment]
> so is there no way to get it fixed in that case?

the theme needs fixing
fix it yourself or contact the author
