### ISSUE TITLE
[Bug] - Some plugins randomly disable

### ISSUE THREAD

**Issue by KK-Designs** [BetterDiscord/BetterDiscord#998]
**Describe the Bug**
Some plugins randomly disable

**To Reproduce**
Download some random plugins like `statusCss` and `DoubleClickToEdit` and watch get disabled after reloading the client

**Expected Behavior**
It should run properly and not self disable

**Screenshots**

**Discord Version**
Stable, latest

**Additional Context**
It only happens to some plugins, not all of ### them

**Comment by Inve1951** [comment]
Those plugins no longer receive updates or have been obsoleted.
See our website for current addons.

https://betterdiscord.app
