### ISSUE TITLE
[Bug] Getting rid of the "update" hover message

### ISSUE THREAD

**Issue by LoneDev6** [BetterDiscord/BetterDiscord#999]
**Describe the Bug**
I can't get rid of this since some Discord updates.

**To Reproduce**
No idea sincerely

**Expected Behavior**
This hover message to disappear

**Screenshots**
![immagine](https://user-images.githubusercontent.com/27242001/130056106-dd0f42bd-eb61-4721-8989-c338511059dd.png)

**Discord Version**
Stable 94010 (5b2a0b4)
BetterDiscord 1.2.1

**Comment by Bartolinski6** [comment]
what to do to make it work better discord?

**Comment by rauenzi** [comment]
Manually ensure your plugins are up to date, this is not caused by BD.,
